### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#10]
Part of #2.

I'd like to answer these questions:

1. Do we want an always-visible call-to-action button in the mobile menu bar? (E.g. "Login")
2. How to layout our mobile menu?
3. Do we want a second menu for Docs, or a single merged menu?

Here are a few mobile sites that are comparable to Gitpod, for inspiration.

---

<img width="640" alt="Screenshot 2019-03-15 at 19 03 57" src="https://user-images.githubusercontent.com/599268/54452329-36482200-4755-11e9-97a4-eab78c9ff802.png">

- Right menu icon
- Partial overlay menu
- Right call to action button: "Sign up"

---

<img width="640" alt="Screenshot 2019-03-15 at 18 54 53" src="https://user-images.githubusercontent.com/599268/54452419-68f21a80-4755-11e9-959b-2d1636da78f6.png">

- Left menu icon
- Full overlay menu
- Right call to action button: "Go to app"

---

<p align="center">
<img width="320" alt="Screenshot 2019-03-15 at 18 56 57" src="https://user-images.githubusercontent.com/599268/54453089-db172f00-4756-11e9-8b99-134373acc32b.png">
</p>

<img width="640" alt="Screenshot 2019-03-15 at 18 57 16" src="https://user-images.githubusercontent.com/599268/54453105-e4080080-4756-11e9-959b-e2baed870d65.png">

- Two menu icons: Left for Docs tree, Right for website
- Full overlay menus
- (No call to action button, but Kubernetes is not an app)

**Comment by jankeromnes** [comment]
FYI we already have a few concepts:

<img width="320" alt="Button use – 1" src="https://user-images.githubusercontent.com/599268/54453574-e4ed6200-4757-11e9-9315-98e9788966ba.jpg">

- Right menu icon -- blue when open (I'd prefer the icon to become a cross)
- Full overlay menu -- non-standard grid of boxes (I'd prefer a familiar list)
- No call to action button (I'd prefer an always-visible "Login" button)

---

<img width="320" alt="Docs" src="https://user-images.githubusercontent.com/599268/54453596-f0d92400-4757-11e9-8839-59e49f09d34d.jpg">

- Two menu icons on the right... confusing, but tricky to get right

Can we make the docs menu less confusing? E.g. move the Docs menu icon to the left, or merge the docs tree into the common menu? Not sure.

**Comment by ChristinFrohne** [comment]
Cool inspiration, I did some more mockups with that in mind. 
![Button use – 5](https://user-images.githubusercontent.com/46345125/54530687-b227b180-4983-11e9-918c-5f7a1655bd71.jpg)
![Button use – 7](https://user-images.githubusercontent.com/46345125/54530688-b227b180-4983-11e9-9399-ecc53b6c8c5c.jpg)

Which screens are still missing or need a fixing? 
- screen for login user
- footer
- features 

Let me know, if there is anything else :)

**Comment by jankeromnes** [comment]
Really cool mockups! I've implemented the first one for now.

> Which screens are still missing or need a fixing?
> - screen for logged in user
> - footer
> - features

Not sure what you mean by "screen for logged in user":
- the _website's_ look when already logged in (@svenefftinge suggested replacing the Login button with an avatar, but as a user I still want a big button that takes me to the app... maybe we don't change the website even if you're logged in? Or use a "Go to app" button like CircleCI?)
- the _app's_ look when you've just clicked Login (the app also has many pages, but some are more important, see below)

Other pages that need mobile re-work:

- pricing (like features, this one is a bit complicated I guess)
- blog (should be pretty easy to fix for mobile, no need for a mockup)
- docs (same, except we need a place to put the docs tree-menu in... I'll try to put it inside the expandable "Docs" menu-item from your concept)

**Comment by jankeromnes** [comment]
I think this is fixed now (see latest adjustments in #14).
