### ISSUE TITLE
Record a screencast for the VS Code desktop support

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1001]
Hi @pawlean,

I think the new VS Code desktop support (https://www.gitpod.io/docs/develop/vscode-desktop-support) is a great candidate for a new screencast.

I'd like to add it to the existing screencasts, but also to the specific docs page listed above. I can update the website once the video URL is available.

Thank you :pray:

PS: No rush on this, settle in first and catch up :smile:

**Comment by pawlean** [comment]
Closing this as tracking in #1178.
