### ISSUE TITLE
Landing page revamp

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1004]
Only 3,7% of all website users view /features. That's why we decided to merge the landing page on features. In the same go, we also included some messaging and visual improvements.

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1559%3A17
![Home - merged features (3)](https://user-images.githubusercontent.com/46345125/133974828-0d6a46ab-9fec-4e7e-a511-aa2b975530f0.jpg)

**Comment by ChristinFrohne** [comment]
I added a few comments to the Figma file to explain the implementation cc @nisarhassan12

**Comment by phimae** [comment]
@ChristinFrohne do we already know which updated tweets we will use for the social proof section? The JetBrains IDEs will show screenshots, too when hovering over, right?
