### ISSUE TITLE
Apply `max-width` design system

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#101]
"Alright, we've settled on a system for now.
* Based on a 1440 screen out max width is 1312px (so a 64px margin on either side). This can be a max width even on larger screens for now.
* We also have 1136px which has 152px margin on either side. Use this if anything is 1140 in the layouts.
* For the blog we have 1248px with a margin of 96px.
    * That should be it for modules on the 8px grid.
    * Then blog has a content width of 736px and some text pages have 900px. We know as a system this seems disjointed but we're trying to keep these dynamic, otherwise things start to look the same on each page."

**Comment by nisarhassan12** [comment]
@mikenikles Is that still relevant with the migration to Chakra UI ? Thanks

**Comment by mikenikles** [comment]
I think you meant Tailwind CSS 😉. Nope, no longer valid.

**Comment by nisarhassan12** [comment]
Yeah. I meant Tailwind 😄.

**Comment by mikenikles** [comment]
I hear good things about Chakra too, but haven't tried it yet :).

**Comment by nisarhassan12** [comment]
I have tried it and it makes things like themeing quite simple and easy also the builtin components are quite nice good looking and accessible.
