### ISSUE TITLE
"Don't Just Take Our Word for It" part is confusing

### ISSUE THREAD

**Issue by rugk** [gitpod-io/website#101]
**Describe the bug**

On the home page, there is this empty part:
![image](https://user-images.githubusercontent.com/11966684/56607304-83e36480-6608-11e9-8c8d-93b8f25b8656.png)

**To Reproduce**

Go to home page, scroll down. (Firefox here)

**Expected behavior**

Should there be something? I find this kinda confusing… :thinking:

**Comment by svenefftinge** [comment]
Das anyone know how to detect if content blocking is enabled via javascript or whether that's even possible?

**Comment by rugk** [comment]
…just detect whether the element is (still) there or not.

**Comment by JanKoehnlein** [comment]
Same here. ABP installed but deactivated on the website.
