### ISSUE TITLE
[Docs Feedback]: missing mention of `definetely-gp` in the docs

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/website#1017]
### Page URL

https://www.gitpod.io/docs/config-gitpod-file

### User feedback

In https://github.com/gitpod-io/definitely-gp, the website of the repo is listed as https://www.gitpod.io/docs/config-gitpod-file/#definitely-gp-repository, but the URL fragment `definitely-gp-repository` means that there should be a `Definetely-GP Repository` or something similar, but this is not present. It looks like this was here before, at least here: https://github.com/gitpod-io/website/commit/3ff31340b7ea2cee4ccb57458c7a007ad1784fb9#diff-a929df069aa26a0bb5e5d15f91433e9ab0a4d1d36db1f73892781c7a60b8140eL40.

## Possible resolutions
- remove the URL from the definetely-gp repo
- add some text in the docs about it

**Comment by mikenikles** [comment]
Closing due to https://github.com/gitpod-io/gitpod/issues/8473
