### ISSUE TITLE
Can't find any way to upgrade to Student Unlimited

### ISSUE THREAD

**Issue by FeixuRuins** [gitpod-io/website#1032]
After weeks of trying to get in touch with Gitpod about Student Unlimited, they finally whitelisted my school's domain. I then set my primary email on Github to it but nothing happened. Where do I sign up?

From @jankeromnes:
> 1. Make sure that `(email)` is your primary email address in https://github.com/settings/emails
> 2. Visit https://gitpod.io/subscription and upgrade to Student Unlimited

This is what I see on the Subscription page-
![image](https://user-images.githubusercontent.com/66232834/112869716-70aa6080-908b-11eb-8a1f-36774e71c3df.png)
No mention of the Student Unlimited plan.

Any help would be greatly appreciated. It's been 18 days since I ran out of hours and I've emailed Gitpod multiple times about the Student Unlimited plan and it feels like they're just ignoring me.

Gitpod is awesome, but trying to get Student Unlimited has been a terrible experience.

**Comment by jankeromnes** [comment]
Hi @FeixuRuins, so sorry that we were so slow to help you out.

Gitpod's admin interface shows you as verified student. Do you still not see the Student Unlimited plan in https://gitpod.io/plans ?

I agree that we should absolutely step up our support.

**Comment by FeixuRuins** [comment]
I see it now. It wasn't showing before the UI overhaul, for some reason.
Thank you!
