### ISSUE TITLE
[Docs Feedback]: Provide a "preview" indicator in the nav

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1070]
### Page URL

All

### User feedback

See https://github.com/gitpod-io/website/pull/1062#issuecomment-939904615

**Comment by loujaybee** [comment]
Just pulling the original image through for reference: 

![image](https://user-images.githubusercontent.com/5528307/137689561-0a6f1656-8d0f-4b3b-bc97-8962db7c74ac.png)

**Comment by mikenikles** [comment]
New "Beta" labels have been added.
