### ISSUE TITLE
Answer security questions

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1071]
Provide answers to the questions raised in https://dev.to/stack-labs/gitpod-how-to-use-kubectl-and-manage-kubernetes-clusters--4edp:

> Are Gitpod secrets really secured ?
> Are Gitpod workspace perfectly isolated ?
> Is it reasonable to put kubernetes cluster connection informations on Gitpod?

**Comment by chrifro** [comment]
@securitymirco What's the status here? :)

**Comment by securitymirco** [comment]
Closing this issue in favour of https://github.com/gitpod-io/website/pull/3156
