### ISSUE TITLE
[startups]: Swap the linked blog post to the local vs Gitpod comparison once #1084 is merged

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1095]

**Comment by nisarhassan12** [comment]
> Could you take care of this issue 🙏 ?

Sure. @ChristinFrohne Can you provide me with a mockup of how this is gonna look like ? i.e we are no longer gonna link to the blog post instead of the comparison page while the current widget is dedicated to posts(guides) and so on. We are probably gonna remove it right? and instead maybe add a link to the comparison page ? 

![image](https://user-images.githubusercontent.com/46004116/141250812-42da6e67-7834-4d27-9b3a-c304e469a346.png)

**Comment by ChristinFrohne** [comment]
sure @nisarhassan12  see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1818%3A234)
<img width="723" alt="Bildschirmfoto 2021-11-17 um 13 33 21" src="https://user-images.githubusercontent.com/46345125/142201408-50fcabed-26b9-489a-a438-aeb3259f22ba.png">

**Comment by nisarhassan12** [comment]
Fixed in #1442
