### ISSUE TITLE
Improve mobile view for landing page

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1165]
Biggest changes:
- adjusted spacing
- [x] new view for switching between different IDEs
- [x] move explaining text before images

Mockup: https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2427%3A354

**Comment by nisarhassan12** [comment]
> adjusted spacing

@ChristinFrohne I'll tackle adjusting the spacing in https://github.com/gitpod-io/website/pull/1268 as I already have some changes up relevant to this so I will make the rest of the relevant changes there.

**Comment by nisarhassan12** [comment]
Closing this as it is fixed by #1268 #1271
