### ISSUE TITLE
[Screencasts] Create new screencasts

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#1178]
Screencasts have proven to be popular with our existing and new users. Let's create some more! 🚀

This will track the requests that we've gotten from the community. Feel free to drop some ideas under this issue as well.

## IDE
- [x]  **VS Code Desktop Support (#1001) (filming done)** 
- [x] **OpenVSX Extensions (filming done)**
- [x] **Local Companion App (_first draft done_)**

## Meta
- [ ] Navigating & understanding Teams & Projects

## Workspace
- [x] **Using custom docker images (_first draft done_)**

## Self-hosted
- [ ] Follow through a self-hosted installation

## General
- [x] **Using Environment Variables (_first draft done_)**
- [x] ~How to ssh into Gitpod~ (covered by local companion app)
- [x] **Using an iPad with Gitpod (filming done)**
- [x] **Git integrations (_first draft done_)**
- [x] How to use a database with Gitpod (filming done)

**Comment by Jsjkwnw** [comment]
Screencast porque dice (no se encuentra dispositivo)

**Comment by Siddhant-K-code** [comment]
> Follow through a self-hosted installation

Any Updates/ Plans to this? 
@pawlean
