### ISSUE TITLE
Add Hotjar or FullStory to `/docs`

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1186]
Review the following products:
* [FullStory](https://www.fullstory.com/)
* [Hotjar](https://www.hotjar.com/)
* Alternatives?

Decide which one we'll use and implement it for the docs located at `/docs`.

Depending on how involved the implementation is, let's create an open source Svelte component.

**Comment by chrifro** [comment]
We'll have a closer look at enabling website tracking and services to enhance the data next quarter. This process will be documented in Notion. Once a decision has been made, we'll summarise it in a new issue
