### ISSUE TITLE
[Docs Feedback]: Bash Code Wrong due to escaping when generating pages

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/website#1190]
### Page URL

https://www.gitpod.io/docs/self-hosted/latest/configuration/docker-registry

### User feedback

In part https://www.gitpod.io/docs/self-hosted/latest/configuration/docker-registry#example-google-cloud-registry-credentials
The code snippet is falsely generated:
![image](https://user-images.githubusercontent.com/37072526/139788795-5b727cf4-48b6-466e-88d8-f12bd25983ba.png)
It seems that they escape quotes next to them. Though the source code and generated markdown preview are correct.

On mdsvex's playground, it seems to work as expected:
![image](https://user-images.githubusercontent.com/37072526/139789163-46e86c97-659c-4e23-a1d0-0b011ae12689.png)

**Comment by mikenikles** [comment]
Thanks for letting us know. This may be related to #98 as well.

I tried in a new SvelteKit app, and it happens there too.
1. `npm init svelte@next my-app`
2. Follow the prompts
3. `npx svelte-add@latest mdsvex` and `npm i`
4. Add a new `src/routes/docs.md` file with the Markdown content that causes an issue

I'll continue to investigate 👀

**Comment by Siddhant-K-code** [comment]
This is still an issue, updated URL: https://www.gitpod.io/docs/configure/self-hosted/helm-deprecated/configuration/docker-registry

![image](https://user-images.githubusercontent.com/55068936/194611587-51ee636a-7aec-4834-a882-5ca2f3a7dd77.png)

**Comment by Cahllagerfeld** [comment]
Based on the above-posted screenshot, I assume this is solved 👍
