### ISSUE TITLE
Hide/Show notification banner on end/start dates

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1192]
### Describe your feature

Currently, [the announcement banner](https://github.com/gitpod-io/website/blob/ba9dd1864f61a7b6537c69189bdd0128ef5ae75a/src/components/banners/announcement.svelte#L10) appears constantly, a nice small optimisation could be a conditional start and end date that hides the banner after a certain time (and/or starts the banner when we want it to). 

### How to test

* Go to website (in incognito if you've already dismissed it)
* Refresh the website and you'll see the current announcement

See: [Internal Discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1635859047054400)

**Comment by ngonsoto** [comment]
Hi, I would like to work on this issue. 
As I understand, the feature defines a date range (start and end date) and shows the banner only in that date range.
Is it right?

**Comment by ngonsoto** [comment]
So I added the start/end date range for the banner and a timer which hides it after {n} seconds (currently 10 seconds in my fork). This does not close the banner permanently like the "X" button does, instead just hides it and can appear again if the website is reloaded.
Please let me know if any changes are needed or is it OK to make a pull request.

**Comment by nisarhassan12** [comment]
Hi, @ngonsoto Thanks for looking into it and sorry for the late response. 

> So I added the start/end date range for the banner

Only adding the start/end date range for the banner is enough for the PR to be made. So, please do Open up a Pull Request for that. 

> timer which hides it after {n} seconds

I'm not sure whether we want to hide it after {n} seconds when the user is on the site, mostly the announcements are important and want the users to see them and have them there unless they are seen and the user intentionally clicks on the close button to get rid of them.  I would like to know what others think about this cc @loujaybee @ChristinFrohne
