### ISSUE TITLE
package.json -> +        "husky": "^7.0.0",

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#1196]
On a fresh checkout of gitpod-io/website and prebuild the package json is modified:

```
iff --git a/package-lock.json b/package-lock.json
index 021a33d..c678ce3 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -24,7 +24,7 @@
         "github-buttons": "^2.19.1",
         "hast-util-heading-rank": "^2.1.0",
         "hastscript": "^7.0.2",
-        "husky": "^7.0.4",
+        "husky": "^7.0.0",
         "lint-staged": "^11.2.6",
         "mdast-util-to-string": "^3.1.0",
         "mdsvex": "^0.9.8",
```

1. Let's fix it
2. Is there a guide for updating nom dependencies. I would do it myself but remember something about svelte requires special steps.

**Comment by mikenikles** [comment]
I upgraded all dependencies a few days ago. The ones I didn't are no longer maintained and rewriting the code to use alternative libraries isn't feasible - too much effort for little gain.

Starting in January, we'll have a new team member who will be able to help us stay current.
