### ISSUE TITLE
[Docs Feedback]: How can I develop VS Code extensions?

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1209]
### Page URL

https://www.gitpod.io/docs/vscode-extensions

### User feedback

You mention isntalling from a VSIX but don't say how to do it. New extensions being tested against gitpod may not be in any registry yet.

**Comment by Siddhant-K-code** [comment]
We have sufficient number of information on the [updated docs](https://www.gitpod.io/docs/references/ides-and-editors/vscode-extensions#install-vs-code-extensions-from-a-vsix-file)
