### ISSUE TITLE
Fix footer layout

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1211]
**Issue:** we need to be consistent in our footer structure. It doesn't make sense to randomly use the Gitpod logo instead of spelling the name. Usually, it's spelled out (e.g. Gitpod vs Codespaces). Furthermore, it doesn't align with the Gitpod logo in front of the copyright 
<img width="408" alt="Bildschirmfoto 2021-11-04 um 10 04 27" src="https://user-images.githubusercontent.com/46345125/140286592-7ba6e299-373e-4880-97e7-4c5a0059f4bb.png">

**Solution:**
`Gitpod for startups`

cc @phimae

**Comment by phimae** [comment]
You have a point there - @JohannesLandgraf and I discussed this to make it stand out a bit but appreciate there should be consistency. I'm fine rolling back to normal text.
