### ISSUE TITLE
[contributing/cla]  Where contributions are not trival ("de minimis") 

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#1213]
>  Where contributions are not trival ("de minimis") Gitpod requires contributors to sign a contributors license agreement before we will be able to merge your contribution.
>
> Is this the case for `gitpod-io/gitpod`?
> 
> @meysholdt could you verify if this is the case? Do we merge community contributions for `gitpod-io/gitpod` without requiring a singed CLA when the change is only a typo?

_Originally posted by @gtsiolis in https://github.com/gitpod-io/website/pull/1187#r743150070_

**Comment by ghuntley** [comment]
Typically open-source projects with CLA take https://en.wikipedia.org/wiki/De_minimis into consideration in the implementation. Items such as spelling mistakes and 1-2 lines of code changes do not require a CLA. If Gitpod wants to do blanket CLA (which is fine) then the /contributing section will need updating.

cc @mads-hartmann.

**Comment by mads-hartmann** [comment]
@ghuntley @gtsiolis My preference would be to require CLA for all changes for the following reasons:

1. This simplifies the process a bit, we don't have to make a judgement call or specify what is considered a non-trivial change.
2. Once we have the [CLA Bot PR](https://github.com/gitpod-io/gitpod/pull/6318) merged (still pending legal sign off from @meysholdt) the process of signing the CLA is really lightweight and automatic
3. I don't believe the [CLA Assistant GH Action](https://github.com/cla-assistant/github-action) that we want to use makes it possible to distinguish between whether or not a PR needs to have CLA signed. The CLA requirement is the user and not the change-set as far as I can see :)

**Comment by 0Grit** [comment]
As long as it's literally 'trivial' to sign the CLA.
