### ISSUE TITLE
[contributing] documented workflow should be Gitpodified 

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#1214]
# Issues

Over at https://www.gitpod.io/docs/contribute/features-and-patches/submitting-a-pull-request the documented workflow assumes someone is contributing using their local computer instead of using the benefits that Gitpod brings. 

# Next steps

Reduce contributing steps down to `https://gitpod.io/#https://github.com/:username/gitpod`

# See also
>**thought**: I thought it would be as easy as visiting the fork, no?
>  https://gitpod.io/#https://github.com/:username/gitpod

_Originally posted by @gtsiolis in https://github.com/gitpod-io/website/pull/1187#r743136830_

**Comment by aserputov** [comment]
Hey, @ghuntley  that's sounds like a good issue, could you please assign me to this and give a lit bit more info ?

**Comment by ghuntley** [comment]
https://user-images.githubusercontent.com/127353/140470787-d5a84934-cc0e-474e-9384-c2bee1e5e17f.MOV

**Comment by aserputov** [comment]
@ghuntley, thank you very much. I will try it now:)

**Comment by Cahllagerfeld** [comment]
I think this is closeable, isnt it?

**Comment by aserputov** [comment]
@Cahllagerfeld I think so too.

**Comment by Cahllagerfeld** [comment]
Closed with PR #1219
