### ISSUE TITLE
[Docs Feedback]: Vim example for extensions not working

### ISSUE THREAD

**Issue by omenking** [gitpod-io/website#1222]
### Page URL

https://www.gitpod.io/docs/references/gitpod-yml#vscode.extensions

### User feedback

While reading the documentation I saw the vim extension example.
Upon starting up my workspace it said it was not valid.
Either I am referencing wrong or the documentation is wrong or incomplete when citing the name for this extension

<img width="446" alt="Screen Shot 2021-11-08 at 7 09 18 AM" src="https://user-images.githubusercontent.com/7776/140740047-906bb4fa-831d-4ac3-bc3f-02119ed3c01e.png">

```
vscode:
  extensions:
    - vscode.vim
```

<img width="824" alt="Screen Shot 2021-11-08 at 7 13 23 AM" src="https://user-images.githubusercontent.com/7776/140740187-de47f63a-24b5-49d0-a6ce-029af6332643.png">

https://open-vsx.org/extension/vscodevim/vim

**Comment by akosyakov** [comment]
👍 It should be `vscodevim.vim`.

**Comment by omenking** [comment]
I am giving it a go

**Comment by omenking** [comment]
I have confirmed this fixes the issue. Opening Pull Request

**Comment by omenking** [comment]
PR submitted.
https://github.com/gitpod-io/website/pull/1224
