### ISSUE TITLE
Update links for the newsletter signups

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1229]
**Problem:**
Currently, we are just storing the signups in a Google Sheet but don't use the information. Automatically integrating the data and aligning the information in case the user already exists, is technically quite complex. See also [#6509
](https://github.com/gitpod-io/gitpod/issues/6509)
**Solution:**
We decided to go for an MVC by linking all "sign up of newsletter" buttons to h[ttps://gitpod.io/notifications](https://gitpod.io/notifications) so the users can update the settings themselves. We might iterate on this flow in the future, but for now, this is the simplest implementation.

**Comment by nisarhassan12** [comment]
@ChristinFrohne Do we want to keep the relevant code for the signups ? as we might iterate on this flow in the future or do we want to get rid of it (as we want to the ambassador program signups https://github.com/gitpod-io/website/pull/1252#issuecomment-971365831) ? Thanks

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made Pr https://github.com/gitpod-io/website/pull/1263 for fixing this. The newsletter covers both the changelog updates + dev x updates and tips atm right ? 
![image](https://user-images.githubusercontent.com/46004116/142480979-05989da1-041e-4a30-acc0-f3c5af0bd8a6.png)

Maybe it's just me but to me, the UI for the notifications is not descriptive enough i.e it does not mention where to sign up for the newsletter instead there are checkboxes for different types of email notifications. I think it would make sense to have some descriptive text on the notifications explaining about newsletter signs. WDYT ? Thanks

**Comment by ChristinFrohne** [comment]
I agree, can you open an issue for that in [https://github.com/gitpod-io/gitpod/issues](https://github.com/gitpod-io/gitpod/issues) so the product team can look into it? 🙏

**Comment by nisarhassan12** [comment]
> can you open an issue for that

Done https://github.com/gitpod-io/gitpod/issues/6799

**Comment by ChristinFrohne** [comment]
Remember to move issues to the [Engineering Inbox](https://github.com/orgs/gitpod-io/projects/3) whenever you create a new issue. By that, you can be certain that it will be looked at
