### ISSUE TITLE
[Docs Feedback]: Explicitly state and show support for Chrome Browser Extension for various git hosted providers

### ISSUE THREAD

**Issue by omenking** [gitpod-io/website#1236]
### Page URL

https://www.gitpod.io/docs/browser-extension

### User feedback

When reading this page I could not tell if the chrome extension was only for GitHub or for all providers.

Ideally showing screenshots would be useful to end user, simple solution is to add the names.

<img width="1068" alt="Screen Shot 2021-11-10 at 7 16 45 AM" src="https://user-images.githubusercontent.com/7776/141111727-bbaa05d4-af55-4fea-b661-4c04c850d841.png">

---
You can use these screenshots if you like:

<img width="577" alt="Screen Shot 2021-11-10 at 7 06 16 AM" src="https://user-images.githubusercontent.com/7776/141111989-3fb65951-9f1b-47a3-81c3-34c1210eaed8.png">

<img width="986" alt="Screen Shot 2021-11-10 at 7 20 27 AM" src="https://user-images.githubusercontent.com/7776/141112108-99ee3e94-b7fe-4d4d-9da2-aaa42edd27d0.png">

**Comment by pawlean** [comment]
We've updated this now, thanks @omenking! https://www.gitpod.io/docs/browser-extension
