### ISSUE TITLE
Fresh coat of paint for the self hosted docs post installer

### ISSUE THREAD

**Issue by metcalfc** [gitpod-io/website#1237]
- [ ] Review docs post install guide updates
- [ ] Move self hosted docs to markdown
- [ ] Add day 2 operations section (updates, troubleshooting, etc)

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
