### ISSUE TITLE
[Docs - Quickstart] - Requesting swift

### ISSUE THREAD

**Issue by eob** [gitpod-io/website#1245]
Hello!

We develop with server-side Swift and are wondering if you would consider supporting! It's not broadly known but Swift works just fine on linux.

Here is an example from GH Codespaces (I haven't tried this) that might be useful to see:

https://github.com/taki-on/swift_codespaces

**Comment by Siddhant-K-code** [comment]
duplicate of https://github.com/gitpod-io/website/issues/1750
