### ISSUE TITLE
[Docs Feedback]: Small mistake describe scope pattern in documentation

### ISSUE THREAD

**Issue by omenking** [gitpod-io/website#1250]
### Page URL

https://www.gitpod.io/docs/environment-variables

### User feedback

It says "repo/owner"

<img width="766" alt="Screen Shot 2021-11-15 at 4 12 59 PM" src="https://user-images.githubusercontent.com/7776/141854599-fd0ef5dc-0fd2-46d5-be24-4c33340a9889.png">

In the actual UI it says "org/project"

<img width="543" alt="Screen Shot 2021-11-15 at 4 11 52 PM" src="https://user-images.githubusercontent.com/7776/141854634-56a9fbab-f34c-4c91-90ef-a27609bd80f9.png">

So I think the docs means to have "owner/repo"

It may be a good idea to settle on some consistent language here.

**Comment by gtsiolis** [comment]
Nice catch, @omenking! Added https://github.com/gitpod-io/website/pull/1255 and https://github.com/gitpod-io/gitpod/pull/6737 to resolve this.
