### ISSUE TITLE
[epic] Improve responsive design

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1253]
When checking the website on my phone, instead of using the DevTools mobile preview, many things don't look right. 
We need to watch out more for responsive layout when merging new pages and prioritize fixing the current issues. Many things look really bad!
When using components consistently, it should become a lot easier.
cc @nisarhassan12 

It's probably best to address these issues in separate PRs

Happy to discuss if anything is unclear 🙂

|status quo| improvement|
|-|-|
|reduce top spacing. This issue occurs on many pages. All pages should be checked ![IMG-7904](https://user-images.githubusercontent.com/46345125/141961908-f70d6231-dbfc-41df-bbc0-b0a9442327fc.PNG)|  reduce spacing. 48 or 56px should be good ✅ |
| improve call out section ![IMG-7909](https://user-images.githubusercontent.com/46345125/141962763-417f37a7-f033-4ebf-b008-9ebcbf209b70.PNG)| see also #1166 Fixed ✅ <img alt="Bildschirmfoto 2021-11-16 um 10 54 54" src="https://user-images.githubusercontent.com/46345125/141963166-3c6465fc-09c6-423d-af30-9f991b538247.png">|
| the spacing on /contact is off ![IMG-7911](https://user-images.githubusercontent.com/46345125/141963488-bfffb797-c3bc-4b78-a37d-5576a96aa607.PNG)| reduce spacing ✅ |
| icons are partially blurry ![IMG-7907](https://user-images.githubusercontent.com/46345125/141965066-d3229a0a-c18b-47c3-8a52-9798dfea58d9.PNG)| optimize image performance see also #155 |
| reduce spacing boxes and have a consistent styling ![IMG-7912](https://user-images.githubusercontent.com/46345125/141964059-1bf2ea9e-97bc-47f5-ad8c-430a8ae5e015.PNG)| reduce top spacing. See also https://github.com/gitpod-io/website/issues/1144#issuecomment-951643112 ✅|
| adjust the alignment for the FAQ section ![IMG-7908](https://user-images.githubusercontent.com/46345125/141964316-2b6e9ff4-e38e-4b13-bc9b-09c50ddbc506.PNG)|  see [Figma mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1%3A5009) ✅  <img width="376" alt="Bildschirmfoto 2021-11-16 um 11 04 42" src="https://user-images.githubusercontent.com/46345125/141964916-dd85feba-f35e-4020-bfd5-f694f261cf2c.png">|
| for features the text should always be before the image and the spacing needs to be adjusted so it's clear which parts belong together. The issue can be found on several pages not just the landing page, e.g. Gitpod for startups![IMG-7906](https://user-images.githubusercontent.com/46345125/141965216-46d336ee-748d-41c3-b10f-0b6001c42523.PNG)| see also #1165, [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2427%3A354)✅ <img width="379" alt="Bildschirmfoto 2021-11-16 um 11 08 17" src="https://user-images.githubusercontent.com/46345125/141965504-15d30339-5f5b-4c09-ab0e-eeec00f9259c.png">|
| the container width for text should be 343px. Currently we sometimes use 343px e.g. on the landing page or /changelog and 296px on pages like /community or /for/startups. On mobile we should try to use as much vertical space as possible to reduce the need to scroll. ![IMG-7905](https://user-images.githubusercontent.com/46345125/141966602-bd080eca-f0d1-4914-a6d8-019af7b277cd.PNG)| Use a width of 343px for text and boxes ✅. See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2427%3A354)| 
|on /community the same box style is sometimes 343px width (that's correct) and sometimes significatly smaller. We need to be consistent in the layout. <img width="363" alt="Bildschirmfoto 2021-11-16 um 11 20 23" src="https://user-images.githubusercontent.com/46345125/141967395-ef1695da-a24c-4fc6-94b8-fc907b6706bc.png"> | use a consistent width of 343px<img width="301" alt="Bildschirmfoto 2021-11-16 um 11 21 27" src="https://user-images.githubusercontent.com/46345125/141967574-49219873-e2a3-4e15-ab48-2c9adae64cd9.png">|
| Align buttons <img width="360" alt="Bildschirmfoto 2021-11-16 um 11 15 13" src="https://user-images.githubusercontent.com/46345125/141967645-80fedfde-ef32-4ff2-af1a-3846e309cd25.png">| If they don't fit next to eachother they need to be left aligned. See also #1150 ✅ |
| reduce top spacing ![IMG-7902](https://user-images.githubusercontent.com/46345125/141967876-774cba2d-380c-4413-bd24-8216d8dc7dc2.PNG)| reduce top spacing and have it consistent for all boxes ✅ |
| The spacing in the boxes on /pricing is off ![IMG-7903](https://user-images.githubusercontent.com/46345125/141968028-6e530e2e-dbef-43bc-b753-2e9f169fc4e4.PNG)| there is a new mockup for the pricing page coming soon, so we can include that change then.|
| the buttons for the different IDEs are too small to click on and the resolution of the icons is terrible.  <img width="357" alt="Bildschirmfoto 2021-11-16 um 11 30 36" src="https://user-images.githubusercontent.com/46345125/141969309-b2d318dc-0f5e-4786-970c-a8dc7c847c90.png">|  see also #1165 ✅<img width="303" alt="Bildschirmfoto 2021-11-16 um 11 33 13" src="https://user-images.githubusercontent.com/46345125/141969434-b45952bc-12b8-4c7d-ac1f-41dfe6b72462.png">

**Comment by nisarhassan12** [comment]
> reduce spacing. 48 or 56px should be good

@ChristinFrohne What should be the device width starting from which or going below the mobile styles should be applied ?

**Comment by ChristinFrohne** [comment]
>@ChristinFrohne What should be the device width starting from which or going below the mobile styles should be applied ?
Also when the banner is shown do we have to make sure that even then the spacing is 48px at the top on mobile ? Thanks

 @nisarhassan12 Regarding the responsive design, would be great if you could get inspiration for that from other best practices. 
The spacing should stay the same also when we have an active banner
