### ISSUE TITLE
Review all links to /contact

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1257]
Noticed that many pages don't link directly to the contact form after  #976 has been merged.

Examples: 
- on https://www.gitpod.io/docs/professional-open-source#who-is-eligible the "get in touch" link should link to https://www.gitpod.io/contact/support?open-source-sponsorship
- on https://www.gitpod.io/self-hosted "get in touch" should link to https://www.gitpod.io/contact/sales?self-hosted

Next action:
- check all links to /contact if they are correct or if they need to be specified linking directly to the related contact form

**Comment by nisarhassan12** [comment]
@ChristinFrohne In the Structured data(that is used by Google Jobs) on our careers page in the contact point for the hiring organization we have the URL set to https://www.gitpod.io/contact/ if one wants to reach us it in regards to a career where are they supposed to go ? Should I make this link point to support ? and maybe we add a new subject there ?
