### ISSUE TITLE
Anchor links with square brackets scroll to top of page

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1258]
### Page URL

https://www.gitpod.io/docs/references/gitpod-yml

### User feedback

The anchor links with square brackets seem to not work fully for some reason. 

**Steps to replicate:**
1. Go to: https://www.gitpod.io/docs/references/gitpod-yml
1. Click an anchor that includes square brackets, e.g. `ports[n].visibility`
1. https://www.gitpod.io/docs/references/gitpod-yml#ports%5Bn%5D.visibility

**Expected result**
* Scrolls to anchor

**Actual result**
* Scrolls to top of page

Note: If you click the anchor for a second time, it dose work, and does scroll.

**Comment by akrifari** [comment]
I would like to help this one.

**Comment by nisarhassan12** [comment]
Thanks a bunch, @akrifari for offering to help. I have assigned you to the issue.
