### ISSUE TITLE
Link directly from CTA to gitpod.io/new (encore)

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#1270]
Linking directly from 'Try now' or 'Signup' CTA buttons, to `gitpod.io/new`, should afford the same flexibility of choices as going through the current [#get-started](https://www.gitpod.io/#get-started) section, while allowing users to skip the slighlty-awkward intermediate step.

This should be doable once users can also create new repos from templates during the Login flow in the Dashboard - see https://github.com/gitpod-io/gitpod/issues/5583

See #1139 and #1194 for an earlier run at this, which was reverted.

**Comment by phimae** [comment]
Does it make sense to close this issue? @jldec

**Comment by jldec** [comment]
Thanks @phimae 
Closing since we link directly from the CTA to `gitpod.io/workspaces` now.
See https://github.com/gitpod-io/website/pull/1836
