### ISSUE TITLE
Provide example / contextual URL on `/#getting started`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1274]
### Page URL

https://www.gitpod.io/#get-started

### User feedback

Provide a full example link for the "prefix any URL". The feedback comes from [this usability test (internal link)](https://www.notion.so/gitpod/Vinny-Ruia-f687beea5c79434aa3c3bbc66dc16f9a) where a user tried to paste without the https, suggesting a full URL example here could help. 

![image](https://user-images.githubusercontent.com/5528307/142922700-f128d834-f1ed-4561-ab6d-a41db044fa4b.png)

**Comment by Siddhant-K-code** [comment]
For Which git context URL, we should be biased towards?

It can be something like this:
`gitpod.io/#https://github.com/gitpod-io/website`

> not `Gitpod` repository, because it is huge.
