### ISSUE TITLE
Document VS Code Settings Sync Feature

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1276]
* Users are often unaware of the VS Code settings sync feature and how it works [[1](https://github.com/gitpod-io/gitpod/issues/5931)][[2](https://github.com/gitpod-io/gitpod/issues/7529)]
* We should describe to users how this feature works and how to set it up for their IDE
* e..g on https://www.gitpod.io/docs/editors/vscode-browser

See this [internal link](https://gitpod.slack.com/archives/C01KPEPNBD0/p1637654418143200)

At the time of writing, the extensions page is separate: https://www.gitpod.io/docs/vscode-extensions#user-extensions, we should look into the content of this page, and see if consolidating makes sense.

**Comment by akosyakov** [comment]
It's important to clarify that different auth providers are used in VS Code Desktop and Web, so one cannot expect them to sync automatically, see https://github.com/gitpod-io/website/issues/1282
