### ISSUE TITLE
[Docs - Quickstart] - Requesting html

### ISSUE THREAD

**Issue by vryahn** [gitpod-io/website#1279]
Add HTML support pls

**Comment by pawlean** [comment]
Hey @vryahn! We have one [here](https://www.gitpod.io/docs/languages/html).

**Comment by nisarhassan12** [comment]
What Pauline shared is fine(although it is a bit outdated) @vryahn Let us know in case you have any questions or need help with getting up and running with your HTML project with Gitpod. 

I'm closing this as we're probably not gonna add a quickstart for HTML.
