### ISSUE TITLE
Add a new Careers page

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#128]
We'd like to add a new page to the website, at the address `www.gitpod.io/careers`, with a list of job opportunities and contact info for people who'd like to join us. ❤️

Here is a mock-up of how the page could look like:

<img width="473" alt="Bildschirmfoto 2019-05-17 um 14 17 25" src="https://user-images.githubusercontent.com/599268/57931462-ce2ecd00-78b8-11e9-9c3d-0109984ba289.png">

(Note: The texts in this mock-up are mostly placeholders still. 😅 We'll rephrase them into actual offers pretty soon.)

**Comment by jankeromnes** [comment]
FYI, here is the minified SVG for the Team Icon:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="181.016" height="124.664"><g fill="#1e1e1e" stroke="#26a4dd" stroke-width="2"><g><path d="M75.275 110.249s-9.629-64.824 22.57-65.9 20.844 65.9 20.844 65.9"/><g transform="translate(80.335 12.757)"><ellipse cx="16.98" cy="16.432" rx="16.98" ry="16.432" stroke="none"/><ellipse cx="16.98" cy="16.432" rx="15.98" ry="15.432" fill="none"/></g></g><g><path d="M122.268 123.96s-12.242-82.425 28.7-83.789 26.506 83.789 26.506 83.789"/><g transform="translate(128.7)"><ellipse cx="21.589" cy="20.892" rx="21.589" ry="20.892" stroke="none"/><ellipse cx="21.589" cy="20.892" rx="20.589" ry="19.892" fill="none"/></g></g><g><path d="M105.752 124.496s-9.58-64.473 22.439-65.539 20.738 65.539 20.738 65.539"/><g transform="translate(110.781 27.535)"><ellipse cx="16.887" cy="16.342" rx="16.887" ry="16.342" stroke="none"/><ellipse cx="16.887" cy="16.342" rx="15.887" ry="15.342" fill="none"/></g></g><g><path d="M2.433 110.44s-9.631-64.828 22.568-65.9 20.844 65.9 20.844 65.9"/><g transform="translate(7.495 12.946)"><ellipse cx="16.98" cy="16.432" rx="16.98" ry="16.432" stroke="none"/><ellipse cx="16.98" cy="16.432" rx="15.98" ry="15.432" fill="none"/></g></g><g><path d="M38.698 123.96s-12.242-82.425 28.7-83.789 26.506 83.789 26.506 83.789"/><g transform="translate(45.13)"><ellipse cx="21.589" cy="20.892" rx="21.589" ry="20.892" stroke="none"/><ellipse cx="21.589" cy="20.892" rx="20.589" ry="19.892" fill="none"/></g></g></g></svg>
```

**Comment by ChristinFrohne** [comment]
Here is the mockup with the moved text
<img width="632" alt="Bildschirmfoto 2019-05-21 um 11 11 41" src="https://user-images.githubusercontent.com/46345125/58083568-88744c00-7bb9-11e9-8876-45b52945e231.png">

**Comment by jankeromnes** [comment]
Thanks, and great texts! I would apply again. 🙂

**Comment by ChristinFrohne** [comment]
Here is the text for the site: 

Gitpod: 
Gitpod is an online one-click IDE that launches ready-to-code dev environments from any GitHub page. Automating development environments eliminates hours of tedious setup time, improves teamwork, and makes software development more reproducible and scalable. 

We started developing Gitpod about 2 years ago and this April we officially launched it. Gitpod is a very young product which gives you lots of opportunities to shape its future. Currently we’re working in a team of less than 20 people and we’re planning to grow continually. 

Typefox:
TypeFox is the company behind Gitpod with a team of developer tool specialists and longtime contributors to many open-source projects. We’re a driving force behind the language server protocol and initiators of Eclipse Theia, the next generation IDE that powers Gitpod. A characteristic of our team is a fervour to learn new things. We’re convinced that missing knowledge shouldn’t hold one back, but encourage us to learn more. 

Team:
We’re a young and tech-driven team with the mission of creating developer tools for everyone. In our team we seek for an open and honest mindset, as well as an effective pragmatism. We lead, collaborate and contribute for open-source projects and would love to share that with you. We’re convinced that continuous learning and exploring is the way to go for sustainably building the best solutions. Therefore we’re always curious about new approaches.

**Comment by ChristinFrohne** [comment]
edited wording
<img width="630" alt="Bildschirmfoto 2019-05-28 um 15 35 05" src="https://user-images.githubusercontent.com/46345125/58482238-4a999980-815e-11e9-8984-1317b1f5e9b5.png">

**Comment by jankeromnes** [comment]
New Careers page is up-to-date. More work is happening in #165, so I'll close this issue.
