### ISSUE TITLE
Update /pricing

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1284]
**Major changes:**
- the self-hosted plans are becoming more present
- a feature table is added to compare plans
- the FAQ section is extended and updated
- a trusted by section is added
- tooltips are added to provide more information on certain features
- the responsive design is improved

**Mockups**
Note: there are some comments in the figma file to clear questions about the content and implementation
<img width="1440" alt="Pricing -new" src="https://user-images.githubusercontent.com/46345125/143419325-38ecb986-4cb7-443b-a885-25c80a12fa0e.png">
![Self hosted -new](https://user-images.githubusercontent.com/46345125/143419338-e19381d3-91a7-4b39-9db3-6c34bde8d235.jpg)
[mockups](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2828%3A1288)

**Comment by nisarhassan12** [comment]
>  Note: there are some comments in the figma file to clear questions about the content and implementation

@ChristinFrohne Should I wait for them to be resolved before starting the implementation ?

**Comment by ChristinFrohne** [comment]
oh no, the comments are there for you to help you implement it. e.g. the content of the tooltips. The mockup is ready to go, otherwise, I would have added a "draft" label to it. 🙂

**Comment by nisarhassan12** [comment]
Ah. Sorry I didn't understand it earlier. Now it makes sense.
