### ISSUE TITLE
definitely-gp - elaborate on how to use it

### ISSUE THREAD

**Issue by alzix** [gitpod-io/website#129]
> Sometimes you can’t check in a .gitpod.yml file, for instance because you do not have sufficient access rights. However, you can still provide a .gitpod.yml file through the central definitely-gp repository. 

please elaborate on how

**Comment by jankeromnes** [comment]
Hi @alzix, this is where (in my understanding) Gitpod tries to find a `.gitpod.yml` file, by order of priority:

1. Checked into repository
2. In our [definitely-gp](https://github.com/gitpod-io/definitely-gp) repository, inside a folder that has the same name as the project (e.g. for https://github.com/github/hub, you should add a directory called "hub" in definitely-gp, and place your `.gitpod.yml` inside it)
3. Default `.gitpod.yml` as a fall back

**Comment by jankeromnes** [comment]
Also, I agree that we should probably also elaborate on that on the website directly.

**Comment by alzix** [comment]
>  inside a folder that has the same name as the project

i kind of found out it myself from one of the examples/blogs. Adding this list to website will help.

another thing to consider is mapping .gitpod.yml to a repository. It is not alway 1:1 mapping.
Same configuration may suite multiple projects/repos. Duplicating Docker files and .gitpod.yml files does not seems scalable solution - but this item probably belongs to its own thread :)
