### ISSUE TITLE
/newsletter

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#1291]
# overview

I'm finding a need when engaging with social media to have a "yeah, a future blog post will go into this. Signup to the newsletter"

https://twitter.com/iamvlaaaaaaad/status/1465791596796989449
https://twitter.com/sluongng/status/1465780178219683846?s=20
https://twitter.com/micheal/status/1465792709864484867?s=20
https://twitter.com/olearycrew/status/1465841366089576450?s=20

# problem

The way someone can join the newsletter right now requires them to have a Gitpod account

# request

- Create /newsletter
- Have contents on the website a form where people can signup to the newsletter
- Have contents on the website showcase and set expectations of what they will receive.

**Comment by nisarhassan12** [comment]
Hi. @ghuntley Thanks for bringing this up. See https://github.com/gitpod-io/website/issues/1229#issue-1048657896, https://github.com/gitpod-io/gitpod/issues/6799 while it would be great to have a `/newsletter` but it is technically quite complex. 

![image](https://user-images.githubusercontent.com/46004116/144911872-39aab8e8-81fd-4eef-82bc-3cbcd035d03c.png)

**Comment by nisarhassan12** [comment]
I'm closing this. Please re-open it if we decide to change what we currently have.
