### ISSUE TITLE
Make the prefixing page interactive

### ISSUE THREAD

**Issue by 32leaves** [gitpod-io/website#13]
It would be cool if one could enter their own Github URL on the website and actually open it:
<img width="1111" alt="Screenshot 2019-03-19 at 12 52 23" src="https://user-images.githubusercontent.com/3210701/54604033-14e18180-4a46-11e9-8bbe-c47d0079d7a4.png">

**Comment by svenefftinge** [comment]
I have changed back to an image, to better get the message across.
