### ISSUE TITLE
After navigating pages from the footer the back button does not takes the user to the correct position.  

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1303]
After navigating to different pages of the site via the footer and then navigating back to the homepage via the browser back button does not always takes you to the correct position(from which the user navigated to the page). See the below video to better understand this

https://user-images.githubusercontent.com/46004116/144517427-f4a39333-d09d-4de4-acb2-eba23d4c4467.mov

I was able to reproduce this issue on many pages i.e Pricing, Careers, Local development and so on. Also, I noticed that this does not happen on the Changelog page.

**Comment by nisarhassan12** [comment]
@mikenikles This seems to be impacting the navigation in Safari and the impact is not so small. If one goes to page like Contact or the Changelog and then clicks the Signup button from the fixed nav it does not goes to the Get started now section as expected.  

https://user-images.githubusercontent.com/46004116/145487850-bcb83d1a-4a83-4eb1-84dc-88bdcdc86fd8.mov

**Comment by Siddhant-K-code** [comment]
@chrifro, It is resolved now. See 👀 



https://user-images.githubusercontent.com/55068936/215393058-cc978357-f8d9-4114-8136-7c75eee08d3a.mov
