### ISSUE TITLE
Get started buttons misaligned on the docs landing page

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1307]
More context in #1243.

@ChristinFrohne what device caused the issue with the buttons not being centered?

Looking at various devices at https://www.responsinator.com/?url=https%3A%2F%2Fdeploy-preview-1243--gitpod-kumquat.netlify.app%2Fdocs doesn't show one that causes it.

If you manually resized the browser window, we likely have other places on the site that could look a bit off. In this particular case, there isn't enough space on your screenshot to show three cards next to each other. As Julian suggested, we can either clip the text in the buttons (not preferred) or find a way to dynamically shrink the font size.

Alternatively, we show the stacked layout at a wider screen size. What do you think?

_Originally posted by @mikenikles in https://github.com/gitpod-io/website/issues/1243#issuecomment-982697708_

**Comment by nisarhassan12** [comment]
Closing this as @ChristinFrohne already replied in the PR about this https://github.com/gitpod-io/website/pull/1243#issuecomment-986509231 Please re-open the issue if we want stuff to be further fine tuned. Thanks
