### ISSUE TITLE
Add an education page

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#131]
We want to set up an education page, so teachers can easily see the benefit for their students, the pricing and how to contact us 

Current mockup:
<img width="478" alt="Bildschirmfoto 2019-05-20 um 13 40 41" src="https://user-images.githubusercontent.com/46345125/58019065-e4c96400-7b04-11e9-84f7-ef225b92f060.png">

**Comment by ChristinFrohne** [comment]
text: 

No setup
Don’t waste time on tedious setup. With Gitpod developer environments are automated, reproducible and versioned.

Works on every device
With Gitpod coding gets accessible for everyone. Your students can contribute with a Chromebook or a tablet.

Enhances the workflow
Create customized lessons for your students. Everyone can start working on new assignments within minutes.

Highly Collaborative
Gitpod strengthens collaboration between your students. Code reviews have never been this easy and sharable snapshots foster the team workflow.

Continuous support
Easy maintenance, flexible subscriptions and continuous support if needed.

High security
Data integrity is of utmost importance. Gitpod has high security standards to keep your students and their data safe.


Our mission is to convey our passion for coding to students by eliminating barriers. 

Pricing
We love to support educational programs. Thats’s why we have special a pricing for universities, colleges, schools and non-commercial  courses. Students also have the opportunity to get an individual subscription for 75% less than usual.

Let’s guide the way to code, not to configuration settings.

Please contact us if you have any question.

If you’d like to use Gitpod for commercial courses, please have a look at our partner program.

**Comment by jankeromnes** [comment]
Quick question: What is a "commercial course"?

**Comment by ChristinFrohne** [comment]
I was thinking about private courses where the user has to pay for it. Like edureka.co or udacity.com for example. They also offer training courses for businesses.  The courses on these sites cost lots. So I thought as they seem to have a commercial purpose, they can paid more for Gitpod than schools. Do you think differently?

**Comment by jankeromnes** [comment]
Thanks for explaining! You make a good point, but I'm not quite sure yet how we'll be able to draw the line.

I think that for any university, you have to pay _some_ registration fee (I paid like 200€ / year for Uni and 700€ / year for Eng school), but it can go up to very high (e.g. for "MBA" programs). Also UK and US universities always cost a lot (I think upwards of 9000€ / year). So maybe a threshold on registration fees doesn't make sense.

Maybe the difference is between "full-time studies" and "single-focus training programs"? But then, should we not give student discounts to people following programs like coding bootcamps? (That's people who are just now learning about programming, just like university students.)

**Comment by jankeromnes** [comment]
In order to simplify, I guess we could just accept people who are full-time students at a school or university, i.e. not just following a single / commercial / short-term course?

**Comment by ChristinFrohne** [comment]
yeah, I get your point. I was btw. not talking about the students. There we already have the system with the email with works alright, I guess. I meant the classroom subscription. Could we not just offer it to all official educational programs certified by a state or free coding courses like freecodecamp. And everyone else pays more? I got the idea for this structure from another site which I can't remember now..
Anyways, if you think it's too complicated to differentiate, we can skip it for now

**Comment by jankeromnes** [comment]
> Could we not just offer it to all official educational programs certified by a state or free coding courses like freecodecamp. And everyone else pays more?

Sure, that sounds reasonable. 🙂 Thanks!

**Comment by jankeromnes** [comment]
@ChristinFrohne Another quick question: Reading the page, I don't fully understand the pricing of the "Classroom" plan. Why does it start at $39? Is that for my entire class, or how many seats do I get for that price? (Actually, what is the price of a student seat?)

**Comment by ChristinFrohne** [comment]
The price is just a place holder. I didn't know if we already set up a pricing plan. I just guessed that it will variate depending on the amount of seats, so I put "from" in front. Maybe Gero knows more about the pricing.

**Comment by ChristinFrohne** [comment]
@jankeromnes I found the website, I mentioned before, with a similar education program. I was referring to https://www.jetbrains.com/community/education/

**Comment by jankeromnes** [comment]
Added in 065c4b6c8bda7c4a5e438be31b505f7b136b4086.
