### ISSUE TITLE
[Docs - New Feature]: FAQ seo

### ISSUE THREAD

**Issue by wanghaisheng** [gitpod-io/website#1324]
### Describe your feature

https://github.com/rodneylab/sveltekit-faq-page-seo

there is this tool but I could not figure out how to add this to website
though current site is nice

### How to test

``
```

**Comment by pawlean** [comment]
Do you want us to create a template for this tool @wanghaisheng? Feel free to create one and contribute it, if you'd like. :)

**Comment by wanghaisheng** [comment]
i am kind of code dumb.
how to  create a template 
Maybe I can try

**Comment by pawlean** [comment]
> i am kind of code dumb. how to create a template Maybe I can try

You're more than welcome to give it a go! 

To start, create a new repo on your GitHub account, follow the instructions of setting up for this: https://github.com/rodneylab/sveltekit-faq-page-seo then Gitpodify it (i.e. follow the instructions here: https://www.gitpod.io/docs/getting-started)

LMK how you get on!

**Comment by wanghaisheng** [comment]
I think you are misleading me
