### ISSUE TITLE
Update landing page with JetBrains screenshots

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1327]
The landing page needs to be updated with screenshots for all JetBrains IDEs that are currently in beta
<img width="1132" alt="Bildschirmfoto 2021-12-06 um 13 37 11" src="https://user-images.githubusercontent.com/46345125/144847615-304a8276-cd21-4b84-bef4-b354fa21e967.png">

**To do's:**

- [ ] take screenshots (size: 1250 x 800, zoomed-in, similar style to the existing screenshots, I used the Go examples) @loujaybee [[1](https://github.com/gitpod-io/website/pull/1225#issuecomment-966271470)]
- [ ] adjust screenshots with the current design @ChristinFrohne 
- [x] switch the toggle to Desktop when selecting any Jetbrains IDE @nisarhassan12

**Comment by ChristinFrohne** [comment]
Here are the new screenshots: https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4328%3A3489

**Order:** 
Beta:  GoLand, IntelliJ, PyCharm, Phpstorm
Soon: RubyMine, WebStorm

Could you take care of swapping them out @nisarhassan12 ?

The toggle should be on desktop for all JetBrains IDEs

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made this PR https://github.com/gitpod-io/website/pull/1560 to fix this. Please review it when you get time for some reason the Netlify deploy preview has not triggered which I have reported [here](https://gitpod.slack.com/archives/C01KGM9ETU6/p1644104267740279) meanwhile you can review the PR via opening a Gtipod workspace. 

> - [x]  The toggle should be on desktop for all JetBrains IDEs

Done the following is how it looks: 

![image](https://user-images.githubusercontent.com/46004116/152662762-cf75975c-d93e-487f-b3e5-5772af507032.png)

I have disabled the toggle(i.e it can't be clicked upon or used via a keyboard) when it is one of the JetBrains IDE as they don't have Browser versions so there is no toggling between the two the disabled state also makes this clearer. 

I came up with the disabled state styles myself for the toggle. Can you suggest something better and add it to the component library here https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=513%3A527  ? Thanks 🙏🏿
