### ISSUE TITLE
[code-quality]: refactor the usage of the Faqs component.  

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1360]
Currently, we have the Faqs component being used in different ways i.e on `/pricing` and `/self-hosted` the text contents live inside the page-specific component instance that live in for instance directories like `src/components/pricing` and in some other places they live in page-specific files that live inside the `src/contents` directory. 

It would be best to just have a generic Faqs component that we reuse consistently in all places.

**Comment by Cahllagerfeld** [comment]
I totally see this point, I've got just a small question related to that: 
On the pricing page, we're having quite specific content in the FAQ, here with images or buttons for examples 
<img width="1193" alt="grafik" src="https://user-images.githubusercontent.com/43843195/149086895-b4dc7f80-3c06-47e9-9730-7fdee24f5a3d.png">
We could store the things as a html-string and display it with a `@html`-directive.  In case we provide a `<slot />` for providing these custom things, we probably cant loop over this properly to generate the FAQ-Items. What do you think about this?

**Comment by nisarhassan12** [comment]
Thanks, @Cahllagerfeld for looking into this. 

> We could store the things as a html-string and display it with a @html-directive

I would personally prefer to go with this as it at the end lets us write less code thus resulting in better devx and maintainability and so on using <slot / > does have its advantages but for the Faqs the contents are mostly raw texts and some links so using @html directive is fine here.

**Comment by Cahllagerfeld** [comment]
<img width="1092" alt="grafik" src="https://user-images.githubusercontent.com/43843195/149129555-3b6f97bd-1827-4a75-8fd3-d14225843c5b.png">
The Implementation I did works so far. The only thing I see is that this kind of logics wont work within the `@html`-directive. Do you have an idea on how to fix this?
