### ISSUE TITLE
[Docs - Quickstart] - Requesting kotlin

### ISSUE THREAD

**Issue by asalvidev** [gitpod-io/website#1361]
since Kotlin is becoming quite a popular language, I think it would be useful to have a template based on Kotlin

**Comment by nisarhassan12** [comment]
Thanks, @asalvidev for the issue. @mikenikles or @ghuntley One of you might be interested in making this happen. Thanks

**Comment by Siddhant-K-code** [comment]
Implemented in https://www.gitpod.io/docs/introduction/languages/kotlin#kotlin-in-gitpod
