### ISSUE TITLE
Create Gitpod vs JetBrains landing page

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1363]
View [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=3509%3A2672)
![Gitpod vs JetBrain](https://user-images.githubusercontent.com/46345125/145968045-5c806fd9-d4f7-43d0-bd75-a5ce37002694.jpg)

**Comment by nisarhassan12** [comment]
Reopening it as it should not be closed until https://github.com/gitpod-io/website/pull/1366/#issuecomment-998407677 is reverted after reverting the expected review comments.

**Comment by loujaybee** [comment]
I guess this can be closed @nisarhassan12 / @chrifro ? 

Will close because of: https://www.gitpod.io/vs/jetbrains-space

Feel free to re-open if I'm missing something!
