### ISSUE TITLE
[mobile]: some links are in-accessible when the site is being viewed upon in the landscape mode. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1371]
![image](https://user-images.githubusercontent.com/46004116/146609275-6c203ee5-7c9d-4460-9648-86ca377e8585.png)

**Comment by rajatgupta24** [comment]
Hey @nisarhassan12, if the issue isn't taken by anyone, can I do it?

**Comment by rajatgupta24** [comment]
I tried changing the top padding, but there are still some screens on which all items are not visible, I think we should make it scrollable.

**Comment by Cahllagerfeld** [comment]
Hey @rajatgupta24, thanks for having a look into this 🚀 . Are you still working on this?

**Comment by nisarhassan12** [comment]
Sorry, @rajatgupta24 I missed your ping I was on vacation back then.

**Comment by rajatgupta24** [comment]
Hey @nisarhassan12, thanks for the response, yeah I'll be working on this, but I'll update you in 2-3 days, having practicals going on

**Comment by rajatgupta24** [comment]
Hey @nisarhassan12, I looked into it, we can fix it, by either adjusting the margin of nav-items or by adjusting the margin of divider in contact button, but I both are not looking good, 

there is another way of fixing it is commenting out the contact btn, which I think isn't good.
Any thoughts??

**Comment by nisarhassan12** [comment]
Thanks, @rajatgupta24 I think making the items container scrollable would work i.e you could set `overflow-y: auto` with `max-height: 100vh` on mobile on the items container and then it would automatically show the scroll bar.
