### ISSUE TITLE
[self-hosted]: improve the enterprise license form. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1381]
The form needs some improvements i.e the space above the text area label should be consistent in accordance with the rest of the labels + the selects don't have any default values which isn't great. 

![image](https://user-images.githubusercontent.com/46004116/146848004-b434a918-55fb-447d-b2c0-6029298ab8e5.png)

**Comment by nisarhassan12** [comment]
I will fix making the spacing consistent above the text area label in https://github.com/gitpod-io/website/pull/1329/

**Comment by ChristinFrohne** [comment]
>@ChristinFrohne Any suggestions on what can be used as the default values for the user selects ? Thanks

it's always great to have a look at how others are doing it. I guess the common solution would be to just use "Select"
