### ISSUE TITLE
create a reusable features table component. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1384]
In https://github.com/gitpod-io/website/pull/1084/commits/d32cc8c2ba6c165d04218d3647e44ad3a7ae7b50 I refactored some of the code relevant to the feature tables that we use but not all. Currently, there are some duplications/inconsistencies from page to page that is why we should create a re-usable component that results in consistency everywhere and is easier to re-use. 

Mockup to follow: https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=3012%3A1274

Feedback from Christin that can be addressed as part of this Pr. 

- [ ] ~~We should also improve the table view for tablet size devices as suggested here https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=3541%3A3413 by Christin.~~
- [ ] the logos are overlapping when resizing the window this can be re-produced with the table on https://www.gitpod.io/vs/jetbrains-space
       <details>
        <summary>Screenshot:</summary>
        <img src="https://user-images.githubusercontent.com/46004116/148175319-fd79c561-a47b-471a-9fba-2466893454c0.png" alt="Screen">
       </details>
- [ ] the spacing between the category items column and the card like columns should be decreased.

**Comment by Cahllagerfeld** [comment]
Are you already working on this @nisarhassan12 ?

**Comment by nisarhassan12** [comment]
Hi. @Cahllagerfeld Thanks. I have not started working on it yet. Feel free to take it over if you want to work on it.
