### ISSUE TITLE
Gitpod don't work in three repositories has one hour ago, some microservice should be down

### ISSUE THREAD

**Issue by jefer94** [gitpod-io/website#1385]
Repositories
- https://github.com/jefer94/calculator-exercise
- https://github.com/breatheco-de/apiv2
- https://github.com/breatheco-de/admin
- https://github.com/gitpod-io/template-python-django

Probably some microservice of gitpod is down

![image](https://user-images.githubusercontent.com/3018142/147028145-4fb3179a-f7f1-4a7d-adc9-7927651ad069.png)

**Comment by nisarhassan12** [comment]
Thanks, @jefer94 I'm closing this as it is no longer relevant i.e the issue has been resolved. In the future, if you encounter any outages please open an issue on the https://github.com/gitpod-io/gitpod repo instead.
