### ISSUE TITLE
[Docs - New Feature]: CLI: Extend workspace timeout

### ISSUE THREAD

**Issue by ffflorian** [gitpod-io/website#1386]
### Describe your feature

With this command you are able to manually boost the timeout of the current workspace to 180 minutes.

### How to test

1. Be on the *Unleashed* plan
2. Create a new workspace
3. Wait some time until your timeout is about to expire
4. Run
    ```
    gp --extend-timeout
    ```

**Comment by Siddhant-K-code** [comment]
Implemented https://www.gitpod.io/docs/references/gitpod-cli#extend
