### ISSUE TITLE
Add a media kit

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#139]
This is how the site could look like
<img width="956" alt="Bildschirmfoto 2019-06-06 um 08 54 45" src="https://user-images.githubusercontent.com/46345125/59012805-c10e5980-8838-11e9-8cc5-ce4fbaba4d7a.png">

It would cool to add a hover effect to visualize the possibility to download each file

File:
[Media_kit2.pdf](https://github.com/gitpod-io/website/files/3210908/Media_kit2.pdf)

**Comment by jankeromnes** [comment]
@ChristinFrohne there are a few bugs in the PDF:

- [ ] Sven's Twitter is https://twitter.com/svenefftinge (not https://twitter.com/gitpod)
- [ ] Moritz's GitHub is https://github.com/meysholdt (not https://github.com/gitpod-io)
- [ ] Moritz's Twitter is https://twitter.com/meysholdt (not https://twitter.com/svenefftinge)
- [ ] Jan's GitHub is https://github.com/JanKoehnlein (not https://github.com/gitpod-io)
- [ ] The title "USP" doesn't look right (if it's an acronym, please replace it with full words)
- [ ] The Press Mentions don't mention the website/journal/magazine/outlet (e.g. heise.de)
- [ ] "Our Journey" direction is confusing (should either go top to bottom, or have an arrow/rocket at the top, and maybe a flat bottom)
- [ ] "Founding Gitpod" is confusing (is Gitpod a new company?) Maybe "Creating Gitpod" instead (also, it would all read much better in past tense, e.g. "Founded TypeFox", "Created Gitpod", etc)

**Comment by ChristinFrohne** [comment]
Oh weird, I was sure I checked all links. I will do that again. Thanks!

**Comment by ChristinFrohne** [comment]
How do I tick your boxes? 
> * [ ]  "Our Journey" direction is confusing (should either go top to bottom, or have an arrow/rocket at the top, and maybe a flat bottom)

Why? It's structured like a CV, the newest event at top. Founded Typefox starts with the first dot and after launched Gitpod the line continues because from here we continue our journey. If you still think it's unclear, I can add a symbol

**Comment by ChristinFrohne** [comment]
Here is the adjusted file
[Media_kit2.pdf](https://github.com/gitpod-io/website/files/3276246/Media_kit2.pdf)
