### ISSUE TITLE
nav toggle moves out of the viewport on mobile when the content overflows.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1396]
On mobile on the /changelog page, the nav toggle is not accessible anymore as the Nav is overflowing the viewport. 

<img src="https://user-images.githubusercontent.com/46004116/147305019-9c82c115-68f2-4b77-90d7-3b6b9eb7e216.png" alt="Screenshot" height="600"/>

**Comment by nisarhassan12** [comment]
Reopening this as I encountered the same bug on https://www.gitpod.io/privacy it happens whenever there is some content that overflows the screen in this particular case it was caused by the link which does not break onto the next line and has a width wider than the viewport. 

![image](https://user-images.githubusercontent.com/46004116/147307464-032f67c6-c9f1-49f4-abc4-c40624449477.png)

**Comment by mikenikles** [comment]
There are likely a few other ones. Thanks for reopening this issue.

I expect the Lighthouse tests to catch that, we just need a way to run lighthouse on every page in a way that doesn't take hours to run.

**Comment by nisarhassan12** [comment]
Thanks, @mikenikles I just manually ran Lighthouse on https://www.gitpod.io/privacy it does not catch it there as well. I just saw that https://www.gitpod.io/vs/jetbrains-space is also broken i.e there are now horizontal scroll bars. What do you think  Would it be fine if we re-add `overflow-x: hidden` to the root element as part of the reset apart from the docs(as overflow hidden was causing the issues there)?
![Screen Shot 2022-01-05 at 11 07 07 AM](https://user-images.githubusercontent.com/46004116/148168628-e70a352c-a786-4ae5-a88c-2df3356ab828.png)
