### ISSUE TITLE
/pricing improvements

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1404]
Great to see that the new pricing page is implemented. Here are a few more things that need to be addressed.

**General:**

- [ ] use a switch instead of the toggle #1387
- [x] pricing cards: align text to the center and reduce spacing (see mockup)
<img width="305" alt="Bildschirmfoto 2021-12-28 um 11 29 52" src="https://user-images.githubusercontent.com/46345125/147557183-4730bc8c-5884-49b5-aee0-5d413138f1d5.png">

- [x] tooltips: move tooltips above the icon instead of underneath, update the layout (bubble style), color - what do you think about using a dark background? (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2828%3A1288), see [GitHub](https://github.com/pricing) for inspiration)
- [ ] #1416
<img width="741" alt="Bildschirmfoto 2021-12-28 um 11 42 39" src="https://user-images.githubusercontent.com/46345125/147558164-55a6291f-c93a-46ad-8efd-64b69e3c6fe0.png">

- [x] link "view requirements" to https://www.gitpod.io/docs/professional-open-source
- [x] add a pop-up to redeem student offer. Currently, there is no link❗️
<img width="359" alt="Bildschirmfoto 2021-12-28 um 11 46 42" src="https://user-images.githubusercontent.com/46345125/147558512-d43c449b-ac49-4d12-a213-02c7abb207c2.png">

- [x]  FAQs: add new items based on the Figma comments, update the current FAQs (e.g. link to student plan is outdated)
- [x] Self-hosted: Why is there a "+"? it can be removed
<img width="324" alt="Bildschirmfoto 2021-12-28 um 11 54 32" src="https://user-images.githubusercontent.com/46345125/147559210-c2d6db67-2b15-409f-a654-e9ec47267e53.png">

**Mobile:**

- [x] could you shorten the text to "get started" on mobile? By that we reduce vertical space. Alternatively, move "for" to the next line
<img width="388" alt="Bildschirmfoto 2021-12-28 um 11 52 29" src="https://user-images.githubusercontent.com/46345125/147559084-4b7aafab-ff67-4834-829e-c0dfe9096d20.png">

**Comment by nisarhassan12** [comment]
> link to student plan is outdated

@ChristinFrohne you meant the Gitpod for Students link? right ? where is it expected to link to ? Thanks

![image](https://user-images.githubusercontent.com/46004116/147924531-a5a8be32-2aeb-4c71-9190-1210dc50fd12.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made a Pr for this https://github.com/gitpod-io/website/pull/1415 for the 2 remaining todos I will make isolated small follow up PRs.
