### ISSUE TITLE
redirect most relevant pages from community.gitpod to docs

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1405]
**Issue:**
- After we closed down the community, we're losing quite a lot of website traffic. In the last 3 months ca. 30% of all SEO traffic came from community.gitpod.io (43k clicks and 913k impressions).
- Many users complained on Discord that some information isn't accessible anymore 

**Solution**
1. add redirects for the most visited pages to the related documentation
2. if there is no documentation yet, we should consider adding it. (to make this issue more actionable we could create new issues for every topic that should be included in the docs)

List of most visited pages in the last 16 months (all pages with +200clicks should be checked)
https://docs.google.com/spreadsheets/d/1mprS-3NmIC8ntMvbbtezVn5VFXTH4duNvtcuBmGVmfU/edit#gid=628549619

**Comment by ChristinFrohne** [comment]
@mikenikles is this still the right place for the issue or should it be under https://github.com/gitpod-io/gitpod/issues?

Is this something you could take care of? 🙏

**Comment by mikenikles** [comment]
Closing this since there is now a site-wide redirect to Discord on any of the links mentioned in the spreadsheet. I also see ([internal link](https://gitpod.slack.com/archives/C01KGM9EBD4/p1655966632174459?thread_ts=1655966381.163069&cid=C01KGM9EBD4)) that the Discourse server no longer exists.

Feel free to re-open if I missed any other discussion related to this topic.

**Comment by meysholdt** [comment]
Hello!

as per discussion here, I have created a backup of the discurse communities VM instance's root disk image. Find it [here](https://console.cloud.google.com/storage/browser/gitpod-discourse-community-vm-backup-2022-07-26-2;tab=objects?forceOnBucketsSortingFiltering=false&project=gitpod-discourse-community&prefix=&forceOnObjectsSortingFiltering=false).
```
gs://gitpod-discourse-community-vm-backup-2022-07-26-2/gitpod-discourse-community-2022-07-26-2.vmdk
https://storage.cloud.google.com/gitpod-discourse-community-vm-backup-2022-07-26-2/gitpod-discourse-community-2022-07-26-2.vmdk
```

This backup can be used to recreate the VM and resurface all content from the site that once ran on community.gitpod.io.
