### ISSUE TITLE
Adding a "built on" section 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#141]
I think a "built on" section at the end of the git-graph on the main site would be good. 
It should contain logos from kuberneteres, Docker, Theia, VS Code, etc. 

It gives the user a fast overview about the tech behind Gitpod and increases trust

**Comment by jankeromnes** [comment]
Maybe just above the "Explore Features", so that the call-to-action remains at the very end of the GitGraph?

**Comment by ChristinFrohne** [comment]
I would say it fits the best just above "explore features"
