### ISSUE TITLE
feature table: add a hover style so it's easier see the different rows

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1416]
![image](https://user-images.githubusercontent.com/46004116/147940060-c888a59a-abbd-46b6-84d3-dbaa85e9c40f.png)

**Comment by Cahllagerfeld** [comment]
Shall we tackle this with #1384, when we recreate the whole component, or do this before? The concern I'm having is, that the component is currently organized in columns and not rows. Do we need to restructure the whole component for this, to work with rows? @nisarhassan12

**Comment by mikenikles** [comment]
@chrifro Do you think this is something we want to implement?

**Comment by Siddhant-K-code** [comment]
I am not in support of this. 

@chrifro wdyt?

**Comment by chrifro** [comment]
Yes, this is very nice to have especially for longer tables. The Figma component can be found [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2056%3A4219).

**Comment by Siddhant-K-code** [comment]
Reopening this due to #3298
