### ISSUE TITLE
Docs - Use ADRs?

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#1432]
We should think about using architecture decision records when making decisions in the repo, especially as the team grows in the future. There's a [npm-package](https://www.npmjs.com/package/adr) for it, that seems to generate table-of-contents and markdown-templates for this.

Mike and me had a chat about this in slack already, thats the 'official' issue for it.

**Comment by Siddhant-K-code** [comment]
We are now using it:

https://github.com/gitpod-io/website/blob/031ebe24dffa417df98dfd90396cd6f8b3b96e39/package.json#L55
