### ISSUE TITLE
Document Incremental Prebuilds and Incremental Workspaces

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#1439]
### Describe your feature

We should document Incremental Prebuilds 😁

They attempt to make new Prebuilds faster by using a Prebuild from an older commit as a base (as opposed to starting from scratch, which is what happens for non-incremental Prebuilds, or when no suitable parent Prebuild can be found).

When a new Prebuild is started for a Project's commit, and the Incremental Prebuilds feature is enabled for this Project, Gitpod will look for a "compatible" Prebuild from an ancestor of this commit by fetching and "walking back" the history of the commit (Gitpod currently fetches 100 ancestor commits, because anything prior to that is considered obsolete).

"compatible" means a few things (e.g. the parent Prebuild should be already finished and successful; it should have the same `init` / `before` / `prebuild` tasks, it should not be incremental itself, etc.)

The precise parent-selection logic is implemented here:

https://github.com/gitpod-io/gitpod/blob/91c09f7c2bfae33fc6085e48c22f897409a16732/components/server/ee/src/workspace/workspace-factory.ts#L66-L113

Would be cool to translate this into natural language in our docs.

### How to test

1. Go to a Gitpod Project's Settings, and enable Incremental Prebuilds
2. Start a new Prebuild (e.g. by pushing a commit to a branch, or by clicking the `Run Prebuild` button)

**Comment by jldec** [comment]
Prioritizing since we're talking about using incremental prebuilds more
e.g. in https://github.com/gitpod-io/gitpod/issues/13754
