### ISSUE TITLE
improve the tooltips as per the specs. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1448]
The specs can be found here: https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Website-Component-Library?node-id=518%3A1074

Relates to https://github.com/gitpod-io/website/pull/1415#pullrequestreview-848884744

**Comment by Cahllagerfeld** [comment]
I just saw you commited some changes to the Tooltip-Component with #1415. If I saw it correctly theres just the arrow missing on the tooltip. Does this have priority, or should I work on something else?

**Comment by Cahllagerfeld** [comment]
Do we need `Popper.js` here? See [this](https://popper.js.org/docs/v2/modifiers/arrow/) reference for example

**Comment by nisarhassan12** [comment]
Thanks, @Cahllagerfeld for looking into it. I'm not sure about Popper anything that complies with our Figma specs and auto-adjusts to the sides in both x and y direction would work fine for see https://github.com/gitpod-io/website/pull/1415#pullrequestreview-848884744 The tooltips used on GitHub seem to work pretty well.

**Comment by nisarhassan12** [comment]
> should I work on something else?

Meanwhile, feel free to pick up any other issue where no one is assigned. I saw that you made and closed a PR I'm sorry that I was not descriptive enough while opening the issue.
