### ISSUE TITLE
Document Gotchas when running websites in Gitpod

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/website#145]
let's collect issues that may occur when you run a website from a Gitpod-Workspace:

1. can't connect via `http`
A: app must use `https`

2. redirect to `localhost`
A: configure URL of app.

3. Access Denied
A: Did the app validate the `host` header?

4. JS-Error `cross_framing_protection.js?v=5.0.0-dev:13 Unsafe JavaScript attempt to initiate navigation for frame with URL`
A: A website running in the preview view tries to redirect the root window. Full example error message: 
> cross_framing_protection.js?v=5.0.0-dev:13 Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://f8ea083f-7bcb-4649-acca-2981eba05687.ws-eu0.gitpod.io/#/workspace/phpmyadmin' from frame with URL 'https://8080-f8ea083f-7bcb-4649-acca-2981eba05687.ws-eu0.gitpod.io/'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

> (anonymous) @ cross_framing_protection.js?v=5.0.0-dev:13
cross_framing_protection.js?v=5.0.0-dev:13 Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'https://8080-f8ea083f-7bcb-4649-acca-2981eba05687.ws-eu0.gitpod.io/'.
    at https://8080-f8ea083f-7bcb-4649-acca-2981eba05687.ws-eu0.gitpod.io/js/cross_framing_protection.js?v=5.0.0-dev:13:18

5. can't open port. 
A: see https://github.com/gitpod-io/gitpod/issues/581

**Comment by jankeromnes** [comment]
- `Invalid Host Header`
    A: WebpackDevServer refuses to serve the web app because configured `host` doesn't match request host (solution: `--disable-host-check` or `disableHostCheck: true`)

**Comment by jankeromnes** [comment]
Is https://www.gitpod.io/blog/gitpodify/#solving-common-preview-problems a good enough collection of website gotchas that we can close this issue?

If not, how should it be improved?

**Comment by meysholdt** [comment]
that's good!
