### ISSUE TITLE
Disable the Lighthouse CI integration

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1452]
Hey @nisarhassan12, could you please disable the Lighthouse CI integration? Correct me if I'm wrong, but the `./budget.json` file is empty and Lighthouse doesn't really test anything. If that's the case, let's not run the integration as it unnecessarily slows down the time it takes to merge a PR and also wastes CPU time.

**Comment by Cahllagerfeld** [comment]
I'd disable the action manually in the `Actions tip` from Github and leave the action for now in the `workflows` folder. In case thats fine I can do this 👍
