### ISSUE TITLE
Deindexation of gitlab.gitlab.gitpod.io subdomain

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1464]
The gitlab.gitlab.gitpod.io Subdomain seems to have no relevant impact on SEO. Due to the thin content, we should noindex and block the pages (robots.txt) to be crawled from Google.

Same for /changelog/-Path, as it's duplicate content to /changelog

- [ ] remove `gitlab.gitlab.gitpod.io`
- [x] remove `/changelog/*`

**Comment by ChristinFrohne** [comment]
Can we close this issue @Cahllagerfeld ?
gitlab.gitlab.gitpod.io will be retired during this week [1] and the changelog indexation was already adjusted in #1604, right? :)

**Comment by Cahllagerfeld** [comment]
Yes, good catch!

Thanks Christin 🚀
