### ISSUE TITLE
performance issue because of "YouTube"-embeds 

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1465]
The issues are most likely a "YouTube"-embed-related issue: Lazy-loading of YouTube container may fix the problem

- [ ] Remove unused JavaScript ([affected pages](https://docs.google.com/spreadsheets/d/1jRm5r_JpGpk-NyBwyyF2pGevBiVHhPZcSWgaIpXCEtY/edit#gid=0))
- [ ] Remove unused CSS ([affected pages](https://docs.google.com/spreadsheets/d/1GFocotMQOjbfXwX27oqEqcN6orvY_SHS-lF8bPaWxsY/edit#gid=0))

**Comment by mikenikles** [comment]
Closing as duplicate of #1175.
