### ISSUE TITLE
Error 404 Page Not Rendering in Production

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/website#1479]
## Description
Error 404 page not working in Production, while it is working in local.

## Regenerate this issue
- Go to Any endpoint which doesn't exist, like this [`/errorxyz`](https://www.gitpod.io/errorxyz)

## Related
- https://github.com/sveltejs/kit/issues/930
- [gitpod website's `__error.svelte` file]( https://github.com/gitpod-io/website/blob/main/src/routes/__error.svelte)
- https://github.com/gitpod-io/website/blob/03fe6677cb239af769683e7e99f240988a3c58a5/src/routes/blog/from-gatsby-to-svelte.md#L81

## Video Demo

<a href="https://www.loom.com/share/4d15f8dbf4d0435c8b7020030316606d" target="_blank">
    <p>www.gitpod.io - error page in production - Watch Video</p>
    <img style="max-width:180px;" src="https://cdn.loom.com/sessions/thumbnails/4d15f8dbf4d0435c8b7020030316606d-with-play.gif">
</a>

**Comment by Cahllagerfeld** [comment]
Maybe the setting `split: true` is related to it, see [Netlify-Docs here](https://docs.netlify.com/integrations/frameworks/sveltekit/#limitations)
