### ISSUE TITLE
broken responsive design for some blog posts

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1497]
- [x] Some responsive designs for blog posts are broken. Example: https://www.gitpod.io/blog/gitpodify Not sure if other blog posts are affected as well
<img width="668" alt="Bildschirmfoto 2022-01-19 um 11 09 46" src="https://user-images.githubusercontent.com/46345125/150109702-09b50672-828c-46a8-a720-fa1126d34117.png">

- [ ] #1509

**Comment by Cahllagerfeld** [comment]
Might this be related to the new `typography`-plugin @mikenikles ?

**Comment by nisarhassan12** [comment]
I think this is relevant to https://github.com/gitpod-io/website/issues/1396#issuecomment-1005429095 we need to put back `overflox-x: hidden` and make sure that every element has a max-width of 100%.

**Comment by nisarhassan12** [comment]
Closing this as it has been fixed in #1506
