### ISSUE TITLE
Mobile pricing page

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#15]
<img width="280" alt="Pricing1" src="https://user-images.githubusercontent.com/599268/54674673-3b162880-4afd-11e9-98f9-077ff8e9a1a8.jpg">

> oder was ist wenn wir alle Optionen ausgeklappt nebeneinander haben und der Nutzer kann kann die zur Seite swipen?

**Comment by svenefftinge** [comment]
Or we simply put them expanded below one another?

**Comment by jankeromnes** [comment]
> Or we simply put them expanded below one another?

I'll try that one first as it's the easiest, then we'll see if we need something more sophisticated.
