### ISSUE TITLE
Pricing: display all 4 pricing cards in one row for standard devices

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1505]
Problem:
In the standard view for the Macbook Pro 13" only three of the four pricing cards are visible at first glance. By that, the impression is created that Gitpod only has three pricing plans.
<img width="1429" alt="Bildschirmfoto 2022-01-20 um 10 16 29" src="https://user-images.githubusercontent.com/46345125/150309625-41ee542a-a1f6-4f2a-af35-d470df17129f.png">

Solution:
Make sure all four plans are shown  in one row on standard desktop devices

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/pull/1557
