### ISSUE TITLE
500 error when loading a page

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1507]
**Problem:**
Philipp and I just both got a <s>505 error </s> 500 error when loading https://www.gitpod.io/pricing. After we refreshed the page, the error disappears. Philipp mentioned that he faced the same issue several times before.

**Comment by nisarhassan12** [comment]
Thanks for the issue @ChristinFrohne @phimae Do you have any ad blockers installed? 

@mikenikles It looks like it is relevant to https://github.com/gitpod-io/website/issues/377

**Comment by phimae** [comment]
I do not have ad blockers installed

**Comment by nisarhassan12** [comment]
I have encountered this myself today with the blog @mikenikles I suspect it was with the pre-rendered version i.e initially there was 500 error and the blog index page rendered as expected.

**Comment by phimae** [comment]
Still happening today when I tried to visit 
www.gitpod.io/customers/vizlib
![image](https://user-images.githubusercontent.com/83109781/153570687-017c65f2-d7c1-4e7a-9671-36fac19e5eaf.png)

**Comment by ChristinFrohne** [comment]
I might found some relating context in Google Search console [[1](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Agitpod.io&item_key=CAMYEyAE)] @mikenikles 
Since January the server sometimes returned a [500-level error](https://en.wikipedia.org/wiki/list_of_http_status_codes) when the page was requested. More [details on the error](https://support.google.com/webmasters/answer/7440203#server_issues).
<img width="884" alt="Bildschirmfoto 2022-03-01 um 11 30 21" src="https://user-images.githubusercontent.com/46345125/156152951-d0bbe06d-198e-4c2f-b8b4-41966f288150.png">

**Comment by mikenikles** [comment]
These are product URLs, note the missing `www`.

I see no recent 500 errors for the marketing website.
![Screenshot_20220301-062252](https://user-images.githubusercontent.com/788827/156186734-4cf3e11a-cd29-4d71-bb81-b11a52ddb18a.png)

**Comment by ChristinFrohne** [comment]
argh, you're right. I got too excited that this could possibly help fix this issue. I should have had a closer look. Sorry for the noise 😬
Will forward this issue to the WebApp team

**Comment by ChristinFrohne** [comment]
Just happened again. Sharing the console notes in case that's helpful @mikenikles 
<img width="1555" alt="Bildschirmfoto 2022-03-04 um 13 24 48" src="https://user-images.githubusercontent.com/46345125/156763111-7892ec83-fff1-4b25-bc3d-66358839fb0b.png">
<img width="806" alt="Bildschirmfoto 2022-03-04 um 13 26 07" src="https://user-images.githubusercontent.com/46345125/156763294-10d4ed90-f030-4244-a78a-01ce866f14aa.png">

**Comment by nisarhassan12** [comment]
I encountered this again today it went away when I reloaded the page

![Screen Shot 2022-03-17 at 3 18 56 PM](https://user-images.githubusercontent.com/46004116/158788284-32b3c11b-5b39-47e9-8d3a-faea434f607e.png)

**Comment by nisarhassan12** [comment]
Thanks for bringing this up again. I tried looking up online but haven't found anything promising yet. Maybe upgrading to the latest svelte kit version would help. I'll sync with Mike about this once he is back from vacation.

**Comment by chrifro** [comment]
@Cahllagerfeld we are assuming that this issue is resolved, right? If so, let's close it and reopen it in case the bug appears again.
