### ISSUE TITLE
/screencasts: YouTube thumbnail is cut

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1524]
We should adjust the thumbnail to fit the video size

https://www.gitpod.io/screencasts/getting-started-with-gitpod
<img width="1042" alt="Bildschirmfoto 2022-01-25 um 08 59 44" src="https://user-images.githubusercontent.com/46345125/150935830-8681a741-9cef-49b6-a472-466a59fac0e5.png">

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne for the issue I specified this in the PR here https://github.com/gitpod-io/website/pull/1438#issuecomment-1017873704 the below shows how it used to be. @mikenikles not sure how this can be fixed. Can you have a look when you get time? Thanks

| This PR | Live Site |
| - | - |
| <img width="1440" alt="Screen Shot 2022-01-21 at 132 08 AM" src="https://user-images.githubusercontent.com/46004116/150417676-2e90311c-ebb6-4ef7-85c6-a643386f3814.png"> | <img width="1440" alt="Screen Shot 2022-01-21 at 1 32 46 AM" src="https://user-images.githubusercontent.com/46004116/150417746-5c7d1016-7928-46f7-81ad-d49f0bb29833.png">  |

**Comment by nisarhassan12** [comment]
@ChristinFrohne I had a discussion about this with Mike and thanks to him we were able to identify the cause of this issue to be the new height CSS property which I set to `620px` for larger screens to avoid having the black borders with this change black borders did get removed but it introduced this issue. The solution would be to roll back there. 

If you look at the following:

- https://devxconf.org
- https://docs.cypress.io/guides/overview/why-cypress#In-a-nutshell

There the videos have black borders as well the black borders are shown when the aspect ratio of the video does not fit the height and width of the iframe. 


I'll make a PR to rollback the change made here https://github.com/gitpod-io/website/issues/1524

Meanwhile, if you find a website where youtube embeds have no black borders across different screensizes. Please let us know and we'll further investigate. Thanks

**Comment by ChristinFrohne** [comment]
Thanks for the context. Let's merge your PR then and keep the issue in mind when we have time to build our own YouTube embed.
