### ISSUE TITLE
Cooperation invitation from Apache APISIX community

### ISSUE THREAD

**Issue by yzeng25** [gitpod-io/website#1533]
Hi folks,

I am Yilin, from the Apache APISIX community. Apache APISIX is a Cloud-native API gateway, and it is the top-level project of the Apache Software Foundation. You can get more details from our GitHub repository[1].

We are developing a plugin to integrate Gitpod with Apache APISIX. I think the plugin is very meaningful for developers and both communities. In addition, it will help Gitpod and Apache APISIX publicize and let more developers and companies know about us.

We are writing an article for this plugin, are you interested in posting this article on your website's blog[2] or some other sections?

I am looking forward to your reply.

Sincerely,
Yilin Zeng

[1] https://github.com/apache/apisix
[2] https://www.gitpod.io/blog

**Comment by pawlean** [comment]
Hey @yzeng25! 

This is awesome! We'd like to look at adding this post maybe in our /guides section. I'm copying @mikenikles here for information. 

Once you've written the article, we can definitely raise a PR to merge it to the guides section.

**Comment by yzeng25** [comment]
Hi @pawlean !

Thanks for your reply. We are planning to get this function done in late-February or Early-March. The article should be ready shortly after it. I will keep things updated in this issue! :)

**Comment by pawlean** [comment]
Sounds like a plan! 🙏🏼 Thanks @yzeng25!
