### ISSUE TITLE
Update start-up times for Gitpod vs Codespaces

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1537]
The first infographic on [Gitpod vs Codespaces](https://www.gitpod.io/gitpod-vs-github-codespaces) from September 2020 is outdated and needs an update. 

@jankeromnes listed the steps to reproduce the current example [on slack](https://gitpod.slack.com/archives/C01LDA27WJC/p1630675207109300?thread_ts=1630667805.105900&cid=C01LDA27WJC)

While looking into this, it would also be great if this sentence (for the new landing page) can be complemented as well.
> Our own XXGB dev image takes only xx seconds to load.

**Comment by phimae** [comment]
Hi @mikenikles! Can we create a PR based on the new insights (link to internal Slack [thread](https://gitpod.slack.com/archives/C01LDA27WJC/p1643911257305519?thread_ts=1630667805.105900&cid=C01LDA27WJC))?

**Comment by nisarhassan12** [comment]
This issue is already addressed by https://github.com/gitpod-io/website/issues/2088
Please re-open if this issue is still relevant. Thanks
