### ISSUE TITLE
Chore: Consistent titles, slugs and anchor references

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1541]
There are cases where the following three are out of sync: 

1. URL's / paths / slugs for documentation
2. The page title / H1
3. The anchor text that links to the page (less important)

This issue is to go through and triage all places where these links are out of sync, and update all content. 

Example: The "network bridging" page and nav entry does not match the slug. This causes challenges when linking, should the copy text in the linking content be "Tailscale" or "Network Bridging". I think it makes sense to try and keep these in sync. If necessary we can have two pages, one for the generic Network Bridging, and one for Tailscale, and/or have Tailscale be linked via an anchor heading / link. 🙏

| Tailscale / Network Bridging Page | 
| ----------- |
| ![image](https://user-images.githubusercontent.com/5528307/151350665-9f459b01-7f6a-487d-9f8e-92a061980700.png) |

**Comment by Siddhant-K-code** [comment]
Most of the Pages are already resolved with PR: #2587

Example:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/55068936/211281814-69b25e04-75fa-44e1-8a3c-067d72a0ddf9.png">
