### ISSUE TITLE
Publish Gitpod vs JetBrains Space landing page

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1549]
**Issue**
we needed to merge #1366 before it was reviewed due to an upcoming merge conflict. https://www.gitpod.io/vs/jetbrains-space is already online but it still needs a thorough content review. Until then the page is not listed in the footer or indexed by search engines and should not be shared yet.

**Remaining to Do's:**

- [ ] review all content especially the feature table 
- [ ] find comparable numbers for the "greater cost efficiency" section and adjust the graphic accordingly
<s>- [ ] add a top banner highlighting our collaboration with JetBrains</s>
- [x] remove linear outlines from the JetBrains logo bubbles

**Comment by ChristinFrohne** [comment]
related PR https://github.com/gitpod-io/website/pull/1421

**Comment by ChristinFrohne** [comment]
I have struggles comparing the pricing. @JohannesLandgraf do you have an idea on how to compare the pricing? 
See [JetBrains pricing](https://www.jetbrains.com/space/buy/?billing=monthly#cloud)

**Context:**
"The pricing looks massive. If you want to use it full time you seem to be way above 100€ per month per dev for the average machine." [[1](https://gitpod.slack.com/archives/C01KGM9AGBG/p1638187789117000?thread_ts=1638178113.110000&cid=C01KGM9AGBG)]

**Comment by ChristinFrohne** [comment]
>add a top banner highlighting our collaboration with JetBrains

see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4327%3A3530)
<img width="648" alt="Bildschirmfoto 2022-01-31 um 10 56 56" src="https://user-images.githubusercontent.com/46345125/151773196-6cac0e76-d8ef-49db-8dad-4387cb879218.png">

Could you add this banner to PR#1421 @nisarhassan12 ? 🙏 The banner should always be displayed, independently of the JetBrains launch banner, but only on this page.

**Comment by JohannesLandgraf** [comment]
Just to make sure there are no misunderstandings: the banner should only be merged on Feb 10 - maybe we do this in a different PR?

**Comment by ChristinFrohne** [comment]
>Just to make sure there are no misunderstandings: the banner should only be merged on Feb 10 - maybe we do this in a different PR?

great that you mentioned it. I thought we always want to have a banner on this page to highlight our partnership with JetBrains.

The general announcement banner would only be visible for a couple of weeks. 

Alternatively, we could also think about adding a note like this: WDYT?
<img width="650" alt="Bildschirmfoto 2022-01-31 um 10 51 17" src="https://user-images.githubusercontent.com/46345125/151812181-289abcc6-d0c5-4ab2-b214-4c1bb26a2287.png">

**Comment by ChristinFrohne** [comment]
Update: let's put the banner on hold. Further changes are addressed directly in PR #1421
