### ISSUE TITLE
Optimize all image assets

### ISSUE THREAD

**Issue by estelle** [gitpod-io/website#155]
Go thru the images directory and optimize all the image assets.

* Puts SVGs thru SVGOMG.
* Resize the screenshots or make new ones without excess white space (i took a bunch, so this is my bad). Then optimize via imageAlpha, Squoosh, or other.  
* Consider using webP with JPG fallback for large image files (or all image files)

**Comment by nisarhassan12** [comment]
This is currently on hold because of https://github.com/gitpod-io/website/pull/160#issuecomment-911987252

**Comment by mikenikles** [comment]
@nisarhassan12 The Jetbrains icons that are blurry all have an `<image />` tag embedded within the svg. Could you please fix that so they match what the `intellij.svg` file looks like?

@ChristinFrohne can you point me to a blurry "Open in Gitpod" button? I checked the ones in the docs and they look alright to me.

**Comment by mikenikles** [comment]
We should try https://github.com/calibreapp/image-actions
