### ISSUE TITLE
Should submit button be disabled on page load?

### ISSUE THREAD

**Issue by estelle** [gitpod-io/website#156]
On the contact page, per the design, the default state of the submit button should be disabled until the form has been checked. 

However, since the form isn't checked until the button is clicked, we shouldn't disable it on load.

So, not 100% sure if we should follow the design, disabling the button. If yes, we should likely check each form control on losing focus rather than on form submit.

**Comment by opensas** [comment]
I just sent this [PR](https://github.com/gitpod-io/website/pull/618) to change the form behaviour. Validations are now applied on every keystroke, error status is shown when the input looses focus and the submit buttons is enabled/disabled accordingly.
I noticed there are a couple more forms, enterpirse-license and extensions-uninstall. If the idea is to apply the same behaviour to those I could try to update them too.

**Comment by nisarhassan12** [comment]
Closing this as part of the issue cleanup. 

Reading this https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/ I don't think we should do that.
