### ISSUE TITLE
[Docs]: Self-Hosted gitpod on k3s

### ISSUE THREAD

**Issue by Pothulapati** [gitpod-io/website#1574]
### Describe your feature

A lot of users would want to test out `self-hosted` installation on a local kubernetes distribution (most like `k3s`). We should have this path documented just like we do for other cloud kubernetes distributions right now

### How to test

Documentation like the existing guides https://www.gitpod.io/docs/self-hosted/latest/installation

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
