### ISSUE TITLE
Include case study and new quote in /for/startups

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#1585]
Hi there! Now that we have case studies, we should inject them in our existing material. For the `/for/startups` page we should do the following:

- [x] Swap the existing quote against the new quote box style (can be the same box as on the /customers page)
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/83109781/153220173-db59bbba-97ce-4ad8-a81e-2769a94f311b.png">

- [x] Add a new section below "Accelerate your workflow" that looks something like this (@ChristinFrohne will provide a more thoughtful mockup) If the page becomes too crowded, we can drop the "Code from anywhere on any device" section 
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/83109781/153221363-c88d8d0e-7011-4913-ba2c-fe0964281c83.png">

**Comment by phimae** [comment]
As discussed in Slack, the design is 🎯 let's implement 💪

**Comment by nisarhassan12** [comment]
Thanks, @phimae I have started working on it.
