### ISSUE TITLE
Inconsistent JetBrains IDE support on website vs docs

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#1591]
### Page URL

- https://www.gitpod.io/docs
- https://www.gitpod.io/

### User feedback

Currently the list of JetBrains on the homepage is not consistent with the docs
| Home page      | Docs |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/5528307/153387162-1ca47b70-f97a-4f0c-b2b4-0c1254f47b0f.png)      | ![image](https://user-images.githubusercontent.com/5528307/153387131-a38096ac-d3c7-489d-a620-177e50c6d6dc.png)       |

**Comment by ChristinFrohne** [comment]
Great catch. Thanks!
Did you follow any specific order for the docs @loujaybee?

My thought was to sort the list by supported, beta, and soon. Followed by the rough number of adoption.

**Comment by loujaybee** [comment]
> My thought was to sort the list by supported, beta, and soon. Followed by the rough number of adoption.

👍 sounds good to me!

**Comment by Cahllagerfeld** [comment]
Are we having any metricks on the popularity of the editors?
