### ISSUE TITLE
Migrate Radio Button to Component Library

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#1597]
We are restricted here by the issue linked in this [comment](https://github.com/gitpod-io/website/pull/1576#discussion_r803498854)

**Comment by chrifro** [comment]
Is this still relevant @Cahllagerfeld ? If so, could you give more context on the radio button? Where is it used?

**Comment by Cahllagerfeld** [comment]
In Sales & Contact Form the selection for the subject is technically a radio button because you are only able to select a single value from the proposed ones. As the styling for the two pages are the same, it would be ideal to make a component out of it, but we were having some limitations from svelte itself here
