### ISSUE TITLE
[responsive design] buttons overflow columns in tables

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1601]
On https://www.gitpod.io/pricing the buttons overflow the table columns when resizing the window

<img width="663" alt="Bildschirmfoto 2022-02-14 um 09 16 49" src="https://user-images.githubusercontent.com/46345125/153825927-555d3464-da45-4222-9e91-98d72429d0b4.png">

cc @Cahllagerfeld because you worked on #1516

**Comment by ChristinFrohne** [comment]
The issue doesn't seem to only relate to tables. See https://www.gitpod.io/docs
<img width="625" alt="Bildschirmfoto 2022-02-14 um 09 25 18" src="https://user-images.githubusercontent.com/46345125/153826975-3a771c64-e669-4868-8913-9ddc045ea3dc.png">

**Suggestion:** shorten button text to "Read now" , "Watch now" etc.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have fixed this in https://github.com/gitpod-io/website/pull/1698 Please review it when you get time. Thanks
