### ISSUE TITLE
[responsive design] misalignment of the quote card when resizing the window

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1602]
Seen on https://www.gitpod.io/for/startups
<img width="752" alt="Bildschirmfoto 2022-02-14 um 09 21 34" src="https://user-images.githubusercontent.com/46345125/153826470-befc731b-f7da-4057-8ee0-addb678990fc.png">

**Comment by ChristinFrohne** [comment]
Thanks for looking into it @Cahllagerfeld but now there is too much spacing. Could you align it to the [component style in Figma? ](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831) 🙏
<img width="1040" alt="Bildschirmfoto 2022-02-16 um 08 41 45" src="https://user-images.githubusercontent.com/46345125/154218537-933bf6d9-d1a7-4d3b-ac83-b6ba7d0e15aa.png">

**Comment by Cahllagerfeld** [comment]
Thats strange, I actually didn't touch the spacing in this spot 🤔 I'll have a look into it immediately 👍

**Comment by ChristinFrohne** [comment]
Thanks! The component is also used on /for/opensource that recently got merged. #1380 Maybe it broke because of that?
