### ISSUE TITLE
Double "See openings" button in /about

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#1629]
Maybe this is a new experiment to double the conversion rate (😂) but there are currently two `See openings` buttons in https://www.gitpod.io/about :

<img width="1391" alt="Screenshot 2022-02-17 at 18 21 22" src="https://user-images.githubusercontent.com/599268/154536156-dc9916a4-7278-4ffd-a83b-497826d3d654.png">

**Comment by Cahllagerfeld** [comment]
Thanks for opening @jankeromnes, I saw it myself, without knowing about your issue, and closed it with #1630.
