### ISSUE TITLE
Align all self-hosted spelling

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#1634]
Internal conversation [[1](https://gitpod.slack.com/archives/C01KLC56NP7/p1645192148137369)]

**Comment by mikenikles** [comment]
If anyone in the community wants to play with Find & Replace in their editor, we agreed to use "Self-Hosted" with capital S and H.

**Comment by nisarhassan12** [comment]
I didn't know that this issue existed I made this PR two days ago based on the Slack conversation that Pauline shared above. 

The PR is now awaiting a review.
