### ISSUE TITLE
Add to documentation how to force workspace image rebuilds

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/website#1641]
Currently, there's no information on how to force a rebuild of a workspace image, even though such functionality exists since May (`gitpod.io/#imagebuild/`)

See https://github.com/gitpod-io/gitpod/issues/4126#issuecomment-901917815

cc @mikenikles

**Comment by shaal** [comment]
thank you

**Comment by mikenikles** [comment]
Added a new "[Manually rebuild a workspace image](https://www.gitpod.io/docs/config-docker#manually-rebuild-a-workspace-image)" section.

**Comment by shaal** [comment]
❤️
