### ISSUE TITLE
[Docs - Quickstart] - Requesting Java

### ISSUE THREAD

**Issue by naresh-chaudhary** [gitpod-io/website#1643]

**Comment by mikenikles** [comment]
Hi 👋, what would you like the Java quickstart to provide?

We have an existing Java - Spring one (https://www.gitpod.io/docs/quickstart/java) that could be a good starting point.

**Comment by nisarhassan12** [comment]
@naresh-chaudhary Thanks for the issue. I'm going to close this as part of the issue cleanup in case you have any questions please feel free to comment below or reach out to us here www.gitpod.io/chat
