### ISSUE TITLE
[for early April] Revamp /about after our offsite in Portugal

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#1644]
**Context**
We are very transparent in many ways as a company:
- We're open source and our development is thus very transparent
- Launching a blogpost series about our Company Building OS makes internal workings more transparent, too
 
One area where we are not so transparent yet is our teams and Gitpodders. 

**Proposed Solution**
Revamp our /about page to make Gitpod more "human", show who we are and what we each do. Thinking about little Gitpodder cards with a short description and a photo. Showing where we are located underlines our remote focus and shows our geo diversity and spread across the world. Our values will be more fleshed out and explicit by then, too. We can talk about them rather than linking out.

**Examples to take inspiration from** (top of my head, did not do research yet):
Gitlab: [[1](https://about.gitlab.com/company/team/)], [2]
Customer.io: [[1](https://customer.io/about/)], [[2](https://customer.io/our-team)]

**Comment by gtsiolis** [comment]
**fyi**: I've forked the team map project ([upstream](https://gitlab.com/gitlab-com/teampage-map), [fork](https://gitlab.com/gtsiolis/team)) from GitLab and added all Gitpodders on a map for fun, see [the map](https://gtsiolis.gitlab.io/team/). 🗺️ 

Re-posting from the [relevant discussion](https://gitpod.slack.com/archives/C01KGM9FXB8/p1647260554268599) (internal):

> The intent was to consider long-term deprecate our team[[1](https://timezone.io/team/gitpod)] on [timezone.io](http://timezone.io/), as it’s not an actively maintained project and does not allow multiple people to manage the team as well as does not include all team members.

> The avatars are pulled from GitHub. I tried adding all team members there but could not add three of us[[1](https://gitlab.com/gtsiolis/team/-/blob/eb078f23b99c8c61ec1f8fa6e342f2fae39e09e5/team.yml#L50)][[2](https://gitlab.com/gtsiolis/team/-/blob/eb078f23b99c8c61ec1f8fa6e342f2fae39e09e5/team.yml#L170)][[3](https://gitlab.com/gtsiolis/team/-/blob/eb078f23b99c8c61ec1f8fa6e342f2fae39e09e5/team.yml#L178)] that didn’t find a GitHub profile. Also, could not add two of us[[1](https://gitlab.com/gtsiolis/team/-/blob/eb078f23b99c8c61ec1f8fa6e342f2fae39e09e5/team.yml#L146)][[2](https://gitlab.com/gtsiolis/team/-/blob/eb078f23b99c8c61ec1f8fa6e342f2fae39e09e5/team.yml#L166)] because the country could not be added. Had to also use a single place as a location for some of us.

> The project is currently open source and the map page is publicly accessible. The source code is a bit over engineered to match the needs of the GitLab team.

**Comment by mikenikles** [comment]
Closing in favour of #2400
