### ISSUE TITLE
Fix Changelog-Button alignment

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#1648]

**Comment by Cahllagerfeld** [comment]
I think we should discuss, if we want to align these headers in general. For example when comparing the `digest-header` with the `changelog-header`. The Digist-header is center-aligned, while the changelog is left-bound. Do we want to make this consistent, and if yes, which is the variant to go? Let me know what you think about this @mikenikles

**Comment by mikenikles** [comment]
This is something for @ChristinFrohne to provide guidance.

**Comment by ChristinFrohne** [comment]
the DevX Digest page should follow the design of our standard headers (centered design). The changelog header is an exception as the whole page layout is different. Here the headline should be left-aligned and aligned with the text. Similar to how it's done on https://linear.app/changelog

|DevX digest| changelog|
|-|-|
|<img width="1023" alt="Bildschirmfoto 2022-02-28 um 10 11 10" src="https://user-images.githubusercontent.com/46345125/155955817-cf5a76c2-5a56-41c4-ad12-9092bf63f822.png">|<img width="1384" alt="Bildschirmfoto 2022-02-28 um 10 14 03" src="https://user-images.githubusercontent.com/46345125/155956197-a9acb602-c277-47b0-9c64-5365f6033225.png">


**Issue**: currently the headline isn't aligned with the text on all screen sizes. Could we improve on that? @Cahllagerfeld 🙏
<img width="682" alt="Bildschirmfoto 2022-02-28 um 10 17 32" src="https://user-images.githubusercontent.com/46345125/155956805-447434dc-d14d-4629-affa-cb1b4aa9f39a.png">
<img width="1096" alt="Bildschirmfoto 2022-02-28 um 10 17 23" src="https://user-images.githubusercontent.com/46345125/155956832-3b423108-187a-4f82-9aab-cc9a92b5947d.png">
