### ISSUE TITLE
Search bar is not inheriting the host domain when running from Gitpod

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/website#1652]
Maybe because we use algolia
<img width="821" alt="Screenshot 2022-02-21 at 6 51 49 PM" src="https://user-images.githubusercontent.com/39482679/154959124-8f51942a-1ba2-4ff6-8265-a6c1e2815302.png">

**Comment by mikenikles** [comment]
Correct, DocSearch from Algolia only indexes our production site.
