### ISSUE TITLE
Users are unable to submit messages through the contact form

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#1669]
Users have reported that they cannot submit messages through the contact form. When trying to submit a message, nothing happens after clicking submit buttons in both forms.

**Affected Contact Forms:**
https://www.gitpod.io/enterprise-license
https://www.gitpod.io/contact/sales
https://www.gitpod.io/contact/support

**Comment by Cahllagerfeld** [comment]
Thats an Issue, related to Netlify.
https://answers.netlify.com/t/netlify-serverless-typescript-functions-fail-with-dynamic-requires/52379
@mikenikles also contacted the Netlify-Support directly and requested a full post-mortem once this issue is resolved.
Are there already news @mikenikles ?

**Comment by phimae** [comment]
Should we, as a quickfix put a callout above the forms that asks folks to send emails to contact@gitpod.io directly until this is fixed?
