### ISSUE TITLE
Home page dropdown dashboard link is black-on-black

### ISSUE THREAD

**Issue by macrakis** [gitpod-io/website#1672]
### Bug description

The "Dashboard" link on the "=" dropdown on the gitpod.io home page is unreadable, because it is black-on-black. I'm on current Chrome (98.0.4758.102) on Windows 10.0.19043 Build 19043.

![image](https://user-images.githubusercontent.com/847626/155552276-9a9d19d3-ecde-4c07-9e88-f009d34c4861.png)

### Steps to reproduce

Go to github.io. Click on the hamburger icon in the upper right.

### Expected behavior

Something legible, e.g., white on black or simply black on white.

### Anything else?

I always find it disconcerting that when I go to gitpod.io, it asks me to "sign up" even though I'm a cookied, logged-in user -- when I open the Dashboard link, I see my workspaces.

**Comment by gtsiolis** [comment]
Nice catch, @macrakis!
