### ISSUE TITLE
Small fixes on the career page

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#168]
- [ ] the width of the pullet points in the job description variate

- [ ] the bullet points should be aligned with the first word (it's currently wrong if the sentence goes over two lines)

- [ ] the recent arrow symbol (v) should be replaced with the icon-arrow and scaled down

- [ ] the team-icon has a different width. The heads are thicker than the body

**Comment by ChristinFrohne** [comment]
@nisarhassan12 could you have a look at this when you have time? :)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Yes! for sure I'm going to work on it now.

**Comment by nisarhassan12** [comment]
@ChristinFrohne Does that look good Now the bullets are aligned with the first word: 
![image](https://user-images.githubusercontent.com/46004116/59171859-8ec56a80-8b5e-11e9-93a1-da7e94f6938d.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Can you explain this
![image](https://user-images.githubusercontent.com/46004116/59172888-cf73b280-8b63-11e9-9700-1051a4b629df.png)
What does it mean Does that mean that they should variate because they are equal in width right now.

**Comment by nisarhassan12** [comment]
@ChristinFrohne Does this icon arrow looks fine Ok
![image](https://user-images.githubusercontent.com/46004116/59173609-1911cc80-8b67-11e9-9571-4a995eaa0ed0.png)
![image](https://user-images.githubusercontent.com/46004116/59173617-28911580-8b67-11e9-9b50-c566a2432fa7.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Please also have a look at the width for them team icon
![image](https://user-images.githubusercontent.com/46004116/59174195-e4ebdb00-8b69-11e9-8b43-67877aeb45e9.png)

**Comment by ChristinFrohne** [comment]
@nisarhassan12 
great, this looks lots better!

> ![image](https://user-images.githubusercontent.com/46004116/59172888-cf73b280-8b63-11e9-9700-1051a4b629df.png)
> What does it mean Does that mean that they should variate because they are equal in width right now.

Before the lines had a different width, but the width should always be the same. On your screenshot it looks like that's the case now :) 

>@ChristinFrohne Please also have a look at the width for them team icon

It seems like the border width of the heads are still thicker than the width of the bodies.

**Comment by nisarhassan12** [comment]
@ChristinFrohne Ok I will try to fix the border width soon.
