### ISSUE TITLE
SEO: Accessibility issues

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1689]
- [x] Ensures <li> elements are used semantically: https://i.imgur.com/UybeutH.png --> Perfect element for [Schema.org](http://schema.org/) FAQ-markup 
[affected pages](https://docs.google.com/spreadsheets/d/1FOq9h399Z4fQJcUJs6NrxpjxYABKXb-MfAqZ22GsFhk/edit#gid=0) 
Note: the issue might be resolved with the new editor page, please double-check

- [ ] Form elements must have labels, [affected pages](https://docs.google.com/spreadsheets/d/1KjyN5GJnekXi2gnVZVGTPf4FSfY90QDA-R3ymUdCB3Y/edit#gid=0)

**Comment by nisarhassan12** [comment]
> - [x] Note: the issue might be resolved with the new editor page, please double-check

@ChristinFrohne This seems to be resolved.

**Comment by nisarhassan12** [comment]
@ChristinFrohne Please review https://github.com/gitpod-io/websitepull/1721 when you get time. Thanks
