### ISSUE TITLE
SEO: security improvements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1690]
**High priority:**
- [x] Content-Security-Policy HTTP header is missing or invalid: -> [affected pages](https://docs.google.com/spreadsheets/d/1SQH6yrPRek4MiXW1Octp1IXUiNSqNNT8fGMPKf_vdb8/edit#gid=0)

**medium priority:**
- [x] page has JavaScript served via a CDN without subresource integrity. [Context](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). [Affected pages](https://docs.google.com/spreadsheets/d/1fr3pn_uELlMGeHsH6sDWi7Eoy0XbiMpSxYF-R_Ixoxw/edit#gid=0).
- [x] page has style sheets served via a CDN without subresource integrity. [affected pages](https://docs.google.com/spreadsheets/d/1xaDnPOf4pMhNheE2fVuO8MMRhpN-MI4Qmq9QhizeHEg/edit#gid=0)
- [ ] Leaks server information useful for compromising servers: Potential issue - Detailed check needed [affected pages](https://docs.google.com/spreadsheets/d/13VpUuQJwCOMsRKVuRXIQtB930T2Q24pj1d6TenEK4M0/edit#gid=0) 
- [x] X-Frame-Options HTTP header is missing or invalid -> [affected pages](https://docs.google.com/spreadsheets/d/1CG5A8vJcQCNU-KOnn5FYcuSef4hbkgoKvdn9Lrq5kV8/edit#gid=0)

**lower priority:**

- [x] Referrer-Policy HTTP header is missing -> [affected pages](https://docs.google.com/spreadsheets/d/1B3P4Z1tBu_AEQNy3vyccW9QF_Dv-keUF9Zh9fMOowoM/edit#gid=0)
- [x] Has external opener links vulnerable to tabnapping -> [affected pages](https://docs.google.com/spreadsheets/d/1kGVyojrUg3tpY_17ueV2cVkJgemUPIfFZQ6MFXaGhiY/edit#gid=0)
- [x] X-Content-Type-Options HTTP header is missing -> [affected pages](https://docs.google.com/spreadsheets/d/1uiN3NolPBnzRVdEaR5SY-JMJSvPFBksA5VCvN4_ZbU0/edit#gid=0)
- [x] X-XSS-Protection HTTP header is missing or invalid -> [affected pages](https://docs.google.com/spreadsheets/d/1Okqdt7alZt2PnJwCQcNxM708e3LZmbPVB_mAVv3W2zE/edit#gid=0)

Context: https://snyk.io/test/website-scanner/?test=211215_AiDcKC_03e94e77afec05a39ed2592f936f625a&utm_medium=referral&utm_source=webpagetest&utm_campaign=website-scanner

The issue is based on the SEO audit findings by Buzzmatic. See all results [here](https://docs.google.com/spreadsheets/d/1mz8Lw33ZO4Ugp-68xKPmtl02ineTdbCmVnFHLzmFvUs/edit#gid=709781716)

cc @MircoatGitpod in case you have any useful information to add to this issue 🙏

**Comment by Cahllagerfeld** [comment]
@mikenikles Do we need to adjust this within our webapp, or are this settings that need to be changed at Netlify directly?

**Comment by Siddhant-K-code** [comment]
@chrifro Most of the TODOs are resolved. Not sure about `Leaks server information useful for compromising servers: Potential issue - Detailed check needed`. Do you have some context behind it?

**Comment by chrifro** [comment]
It was marked as a potential issue in the SEO Audit that needed to be checked. Let's ignore it if we can find anything to it.

Amazing work @Siddhant-K-code ! ✨
