### ISSUE TITLE
New Security Blog

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#1692]
In Order to keep track of security-incidents and being transparent with them @MircoatGitpod came up with the idea of creating a blog-style page where we can publish these.

In a call with Mirco and @ChristinFrohne we decided to kind of reuse the existing `Changelog`-Layout for this.

The Idea is to provide a page at `/security/blog` or `/security/log` where we can put it `markdown`-files and publish them, as mentioned earlier in the Changelog-Style.

Do we need a dedicated Page for every Changelog, or is the Timeline-View we are having at `/changelog` currently enough?

Any additional features, like subscribing to it for example, can come in future PRs.

**Comment by Cahllagerfeld** [comment]
@nisarhassan12 as we spoke earlier today, do you have time working on this, or did you get any other issues assigned already? I can support here in case its needed

**Comment by ChristinFrohne** [comment]
>Do we need a dedicated Page for every Changelog, or is the Timeline-View we are having at /changelog currently enough?

Let's start with the timeline view and when can add the dedicated page view when needed

The security release log should be accessible via /security. For that, we could add a CTA in the headline section with "view security log". 
Question: will the log only include security incidents or does it also include proactive updates? -> This might influence how much we want to highlight it

**Comment by MircoatGitpod** [comment]
Most of the time it will contain high-severity findings only

christin ***@***.***> schrieb am Di. 1. März 2022 um 15:22:

**Comment by ChristinFrohne** [comment]
>Most of the time it will contain high-severity findings only

Then I would suggest not using this as the main CTA. Instead, let's add a new section (see mockup). The text can still be adjusted. Would be great if you could do some general layout polishing while addressing this issue (update icons, use big card style with left-aligned text, add a main CTA)
[see mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1443%3A1802)
<img width="289" alt="Bildschirmfoto 2022-03-01 um 16 22 30" src="https://user-images.githubusercontent.com/46345125/156196693-583f0de1-d214-4efe-80dc-2a59c87396e0.png">

**Comment by nisarhassan12** [comment]
> do you have time working on this
@Cahllagerfeld I just finished working on https://github.com/gitpod-io/website/pull/1693 I can work on this for sure.
