### ISSUE TITLE
Documentation: Private image registries

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/website#1704]
### Describe your feature

We're adding support for private Docker image registries. The support is very rough and needs documentation. The PR (linked below) demonstrates how to use that feature.

### How to test

see PR

**Comment by pawlean** [comment]
Yay! So exciting.

**Comment by csweichel** [comment]
added in https://github.com/gitpod-io/gitpod/pull/8550

**Comment by princerachit** [comment]
I am opening this issue as I don't see associated PR for the docs. Search on gitpod website is also not returning anything useful. Is this actually documented?

**Comment by atduarte** [comment]
@csweichel I would like to pick this up. Could you share some details or pointer on how this works?

**Comment by kylos101** [comment]
@atduarte some pointers:

Setup must be done in a Project's Variables.

1. Define GITPOD_IMAGE_AUTH as the name [[1](https://github.com/gitpod-io/gitpod/pull/8550#issuecomment-1204989728)]
2. The value is `<domain>:<base64 encoded value>` [[2](https://github.com/gitpod-io/gitpod/pull/8550#issuecomment-1205068758)]
   1. The string you base64 encode should be like `username:password_or_apikey`
   2. If using Docker Hub, the domain is `docker.io`
   3. Beware [[3](https://github.com/gitpod-io/gitpod/pull/8550#issuecomment-1205317041)]
3. Limitation: if using a custom image, define it in the .gitpod.yml (not the Dockerfile), [related](https://github.com/gitpod-io/gitpod/issues/10204).

**Comment by kylos101** [comment]
@atduarte ☝ should be enough to pick this up, test it, and update the documentation. I'mma move to breakdown. Would you still like to pick this up?

**Comment by atduarte** [comment]
@kylos101 yes, thank you! I missed the previous comment last week. It's perfect 🙌

**Comment by Siddhant-K-code** [comment]
Please, do take care of https://github.com/gitpod-io/gitpod/pull/8550#issuecomment-1278780916
