### ISSUE TITLE
Add a Privacy Policy reference to all forms that process personal data

### ISSUE THREAD

**Issue by MircoatGitpod** [gitpod-io/website#1709]
### Page URL

gitpod.io

### User feedback

Hi Team,

we need to add a privacy policy reference to forms that process personal data (such as names, email addresses and phone numbers).

E.g: "By submitting this form I acknowledge that I have read and understood [Gitpod’s Privacy Policy](https://www.gitpod.io/privacy). "

If we decide to add a newsletter subscription to a contact from, such form would need to have an opt-in (e.g. a checkbox) allowing the processing for additional purposes.

- [x] I agree to receive marketing communications. I may opt-out at anytime.

cc @Cahllagerfeld 

Best regards,

Mirco

**Comment by Cahllagerfeld** [comment]
Nice Catch 🏀 Thanks for opening!

**Comment by Cahllagerfeld** [comment]
I merged it for now, I'd like to review it with you @MircoatGitpod , once you are fully available again, just to make sure we're not running into another issue there.
