### ISSUE TITLE
Replace shares.io logo with their new rebranded logo

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#1720]
Shares.io recently rebranded and we need to update the logos on `/customers` and `/customers/shares-io`
@ChristinFrohne can you please prepare the files in Figma so that @nisarhassan12 can work the changes in? Thanks! 🙏 

**White logo** (you can't see it, but you can download it)
- - [x] this should replace the logo on the blog image and the customer story info card and preview card 
![Shares_Logo_White_RGB](https://user-images.githubusercontent.com/83109781/157045040-c0636aad-dd40-48b6-833f-05e155f953d3.png)
**Black logo**
- - [x] for the quote section on `/customers`
![Shares_Logo_Navy_RGB (1)](https://user-images.githubusercontent.com/83109781/157045036-1ccb87a7-2896-46d4-87e7-736ac49dc334.png)
**Background**
- - [x] This needs to replace the "investing made social" image on `/customers`
![8eda4243-3337-4604-a8bb-53eea5303e4a_hero-desktop2](https://user-images.githubusercontent.com/83109781/157045054-cb7a5db0-66f5-4091-86cf-660f9600dc8c.png)

**Comment by ChristinFrohne** [comment]
The card image is updated in the mockup [[1](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4324%3A3522)]

For the logo, could you provide us with an SVG file @phimae? I couldn't find it online

**Comment by phimae** [comment]
I'm waiting for their CMO to send me the files - unfortunately they do not have a media kit where I can just download it. PNG does not work?

**Comment by nisarhassan12** [comment]
Thanks, @phimae PNG can work as well but SVG is better in many ways. If you say then I can for now make a PR with the PNGs and swap them with SVGs in a follow-up PR once we get them?

**Comment by phimae** [comment]
Let's do it like that if you don't hear back to me until tomorrow noon CET

**Comment by nisarhassan12** [comment]
@phimae Done. Please review https://github.com/gitpod-io/website/pull/1765 when you get time. Thanks
