### ISSUE TITLE
[Docs Feedback]:  seems to be down

### ISSUE THREAD

**Issue by ionutale** [gitpod-io/website#1745]
### Page URL

https://www.gitpod.io/docs/

### User feedback

the docs seem to be down:
https://www.gitpod.io/docs/

![image](https://user-images.githubusercontent.com/2562455/157458082-9075c36f-6f3c-4285-a0f4-0170f533e79d.png)

**Comment by nisarhassan12** [comment]
Thanks, @ionutale for reporting this looks like Netlify is down and having some issues https://twitter.com/search?q=netlify&src=typed_query

Meanwhile, I just tried visiting https://www.gitpod.io and then used the Nav link for going to the docs and it worked.

**Comment by mikenikles** [comment]
There is currently an ongoing issue with our hosting provider, Netlify: https://www.netlifystatus.com/

**Comment by Cahllagerfeld** [comment]
Closing this, because Docs are up & running again.
