### ISSUE TITLE
[pricing]: Create the question mark popovers for the Pricing Cards. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#176]
- [ ] Create the question mark popovers
![image](https://user-images.githubusercontent.com/46004116/113519922-e4c39780-95a8-11eb-8819-c5fddb6a5877.png)

**Comment by ChristinFrohne** [comment]
@nisarhassan12 I'm removing this from the DCS inbox, as the column for scheduled items is already full and because we are planning to update the pricing plans soon. When we're updating them, we should schedule this issue as well. Please move it back to the inbox then

**Comment by nisarhassan12** [comment]
Thanks. @ChristinFrohne I will hopefully do.

**Comment by mikenikles** [comment]
@nisarhassan12 will this issue be closed as part of #1329?

**Comment by nisarhassan12** [comment]
@mikenikles Thanks for bringing this up yep it will be closed as part of #1329
