### ISSUE TITLE
Small fixes for the website

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#177]
Update of issue #20 

General:

- [ ] adding meaningful alt-tags for all images > for better SEO
- [x]  Add a link < rel="canonical" >for better SEO 
- [ ] links from the footer should open in a separate tab

Home screen:

- [ ] aligning the text in "why Gitpod" to the left, so it has the same look as the columns on the career page
- [x] removing blue glow from all arrows

Features:

- [ ]  aligning "try it out" with the graph
- [ ] adding more space between the button "GitHub marketplace" and the text
- [ ] adjusting size of the gray logos, down scaling and placing them less in the top and more on the whole page
- [ ] adding more space between the navigation and the headline

Pricing:

- [x] more spacing before "interested?"
- [ ] removing link from "contact us" as the "let's talk" button has the same link
- [x]  opening "let's talk" and "I'm a student" link in a separate tab

Blog:

- [ ]  is there a way for the images to load faster? maybe downscale them in size?
- [ ] adjusting the preview text for "dev environments as code" 
- [ ] adding more gray logos at the bottom of each blog post, less on top and smaller 
- [ ] should we add a like-button?

Docs:

- [x]  links to another website should be opened in another tab, e.g. theia, spectrum
- [ ] gray logo on the top left is too small, adding more logos on the bottom
- [ ] updating screenshot of the dashboard, dark theme (dashboard)
- [ ] updating lense-picture (introduction) See issue #74 
- [ ] Table of Contents should remain visible as you scroll down in a long page

**Comment by ChristinFrohne** [comment]
Would be great if you can have a look at this as well @nisarhassan12 
But it's no hurry :)

**Comment by ChristinFrohne** [comment]
Found another thing:

- [ ] when I refresh the pricing site the layout changes (less spacing, smaller font and smaller boxes)

before refreshing
<img width="900" alt="Bildschirmfoto 2019-06-13 um 11 15 34" src="https://user-images.githubusercontent.com/46345125/59420201-bfaad700-8dcc-11e9-8277-09b0d9e7ffe0.png">
after refreshing
<img width="901" alt="Bildschirmfoto 2019-06-13 um 11 14 53" src="https://user-images.githubusercontent.com/46345125/59420198-bde11380-8dcc-11e9-9762-c580b553453d.png">

**Comment by nisarhassan12** [comment]
> Update of issue #20
> 
> General:
> 
>     * [ ]  adding meaningful alt-tags for all images > for better SEO
> 
>     * [ ]   Add a link < rel="canonical" >for better SEO
> 
>     * [ ]  links from the footer should open in a separate tab
> 
> 
> Home screen:
> 
>     * [ ]  aligning the text in "why Gitpod" to the left, so it has the same look as the columns on the career page
> 
>     * [ ]  removing blue glow from all arrows
> 
> 
> Features:
> 
>     * [ ]   aligning "try it out" with the graph
> 
>     * [ ]  adding more space between the button "GitHub marketplace" and the text
> 
>     * [ ]  adjusting size of the gray logos, down scaling and placing them less in the top and more on the whole page
> 
>     * [ ]  adding more space between the navigation and the headline
> 
> 
> Pricing:
> 
>     * [ ]  more spacing before "interested?"
> 
>     * [ ]  removing link from "contact us" as the "let's talk" button has the same link
> 
>     * [ ]   opening "let's talk" and "I'm a student" link in a separate tab
> 
> 
> Blog:
> 
>     * [ ]   is there a way for the images to load faster? maybe downscale them in size?
> 
>     * [ ]  adjusting the preview text for "dev environments as code"
> 
>     * [ ]  adding more gray logos at the bottom of each blog post, less on top and smaller
> 
>     * [ ]  should we add a like-button?
> 
> 
> Docs:
> 
>     * [ ]   links to another website should be opened in another tab, e.g. theia, spectrum
> 
>     * [ ]  gray logo on the top left is too small, adding more logos on the bottom
> 
>     * [ ]  updating screenshot of the dashboard, dark theme (dashboard)
> 
>     * [ ]  updating lense-picture (introduction) See issue #74
> 
>     * [ ]  Table of Contents should remain visible as you scroll down in a long page

**Comment by nisarhassan12** [comment]
> Update of issue #20
> 
> General:
> 
>     * [x]  adding meaningful alt-tags for all images > for better SEO
> 
>     * [x]   Add a link < rel="canonical" >for better SEO
> 
>     * [x]  links from the footer should open in a separate tab
> 
> 
> Home screen:
> 
>     * [x]  aligning the text in "why Gitpod" to the left, so it has the same look as the columns on the career page
> 
>     * [ x]  removing blue glow from all arrows
> 
> 
> Features:
> 
>     * [ ]   aligning "try it out" with the graph
> 
>     * [x]  adding more space between the button "GitHub marketplace" and the text
> 
>     * [x]  adjusting size of the gray logos, down scaling and placing them less in the top and more on the whole page
> 
>     * [x]  adding more space between the navigation and the headline
> 
> 
> Pricing:
> 
>     * [x]  more spacing before "interested?"
> 
>     * [ ]  removing link from "contact us" as the "let's talk" button has the same link
> 
>     * [ ]   opening "let's talk" and "I'm a student" link in a separate tab
> 
> 
> Blog:
> 
>     * [ ]   is there a way for the images to load faster? maybe downscale them in size?
> 
>     * [ ]  adjusting the preview text for "dev environments as code"
> 
>     * [ ]  adding more gray logos at the bottom of each blog post, less on top and smaller
> 
>     * [ ]  should we add a like-button?
> 
> 
> Docs:
> 
>     * [ ]   links to another website should be opened in another tab, e.g. theia, spectrum
> 
>     * [ ]  gray logo on the top left is too small, adding more logos on the bottom
> 
>     * [ ]  updating screenshot of the dashboard, dark theme (dashboard)
> 
>     * [ ]  updating lense-picture (introduction) See issue #74
> 
>     * [ ]  Table of Contents should remain visible as you scroll down in a long page
