### ISSUE TITLE
Improve the contrast of the buttons with the white background

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1796]
The extensions buttons on the Spin up section on the homepage don't seem to have good enough contrast i.e both the section + the buttons have the same off-white: `#f9f9f9` background. 

![image](https://user-images.githubusercontent.com/46004116/159260554-cd8c3ffc-2644-487c-b751-00dd20cfa5d6.png)

### Solution

Initially, I thought that changing the background of the section to white would help but then we will have the same problem on hover. 

cc @chrifro Can you suggest something here when you get some time? Thanks

**Comment by Cahllagerfeld** [comment]
See the button in [figma](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=4%3A142)

**Comment by chrifro** [comment]
Nice catch! Could you adjust the background color for only these specific buttons to sand dark #ECE7E5?

<img width="531" alt="Bildschirmfoto 2022-04-06 um 10 28 56" src="https://user-images.githubusercontent.com/46345125/161931369-67094019-106e-4831-8c96-b4ca4b4b5008.png">

**Comment by Cahllagerfeld** [comment]
Should we add `sand dark` to the buttons mentioned [here](https://github.com/gitpod-io/website/issues/1796#issue-1175316538) as well? 😅
