### ISSUE TITLE
/customers quotes section logos are blurry on Chrome and Brave

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1821]
| Chrome, Brave | Firefox |
| - | - |
| ![Screen Shot 2022-03-24 at 5 41 51 PM](https://user-images.githubusercontent.com/46004116/159918416-fa321429-ab5c-43da-a160-17faf977f1e6.png) | ![image](https://user-images.githubusercontent.com/46004116/159918966-b3d39e52-ae74-499e-a240-1bd3a9154fac.png) |

**Comment by nisarhassan12** [comment]
Thanks, @Cahllagerfeld not sure whether that would help i.e their quality is already good enough if you look at them in Firefox. I think using SVGs instead of PNGS might help.

**Comment by Cahllagerfeld** [comment]
Are these the exports from Figma, or do we store them somewhere else as well?

**Comment by Cahllagerfeld** [comment]
From which Figma-File did you actually get the icons? I can't find them either on the Mockup for [`/customers`](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4054%3A2870), nor in the [`logos-section`](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=513%3A693)

**Comment by nisarhassan12** [comment]
I think they are not in Figma instead If I'm not wrong Philip was the one who provided me with them in a GitHub issue or a PR. 
Here are the SVGs logos for Vizlib https://home.vizlib.com/wp-content/themes/vizlib/img/logos/logo-color.svg
and for Shares.io
![image](https://user-images.githubusercontent.com/46004116/160633276-549a6411-2fb7-4116-9cda-28096ecf9671.svg)

@phimae I didn't find the SVG for Redwood JS online. Can you reach out to them and ask for the SVG logo? Thanks
