### ISSUE TITLE
Pricing Cards: appear too wide on small devices.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1826]
We should set a max-width so that they look close to what we have in the component library. 

![image](https://user-images.githubusercontent.com/46004116/159990415-625bff7e-dde3-4f69-9842-cbf55b1fd12b.png)

**Comment by ramanand-rv** [comment]
Hey @nisarhassan12, I would like to work on this issue and resolve it.

**Comment by nisarhassan12** [comment]
Thanks @ramanand-rv ❤️  Feel free to make a PR. Let me know in case you need any kind of help with it.

**Comment by nisarhassan12** [comment]
@ramanand-rv About the `max-width` value I think `320px` would work fine for devices below `768px`.

**Comment by nisarhassan12** [comment]
@ramanand-rv Let me know in case you need any help? Are you still interested in working on this? Thanks

**Comment by levi-bassey** [comment]
Can I resolve this if @ramanand-rv isn't available.

**Comment by nisarhassan12** [comment]
Thanks, @levi-bassey yeah let's do that. Looks like he is busy.
