### ISSUE TITLE
Sign up button is visible to logged in users on tablet

### ISSUE THREAD

**Issue by levi-bassey** [gitpod-io/website#1839]
The sign up button for tablet currently shows up even though the user is logged in.
![image](https://user-images.githubusercontent.com/43778081/160704132-bf6892bd-35ed-4dbd-a5b5-05c48990a952.png)

@nisarhassan12 is this something that needs fixing? Or is it intentional?

**Comment by nisarhassan12** [comment]
Thanks, @levi-bassey for the issue. 

> @nisarhassan12 is this something that needs fixing? Or is it intentional?

It needs to be fixed. it is un-intentional.
