### ISSUE TITLE
Lazy load images to enhance page load times. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1850]
On the [Changelog](https://www.gitpod.io/changelog) the lighthouse score is 50 and that is because of the fact that all the changelog entries images are loaded on the initial page load.

![image](https://user-images.githubusercontent.com/46004116/161145091-9d304f5f-db5c-4d9d-b27a-01ab1eca17fe.png)

The problem with loading all the images that a page has is that we are never sure if for instance a user will scroll down and see them all thus resulting in unnecessary usage of bandwidth which we can avoid via lazy loading. Lazy loading will help improve the overall performance scores as well.

**Comment by Siddhant-K-code** [comment]
👋🏼 @nisarhassan12 
Any Reasons, why it is kept on hold?
Or, is there any plan to work upon it?

**Comment by nisarhassan12** [comment]
@jacobparis suggested rather than what I have implemented in #1878 we could try native lazy loading by adding the width and height of the image directly to the element.

**Comment by jacobparis** [comment]
Relevant doc https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes

`<img src="image.jpg" alt="..." loading="lazy" />`
