### ISSUE TITLE
Server error (5xx) for https://www.gitpod.io/changelog/introducing-teams-&-projects

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1856]
Since March 2 there is a server error for https://www.gitpod.io/changelog/introducing-teams-&-projects

More details: https://search.google.com/search-console/inspect?resource_id=https%3A%2F%2Fwww.gitpod.io%2F&id=PY4Q77fwWdx0XrIjhn7Ozg&hl=en-DE

Error message:
<img width="940" alt="Bildschirmfoto 2022-04-04 um 09 31 18" src="https://user-images.githubusercontent.com/46345125/161495032-2be5db03-87f0-4675-9582-95e53c20b8ff.png">

**Comment by nisarhassan12** [comment]
Reopening it as the changes made in #1857 were not able to fix it.

**Comment by Cahllagerfeld** [comment]
The issue here was the `&` in the URL. I changed that to an `and`. I checked if we have any internal links to this page, which is not the case. Should we add a redirect from the old-URL to the new one though? What do you think @nisarhassan12

**Comment by Cahllagerfeld** [comment]
I'll add the redirect, just to make sure all links keep working in case someone links to this page from external

**Comment by nisarhassan12** [comment]
Thanks, @Cahllagerfeld for taking care of this. Sorry for the late response. It is great that you have already added the redirect.

**Comment by chrifro** [comment]
The issue still persists, see [here](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Agitpod.io&item_key=CAMYEyAE&hl=en).

In addition to https://www.gitpod.io/changelog/introducing-teams-&-projects this issue also affects gitpod.io/api/xyz in the dashboard. Could you forward the issue to the WebApp team once you identified the problem? 🙏

**Comment by Cahllagerfeld** [comment]
I merged a fix for [these](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Agitpod.io&item_key=CAESIWh0dHBzOi8vd3d3LmdpdHBvZC5pby9zaXRlbWFwLnhtbBgTIAQ&hl=en) pages. I'll close the issue, once this validation is successfull

**Comment by Cahllagerfeld** [comment]
Review from Google is still pending on this end..

**Comment by Cahllagerfeld** [comment]
From the latest report in the Search Console, we're no longer having pages that are affected by `500`s on our website [[1](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Agitpod.io&item_key=CAMYEyAC&hl=en)]
