### ISSUE TITLE
Include additional repositories in changelog

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/website#1859]
:wave: , can we include more than the Gitpod mono repo when generating changelog content? 

I see the current query is limited to our mono repo for now:

https://github.com/gitpod-io/website/blob/2b79ed8eaa6e0da00e458fe8618e519830dd643c/scripts/generate-changelog.js#L92

Here are some repos, which I think we'll want to search for Release Notes. Some of these are private, for those, maybe we could show the release note, but omit the hyperlink to the issue?

1. https://github.com/gitpod-io/ops (private) <-- often contains changes that are user facing for `workspace clusters`
2. https://github.com/gitpod-io/workspace-images/ <-- often contains changes that are user facing
3. https://github.com/gitpod-io/dazzle/  <-- changes are generally user facing
4. https://github.com/gitpod-io/gitpod-packer-gcp-image (private) <-- changes can be user facing
5. https://github.com/gitpod-io/website <-- for features and new pages (e.g. https://github.com/gitpod-io/website/pull/1865 or https://github.com/gitpod-io/website/pull/2446)
6. https://github.com/gitpod-io/openvscode-server <-- changes can be user facing
7. https://github.com/gitpod-io/gitpod-vscode-desktop/ <-- changes are usually user facing

@geropl @corneliusludmann @akosyakov  are there any other repos where you make code changes that are user facing, and would like to have their release notes accounted for in the changelog script?

**Comment by kylos101** [comment]
Hey @mikenikles , has anything like this come up before at Gitpod, having the ability to collect Release Notes from other repos, or private repos?

**Comment by filiptronicek** [comment]
Added some IDE-relevant repos to the issue description, as well as this website repo.

cc @kylos101 @loujaybee

**Comment by filiptronicek** [comment]
Relevant internal discussion: https://gitpod.slack.com/archives/C022HAT0H5Z/p1664265127875659
