### ISSUE TITLE
Subscription to our Security Blog

### ISSUE THREAD

**Issue by securitymirco** [gitpod-io/website#1871]
### Page URL

https://www.gitpod.io/security/log

### User feedback

Let's allow users to sign-up of updates to our security blog. Whenever we publish new content at gitpod.io/security/log I could sent a notification to the mailing list.

**Comment by Siddhant-K-code** [comment]
This is covered by our [Trust Center](https://app.safebase.io/portal/71ccd717-aa2d-4a1e-942e-c768d37e9e0c/preview?product=default) now.
