### ISSUE TITLE
Publish List of Gitpod Subprocessors + Subscription

### ISSUE THREAD

**Issue by securitymirco** [gitpod-io/website#1875]
### Page URL

gitpod.io/subprocessors

### User feedback

To make the management of Data Processing Agreements less complicated for us and our clients, we would love to make our [list of Sub-processors](https://www.notion.so/gitpod/97598e2a004648ca84f46b892a37321f?v=1eaededb363f42d792c7e25c446794be) public.

In order to comply with regulatory and contractual requirements we would need to enable our users to subscribe to notifications on our Sub-processors. These notifications could be sent individually to anyone who signed-up.

This webpage does not need to be linked anywhere at gitpod.io.

**Comment by chrifro** [comment]
Oh it's the one-year anniversary of this issue 🥲
Is it still relevant @securitymirco? Could you give me access to the Notion page? 🙏

>In order to comply with regulatory and contractual requirements we would need to enable our users to subscribe to notifications on our Sub-processors.

Any thoughts on how to accomplish this? I don't think it's worth the effort creating a new email setup for this. WDYT?

**Comment by securitymirco** [comment]
@chrifro I think we are good them here https://www.gitpod.io/sub-processors. Also there is our new trust center + email notifications being sent out once we change sub processors.

**Comment by Siddhant-K-code** [comment]
Thanks @securitymirco ✨
