### ISSUE TITLE
Border Radius Fix

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1877]
"Big Card" and "Narrow Card" should have a border radius of 16px instead of 40px

[Figma Link](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831)

**Comment by chrifro** [comment]
It's adjusted in the component library. Over to you @nisarhassan12 🏀 🙌
