### ISSUE TITLE
Mobile: secondary buttons too small

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1881]
Secondary buttons have a font-size of 12px instead of 14px. It’s hard to read and does not fit the styleguide
<img width="323" alt="Bildschirmfoto 2022-04-06 um 12 09 24" src="https://user-images.githubusercontent.com/103135399/162199298-422efd97-1ffb-4cb8-9965-5f308bf0ae6f.png">

**Comment by chrifro** [comment]
This change aligns with the component library and is ready for implementation 
cc @nisarhassan12
