### ISSUE TITLE
Do not remove CLA link as the CLA template includes https://www.gitpod.io/cla

### ISSUE THREAD

**Issue by tnir** [gitpod-io/website#1890]
The CLA includes URLs to the repository `https://www.gitpod.io/cla` and signers will see the repo, so I do not think it is good to remove links in #1789.

_Originally posted by @tnir in https://github.com/gitpod-io/website/issues/1789#issuecomment-1091823138_

**Comment by tnir** [comment]
Inviting @meysholdt to address this problem causing the CLA signing delayed in a few weeks cc @gtsiolis

**Comment by Siddhant-K-code** [comment]
That process is different now & managed by @meysholdt.
