### ISSUE TITLE
Search Console error: Submitted URL marked ‘noindex’

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1891]
Affected pages: 37

error:
>Submitted URL marked ‘noindex’: You [submitted this page for indexing](https://support.google.com/webmasters/answer/7440203#submitted), but the page has a ['noindex' directive](https://support.google.com/webmasters/answer/93710) either in a meta tag or HTTP header. If you want this page to be indexed, you must remove the tag or HTTP header.

For more details, see [here](https://support.google.com/webmasters/answer/7440203#submitted_but_noindex) and [here](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Agitpod.io&item_key=CAMYHCAE&hl=en)

**Comment by nisarhassan12** [comment]
@Cahllagerfeld I had a look into it and it turns out that we have to remove the pages from the `sitemap.xml` that have the 'no-index' set so that Google does not try to crawl them.

**Comment by Cahllagerfeld** [comment]
I removed the pages, that are listed in the google-console. Just another question is it correct, that the mentioned pages in the list aren't indexed? I think for the quickstarts, it is because we decided that a couple of weeks ago, but `/vs/jetbrains` but what about `/enterprise-license`

**Comment by nisarhassan12** [comment]
Regarding the `/vs/jetbrains` it is on purpose, for now, we'll remove it later on but for the Enterprise License I'm not sure why we did that in the first place cc @chrifro Do you know why we did that so? Thanks 

 https://gitpod.slack.com/archives/C01KGM9ETU/p1648139777878899?thread_ts=1647545741.096849&cid=C01KGM9ETU6
