### ISSUE TITLE
How to handle icons on cards

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1892]
[[Figma Link](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=254%3A3453)](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=254%3A3453)

**Icon Style**

- No shadows
- Icons should always be as simple as possible
- Gitpod gradient used here

**Tasks**

- Export and exchange icons
- Document icon style in the styleguide

<img width="872" alt="Bildschirmfoto 2022-04-08 um 16 43 46" src="https://user-images.githubusercontent.com/103135399/162696607-e8e19d03-7889-4fb3-9816-a0b8a196631c.png">

**Comment by chrifro** [comment]
picked up in #2022
