### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1893]
[[Figma Link](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=286%3A7601)](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=286%3A7601)

-  [x] Adjust height accordingly to the Figma design file (48px instead of 60px height)
- [x] New hover state (outline)
- [x] Dark mode

**Comment by chrifro** [comment]
The toggle component has been updated in the component library. Could you adjust it on the website as well @nisarhassan12 🙏

Changes: the hover has a linear stroke now, there is no more shadow, and the selected item changes on hover. The button height was never in sync with the height in the component.


Thanks!

**Comment by nisarhassan12** [comment]
> - [ ] and the selected item changes on hover.
@chrifro I have made the changes in https://github.com/gitpod-io/website/pull/2050 apart from changing the selected item on hover. I'll make a follow-up Pr for that.
