### ISSUE TITLE
Pricing page Cards Update

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1894]
[[Figma Link](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=274%3A3937)](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=274%3A3937)

- Add a label to the highlighted plan
- Drop shadow with #FFCA64 at a 24blur

**Comment by chrifro** [comment]
@SaraHesse to keep a better overview, it would be best to collect all information relating to one issue in the same issue.

I will be merging this issue with #1880 as both address the design of the pricing cards
