### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1896]
[[Figma Link](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=274%3A3344)](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=274%3A3344)

**Additional Colors**

[[Figma Link](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=286%3A3962)](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=286%3A3962)

#1A1712 Additional darkmode black
#23211E Additional darkmode very dark grey
#999795 Old light grey is now a darkmode grey
#D9994E Kumquat almost ripe (darkmode)

- Dark mode toggle in the footer
- Exchanged colors
- Different 3D illustration in the first viewport
- Visuals will be in a separate task since they are still WIP

**Comment by nisarhassan12** [comment]
Fixed in #1865
