### ISSUE TITLE
Get started Module Button adjustment

### ISSUE THREAD

**Issue by SaraHesse** [gitpod-io/website#1902]
The "launch workspace" button should be equidistant from top, right, bottom, left (0.75rem everywhere).
The space between icon and typography needs to reduce to 0.5rem. 
Should look like this: 

<img width="705" alt="Bildschirmfoto 2022-04-12 um 10 02 02" src="https://user-images.githubusercontent.com/103135399/162912900-fe647624-75a5-4df4-9b81-6a964c7c22cc.png">

**Comment by levi-bassey** [comment]
Is anyone working on this? I want to try fixing this.

**Comment by chrifro** [comment]
Hi @levi-bassey, there is no one working on this issue yet. Feel free to tackle it. 
Thanks for your help 🧡
