### ISSUE TITLE
To be published - Gitpod Cookies Policy

### ISSUE THREAD

**Issue by MircoatGitpod** [gitpod-io/website#1935]
### Page URL

https://gitpod.io/cookies

### User feedback

Dear Team,

we are planning to release a new Cookies Policy that is separate but also expands our current [Privacy Policy](https://www.gitpod.io/privacy).

I already created a`cookies.md`file under src/routes in https://3000-gitpodio-website-wnnbqgeita9.ws-eu41.gitpod.io/cookies and pasted the unformatted content.

- [ ] Format document and cookie table into one page
- [ ] @MircoatGitpod to publish the new version Privacy Policy
- [ ] Add current date to Cookie Policy (same as inside the Privacy Policy)
- [ ] Publish page under https://gitpod.io/cookies
- [ ] Add Cookie Policy reference into our Website Footer (below "Privacy Policy" in "Legal")
![image](https://user-images.githubusercontent.com/97025146/164651877-efdc9ad1-e2bc-4b87-a413-a010d541ee2c.png)

References
[Cookie Policy](https://docs.google.com/document/d/1qrTno7DanvJnL8h-oMK7SpnVy-19mLVi/usp=sharing&ouid=104881937191958652298&rtpof=true&sd=true) document in Google Drive 
[Cookie Table](https://www.notion.so/gitpod/a8f22878433e4c00a98dc5affe08f42d?v=2ec614009b1749c2a16401300ed1208d) inside Notion

**Comment by MircoatGitpod** [comment]
cc @Cahllagerfeld @chrifro we can use this ticket to organise our efforts for publishing our new cookies policy. I definitely need your help in formatting / design.

**Comment by chrifro** [comment]
Is this issue still up-to-date?  @MircoatGitpod 
Do you still need any help? :)

**Comment by MircoatGitpod** [comment]
@chrifro thx for the reminder! I will close this issue as we will publish the policy together with our cookie banner.
