### ISSUE TITLE
use box shadows consistently with the component library

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1950]
In the component library, we only have 3 box shadows while on the live site we have a total of 5 we should make it so that the 3 mentioned in the component library are used consistently. 

```scss
--shadow-light: 0 1px 1px rgba(0, 0, 0, 0.1);
--shadow: 0 0.625rem 1.5rem 0rem rgba(0, 0, 0, 0.08);
--shadow-medium: 0 1.25rem 2.5rem rgba(0, 0, 0, 0.1);
--shadow-brand: 0 0.625rem 1.5rem var(--brand-quaternary);
--shadow-light-1: 0px 3.58399px 8.95998px rgba(0, 0, 0, 0.08),
    0px 8.95998px 35.8399px rgba(0, 0, 0, 0.12);
```

**Comment by chrifro** [comment]
Some shadows also don't align with the component library, see this example
|live|mockup|
|-|-|
|<img width="600" alt="Bildschirmfoto 2022-06-15 um 08 30 09" src="https://user-images.githubusercontent.com/46345125/173758033-c5427df8-a153-4032-ac14-47b20cbe5ee6.png">|<img width="395" alt="Bildschirmfoto 2022-06-15 um 08 30 18" src="https://user-images.githubusercontent.com/46345125/173758074-8068eafe-e8cd-43d7-9566-c1f81fbe0c1a.png">
|

see https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831

**Comment by nisarhassan12** [comment]
@chrifro Do you mean using only 4 shadows for the light mode and 3 for the dark as per the Figma file? and getting rid of any other shadow being used and switching that to use one of the values from the shadows defined in the mockup ?

**Comment by chrifro** [comment]
Exactly. These are the style that should be in use
<img width="232" alt="Bildschirmfoto 2022-07-05 um 15 46 39" src="https://user-images.githubusercontent.com/46345125/177342799-3146892f-bf2c-4445-b60f-7c9489425a36.png">

If you find any shadows that are not close to any of the specifics in the component library, let me know and we will find a solution :)

**Comment by chrifro** [comment]
I think some shadow styles have already been updated by now. Some have not. E.g. labels in dark theme should follow the button shadow style
<img width="414" alt="Bildschirmfoto 2022-11-25 um 10 53 22" src="https://user-images.githubusercontent.com/46345125/203954467-f68e0f19-afbe-45b8-9b88-e2061e498229.png">

Let's review all shadow styles and align them with the component library [[1](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=557%3A1088&t=cXyXZpEeZTp0dpDs-1)]
