### ISSUE TITLE
[dark-mode]: images that need adjustments.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#1958]
- [x] 1) Homepage -> section **Where teams code together** the white version does not look bad but i think it would look more nicer if it had a dark mode variant.
![image](https://user-images.githubusercontent.com/46004116/165453661-52ad6151-00c8-4998-ab60-232a35f9cfc4.png)
- [ ] 2) Screencast preview image
![image](https://user-images.githubusercontent.com/46004116/165453953-9c66963d-a4bf-4250-b4df-57cec3354451.png)
- [x] 3) Illustration for the callout section
![image](https://user-images.githubusercontent.com/46004116/165454046-abc8bd6d-a1fd-4da0-b6e9-e4cbae555bb5.png)
- [ ] 4) Hero image `/customers`
![image](https://user-images.githubusercontent.com/46004116/165497922-e454041e-bde8-46e4-a7df-5712daed3d3d.png)
- [ ] 5) mage in the header on the support page
![image](https://user-images.githubusercontent.com/46004116/165498321-e19ae985-15d7-4bf3-94b9-1d691d73236f.png)
- [x] 6) Cube illustration  that shows up on submission success on contact forms 
![image](https://user-images.githubusercontent.com/46004116/165499149-b47b6e91-618e-4597-8811-7ef5d40c22fe.png)
- [x] 7) Illustration on `/unsubscribe`
![image](https://user-images.githubusercontent.com/46004116/165499303-2eace2bb-bea4-4c4d-a456-b4a27bab819f.png)
- [x] 8) Quote images for Shares.io, Vizlib (something which we can probably ignore.)
![image](https://user-images.githubusercontent.com/46004116/165499960-a704939c-2975-4a1e-ab19-be729428df76.png)
- [x] 9) `/for/startups` Feature image in **Scaling from 3 to 45 engineers in 5 months** section
![image](https://user-images.githubusercontent.com/46004116/165500323-ad2ffde9-ff1a-4456-88cc-3d74449040de.png)
- [x] 10)`/for/opensource` Wreft logo under **Opensource is in our DNA section**
![image](https://user-images.githubusercontent.com/46004116/165500895-3edafbf3-e777-4fbb-ada1-956ae2eeade6.png)
- [x] 11)`/vs/github-codespaces` graphic for **Ready in a flash** and **Resource efficent** sections. 
![image](https://user-images.githubusercontent.com/46004116/165502262-8e4473dd-6cc2-44cb-93ad-1866d6f1f875.png)
- [x] 12) `/vs/local-development` illustration used in **Ready within seconds when working in the cloud** 
![image](https://user-images.githubusercontent.com/46004116/165503745-91ff5d22-2b3e-43b3-ab19-a555108b9d41.png)
- [x] 13) `/vs/jetbrains-space` illustration for **Your environment, your tools, your craft** section.
![image](https://user-images.githubusercontent.com/46004116/165504305-c18e6dc5-bedb-40d4-b591-8f0cc86b21e7.png)
- [x] 14) `/vs/jetbrains-space` image under **Ready to launch your JetBrains IDE within Gitpod?**
- [x] 15) ![image](https://user-images.githubusercontent.com/46004116/165504565-cbec694a-f55b-4b96-8f87-641d203654bf.png)
- [ ] 16)below images on the `/media-kit` page
![image](https://user-images.githubusercontent.com/46004116/165505120-b7a2f7b4-c183-4741-972d-5e118762240b.png)
![image](https://user-images.githubusercontent.com/46004116/165505237-29968416-8741-467e-9063-be2cd1d3b876.png)

**Comment by chrifro** [comment]
Here is the first bunch of improvements @nisarhassan12 
regarding 1) we have a new animation for that see [internal link](https://gitpod.slack.com/archives/C01KYFKAUQ4/p1651500448316269?thread_ts=1651252445.736659&cid=C01KYFKAUQ4)
regarding 3) you can find the dark-theme cube pattern [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=1772%3A3079)
regarding 6) 7) you can use the same image as for the header. [Here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=1772%3A3079) is the final version. Please use this version for the primary header image as well. I'm working on aligning the light theme cube exactly to it as well.
regarding 11) 12) could you not just adjust the font color?
regarding 13) see [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5019%3A4846)


Image adjustments that can be postponed for now: 2) 8) 16)

**Comment by nisarhassan12** [comment]
Thanks @chrifro 

> regarding 3) you can find the dark-theme cube pattern [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=1772%3A3079)

Regarding 3 can you put in the dark mode images here https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=1778%3A3228 in the component library? From there I'll be able to export them in the correct shape i.e with CSS adjusting the shape is impractical. Thanks

**Comment by chrifro** [comment]
Sure here it is: https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=1783%3A3120

Note: the light theme cards are not adjusted yet to the new design

**Comment by nisarhassan12** [comment]
> regarding 1) we have a new animation for that see [internal link](https://gitpod.slack.com/archives/C01KYFKAUQ4/p1651500448316269?thread_ts=1651252445.736659&cid=C01KYFKAUQ4)

@chrifro I have adjusted/addressed the rest for 1) it would make sense to tackle that in a follow-up Pr.

**Comment by nisarhassan12** [comment]
@chrifro Please provide me with the dark mode version of the following for `/vs/local-dev` I tried exporting it as an SVG and the size is too big because the SVG itself contains raster images. Thanks
![image](https://user-images.githubusercontent.com/46004116/168027904-d8ea49e1-bbce-460e-a664-2b05aa4ee45a.png)

**Comment by chrifro** [comment]
You can find the image [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5062%3A5585)

**Comment by nisarhassan12** [comment]
> Image adjustments that can be postponed for now: 2) 8) 16)

@chrifro when do you expect to get back to me regarding these Thanks.

**Comment by chrifro** [comment]
I think the images are okay as they are and we can close this issue. Thanks for keeping track!
