### ISSUE TITLE
[Bug] Self-Hosted Pricing Page UI scales in a way that text is hidden and overflows

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#1964]
There is a bug in the feature list on the [Self-Hosted Pricing page](https://www.gitpod.io/self-hosted). See the screenshot below, but under certain window width the text on the "Register and Install Now" button overflows and the air gapped feature description is covered. This only happens in a limited number of window widths, and as such is not a blocker. 
<img width="1125" alt="Screenshot 2022-04-28 at 08 50 25" src="https://user-images.githubusercontent.com/22516873/165695184-9aa62ba6-96a3-4e39-9787-443f6bc3c3da.png"> 

(Screenshot is from #1940 and assumes it has been merged)

**Comment by nisarhassan12** [comment]
I have fixed this in https://github.com/gitpod-io/website/pull/2072
