### ISSUE TITLE
submit-form to sendgrid injects tracking params into message text

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#1983]
https://github.com/gitpod-io/website/blob/main/src/functions/submit-form.ts

this

> We've encountered a bug (https://github.com/gitpod-io/gitpod/issues/9559) which is causing new prebuilds to fail. 

turns into

> We've encountered a bug (https://github.com/gitpod-io/gitpod/issues/9559)?utm_source=sendgrid&utm_medium=email&utm_campaign=all-sendgrid-emails which is causing new prebuilds to fail. 

(see internal [discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1639603049217900))

**Comment by Siddhant-K-code** [comment]
@jldec can you please confirm that, is it still a bug?

**Comment by jldec** [comment]
Message: testing a message with a link from the form at this link :)

https://www.gitpod.io/contact/support
?utm_source=sendgrid&utm_medium=email&utm_campaign=all-sendgrid-emails

answering the question in [https://github.com/gitpod-io/website/issues/1983?utm_source=sendgrid&utm_medium=email&utm_campaign=all-sendgrid-emails#i…](https://github.com/gitpod-io/website/issues/1983?utm_source=sendgrid&utm_medium=email&utm_campaign=all-sendgrid-emails#issuecomment-1271780647)

**Comment by Siddhant-K-code** [comment]
Thanks, @jldec for confirming this. I will take a look at this with @Cahllagerfeld

**Comment by jimmybrancaccio** [comment]
Of note, once we move over to the Front API (#2754) this won't matter.
