### ISSUE TITLE
General suggestions for adjustments 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#20]
**General:**
- [x] grey sub headline should be everywhere the same (no capital letters)

- [x] Footer: links to GitHub, Twitter and Spectrum don't work yet

- [x] ~~showing  avatar, if you are logged in?~~ (EDIT: we're now using a generic `Go to app` button)

- [x] placing some random gitpod logos in the bottom of longer sites. So far they are only on the top 
- [x] I found a gitpod-logo behind text (tos)
- [ ] removing glow from arrows

**Start screen:**
- [ ] Get-started-animations starts too early. The user will probably not see it 

- [ ] texts underneath "url prefix", "browser extension", "GitHub App" should start on the same height, same count for the 3 dots and the arrows on the sides

- [x] "Learn more"-links don't work. Generic links should be avoided in order to optimize SEO. Suggestion: "GitHub Marketplace" and "Add Browser Extension"

- [ ] smaller frame for the learn-more-buttons (less spacing on the sides)

- [ ] aligning the text in "why Gitpod" with the "w" and the outer border

- [x] maybe better to open the workspaces in a separate tab?

- [x] aligning "tell me more" to the height of the dot

- [x] Try "it" now

- [ ] @gitpodio from the twitter accounts is not directed to the current twitter account

**Features:** 
- [ ] the images look weird. maybe adding a frame or adjust their background color and crop them partially helps

- [ ] updating the link for prebuilt workspaces

- [ ] adjusting names of the buttons. suggestions: "Blog Post", "Docs"

- [ ] play-Video-Button doesn't work

- [x] updating request-support-button

**Pricing:** 

- [ ] updating link "get-started" - opening billing window? if yes, maybe rename the button to "buy now"? 

- [ ] adjusting font size in "team subscription" 

- [ ] renaming button in "team subscription" which site is supposed to be seen afterwards? Suggestion: "contact us"

- [x] "I'm a Student"-button is not working yet

- [ ] more spacing after the table and "interested?" would be good

- [x] updating link "let's talk"

**Blog:** 

- [ ] is there a way for the images to load faster? maybe downscale them in size?

- [ ] adjusting all images with screenshots to the frame

- [x] the link to the author should rather not be under date

- [x] font size of the sub headline and headline in the blog posts is too big

- [x] links to the author should rather be open in a new tab, this should count for all links which link to another website. (often missing in blog posts)

- [ ] what about a "back-button" on the site?

- [ ] images in "bring your own docker image to work" don't work :D 

**Docs:**

- [ ] links to another website should be opened in another tab, right?

- [ ] links in "Release notes" link to medium and not to our blog

- [ ] updating screenshot of the dashboard if we change it to the dark theme

- [ ] updating lense-pictures with the new Url (gitpod.io/#) and use .png files? (getting started and browser extension)

**Comment by svenefftinge** [comment]
> the images look weird. maybe adding a frame or adjust their background color and crop them partially helps

What's weird about them?

**Comment by ChristinFrohne** [comment]
> > the images look weird. maybe adding a frame or adjust their background color and crop them partially helps
> 
> What's weird about them?

- the grey background color of the first 4 images is different, but the one of the fifth is the same as the general backround. 
- the yellow thing is cut
<img width="108" alt="Bildschirmfoto 2019-03-26 um 11 54 30" src="https://user-images.githubusercontent.com/46345125/54991958-5cc05580-4fbe-11e9-8f23-6a59e63b6f3e.png">

If you send me the images, I can edit the background and crop them if necessary

**Comment by jankeromnes** [comment]
Great feedback, thanks! I'll also try to help address all this. Additonally:

**Docs:**

- [ ] Table of Contents should highlight the page you're currently on
- [ ] Table of Contents should remain visible as you scroll down in a long page
- [ ] Steal https://github.com/gitpod-io/gitpod-docs/pull/83
- [ ] Archive https://github.com/gitpod-io/gitpod-docs/ and verify the website has all the latest changes

**Comment by ChristinFrohne** [comment]
I have been reading some articles about product launching and website improvements. Here are some key findings we might want to look into: 

- [ ] add a share button on the blog posts and the video (likeliness of sharing increases) 

- [ ] add a sign in button for the newsletter, maybe underneath the blog posts overview (generating leads) 

- [ ] is a voice search possible? 40% of mobile search is done by voice in USA (not sure if that is relevant yet)

- [ ] once our logo is called "apple-touch-icon.png" is that one used? We should rename it (SEO optimization) 

- [ ] I am guessing you already took care of the alt-tag, URLs and meaningful meta descriptions

- [ ] should we buy google keywords? i tried some: 
- "online IDE" shows coder.com, codeanywhere.com, repl.it, etc. (no Gitpod on the first 2 pages)
- "frictionless coding" no Gitpod
- "prebuilt workspaces GitHub" no Gitpod
-"frictionless coding GitHub" 7. place Gitpod
- "online IDE GitHub" 3. Gitpod 
- "one click IDE" 4. Gitpod

**Comment by jankeromnes** [comment]
> add a share button on the blog posts and the video (likeliness of sharing increases)

The video already has a share button (comes from the modal overlay or YouTube directly).

+1 on adding share buttons to our blog posts though (right now, when you're finished reading, there is nothing more to do: no like, no comment, no share...)

> once our logo is called "apple-touch-icon.png" is that one used? We should rename it (SEO optimization)

We have at least three website icons: `gitpod.svg`, `gitpod-196x196.png` and `apple-touch-icon.png`:

https://github.com/gitpod-io/website/blob/c37dcb60f9021cdb4bb883ced6116c6278c64cbc/src/layouts/index.tsx#L8-L10

I think I've read somewhere that `apple-touch-icon.png` should not be renamed, but I may be wrong.

Also, our logo at the top of each page doesn't have a file name, because it is inlined by Gatsby (i.e. instead of having a `src="/resources/gitpod-logo.svg"`, it has `src="data:image/svg+xml;base64,PHN2ZyBpZD0ibG9nby1ma..."`, which is a URL that directly encodes the image). Not sure how that plays with SEO, but it would be nice if searching for "Gitpod logo" on Google Images returned a good SVG logo.

And in general, many images are still missing `alt=""` attributes. I'll make a pass to fix them this week.

**Comment by ChristinFrohne** [comment]
- [ ] the grey logos are sometimes too big (feature, docs) 

- [ ]  less grey logos on the top of the pages and more on the bottom (small ones)

- [ ] the feature page needs more space on the top

**Comment by ChristinFrohne** [comment]
Updated in #177
