### ISSUE TITLE
Missing JetBrains plugin support on gitpod.yml page

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2003]
### Describe your feature

Documentation on the plugin YAML from the IDE pages: 
https://www.gitpod.io/docs/ides-and-editors/intellij

Is missing from the gitpod YAML reference page:
https://www.gitpod.io/docs/references/gitpod-yml

**Comment by akosyakov** [comment]
I'm not sure yet about adding it till we settled on the format.

**Comment by loujaybee** [comment]
FWIW, it's not currently marked with experimental on the other pages, @akosyakov ?

![image](https://user-images.githubusercontent.com/5528307/167414092-357c10de-7611-42ff-86fd-1d57e8a95596.png)

**Screenshot:** There's a disclaimer on prebuilds, but not on plugins support

**Comment by akosyakov** [comment]
@loujaybee overlooked it 🤦 we need to add it there as well

**Comment by akosyakov** [comment]
Then we should cover `jetbrains` completely with prebuilds as well?

**Comment by andreafalzetti** [comment]
PR ready for review: https://github.com/gitpod-io/website/pull/2021

@loujaybee @akosyakov
