### ISSUE TITLE
Update git providers' logo opacity 

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2008]
The GitLab, GitHub, and Bitbucket logos should have 100% opacity, colored in #f9f9f9. The Bitbucket logo has an additional gradient.
See in [Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4189%3A3406)

|now|new suggestion|
|-|-|
|<img width="335" alt="Bildschirmfoto 2022-05-09 um 14 29 36" src="https://user-images.githubusercontent.com/46345125/167410034-bedd8cfc-2b3e-4e4f-8f56-d9d4efe9ac1c.png">| <img width="313" alt="Bildschirmfoto 2022-05-09 um 14 31 38" src="https://user-images.githubusercontent.com/46345125/167410433-ed5a6e62-b3bd-45c9-bc7b-3552a5ef0afa.png">

related issue #2001

**Comment by nisarhassan12** [comment]
@chrifro I have fixed this issue in #2096 

I see in the new suggestion column that the text is changed to "Link" from "Continue" I see on the Gitpod dashboard it is "Continue" should we continue with what we have for consistency?

Or do we plan to update it on the dashboard as well? Thanks

**Comment by chrifro** [comment]
Yes,  please stick with "continue". The text in the mockup is out of date. I only meant to highlight the logos. Thanks!
