### ISSUE TITLE
Update card styles

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2018]
Big, narrow and medium cards:
- [x] remove shadow
- [x] add gradient stroke

feature highlight, CTA call-out, single quote, tweets, case study, huge card, blog card, forms:
- [x] add gradient stroke 

tables:
- [x] remove grey shadows
- [x] replace old yellow-shadow style with the new light theme yellow shadow style
- add gradient stroke to all cards

See all components [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831)

**Comment by nisarhassan12** [comment]
@chrifro The tweets have a white background whatever we have a white background can't have the gradient stroke i.e the white at the top won't work. Should I update the colour for the tweets to #f9f9f9 ? Thanks

**Comment by chrifro** [comment]
It's okay that the stroke is not completely visible. Let's stick to the recommendations by MAD [[1](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=770%3A7672)]. 
Card color: #FFFFFF

**Comment by nisarhassan12** [comment]
> Let's stick to the recommendations by MAD [[1](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=770%3A7672)].
Sorry, @chrifro I don't see the white background apart from the tweets the mockup component library itself uses #f9f9f9. They probably meant #f9f9f9 as white ? I'm confused a bit or is it that the component library and there mockups are outdated ?

**Comment by chrifro** [comment]
I'm not sure I understand the issue. 
Both, the [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831) and the [MAD file](https://www.figma.com/file/7cegM2Pg34OpJcOmrjbijj/Website-2022?node-id=668%3A8454), say that tweets have a  #ffffff background. Most other cards have #f9f9f9 as a background, but not the tweets :) 
<img width="843" alt="Bildschirmfoto 2022-05-17 um 14 02 00" src="https://user-images.githubusercontent.com/46345125/168806634-611d2071-d65d-4985-94e6-e490f4d755d7.png">
