### ISSUE TITLE
Update design "card for several quotes"

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2019]
**Changes:**
-  [x] update width to 1182px
- [x] add gradient stroke
- [x] no hover state besides the logo hovers at the top. 
- [x] 3 sec auto swipe to next (Gitlab –> Customer io)

[Figma component](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831)
<img width="1127" alt="Bildschirmfoto 2022-05-11 um 11 14 50" src="https://user-images.githubusercontent.com/46345125/167814863-7b03f0a4-98b7-42c4-811b-5bb01d018354.png">

**Comment by nisarhassan12** [comment]
> - no hover state besides the logo hovers at the top.

@chrifro Sorry I'm unable to understand this. Can you please explain? Thanks

**Comment by chrifro** [comment]
Sure, sorry for being unclear @nisarhassan12  

The hover state should be that the logo color becomes colorful while the quote itself stays the same until another logo is clicked.

I think the animation between the different quotes can be improved, but that can also be addressed in a follow-up PR :)

**Comment by nisarhassan12** [comment]
Thanks, Christin. I agree that the animation can be improved we can iterate on this later on.

> The hover state should be that the logo color becomes colorful while the quote itself stays the same until another logo is clicked.

I would say let's leave it as is i.e GitHub changes the quotes here https://github.com/pricing on hover as well.

**Comment by chrifro** [comment]
I discussed that change with MAD and they highly recommended not to do that. Let's go for their suggestion
