### ISSUE TITLE
Improving SEO

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#202]
Possibilities to improve SEO (content first) 

- [ ] adding meta description for every sub page & focusing on one keyword per page → better information on google search 

- [ ] meta description for gitpod.io that awakes curiosity. Including keyword: `online IDE` (very important) possibly `web`as well 

- [ ] longer title? Currently, 30 characters - 40 recommended

- [ ]  using keywords in headlines <h..> → LSI keywords like code editor, compiler, java, JavaScript, python, web ide github

- [ ] adding keyword `online IDE` in URL? 

- [ ] if using bold fonts, highlighting keywords with it

- [ ] using keywords in alt-tags for images

- [ ] generally more text on gitpod.io, currently 286 characters- suggested 300 - 500 sames counts for sub pages 

**Generating backlinks via comments with a link**. 

- [x] https://www.telerik.com/blogs/top-5-javascript-online-ides-to-use-in-2019, 

- [x] https://www.hongkiat.com/blog/cloud-ide-developers/

- [x] https://www.cloudways.com/blog/top-ide-and-code-editors-php-development/

- [x] https://hackr.io/blog/best-java-ides

- [x]  https://www.developerdrive.com/9-best-free-cloud-ides/

- [x] https://ourcodeworld.com/articles/read/200/top-7-best-free-web-development-ide-for-javascript-html-and-css

- [x] https://www.quora.com/What-is-the-best-IDE-for-web-development-in-2019

- [x] https://zapier.com/engineering/best-cloud-ides/

- [x] https://en.softonic.com/solutions/what-are-the-best-cloud-ides#

- [x] https://www.codewall.co.uk/some-of-the-best-ides-to-use-in-2018-2019/#comment-1781

- [ ] https://en.softonic.com/solutions/what-are-the-best-ide-for-nodejs?utm_expid=.CzNYPj_ZSwWPjo4AdF-leA.0&utm_referrer=https%3A%2F%2Fen.softonic.com%2Fsolutions%2Fsearch%3Fq%3D%2Bide#, https://en.softonic.com/solutions/what-are-the-best-ide-for-c-and-c?utm_expid=.CzNYPj_ZSwWPjo4AdF-leA.0&utm_referrer=https%3A%2F%2Fen.softonic.com%2Fsolutions%2Fsearch%3Fq%3D%2Bide, https://en.softonic.com/solutions/what-are-the-best-lightweight-ide-for-java?utm_expid=.CzNYPj_ZSwWPjo4AdF-leA.0&utm_referrer=https%3A%2F%2Fen.softonic.com%2Fsolutions%2Fsearch%3Fq%3D%2Bide

**Generating backlinks via guest posts.** 
Possible websites: https://alistapart.com/about/contribute/, https://contribute.hackernoon.com/, https://www.geeksforgeeks.org/contribute/, https://www.smashingmagazine.com/write-for-us/, https://scotch.io/write-for-us, https://blog.newrelic.com/, https://codecondo.com/write-for-us/

- [ ] backlink from the Theia article on wikipedia 

**Platforms to register**

- [x] https://startuptracker.io/

**Comment by ChristinFrohne** [comment]
<img width="601" alt="Bildschirmfoto 2019-06-27 um 08 37 19" src="https://user-images.githubusercontent.com/46345125/60255478-24d3f180-98d0-11e9-9300-e846b0812ec0.png">

Detailed information for every page on https://derdigitaleunternehmer.de/seo-ranking-verbessern/

**Comment by ChristinFrohne** [comment]
More information:
<img width="939" alt="Bildschirmfoto 2019-06-27 um 13 30 10" src="https://user-images.githubusercontent.com/46345125/60262996-d4649000-98df-11e9-813c-d59d13267922.png">
https://app.neilpatel.com/de/seo_analyzer/site_audit?domain=gitpod.io&view=all

**Comment by jankeromnes** [comment]
- [ ] Use lowercase canonical links (when multiple case-combinations are available, Netlify [forcefully redirects](https://community.netlify.com/t/my-url-paths-are-forced-into-lowercase/1659/2) to the lowercase version, so using non-lowercase canonical URLs hurts our SEO)
