### ISSUE TITLE
Update /contact layout

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2023]
**Changes:**
- align the component style (it now uses the medium card style but with an h5 font) 
- swap icons

[mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5035%3A10492)

|before|after|
|-|-|
|<img width="1191" alt="Bildschirmfoto 2022-05-11 um 15 58 28" src="https://user-images.githubusercontent.com/46345125/167867689-a9e6da7b-045d-4141-9926-472c88d0ebbf.png">|<img width="651" alt="Bildschirmfoto 2022-05-11 um 15 58 34" src="https://user-images.githubusercontent.com/46345125/167867737-ec1b0541-e5d1-4591-97cf-61793276eccb.png">|

**Comment by nisarhassan12** [comment]
@chrifro I merged the relevant Pr because I wanted to base the work in other Prs on that. Let me know in case you have any feedback I'll address that in a follow-up. Thanks
