### ISSUE TITLE
footer layout needs to be adjusted for smaller devices

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2026]
When resizing the view when we get to smaller screens this is how the footer looks which is terrible we should make it so that it breaks into two columns at a smaller viewport. 

![image](https://user-images.githubusercontent.com/46004116/167903206-407cbd40-5f03-4992-81c9-9aa30855e03c.png)

**Comment by IhsenBen** [comment]
can I work on this?

**Comment by Damkols** [comment]
can i fix this issue

**Comment by nisarhassan12** [comment]
@IhsenBen Feel free to work on this. 

Sorry, @Damkols Ihsen was the first to ask that is why I gave Ihsen the go-ahead to work on this but feel free to look into the other open issues and ask if any of the issues seem interesting to you to work on.

**Comment by nisarhassan12** [comment]
Hi, @IhsenBen Are you still interested in working on it? 

if not then we can pass it on to @Damkols if he is still interested in working on this otherwise I can raise a Pr.

**Comment by IhsenBen** [comment]
Hi @nisarhassan12, sorry for the delay I got busy with work.
meanwhile, I tried to fix the problem, but I noticed the tailwind breakpoints actually made sense and 4 columns layout only happens in a specific wv ratio and doesn't impact phone screens or pads.
you can assign it to someone else.
apologies again

**Comment by nisarhassan12** [comment]
I'm taking over this.
