### ISSUE TITLE
[Docs Feedback]: Add VS Code SSH limitations to FAQ page

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/website#2032]
### Page URL

https://www.gitpod.io/docs/ides-and-editors/vscode

### User feedback

There are certain limitations on the level of customizations that we can make in VS Code Desktop when it comes to the  VS Code SSH extension ([see Slack discussion](https://gitpod.slack.com/archives/C03EG2PND38/p1652340037714309)). 

For example, users have to select all the time "what platform the remote host is using: Linux, Windows, MacOS", or accept the fingerprint or trust the authors, etc.

It would be helpful to document somewhere these limitations and side-effects so that users can discover them or we can easily explain why it happens. (e.g. FAQ page)

**Comment by loujaybee** [comment]
Relates to: 
- https://github.com/gitpod-io/gitpod/issues/9568

**Comment by loujaybee** [comment]
Should now be covered here: 

https://www.gitpod.io/docs/ides-and-editors/vscode#optimizing-vs-code-desktop
