### ISSUE TITLE
/docs polish

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2068]
Here is a list of a few follow-up improvements to the layout of the new docs ✨

- [ ] the navigation breakpoints change while scrolling 

| active header | inactive header|
|- |- |
|<img width="267" alt="Bildschirmfoto 2022-05-18 um 10 50 06" src="https://user-images.githubusercontent.com/46345125/168998749-49e7d4ae-ffe4-4c5b-958c-fb2a29f1a99e.png">|<img width="304" alt="Bildschirmfoto 2022-05-18 um 10 50 00" src="https://user-images.githubusercontent.com/46345125/168998780-11066194-3b6e-4570-98b8-20a7615fbf04.png">|

- [x] the navigation on both sides should align on the top with the content
<img width="1467" alt="Bildschirmfoto 2022-05-18 um 10 53 24" src="https://user-images.githubusercontent.com/46345125/168999403-27dac017-437c-4006-b00e-34412162d49a.png">

- [x] update border radius for code snippets from 4.8px to 12px
<img width="437" alt="Bildschirmfoto 2022-05-17 um 09 19 59" src="https://user-images.githubusercontent.com/46345125/168999557-022cbeff-8c12-456f-8054-61e8ee5ce7ae.png">

- [x] allow code bubbles inside a call-out

|currently |improvement |
|-|-|
|<img width="708" alt="Bildschirmfoto 2022-05-17 um 09 16 11" src="https://user-images.githubusercontent.com/46345125/168752225-f1db4df9-f4b3-4693-aa55-8147f764c4af.png">|<img width="579" alt="Bildschirmfoto 2022-05-17 um 09 18 04" src="https://user-images.githubusercontent.com/46345125/168752280-54a62cd2-5d59-4423-8b4a-f1aa22e1e37d.png">|

- [ ] show all left navigation sub-items by default

**Comment by Cahllagerfeld** [comment]
Do you have an idea, of how to get around the line break when the font-weight gets bigger @nisarhassan12? I tried it with `whitespace-nowrap`, but then there's an issue with the overflow, that content gets cut off..

**Comment by Cahllagerfeld** [comment]
I had a look at the line-break thingy together with @nisarhassan12 yesterday. It seems like it's a thing we can't prevent when changing the font-weight. If the font-weight gets higher, it will require more space, when preventing the linebreak, we're running inside an overflow issue where the text gets cut off.


Is this something we can have a look at later, it's the only point that's open currently. The other changes are good to go then 🤔

**Comment by Cahllagerfeld** [comment]
I had a look at the line-break thingy together with @nisarhassan12 yesterday. It seems like it's a thing we can't prevent when changing the font-weight. If the font-weight gets higher, it will require more space, when preventing the linebreak, we're running inside an overflow issue where the text gets cut off.


Is this something we can have a look at later, it's the only point that's open currently. The other changes are good to go then 🤔

**Comment by akosyakov** [comment]
> show all left navigation sub-items by default

I don't think it is good idea. We should be picky about what we put at the top. It communicates our focus. Everything important should be visible without any scrolling.
