### ISSUE TITLE
Document S3 bucket config in self-hosted docs

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/website#2071]
Follow-up issue: Document S3 bucket config in self-hosted docs

_Originally posted by @corneliusludmann in https://github.com/gitpod-io/gitpod/issues/10073#issuecomment-1129957181_

**Comment by lucasvaltl** [comment]
The current UI makes this more or less self-explanatory. Will close this ticket.
<img width="803" alt="image (4)" src="https://user-images.githubusercontent.com/22516873/173848755-5c77be61-5e5a-4754-b089-d84116018888.png">
