### ISSUE TITLE
Minor link shift when opening docs top-level links that include sub-pages

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#2077]
### Problem to solve

Following up from an early discussion today with @chrifro there's minor link shift when opening docs top-level links that include sub-pages, see video below.

https://user-images.githubusercontent.com/120486/169151311-3e2f2413-802e-4bb2-bf37-4e1d0eb1875c.mov

**Comment by chrifro** [comment]
This should be fixed by "show all left navigation sub-items by default" in #2068. Isn't it @Cahllagerfeld ? 🙂

**Comment by Siddhant-K-code** [comment]
It is fixed now 😄
