### ISSUE TITLE
Variables in documentation to substitute values (e.g. self-hosted URL)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2091]
Other documentation products (such as Auth0 and Stripe) have tokenization which facilitates swapping of variables in code snippets. This would be useful for Gitpod in the case of swapping the URL's of the gitpod documentation to point to a self-hosted installation. The reason the URL poses a challenge for self-hosted is when end-users who are not very familiar with Gitpod follow docs links but go to the SaaS installation and there's no real way for administrators to guide these end-users that they're working in the wrong installation (SaaS) rather than self-hosted installation. 

|With tokenisation|Anon|
|-|-|
|![image](https://user-images.githubusercontent.com/5528307/169530774-e6801623-a934-45dc-ad7a-f9fcfbfa01e7.png)|![image](https://user-images.githubusercontent.com/5528307/169530791-ab9a7a04-e0f2-4b8a-a51e-b4aca8f3f6c1.png)|

**Comment by loujaybee** [comment]
A potential 🛹 could be to cache / store the value in `localStorage`, so a user can input their own domain somewhere in a self-hosted installation setup guides, and this makes the current docs swap to the localStorage URL, and not the SaaS one.

**Comment by rgoldfinger-quizlet** [comment]
One idea might be to use the chrome extension, which is already configured with the self-hosted url.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.

But, We can revisit later, if we require this for API Docs (https://github.com/gitpod-io/website/issues/3112)
