### ISSUE TITLE
logo mark disappears after navigating on Safari

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2093]
Follow up on https://github.com/gitpod-io/website/pull/2092#issuecomment-1132922649 

When we navigate in a sequence from left to right-clicking the nav links to the changelog page all of a sudden the Gitpod logo orange mark disappears.

**Comment by Siddhant-K-code** [comment]
It's working now :)

<img width="1339" alt="image" src="https://github.com/gitpod-io/website/assets/55068936/28acce52-1900-4ca6-a4ef-c7e9450fe70e">
