### ISSUE TITLE
/support image needs adjustment for dark mode. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2134]
We might want to add the orange shadow around the monitor image as is the case for the monitor on `/vs/jetbrains-space` on the dark mode. 
![image](https://user-images.githubusercontent.com/46004116/170739999-7f8b160f-4c10-47be-a1ee-4b63b89765f8.png)

**Comment by chrifro** [comment]
Yes, let's add the shadow here as well. Also, the secondary button should be grey as usual (sorry for the bug in the mockup)

**Comment by nisarhassan12** [comment]
@chrifro I can't add the shadow myself with code as the image is neither a square nor a circle. Can you please do that in Figma and share a link with me? Thanks

**Comment by chrifro** [comment]
I added it to the mockup https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5639%3A7828
