### ISSUE TITLE
move away from lottie animations. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2135]
At the moment the edit and share workspace animations are powered by Lottie the problem with this is that the Lottie player Js library is huge in size i.e `334.7 KB` of JavaScript. We use the `lottie-interactivity`(18.5 KB) package to trigger the animations when the element is brought into the viewport.

If the animations are to be done with Vanilla CSS and JavaScript then that would result in orders of less magnitude of code being shipped resulting in making the load time faster.

**Comment by Siddhant-K-code** [comment]
This would be a high-effort task, but it would be required to improve performance.

**Comment by Siddhant-K-code** [comment]
See https://github.com/gitpod-io/website/pull/3257#issuecomment-1385202002 for performance comparisons

**Comment by Siddhant-K-code** [comment]
[Research Report 🧵](https://github.com/gitpod-io/website/pull/3257#issuecomment-1400766738)
