### ISSUE TITLE
Document heartbeating and default timeout behaviours

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2144]
Document how long workspaces stay alive, and under which circumstances they are stopped. 

**Consider/detail:** 
1. When editors are not connected
2. Connecting via SSH (and how that keeps the timeout open)
3. Workspace timeout vs the editor timeout
4. Document what triggers the timeouts in different editors (e.g. key strokes)
5. The impact of multi-editors on triggering timeouts.

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/9038

Related internal conversations [[1](https://gitpod.slack.com/archives/C01KGM9BH54/p1657708169805629)][[2](https://gitpod.slack.com/archives/C02P236JZPC/p1657189005044789?thread_ts=1657128160.152419&cid=C02P236JZPC)]

**Comment by loujaybee** [comment]
https://github.com/gitpod-io/customers/issues/57

**Comment by andreafalzetti** [comment]
x-posting a reply I left in Discord about SSH timeouts, hopefully it helps when we'll document SSH timeout behaviors on our docs:

---

When you connect to a workspace via SSH gateway the heartbeats are sent when we notice activities (data being received, such as new pty sessions or user typing). Once the user closes the connection of the pty session, it will send a `closed` event which resets the workspace timeout to 5 minutes. If no clients send heartbeat within 5 minutes, the workspace will stop.

See related code

- Skip heartbeat if in case of inactivity: [https://github.com/gitpod-io/gitpod/blob/5c6a1aff678685a90b32b03b88b7e639bf6c8c7b/components/ws-proxy/pkg/sshproxy/forward.go#L119-L122](https://github.com/gitpod-io/gitpod/blob/5c6a1aff678685a90b32b03b88b7e639bf6c8c7b/components/ws-proxy/pkg/sshproxy/forward.go#L119-L122)
- Sending heartbeat: [https://github.com/gitpod-io/gitpod/blob/5c6a1aff678685a90b32b03b88b7e639bf6c8c7b/components/ws-proxy/pkg/sshproxy/forward.go#L125](https://github.com/gitpod-io/gitpod/blob/5c6a1aff678685a90b32b03b88b7e639bf6c8c7b/components/ws-proxy/pkg/sshproxy/forward.go#L125)
- Sending last heartbeat in case of `closed` event: [https://github.com/gitpod-io/gitpod/blob/5c6a1aff678685a90b32b03b88b7e639bf6c8c7b/components/ws-proxy/pkg/sshproxy/forward.go#L128-L130](https://github.com/gitpod-io/gitpod/blob/5c6a1aff678685a90b32b03b88b7e639bf6c8c7b/components/ws-proxy/pkg/sshproxy/forward.go#L128-L130)
