### ISSUE TITLE
Docs for PR/MR context should mention that review panel in VS Code is GitHub-specific 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#2147]
https://www.gitpod.io/docs/context-urls#pullmerge-request-context

This section of the docs talks about reviewing a PR in VS Code.
It needs to mention that this capability requires the extension github.vscode-pull-request-github which is GitHub-specific.

(If there are similar extensions for other Git providers like GitLab, please open a separate issue in https://github.com/gitpod-io/gitpod/issues)

See [slack](https://gitpod.slack.com/archives/C01KPEPNBD0/p1653984994316269) for context (internal)

**Comment by Siddhant-K-code** [comment]
Resolved now 😄 
![image](https://user-images.githubusercontent.com/55068936/194596848-a5a3af97-4b4e-47c5-af21-5658cd4bc71e.png)
