### ISSUE TITLE
Deeplink to Self-Hosted Pricing page Feature Table

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2159]
### Describe your feature

In order to be able to give customers a link to the "features", we would like to be able to deeplink to the "View all features" section of the [self-hosted pricing page](https://www.gitpod.io/self-hosted). Specifically, we want to be able to deep link to the red box here:

<img width="1293" alt="Screenshot 2022-05-31 at 21 12 57" src="https://user-images.githubusercontent.com/22516873/171266931-0a724c5c-e5cf-4c95-b38c-287ffedd216a.png">

**Expected Behaviour:**
When hovering over the title, an anchor appears that you can click. This changes the URL to a deep link to this section. You can then copy this URL and share it. The same behaviour is already available in our docs. 

### How to test

Open respective page, press anchor next to the section title, copy URL, past URL in different window. The page that is opened should have "View all features" at the very top.

**Comment by nisarhassan12** [comment]
Hi, @lucasvaltl Thanks for the issue. I have fixed this in #2264 please review when you get time. For consistency, I have deep-linked title for all of the feature tables i.e on `/pricing`, `/vs/local-development` and `vs/github-codespaces`.
