### ISSUE TITLE
Sections for Pricing Page Feature List. 

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2160]
This is not a Must for Q2 2022. But if we have capacity, this would be good to do soon. 

### Describe your feature

In order to better organise our feature list on the pricing page(s), we should have sections that allow us to group features by topic - see examples from [vercel](https://vercel.com/pricing) and [curity](https://curity.io/product/plans/). This means adding the ability to have these sections, and then defining which feature should be in which section. 

### How to test

When navigating to the pricing page, I can see clear groupings of features.

This likely would first need a design proposal @chrifro.

**Comment by chrifro** [comment]
Sure, thanks for the example links. That's always super helpful.

Here is the [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=4999%3A6840):
<img width="1153" alt="Bildschirmfoto 2022-06-02 um 14 13 41" src="https://user-images.githubusercontent.com/46345125/171627225-fd631704-2a0b-47ad-949d-3fbf2d71cf56.png">

The headlines are just a placeholder. What would be the correct order and naming @lucasvaltl ?

**Note:** the longer the feature list gets, the more important it is to implement #1416

**Comment by lucasvaltl** [comment]
Awesome, thanks @chrifro that looks great! :) In terms of order and naming, I think I can do that once we have the feature implemented. Will need to work with @metcalfc on it :)
