### ISSUE TITLE
[Docs - New Feature]: Toggle to switch between different versions of the same content

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2162]
### Describe your feature

As part of our effort to [improve the way we represent Self-Hosted in our documentation](https://www.notion.so/gitpod/Documentation-Structure-Self-Hosted-vs-SaaS-in-the-same-Docs-8584781084eb4ec6a7008c91e08ad39b) (internal link), we want to add the ability to toggle between Self-Hosted and SaaS related blocks of content.

Examples of where this could be used: 
- We could have two versions of [how to set up the jetbrains gateway ](https://www.gitpod.io/docs/ides-and-editors/jetbrains-gateway#getting-started) (where the Self-Hosted version explains that you need to update the Gitpod host to your installations url, assuming this is necessary)
- [We could have two versions of how to use the browser extension (with a toggle](https://www.gitpod.io/docs/browser-extension#use-with-gitpod-self-hosted) instead of two sections

**Value:**
- This allows us to use the same docs page for both versions of the product, while still allowing us to describe nuanced differences between them.
- This allows us to implement what was done via https://github.com/gitpod-io/website/pull/2106 in a more sustainable manner.  

**Related:**
We already have a first version of this as part of the work to introduce reference architectures: https://github.com/gitpod-io/website/pull/2106. 

### How to test

Open docs page that has this, toggle between versions.

**Comment by lucasvaltl** [comment]
I think the simplest way of going about this is to make what was introduce in #2106  generic. Might be enough to rename [cloud-platform-toggle.svelte](https://github.com/gitpod-io/website/pull/2106/files#diff-c467771b951facabf5b3fc45dc40a7445aeda693d84a11d0cecce1775ce9ed2d) into something more generic & fix the things mentioned in the inline comments - but I am in no way an expert and I am not sure if we want to have a design pass on this.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
