### ISSUE TITLE
[Docs - New Feature]: SaaS & Self-Hosted Tags for Docs Pages & Sections

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2163]
### Describe your feature

As part of our effort to improve how we deal with differences in self-hosted and SaaS in our docs, we want to add the ability to tag pages as well as specific sections with SaaS | Self-Hosted | All in order to indicate which version of Gitpod a certain piece of content applies to. 

**Value:** 
Allows us to clearly indicate for which version of the product a piece of content is relevant for. This allows the reader to act accordingly and disregard something. 

**Acceptance Criteria:**
- One can tag either the headline of a docs page or any of the other headers with SaaS | Self-Hosted | All Versions
- Bonus points for a tooltip that allows us to give context on what Self-Hosted / SaaS is (see screenshot below)
- The more centrally managed we can make this the better for future sanity. I.e. if we can centrally change what the tooltip says, instead of having to do this on every docs page, that would be 👍 

**Prior work:**
We could reuse the bubbles we have already in the docs, e.g. in the IDEs & Editors nav bar

**Inspiration:**
- Gitlab has this exact feature in their docs:
<img width="819" alt="Screenshot 2022-06-01 at 12 14 04" src="https://user-images.githubusercontent.com/22516873/171381710-8e840bc6-dacc-486a-a2b3-e03661de9a0b.png">

### How to test

Add annotation to a docs page, see it in the preview.

**Comment by Cahllagerfeld** [comment]
One idea from my side: 
Having a dedicated color for self-hosted annotations, so the color immediately represents the relevance for self-hosted

**Comment by ghuntley** [comment]
Thoughts on how to approach:

```yaml
---
feature-availability:
   - saas
   - self-hosted v22.04
---
```

Which renders as "SaaS" and "Self-Hosted from v22.04"

Implement infrastructure tooling that enforces build errors if the YAML front matter fails to pass (for example someone has configured incorrect version string in the frontmatter)
