### ISSUE TITLE
Animation of trusted by logos

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2165]
**Changes:**
- [x] move the trusted by section further up the page
- [ ] always show four logos at a time that are rotating similar to https://launchdarkly.com/
- [x] change headline style and text to "unleashing developer teams at"

[mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965): 
<img width="652" alt="Bildschirmfoto 2022-05-23 um 10 51 23" src="https://user-images.githubusercontent.com/46345125/171582170-e5701751-b349-45f3-8ebf-2886d5db0a5c.png">

**Comment by nisarhassan12** [comment]
> - [ ] always show four logos at a time

@chrifro I have made the logos rotating see https://github.com/gitpod-io/website/pull/2194 but at the moment there are only three logos in a row and that is because we only had 10 logos for having 4 in a row we will need 12 logos.

**Comment by nisarhassan12** [comment]
@chrifro Also about the 4 logos how do you envision them on mobile? it works fine with 3 side by side but not with 4 we might have to wrap one onto the next line.

**Comment by chrifro** [comment]
> that is because we only had 10 logos for having 4 in a row we will need 12 logos.

We can add the JetBrains and 4geeks academy logo. Let's use this order: GitLab, JetBrains, Google, Redwoodjs, Uber, Shares, Datastax, freecodecamp, amazon, astrato, 4geeks, code institute

>I'm using more spacing below the new title as opposed to what you suggested in the mockup

👍

>Also about the 4 logos how do you envision them on mobile? it works fine with 3 side by side but not with 4 we might have to wrap one onto the next line.

Great point, let's use 3 for mobile then

**Comment by nisarhassan12** [comment]
@chrifro I have updated the Pr so that we have 4 logos.

Regarding using 3 can you re-review the PR for now there are 4 in a row with the size reduced if that does not look good then we can follow up from there and drop one.

**Comment by chrifro** [comment]
4 on mobile should work as well. Let's focus on the animation first. And the spacing needs some alignment as well. I updated the mockup [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965)

**Comment by nisarhassan12** [comment]
@chrifro I have updated the spacing it's now 80px between the logos before it was 128px also about the animation do we want it to look exactly like launch darkly? in my opinion their animation looks a bit glitchy and too be honest I don't know how they have implemented that glitchness. Can you enlist the exact changes that I should be making ? Thanks

**Comment by chrifro** [comment]
Sure some things that come to my mind @nisarhassan12 :
- the logo size should stay the same
- I like the rotation style of https://launchdarkly.com/. It looks like it's a rotating cube 
<img width="203" alt="Bildschirmfoto 2022-06-14 um 14 17 09" src="https://user-images.githubusercontent.com/46345125/173575321-d15e1094-9458-422f-b27d-a0d9661c59b4.png">
- the speed is too fast 

- the order of logos: 

first round: GitLab, JetBrains, Google, Redwoodjs 
second round: Uber, Shares, Datastax, freecodecamp, etc. (see comment above)

**Comment by chrifro** [comment]
It works great. We can keep it as it is. Great work!
