### ISSUE TITLE
Improve twitter quotes

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2167]
**Changes**:
- [x] I tried to highlight the companies more and to make the advocate look more connected to Gitpod (orange frame, monochrome picture)
- [ ] Add company logo
- [x] updated headline to be more enterprise focussed
- [x] remove the link to Twitter to not drive visitors away from our website  [[1](https://www.notion.so/gitpod/Improve-website-for-enterprise-77d5f8a8b97f40fe9d99f6862225f899#73d6e2c466ba41ee94ff44177e2b3b5e)]

[Mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965):
<img width="963" alt="Bildschirmfoto 2022-06-02 um 10 48 13" src="https://user-images.githubusercontent.com/46345125/171592612-dc158dea-5297-49f8-a2f4-88869b7e9379.png">

**Next steps:**
- update the current quotes
- add additional quotes (replace old quotes) -> see [here](https://www.notion.so/gitpod/Improve-website-for-enterprise-77d5f8a8b97f40fe9d99f6862225f899#0b9f878ee6d6494e8cf7404427334e58) for inspiration @MichaelAring

**Comment by chrifro** [comment]
@nisarhassan12 sorry I totally missed the ping. Is this the only thing that is blocking this issue from being merged? Next time, please ping me again in case I don't answer 🙇‍♀️

Let's go for the MVC and write out the company name instead of adding the logo. We can always iterate on it 🙌

**Comment by chrifro** [comment]
What's the status here @nisarhassan12 ?

**Comment by nisarhassan12** [comment]
@chrifro once done with the current issues I'll look into this see https://github.com/gitpod-io/website/pull/2240#issuecomment-1185221607 on why it got delayed.
