### ISSUE TITLE
Implement a feedback widget for the docs

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#217]
Inspired by https://vercel.com/docs

![image](https://user-images.githubusercontent.com/788827/113761813-e6df4080-96e5-11eb-83f7-7a4db22108b5.png)

![image](https://user-images.githubusercontent.com/788827/113761768-d62eca80-96e5-11eb-8dd9-610dd45d1b63.png)

**Comment by ghuntley** [comment]
Related - https://github.com/gitpod-io/website-kumquat/issues/380

**Comment by mikenikles** [comment]
A few implementation notes:
* Feedback will be collected [in a spreadsheet](https://docs.google.com/spreadsheets/d/1DrgFXvDsLmu6kUoBHMfgYqBtqyT9kr4OHqcKX31FbXw).
* Feedback will be emailed to contact+docs-feedback.
* The following data will be captured:
  * `email`: Optional, the user's email address to get in touch
  * `emotion`: The emoji the user clicked
  * `url`: The documentation page's URL
  * `note`: Optional, additional context provided by the user
