### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/website#217]
Introduce TypeFox and a bit of our history

**Comment by ChristinFrohne** [comment]
@nisarhassan12 here is the mockup and all related images 
![About Typefox](https://user-images.githubusercontent.com/46345125/60796867-887eda00-a16e-11e9-8f1f-57812aed716f.png)
[About-us.zip](https://github.com/gitpod-io/website/files/3367503/About-us.zip)

**Comment by nisarhassan12** [comment]
@ChristinFrohne here is What is looks like. Could you please provide the images and the icons used in the mockup?
![image](https://user-images.githubusercontent.com/46004116/60860189-db1fcb00-a22e-11e9-8045-6e40d09ac735.png)

**Comment by ChristinFrohne** [comment]
Very nice! @nisarhassan12 
Underneath the mockup image is a .zip folder. There you should find all the images

**Comment by nisarhassan12** [comment]
Thanks! a lot  @ChristinFrohne :)
