### ISSUE TITLE
⌘+K does not work(it does but not really) on firefox for focusing the search bar

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/website#2172]
Hey 👋 
It seems that firefox overtakes "⌘+K" shortcut right after Gitpods own search bar is focused.
https://user-images.githubusercontent.com/39482679/171872290-26cd1879-81c6-4c44-82d4-504b02ed57bd.mov

**Comment by Cahllagerfeld** [comment]
We need to `preventDefault` here. By doing so we would highjack a Firefox native Command for jumping to the url-bar

**Comment by axonasif** [comment]
Nice! Sites like slack and Discord does that I guess.
