### ISSUE TITLE
Document compatibility (OS, browser, etc)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2185]
### User feedback

1. Operating systems (for the desktop clients, e.g. JetBrains and VS Code, and product features such as SSH Gateway and SSH clients on users machines)
2. Browsers (+ which versions)
3. Third party clients (e.g. VSCodium)
4. Programming and frameworks (if any limitations exist)

This also applies to self-hosted (e.g. cloud providers, etc), we should think to align the documentation.

**Comment by jeanp413** [comment]
A user in front was using https://www.mightyapp.com/ and it seems that vscode desktop login process does not work in there and the browser tab does not get opened, ([slack thread](https://gitpod.slack.com/archives/C01KGM9BH54/p1654535234596929))

**Comment by loujaybee** [comment]
This is now mostly covered with the compatibility matrix; https://www.gitpod.io/docs/references/product-compatibility-matrix will close this issue and raise smaller ones to update missing items on that documentation.
