### ISSUE TITLE
Improve sales form

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2186]
- [x] update drop-down arrow with the usual style (see [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=518%3A1074))
<img width="396" alt="Bildschirmfoto 2022-06-07 um 10 31 10" src="https://user-images.githubusercontent.com/46345125/172336173-2d5e3d98-57d1-4f1f-a8a3-2259a87bd720.png">

- [x] reduce logo sizes to align with the mockup (they seem a bit too big)
- [x] update JetBrains logo for dark theme 
<img width="155" alt="Bildschirmfoto 2022-06-07 um 10 36 51" src="https://user-images.githubusercontent.com/46345125/172335713-e42c57a8-a0ab-4cb5-aeb1-1a4751eb5e65.png">

cc @nisarhassan12 because you worked on it before

**Comment by nisarhassan12** [comment]
> - [ ]  update JetBrains logo for dark theme

What color should I use for the dark mode ? cc @chrifro

**Comment by chrifro** [comment]
Could you add another subject with "get a demo" as Philipp suggested [[1](https://gitpod.slack.com/archives/C035763SNSE/p1654602046994829?thread_ts=1653897999.102369&cid=C035763SNSE)] as well? It can be sorted after "self-hosting". And can you make preselected if someone clicks the "get a demo" button e.g. on /for/enterprise? 🙏

**Comment by chrifro** [comment]
>What color should I use for the dark mode ? cc @chrifro

same as for the other logos: #999795 and the font should be transparent. I updated the logo [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2410) as well
