### ISSUE TITLE
GitHub Student Pack

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#219]
URL: gitpod.io/github-student-developer-pack

**Links**
Try now = Try now section of the start screen 
Get student package = https://education.github.com/pack
Gitpod docs = https://www.gitpod.io/docs/10_Getting_Started/
Envelope icon = mailto:contact@gitpod.io?subject=Github%20Student%20Pack%20question
 
**Images**
[Github-student-package.zip](https://github.com/gitpod-io/website/files/3372408/Github-student-package.zip)

**Color**
the yellow line has the same color as the backpack #FDB02F 

**Mockup**
![GitHub Student Package](https://user-images.githubusercontent.com/46345125/60884540-64de9100-a24d-11e9-9005-9113efe73fad.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Hey! Could you please also provide the handshake svg that is used in one of the offers card and the tick icon?

**Comment by ChristinFrohne** [comment]
The latest mockup including the feedback from GitHub 

![GitHub Student Package](https://user-images.githubusercontent.com/46345125/60950078-c4dd4200-a2f6-11e9-9659-269ac4b0e0b8.png)

@nisarhassan12 you should be able to find both graphics in the project, as they have been used before
I also attached them here again [Archiv.zip](https://github.com/gitpod-io/website/files/3376280/Archiv.zip)
