### ISSUE TITLE
Add contact form for self-hosted community license

### ISSUE THREAD

**Issue by MichaelAring** [gitpod-io/website#2192]
- [Internal discussion](https://gitpod.slack.com/archives/C01LDA28WV6/p1653035219696759)

**Comment by chrifro** [comment]
**Context:**
It would be a simple form that would ask the user for company name / domain, number of engineers and work email before permitting to download. This change makes sense in the context of our [qualified lead generation efforts](https://www.notion.so/gitpod/Lead-Generation-Foundations-962124be8e684d3f92db4dc1cc0ea5c5#8e582b7b78574dfbb5bd8174fe849e25). At KubeCon, we also met a couple of companies who were using our self-hosted license without us knowing :rocket:


**Outstanding to-do's:**

- [ ] create /community-license page based on https://www.gitpod.io/enterprise-license 
- [ ] rename the “install now” button to "request free license" on the [community plan](https://www.gitpod.io/self-hosted) and link it to the new form
- [ ] And adding a link to the same form from https://www.gitpod.io/docs/self-hosted/latest that replaces `We provide a community license for free (right click and save link as here). To get an enterprise license, [fill out this form](https://www.gitpod.io/enterprise-license).`  with `We provide a community license for free. Just fill out this form to request the license. For the professional license, please get in contact by submitting this form.`


mockup: 
<img width="936" alt="Bildschirmfoto 2022-06-08 um 09 45 18" src="https://user-images.githubusercontent.com/46345125/172561204-f8b7855a-ee51-4561-bf2a-a04dd625cded.png">


cc @lucasvaltl

**Comment by nisarhassan12** [comment]
@chrifro @phimae I have made Pr #2237 for this please have a look when you get time. Thanks
