### ISSUE TITLE
GitLab instance registrations should include read_repository scope

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#2196]
Some users have reported authentication issues with their GitLab registration.
It appears that read_repository scope is now required when registering a GitLab instance.

https://www.gitpod.io/docs/gitlab-integration#registering-a-self-hosted-gitlab-installation

From a helpful support email ([internal](https://app.frontapp.com/open/cnv_jd17xsa)) 

> When I looked closer at the URL that gitpod used to try to authorize to my GitLab instance I saw that it also had "read_repository" in the scope. When I activated this checkbox in the gitlab application integration settings everything worked again.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
