### ISSUE TITLE
Code blocks need more line-height / separation

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2204]
Resolve issues with line height and `code blocks`

**To replicate:** 
1. Add a wrapped line with two stacked elements that are wrapped in backticks , e.g `stuff`

**Expected result:** 
* Line height continues to separate the text

**Actual result:** 
* Lines are smushed together

Example: 
![image](https://user-images.githubusercontent.com/5528307/172861033-254a3d89-85b8-49ee-8504-617606149778.png)

**Comment by nisarhassan12** [comment]
@chrifro reducing the padding in the y direction for inline code blocks will do the trick. Can you suggest a new padding value at the moment there is 4px both at the top and bottom? Should I reduce that to 2px? 

You can see it here https://www.gitpod.io/docs/config-start-tasks#one-line-tasks we already reduced it a bit it does not look like what we have above in the screenshot.

**Comment by Siddhant-K-code** [comment]
It is fixed now 😄 
![image](https://user-images.githubusercontent.com/55068936/194596350-c2e74d31-6c34-4776-878c-9be657f64829.png)
