### ISSUE TITLE
Document new team billing

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#2216]
We introduced new way to manage team billing for project teams with gitpod-io/gitpod#8041.   
This needs to be documented to explain the difference is between the 2 subscription models.

The benefit of the new team billing mechanism (compared to the older "[Team Plans](https://www.gitpod.io/docs/teams)" in your personal settings), is that adding/removing members from a project team automatically adds/removes members from the billing subscription. The selection and price per seat of the 2 plans is identical.

The new project team billing will auto-subscribe every existing member of the project team when team billing is set up. This includes the owner of the team (unlike the older team plans, whose owners are not auto-subscribed). 

For more control over who participates in the team plan billing, you can still use the older Team Plans, but you will have to manage each seat manually.

**Comment by jankeromnes** [comment]
> The selection and price per seat of the 2 plans is identical.

True, except when new members join within a billing period:
- In "legacy Team Plans", you always pay for a full month, regardless when the new seat is added (even if it's added 1 day before the next billing period)
- In "new Team Plans", you pay pro-rated (i.e. if a new member joins your team in the middle of a month, you only pay for the remaining half month)
