### ISSUE TITLE
Add 3rd hierarchy level to docs-sidebar

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#2221]
### Describe your feature

We should think about adding a third hierarchy level to our sidebar.

### User impact

Especially for reading the self-hosted docs, it would improve the logical structure of our documentation and increase the understandability.

### Additional context

This feature would not just be relevant for self-hosted, but also for IDEs for example: We would be able to group the Jetbrains and VS-Code-related Editors better inside the IDE's group for example; 

[See private Conversation in Slack](https://gitpod.slack.com/archives/C021JDXHXMF/p1654155840646119?thread_ts=1653566393.088229&cid=C021JDXHXMF)

**Comment by lucasvaltl** [comment]
This is related to, and likely replaces https://github.com/gitpod-io/website/issues/1547. Will close that other ticket.
