### ISSUE TITLE
[quotes]: reset the timer when a logo is clicked

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2224]
The logos section that we have on several pages i.e `/enterprise`, `/customers`, `opensource` and so on needs to have the timer (that switches to the next quote every  10 seconds) to be reset to 0 when a logo is clicked so that the next quote comes up after 10 secs and not instantly.  

![image](https://user-images.githubusercontent.com/46004116/173347792-103ffb9b-a283-4fb5-a9a6-269e1ffd33ef.png)

**Comment by nisarhassan12** [comment]
@jacobparis I have moved it to the need technical help column as I ran out of time I did try to fix this but was not able to do so. I think it would make sense if either someone is able to take this. Thanks 🙏🏿

**Comment by chrifro** [comment]
I think it's fine to not have a timer once a logo has been clicked. By then user understood how to navigate through the section and could do it manually
