### ISSUE TITLE
[Docs Feedback]: 

### ISSUE THREAD

**Issue by foufrix** [gitpod-io/website#2229]
### Page URL

https://gitpod.io/docs/getting-started

### User feedback

The user of brave should deactivate brave shields as it messes up the police and makes the console and some stuff unreadable

**Comment by atduarte** [comment]
I just tried and can't reproduce. Could you share a picture of what you mean please?

**Comment by foufrix** [comment]
I retried and confirm that I don't have this behavior anymore
