### ISSUE TITLE
[Docs Feedback]: Document how to turn off output colorization in gitpod-cli

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/website#2235]
### Page URL

https://www.gitpod.io/docs/command-line-interface

### User feedback

Some commands use colors in the output. We recently introduced a `--no-color` flag for explicitely turning off colors. Additionally, there are some built-in conditions for which colors get disabled automatically. 

For visibility, we should document those flags/conditions.

Resources:

- https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/pkg/utils/colors.go

**Comment by Siddhant-K-code** [comment]
Is this the only use case?

<img width="573" alt="image" src="https://user-images.githubusercontent.com/55068936/210952334-83e644db-a06b-40da-a508-e0e86b95629e.png">
