### ISSUE TITLE
Document configurability of SSH Gateway / SSH connections

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2238]
Currently, the SSH Gateway configuration is not configurable in self-hosted. Some customers have struggled, or cannot get port 22, or SSH configured. We should be explicit that currently there is no way to disable SSH In self-hosted, and/or document any workarounds, or setup changes to try to get SSH working. We should also point out that SSH is also the preferred connection for all desktop IDE's and not just direct SSH access. 

Relates to: 
- https://github.com/gitpod-io/website/issues/2178
- https://github.com/gitpod-io/gitpod/issues/7452
- https://github.com/gitpod-io/gitpod/issues/10645

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
