### ISSUE TITLE
Versioning of Docs

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#2247]
### Describe your feature

While evolving Gitpod Self-Hosted we need to make sure the documentation is versioned, so people who are on an older Gitpod release are able to find their relevant information.

### User impact

Users who are running an older release, can look into older documentation, which may decrease the amount of support requests

**Comment by lucasvaltl** [comment]
No this lives at different levels. #2162 is about switching within a paragraph (e.g. between an AWS and GCP version of a section), this is about a global way to change between versions of the documentation.

**Comment by lucasvaltl** [comment]
@Cahllagerfeld what is the state of this issue and the related PR?
