### ISSUE TITLE
GitHub Stars Button is really buggy

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#227]
Sometimes it works, sometimes it doesnt ¯\_(ツ)_/¯ On mobile (iOS) it never does

<img width="295" alt="CleanShot 2021-04-06 at 23 11 43@2x" src="https://user-images.githubusercontent.com/22498066/113779162-8f64c300-972d-11eb-983f-b5d0b90ef878.png">

Hot fix for the release could be to style the button according to MAD's specs and manually put in our GitHub Stars each other day 😊

**Comment by nisarhassan12** [comment]
Closing this as it seems like it can't be re-produced anymore. Please re-open this if you see the issue again.
