### ISSUE TITLE
Look into using docsy and docs.gitpod.io for documentation

### ISSUE THREAD

**Issue by mrzarquon** [gitpod-io/website#2284]
Currently docs are a subsection of the Gitpod website and a part of the same repository, meaning a change to documentation requires a change to the entire website.

Moving docs to their own domain and repo means the review process can be optimized for technical content and information.

[Docsy](https://www.docsy.dev/about/) is a common platform used for this. Many opensource projects use a docsy system and so would be familiar to users of other opensource projects.

**Comment by loujaybee** [comment]
One consideration here is the fact that coupling these two is that we do get link validation between pages, which is super helpful, and quite easy to break. Wonder if there would be some way to retain that if broken down.

**Comment by Cahllagerfeld** [comment]
Thanks for bringing this up. 🙏 
We've discussed that in our docs-sync and decided to postpone that decision, due to other priority things, that are going on currently. I'll leave that issue open though, to not lose track of it. We'll come back to it later

**Comment by Siddhant-K-code** [comment]
We have the [docs.gitpod.io ](https://docs.gitpod.io/). No Plans for Docsy Implementation.
