### ISSUE TITLE
Change subject line for emails submitted through the community license form

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#2289]
**Current behavior**
Currently, submitting an email on https://www.gitpod.io/community-license will have
Subject line: `Requesting a professional Self-Hosted license (from XXXX@XXX.com)`

**Expected behavior**
Subject line: `Requesting a Community Self-Hosted license (from XXXX@XXX.com)`

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/commit/7085c1304bbb582e215eefc18e7c5b03510f8061
