### ISSUE TITLE
Logo disappears after some time on home

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#229]
Cannot exactly say how to reproduce but the logo on top left disappears quite regularly.

![image](https://user-images.githubusercontent.com/22498066/113782731-f2a52400-9732-11eb-8ea1-192faf582af6.png)

**Comment by nisarhassan12** [comment]
I'm also not able to re-produce this. I tested on Chrome andriod and Safari on Desktop.

**Comment by nisarhassan12** [comment]
Closing this please re-open if you encounter this issue again.
