### ISSUE TITLE
Rename Professional to Enterprise Plan

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#2306]

**Comment by nisarhassan12** [comment]
Hi, @JohannesLandgraf I see you have assigned yourself here. Can someone else take over it ?

**Comment by Siddhant-K-code** [comment]
It's done :)

<img width="1418" alt="image" src="https://github.com/gitpod-io/website/assets/55068936/373629e2-25e9-4b9c-acd7-acc95e7affc8">
