### ISSUE TITLE
Remember cloud provider tab selection

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/website#2315]
### Describe your feature request

On the reference architecture page, we have tabs for different cloud providers.

![image](https://user-images.githubusercontent.com/24960040/175947976-3fb5b57d-b9ef-4237-92be-c7f8a341f1ee.png)

When the visitor switches the tab, the choice
1. should be selected on every tab on that page (globally),
2. should be remembered when the person visits this page again (store in a cookie?).

### User impact

The user does not have to switch every tab.

### Additional context

- @Cahllagerfeld: Could you help me with implementing this?
- Example from [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html) - toggle between the options and see that it changes on the entire page

**Comment by Siddhant-K-code** [comment]
Fixed in #2786
