### ISSUE TITLE
[Docs Feedback]: Kubernetes pod privilege requirements not documented

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/website#2317]
### Page URL

https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up

### User feedback

Gitpod uses privileged pods to perform a variety of tasks. For example, `shiftfs-module-loader` and `ws-daemon` instances require running in a privileged pod context, and the `ca-updater` pod uses `hostPath` volumes. Users running in strict environments may not be able to grant these privileges themselves at best, or may not be able to use gitpod due to said security policies.

Gitpod security/privilege requirements should be documented so that users can be informed of potential snags before attempting an installation of self-hosted.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
