### ISSUE TITLE
Do the "To do"s.

### ISSUE THREAD

**Issue by estelle** [gitpod-io/website#232]
I put TODO: everywhere there is a todo, including as HREFs
There were already several todo's. 

All the TODO's that lead to a 404 need to be handled before we go live. There are some TODO's that are enhancements, which need separate tickets made for 'post-launch'

**Comment by nisarhassan12** [comment]
I have found only 1 todo and that is the pricing table for the education page. I have made this https://github.com/gitpod-io/website/issues/430 separate issue to track that.
