### ISSUE TITLE
Allow to deep-link into a collapsed toggle / tab

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/website#2321]
### Describe your feature request

On the reference architecture page, we have tabs for different cloud providers that are collapsed with a toggle by default:

![image](https://user-images.githubusercontent.com/24960040/176160339-e9062cfd-1c88-45c0-96f7-778fd140bf7a.png)

With this implementation, we cannot link into a section on a tab. For example, we want to link to some AWS instructions directly. The expected behavior, is that with a deep link, the toggle will be expanded, the proper tab is selected and the view moves to the liked section in this tab.

### User impact

E.g., we have a link like

```
https://www.gitpod.io/docs/self-hosted/latest/reference-architecture/production-ready-single-cluster#kubernetes-cluster/aws/services-nodes
```

which expands the cloud provider-specific instructions toggle, selects the was tab, and jumps to the services nodes instructions.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
