### ISSUE TITLE
[Docs Enhacement - New Feature]: Add an easier method of embedding tweets

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/website#2323]
### Describe your feature request

Like the `youtube: id` plugin, it would be nice to have a similar method of embedding tweets within our markdown files without having to use raw HTML.

### User impact

Easier to embed tweets.

**Comment by Cahllagerfeld** [comment]
Additional Resource: https://www.swyx.io/the-hard-problem-of-rendering-tweets/

**Comment by mikenikles** [comment]
Duplicate of #400
