### ISSUE TITLE
Enable spam prevention for the forms

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2363]
Recently probably some bots took on the forms that we have on our site and flooded our inboxes:

![image](https://user-images.githubusercontent.com/46004116/177233200-abd62818-d35b-48d7-bc37-eaafb53d4797.png)

**Comment by chrifro** [comment]
@axonasif @jimmybrancaccio Do you know if this is still an issue? 🙏

**Comment by jimmybrancaccio** [comment]
@chrifro I haven't seen many or any spam in the Support inbox but this might be because everything goes though the Contact inbox first at the moment. It looks like the above screenshot is from a Gmail inbox and not Front inbox so pending input from @axonasif we may be safe to close this one out.

**Comment by axonasif** [comment]
Nothing critical at the moment, we still do get plenty of spam but most are filtered out via some frontapp-rules, while some slips in. It's safe to be closed, thank you for making sure @chrifro 🙏
