### ISSUE TITLE
Follow-up improvements on the contact widget

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2364]
Follow-up for #2304 
See also related [Slack conversation](https://gitpod.slack.com/archives/C01KGM9ETU6/p1656356392664729)

**Outstanding to-do's:**

- [x] include closing icon inside the box
<img width="262" alt="Bildschirmfoto 2022-07-05 um 09 22 37" src="https://user-images.githubusercontent.com/46345125/177272729-928beaa5-457b-49ea-a425-3fdc00110878.png">

- [x] add hover effect for the closing icon -> add 20% of #FFFFFF
- [x] add hover effect on the selected navigation item: default: #F9F9F9 -> hover: #FFFFFF (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5202%3A6832))
<img width="378" alt="Bildschirmfoto 2022-07-05 um 13 51 59" src="https://user-images.githubusercontent.com/46345125/177321277-cbeb5857-aff2-46ee-a244-980313f85117.png">

- [x] on safari the chat icon disappears after closing the menu
<img width="327" alt="Bildschirmfoto 2022-07-05 um 09 29 31" src="https://user-images.githubusercontent.com/46345125/177273920-de9e2b1a-2974-4b86-afd4-28a95b0a4aee.png">

- [x] on mobile: leave out the pop-up and just show the icon (similar to launchdarkly)
- [x] update icon button style: hover-> add  20% of FFFFFF as we usually do for all button styles, while the button is active it should switch back to default style (gradient orange)
<img width="285" alt="Bildschirmfoto 2022-07-05 um 09 39 26" src="https://user-images.githubusercontent.com/46345125/177275622-3f89095c-1480-47d5-90c7-e786fb088b58.png">

- [x] add shadow (button shadow style) for the whole card to make it stick out a bit more from the background

See [mockups](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5202%3A6832)

Note: the grey gradient for the icon colors that are used in production work great ✨

**Comment by chrifro** [comment]
Not related by could be adjusted in the same PR: the spacing above "unleashing developer teams at" should be reduced from 160px to 72px
<img width="948" alt="Bildschirmfoto 2022-07-05 um 15 56 14" src="https://user-images.githubusercontent.com/46345125/177344738-c1f6f570-b6ca-4ee1-965a-62b3bc5de150.png">

**Comment by nisarhassan12** [comment]
> - [ ] add 20% of #FFFFFF

@chrifro Can you share what that would be in HEX format? i.e I'll just change to that colour in CSS. Also, this is not the only place where we have this colour on hover right?

**Comment by chrifro** [comment]
Sorry my bad. Usually, we always add 20% of #FFFFFF for hover styles but there are a few exceptions. For the light button the hover style is #FFFFFF. See also the [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=513%3A527) and #2327

**Comment by nisarhassan12** [comment]
Thanks, @chrifro No problem. 

> - [ ] while the button is active it should switch back to default style (gradient orange)

What do you mean by active? Do you mean for instance when on the sales page the icon for contact sales will have the orange gradient?

**Comment by chrifro** [comment]
>What do you mean by active? Do you mean for instance when on the sales page the icon for contact sales will have the orange gradient?

I mean that we should not use the grey CTA icon but stick to the gradient style and only apply the standard hover style. I hope this makes it clearer [[1](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5848%3A8363)]👇
<img width="938" alt="Bildschirmfoto 2022-07-06 um 09 27 24" src="https://user-images.githubusercontent.com/46345125/177494293-1858843f-a745-44ed-bfd4-35ba29eadbd8.png">

**Comment by chrifro** [comment]
Looks good. Can you check that the closing icon fulfills the accessibility requirements for mobile?

**Comment by nisarhassan12** [comment]
> Can you check that the closing icon fulfills the accessibility requirements for mobile?
Thanks for bringing this up. No, it does not.

I expanded the tap target so that it is `48x48` pixels and the follow is how it looks(the red border is for illustration)

![image](https://user-images.githubusercontent.com/46004116/177727137-88991115-dfa7-4757-bf82-2a350892d989.png)

It looks fine but it introduces 2 accessibility issues: 

- the tap area is overflowing the card. 
- tap targets are now too close i.e it should be at least 8px between the 2 tap areas. 

The solution is to add more spacing to the top which might not look good. The following is how it looks with that change the following is how it looks: 

![image](https://user-images.githubusercontent.com/46004116/177729715-7149a66c-9ddd-4c12-909f-e1b0114d67dc.png)


Please have a look at the deploy preview and let me know if we should revert it and do something else. Thanks

**Comment by chrifro** [comment]
I updated the [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5202%3A6832) accordingly. It's now minimal outside of the card but I guess that is okay as clicking outside of the card triggers the same behavior (closing the card)
<img width="560" alt="Bildschirmfoto 2022-07-07 um 12 07 42" src="https://user-images.githubusercontent.com/46345125/177749195-a5420ba9-b3b1-43a1-829f-c721769c3d29.png">
