### ISSUE TITLE
Improve layout of code snippets inside docs

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2366]
Follow-up issue for #2313 

|before|after|
|-|-|
|<img width="845" alt="Bildschirmfoto 2022-07-05 um 14 52 07" src="https://user-images.githubusercontent.com/46345125/177338212-eff1c9fa-5629-455b-848d-81d495e3049e.png">|<img width="769" alt="Bildschirmfoto 2022-07-05 um 15 25 04" src="https://user-images.githubusercontent.com/46345125/177338376-c1265601-dafe-43db-a0db-422d87c5fcd5.png">|

The "copy code" button is supposed to use the same style as other links -> the underline disappears on hover and the font turns black

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5010%3A4831)

WDYT @Cahllagerfeld?

**Comment by Cahllagerfeld** [comment]
Hey @chrifro, small thing.
The Codefence is having the feature that you can pass in a file name, like `.gitpod.yml` to signalize that the displayed file is a concrete one.. In case the title gets provided, it's displayed instead of the language tag at the top left. Do we need a special layout for the case a title is displayed instead of just the language? This feature isn't used currently (because its new), but might get more relevance in this quarter when iterating over the docs

**Comment by Cahllagerfeld** [comment]
WIP: How should the header of the codefence look in dark mode? I'd personally turn it a bit lighter than the actual code, the next lighter color we have in our palette is the one in the screenshot, I'm not sure if I like it... wdyt?

<img width="809" alt="grafik" src="https://user-images.githubusercontent.com/43843195/177360843-4fc7be19-21ea-42dd-94d5-cd8a949f8294.png">

**Comment by chrifro** [comment]
>Do we need a special layout for the case a title is displayed instead of just the language?

Let's stick with this design for now and iterate on it once this new feature is in use 

>I'm not sure about the underline for copy code, because it's technically not a link, we aren't redirecting the user somewhere else, it's more a button, that triggers the copy function.

My thought was that the underlined text helps to indicate that the text is clickable. The user is already trained on our website that all underlined elements can be clicked. When we are just using plain text, it's not obvious that the user can interact with the text, especially on mobile. That's why I suggest sticking with it.

>How should the header of the codefence look in dark mode?

Great questions. I created another [mockup](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2052%3A3285) for it
<img width="800" alt="Bildschirmfoto 2022-07-06 um 09 17 27" src="https://user-images.githubusercontent.com/46345125/177492220-7e568173-69cc-4289-8a94-124393db9f1d.png">
