### ISSUE TITLE
new design for the stars widget

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2378]
We should use the following design for the widget as that is more intuitive and visually less distracting.
![image](https://user-images.githubusercontent.com/46004116/177730925-393e8dfa-21f6-4169-bb7d-ba7e2ac5a499.png)

Originated from https://github.com/gitpod-io/website/pull/2352#issuecomment-1175845707

**Comment by nisarhassan12** [comment]
@chrifro I have brought it up internally https://gitpod.slack.com/archives/C01KGM9ETU6/p1657791058751219 once a decision is made there I'll start the implementation.

**Comment by Cahllagerfeld** [comment]
When moving this to the Layout and requesting the data from the Github-API we might run into rate-limiting issues [[1](https://docs.github.com/en/rest/overview/resources-in-the-rest-api)] as it looks like only 60 requests per hour our allowed for unauthenticated requests. 

That's probably no blocker for the clients, but for the prebuild as the API will be hit for every page created during the build-process

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/commit/e826e4d2859661fc05ccec5e4977e10614d6ed65
