### ISSUE TITLE
flickering for star widget

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2379]
When loading the page there is a lot of flickering in the right corner. It takes some time until the star widget and the logged in user state is loaded correctly.

See screencast
https://user-images.githubusercontent.com/46345125/177750097-661983b1-a545-4266-8733-a5b7466aa1b7.mov

cc @nisarhassan12 because of #2352

**Comment by nisarhassan12** [comment]
Thanks, @chrifro for bringing this up. Sorry that I didn't test the deploy preview myself for now I have reverted #2352 and opened a new Pr which should be merged once https://github.com/gitpod-io/website/issues/2378 is implemented in the next week.

**Comment by nisarhassan12** [comment]
https://github.com/gitpod-io/website/issues/2378#issuecomment-1184222303

**Comment by Cahllagerfeld** [comment]
Hey @nisarhassan12,
thats live now, isn't it?

**Comment by nisarhassan12** [comment]
Thanks, @Cahllagerfeld for bringing this up. The changes are live so I'll close this now.
