### ISSUE TITLE
Improve layout of cookie banner 

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2386]
**Context**
Through the introduction of a [new cookie consent flow](https://github.com/gitpod-io/website/pull/2094), users are being opted out of analytics cookies by default. The cookie banner should be improved to increase the number of website visitors we can track while following industry standards in GDPR compliance. [[1](https://www.notion.so/gitpod/Analytics-Regaining-Visibility-of-Website-Visitors-139541644400495bb9eee3e3ebf907c4)]

**To-do's**
- [ ] implement new cookie banner (see mockup below)
- [ ] don’t hide cookie banner until an option is selected
Currently, the banner disappears after viewing the cookie settings. On other websites e.g. Vercel the banner stays visible until a decision has been made

**Mockup**
[source](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5851%3A9369)
<img width="719" alt="Bildschirmfoto 2022-07-06 um 11 12 34" src="https://user-images.githubusercontent.com/46345125/177798589-1c61a044-7b13-44c2-b71a-bd50ae2df51a.png">

**Comment by nisarhassan12** [comment]
@chrifro We already have quite a lot going on mobile. Can you share a mobile mockup for it as well? Thanks

**Comment by chrifro** [comment]
>Can you share a mobile mockup for it as well?

Sure, I added a [ mockup ](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6002%3A9725) for mobile.

>This is how it looks on my 13inch M1 Macbook the CTAs are hidden behind it the same is true for some bigger screens and smaller screens such as tablets. Is it fine like this ?

- By default, it should be aligned with the bottom of the contact widget. So the contact widget could move further down.
- the cookie window can be generally placed a bit further down the screen 
- the margins can be decreased from 32px to 24px
- then the CTAs should be slightly visible. It's not optimal but ok I'd say. It's similar to Vercel, right?

**Comment by nisarhassan12** [comment]
> - [ ] the cookie window can be generally placed a bit further down the screen

Isn't it supposed to be fixed while scrolling? with a fixed position it can't be below the viewport otherwise it'll never be accessible. 

> - [ ] the margins can be decreased from 32px to 24px
> - [ ] By default, it should be aligned with the bottom of the contact widget. So the contact widget could move further down.

The margins for the contact widget are 16px from both the bottom the right so to align it we will have to make the margins the same. 

> - [ ] then the CTAs should be slightly visible. It's not optimal but ok I'd say. It's similar to Vercel, right?

I tried 16px but it is still not visible. I deleted all the cookies and local storage on Vercel's website but I don't see it how it is there not sure why.

**Comment by chrifro** [comment]
>Isn't it supposed to be fixed while scrolling? with a fixed position it can't be below the viewport otherwise it'll never be accessible.

Yes, it's fixed while scrolling but it should be placed 8px above the window size 

>The margins for the contact widget are 16px from both the bottom the right so to align it we will have to make the margins the same.

What about making it 8px for both the bottom of the contact widget and the cookie pop-up? 

> I deleted all the cookies and local storage on Vercel's website but I don't see it how it is there not sure why.

You can use the incognito window to test it 

> the margins can be decreased from 32px to 24px

To be clear, here I'm talking about the spacing inside the cookie card

**Comment by nisarhassan12** [comment]
@chrifro I have made Pr #2426 for it. Please have a look when you get time. 

I have made it 8px from below. 

> To be clear, here I'm talking about the spacing inside the cookie card

Ah in development the inside spacing is referred to as the padding while the outer spacing is called margin that is why I got confused :) 

Also I have used less spacings for mobile than what you specified in the mockup to make it take less space on smaller phones. 

> You can use the incognito window to test it 

Not sure why but I don't see it there as well :(

**Comment by chrifro** [comment]
It's a bit tricky to test with the Netlify banner, but it should be fine
<img width="1259" alt="Bildschirmfoto 2022-07-15 um 09 06 11" src="https://user-images.githubusercontent.com/46345125/179170727-6ddcad51-4df1-41c1-88b2-a59045940c51.png">

>Ah in development the inside spacing is referred to as the padding while the outer spacing is called margin that is why I got confused :)

Thanks for clarifying it. I will keep it in mind :)

**Comment by nisarhassan12** [comment]
> It's a bit tricky to test with the Netlify banner, but it should be fine

Thanks Christin. FYI you can get rid of the Netlify bar if you click on the arrows(opposing each other) in the right it will collapse and show a close button like the following which will close the bar once clicked

![image](https://user-images.githubusercontent.com/46004116/179171258-87853f1a-8817-4c70-8050-3952801f03e8.png)
