### ISSUE TITLE
Content for `/self-hosted`

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#2402]
Especially when coming from a search engine, the first thing people see on the Self-Hosted Page is pricing. We should add more content around it and/or restructure the page a bit. 

Ideally, we can involve the CX Team in this, so they can give input on what things or FAQs we can/should address on that page.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
