### ISSUE TITLE
Illustration is cropped on home

### ISSUE THREAD

**Issue by juergenhassler** [gitpod-io/website#244]
The Gitpod room image is cropped at the bottom on home
<img width="1426" alt="Pasted_Image_07_04_21__08_53" src="https://user-images.githubusercontent.com/16590836/113823378-dfb84100-977e-11eb-954e-2835d92ad703.png">

**Comment by nisarhassan12** [comment]
It looks like this issue have been resolved 
![image](https://user-images.githubusercontent.com/46004116/117237351-3aa78b80-ae44-11eb-951f-20565167626c.png)
