### ISSUE TITLE
[Docs - New Feature]: Make the custom AMI available on eu-west-3

### ISSUE THREAD

**Issue by dja-fr** [gitpod-io/website#2444]
### Describe your feature request

Make the custom AMI available on eu-west-3

### User impact

The tab listing all AMI ID need to be update.

**Comment by Cahllagerfeld** [comment]
Hey @MrSimonEmms, 
I just came across your comment in the EKS-Repo.
Can you review these changes, or do I need to address someone else with it?
If needed, we can transfer this issue to the main repo as well (like said in the issue)
Let me know if I can support you here, I'm glad to help :)
