### ISSUE TITLE
Improve contact widget

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2448]
**Goal**:
simplify the contact widget
See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6118%3A10043)

|status quo| new design|
|-|-|
|<img width="310" alt="Bildschirmfoto 2022-07-20 um 10 58 53" src="https://user-images.githubusercontent.com/46345125/179941891-26889c77-599d-4f15-91d1-a05f63b4f48b.png">|<img width="272" alt="Bildschirmfoto 2022-07-20 um 11 08 42" src="https://user-images.githubusercontent.com/46345125/179943971-6f1d57a4-d33c-4e4e-9f47-db36fe53e611.png">|

**Changes**:

- [x] ~~remove the grey gradient from icons~~
- [x] remove the circle around the closing icon
- [x] align the size of the closing icon
- [x] speed up the blur animation
- [x] reduce spacing within the buttons before and after the icons to 16px
- [x] align icon sizes according to the mockup
- [x] remove the pointing triangle from the card
- [x] adjust the size of the CTA to 48x48px

**Comment by nisarhassan12** [comment]
Thanks, @chrifro for creating the issue.

> - [ ] remove the grey gradient from icons

Can you tell why do we want to do this? In my opinion, it looks fine with the gradient. 

While we could still remove it the technical implementation would require a lot of effort and maintenance work to have two different icons i.e one in gray and the other with the gradient, I'm not sure about implementing the hover here as well.

**Comment by chrifro** [comment]
>Can you tell why do we want to do this? In my opinion, it looks fine with the gradient.

Great that you ask @nisarhassan12 . We need to make sure that we have a consistent style throughout the whole website and also all marketing assets. That's why we created the component library and defined all global styles there. We should not start introducing new styles that are not reflected there, otherwise, it can quickly have a snowball effect and our assets are not in sync anymore.

>While we could still remove it the technical implementation would require a lot of effort and maintenance work to have two different icons i.e one in gray and the other with the gradient, I'm not sure about implementing the hover here as well.

Thanks for highlighting this. I was not aware of the technical complexity.

Reconsidering this and keeping in mind that it's likely that we will face this issue more often, I will add the new monochrome gradient style to the component library. By that, we are now officially introducing a new style and can continue using the gradient here. 

Thanks for bringing it up 🙌

**Comment by chrifro** [comment]
I added the new style here: https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=1487%3A2144

**Comment by nisarhassan12** [comment]
Thanks @chrifro for doing that sorry I forgot to specify this earlier that the gray gradient is the CSS `100%` value for the `grayscale` filter.

We don't need to define a value inside the component library but it should be noted that we use the `filter: grayscale(100%)` for the grey gradient. 

![image](https://user-images.githubusercontent.com/46004116/184181843-5d9cd4eb-be3e-4cdb-970b-72ea6a6d52e8.png)

In case we want to what you just added to the Component library we will still be facing the same issues as specified in https://github.com/gitpod-io/website/issues/2448#issuecomment-1211650246 

![image](https://user-images.githubusercontent.com/46004116/184182305-f1d35fcf-48f0-4684-b882-eafea7bbd4e2.png)


This above is what we have in prod. Does this all makes sense 
?

**Comment by nisarhassan12** [comment]
> reduce spacing within the buttons before and after the icons to 16px

@chrifro In the latest mockup I see the spacing to be 16px before the icon and 8px after the icon box(which is 24x24) i.e between the icon and the text, and at the end of the text it's 16px. Should I make at 16px after the icon as well ? 

>  align icon sizes according to the mockup

@chrifro They all have inconsistent heights and widths in the mockup inside the 24x24 box I have made the height and width for all of them to be 16x16. While it is possible to set the different height and widths it is not practical. Let me know if I should do that anyway. Thanks

Also the paddings on the right side i.e the space inside the card which holds the button and the close icon is 26px but for the other 3 sides it is inconsistent in the mockup so I have used 32px for the top and 16px for the remaining sides.

**Comment by chrifro** [comment]
>@chrifro In the latest mockup I see the spacing to be 16px before the icon and 8px after the icon box(which is 24x24) i.e between the icon and the text, and at the end of the text, it's 16px. Should I make it 16px after the icon as well anyway?

No, that's correct. 16px padding to the sides and 8px spacing between elements within the button

>They all have varying heights and widths in the mockup inside the 24x24 box I have made the height and width for all of them to be 16x16. While it is possible to set the different heights and widths it is not practical. Let me know if I should do that anyway. Thanks

That's on purpose and that's why they are all in a consistent 24x24 frame. The icons have different dimensions and are scaled differently to appear visually even. This is a common practice. e.g. see the https://www.figma.com/file/6kYl006dbuG4NlEeNn0g8l/Microsoft-Fluent-system-iconography-(Community)?node-id=1124%3A9833

**Comment by chrifro** [comment]
>Also, the padding on the right side is 26px i.e the space inside the card which holds the button and the close icon but the paddings for the other 3 sides are inconsistent in the mockup, so I have used 32px for the top and 16px for the remaining sides.

Thanks, I updated [the mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6118%3A10043) accordingly. Note: the padding does not apply to the closing icon

**Comment by nisarhassan12** [comment]
> But then that's the case for any hover style that involves a color change e.g. the primary button. Could you explain the technical complexity of this hover style compared to others?

@chrifro I have recorded a short video to explain this and will send that over via Slack.

**Comment by chrifro** [comment]
Thanks for the context. Alright, let's keep the gradient as it it

**Comment by nisarhassan12** [comment]
@chrifro In the mockup box around the close button overlaps the first button which is not good for accessibility for this reason I have repositioned it a bit far away in the implementation in #2568 to make sure there is at least 8px whitespace between the two tap targets.

**Comment by chrifro** [comment]
I just looked at the PR, looks great already. One nit: could you add a bit more spacing between the whole widget and the right end of the browser window?  Something around 16px should be good. Thanks!
Feel free to merge it directly once all comments have be en addressed 🚀
<img width="283" alt="Bildschirmfoto 2022-08-12 um 15 53 11" src="https://user-images.githubusercontent.com/46345125/184367952-36b23104-d0dd-4cba-9254-c1995ffb8520.png">

**Comment by nisarhassan12** [comment]
> Something around 16px should be good.

Thanks done ✅ I have made it so that it's 16px when it's tablet or desktop devices and for mobile, I left it to `8px` because there we have a lot less space to work with.

**Comment by nisarhassan12** [comment]
Fixed in #2568
