### ISSUE TITLE
Reconsider top spacing

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2460]
**Context:**
with 160px distance between the navigation bar and the first content element, we currently use quite a lot of spacing. The disadvantage of that can be that valuable information is cut on smaller screen sizes and users need to scroll a lot. See [internal discussion ](https://gitpod.slack.com/archives/C01KGM9ETU6/p1655918699636859). 

**Benchmark**
Vercel: variation between 56px, 44px, 80px and 144px. But 80px being the norm
Launchdarkly: 100px, 80px
Planetscale: 212px, 64px, 120px
Github: 80px, 176px, 114px

**Solution:** 
-  introduce different spacing based on the page layout
- generally, reduce the top spacing

|status quo (160px) |new spacing (72px) for pages like /guides, /pricing, /about, /blog, /changelog, /community, /contact, /screencasts, /vs/ and /for/ pages with a centered text|
|-|-|
|<img width="1298" alt="Bildschirmfoto 2022-07-22 um 09 36 49" src="https://user-images.githubusercontent.com/46345125/180388609-52a04b2f-baca-4f73-bf4b-f5b85f42c23f.png">|<img width="1006" alt="Bildschirmfoto 2022-07-22 um 09 44 42" src="https://user-images.githubusercontent.com/46345125/180389917-7b69453a-f93e-45be-864d-475a4fea89ed.png">

|status quo (160px until image)|new spacing (72px image, 160px text)|
|-|-|
|<img width="1275" alt="Bildschirmfoto 2022-07-22 um 09 49 13" src="https://user-images.githubusercontent.com/46345125/180392418-a6f06565-3ccd-402d-9642-844711006587.png">|<img width="1151" alt="Bildschirmfoto 2022-07-22 um 10 00 08" src="https://user-images.githubusercontent.com/46345125/180392617-5ed2d468-2b43-4485-8bea-01d2032ad394.png">

|status quo (160px)|no new spacing |
|-|-|
|<img width="1285" alt="Bildschirmfoto 2022-07-22 um 10 06 06" src="https://user-images.githubusercontent.com/46345125/180393596-35c21408-9ec5-4721-8c52-ae6c15364fd9.png">| stays the same. Affected pages: www.gitpod.io, /enterprise, /vs/JetBrains-space, 

I would be curious to hear your thoughts on this @nisarhassan12

**Comment by chrifro** [comment]
@nisarhassan12 could you prioritize this issue, as it also affects the webinar landing page and the registration button being cut.

**Comment by nisarhassan12** [comment]
@chrifro I have started working on this.

**Comment by nisarhassan12** [comment]
@chrifro regarding the spacing in the individual customer story page you specified 160px above the text that is not gonna work i.e in the mockup the text you have is too little while on actual case studies it is a lot more if there is always 160px above the text than it will go beneath the card on the right and look misaligned atm both are vertically aligned no matter what the size of the text is. I'll suggest just having `72px` at the top of the element which contains both the text and the image.

**Comment by chrifro** [comment]
>atm both are vertically aligned no matter what the size of the text is. I'll suggest just having 72px at the top of the element which contains both the text and the image.

we can keep the text centered as well and just move the general section further up. So let's go with your suggestion of 72px for the whole element.

>Also, should the spacing at the top of the /customers page is also supposed to be reduced to 72px?

I'm not sure, I understand what you mean by that. Can you show an example?

**Comment by nisarhassan12** [comment]
> Can you show an example?

I meant should I also decrease the top spacing in the header of the `/customers` page see the following:

![image](https://user-images.githubusercontent.com/46004116/181313666-21808ad3-c711-4e09-80cf-e708a0dc376a.png)

**Comment by chrifro** [comment]
I agree with your suggestion to keep the header section centered on the image. The whole section (header section +image) should have a top spacing of 72 px. Does that answer your question? :)

**Comment by nisarhassan12** [comment]
I self-reviewed the PR and merged the changes I went through the entire site excluding the content pages(i.e all the blog posts, docs pages, individual guides and so on. )
