### ISSUE TITLE
Document VS Code Desktop popups (how to optimise)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2461]
Document: 
1. SSH fingerprint
2. Trust the workspace
3. Allowing the VS Code Desktop redirect
4. etc

Either explain how to optimise, or why it cannot be updated / changed. 

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/9568
- https://github.com/gitpod-io/website/issues/2455

Internal link [[1](https://gitpod.slack.com/archives/C01KGM9BH54/p1659517419239619)]

**Comment by akosyakov** [comment]
@loujaybee Does it make sense to track in IDE project as well? You will need update to boards. I moved it in progress for now.

**Comment by loujaybee** [comment]
1. SSH fingerprint is now optimised with SSH Gateway settings
https://www.gitpod.io/docs/ides-and-editors/vscode#connecting-to-vs-code-desktop-ssh
https://www.gitpod.io/docs/ides-and-editors/vscode#optimizing-vs-code-desktop

2. The browser redirect will only need to be dismissed once going forward (not per workspace)
https://github.com/gitpod-io/gitpod/pull/12082

3. How to optimise Workspace Trust is now documented
https://www.gitpod.io/docs/ides-and-editors/vscode#workspace-trust
