### ISSUE TITLE
[Docs - Quickstart] - Requesting PHP Symfony

### ISSUE THREAD

**Issue by hotwebmatter** [gitpod-io/website#2465]
To start a Symfony project, should I modify the [PHP Drupal](https://www.gitpod.io/docs/quickstart/drupal) or [PHP Laravel](https://www.gitpod.io/docs/quickstart/laravel) quickstart?

**Comment by hotwebmatter** [comment]
Never mind, I found this:

[Symfony Demo Application](https://github.com/symfony/demo).

Might be nice to add this to the QuickStart templates, though.

**Comment by Siddhant-K-code** [comment]
copy of #1294
