### ISSUE TITLE
[Docs Feedback]:  Feedback URL is stored as http://sveltekit-prerender/ instead of https://gitpod.io/

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#2467]
### User feedback

Makes it hard(er) to review feedback from people.

<img width="445" alt="2022-07-25_14-22-55" src="https://user-images.githubusercontent.com/127353/180698515-d6ee6549-9e53-4e8d-ad6c-7d4b842ec666.png">

**request:** make all urls https://gitpod.io/ when in production.

**Comment by Cahllagerfeld** [comment]
That's an issue with the Sveltekit Adapter I think. I've started bumping our versions successively, as we are behind over 100 versions. This (hopefully) should resolve when reaching a certain version
