### ISSUE TITLE
Add Self-Host on Azure to /vs/*.*

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#2472]
Gitpod supports self-hosting on Azure:

<img width="292" alt="2022-07-25_21-20-01" src="https://user-images.githubusercontent.com/127353/180766212-a862cfc5-fcad-48a3-8322-8744f5120c27.png">

For each /vs:
- [ ] Create Azure image
- [ ] Implement it

**Comment by chrifro** [comment]
Design 

<img width="216" alt="Bildschirmfoto 2022-07-25 um 14 08 32" src="https://user-images.githubusercontent.com/46345125/180774814-64d4ad60-3573-437c-9115-e393666f75e0.png">

logo
![Microsoft_Azure](https://user-images.githubusercontent.com/46345125/180774355-96b7a75a-fb73-4347-99df-72bbedb70f0b.svg)

**Comment by chrifro** [comment]
- [ ] And update all existing Azure logos with the new logo. e.g. on /vs/github-codespaces
<img width="502" alt="Bildschirmfoto 2022-07-26 um 15 13 28" src="https://user-images.githubusercontent.com/46345125/181014602-7465792f-e536-4e84-814e-2856bdb86374.png">
