### ISSUE TITLE
webinar landing page improvements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2481]
- [x] the second checkbox as discussed on Slack is still missing [1]
- [ ] the form card moves a lot, but should have a fixed position similar to [Vercel's page](https://vercel.com/try/building-the-fastest-digital-storefronts)
- [ ] the page glitches/jumps after filling out the form
https://user-images.githubusercontent.com/46345125/181186645-eaaf1b88-6a74-4f8c-af13-c7641a234632.mov

- [x] duplicate emails should be prohibited from signing up, as it will cause email spam and wash out our registration numbers. See Slack discussion
- [x] Typo: remove "how" in "If you are curious to learn more on how remote developments, have a read through these blog posts."

**Comment by nisarhassan12** [comment]
The two todos that I checked are already fixed see the live site. 

> the form card moves a lot, but should have a fixed position similar to [Vercel's page](https://vercel.com/try/building-the-fastest-digital-storefronts)

That is on purpose to have the form completely visible on small laptops otherwise the button will never be visible see the below screenshot of Mac 13':

![image](https://user-images.githubusercontent.com/46004116/181188650-4590b0e1-b086-48f2-b175-1f1527947653.png)

**Comment by chrifro** [comment]
>That is on purpose to have the form completely visible on small laptops otherwise the button will never be visible see the below screenshot of Mac 13':

[This issue](https://github.com/gitpod-io/website/issues/2460) should fix the top spacing. Could you address that next and afterward align the jumping box? 🙏

**Comment by nisarhassan12** [comment]
> Typo: remove "how" in "If you are curious to learn more on how remote developments, have a read through these blog posts."

@chrifro I have removed the how and also the s at the end of `remote developments`.

**Comment by nisarhassan12** [comment]
>  the page glitches/jumps after filling out the form

@chrifro Can you check against the deploy preview here https://github.com/gitpod-io/website/pull/2491 if the issue is resolved?

**Comment by chrifro** [comment]
It's still moving

https://user-images.githubusercontent.com/46345125/181447635-43e807eb-aceb-4760-862c-a19e726190fb.mov

**Comment by chrifro** [comment]
@nisarhassan12 I will close this issue as the webinar has passed. We can reconsider it for the next webinar
