### ISSUE TITLE
[docs] How to fork a repository?

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/website#249]

**Comment by ChristinFrohne** [comment]
Is this still relevant @svenefftinge?

**Comment by nisarhassan12** [comment]
@ChristinFrohne I think it is still relevant:  https://github.com/iterative/dvc.org/pull/1262#discussion_r422308466

**Comment by ChristinFrohne** [comment]
Could you write about it @nisarhassan12? Or maybe @JesterOrNot would like to look into it?

**Comment by nisarhassan12** [comment]
@ChristinFrohne Thanks sure.
