### ISSUE TITLE
Reorder webinar hosts (cards) in a more scalable way

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#2497]
### Problem to solve

In the new webinars page (see [example webinar](https://www.gitpod.io/webinars/java-remote-development)), the hosts are represented with cards that could scale better if the cards were stacked instead.

Currently, it feels like there's not enough space to host more than one host and hosts at the end can easily go unnoticed.

### Proposal

Reorder webinar hosts (cards) in a more scalable way.

| BEFORE | AFTER (Draft) |
|-|-|
| <img width="1440" alt="Screenshot 2022-07-28 at 2 57 36 PM" src="https://user-images.githubusercontent.com/120486/181500213-8e333fe1-3a22-4451-be29-13aa23668a6b.png"> | <img width="1440" alt="Screenshot 2022-07-28 at 2 57 43 PM" src="https://user-images.githubusercontent.com/120486/181500218-121d655e-2581-4160-947a-58fe8692a5de.png"> |

### User impact

1. Webinar page layout seems broken or squeezed. 🍋 
2. Webinar hosts are not visible enough on small screens or viewports.

**Comment by chrifro** [comment]
Thanks for the suggestion @gtsiolis ✨

We went for the MVC and reused an existing component for the host cards [[1](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2046%3A5923)]

Considering the value of this change and the number of other issues we have on our plate, I'd say it's okay to ignore that change for now and to keep your suggestion in mind for future iterations :) 

I will close the issue with that, feel free to reopen in case you disagree. 🙌

**Comment by gtsiolis** [comment]
Thanks, @chrifro! Sounds good. 🛹
