### ISSUE TITLE
Update logo color for dark theme

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2503]
Change external logo color for the dark theme from white to #999795

|before|new|
|-|-|
|![Bildschirmfoto 2022-07-29 um 15 32 21](https://user-images.githubusercontent.com/46345125/181771259-0395cd1c-0380-4de3-ae34-bac1128deb93.png) |![Bildschirmfoto 2022-07-29 um 15 32 32](https://user-images.githubusercontent.com/46345125/181771287-fd24cf0d-b64e-4ebb-8a71-69835da6de51.png)
|

This change also affects single logos like these ones
![Bildschirmfoto 2022-07-29 um 15 32 45](https://user-images.githubusercontent.com/46345125/181771485-83ffc31a-c277-4cf3-883e-8f790a96a454.png). 

Note: Logos that are not SVG's need to be aligned manually if necessary. 

See [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831)

**Comment by chrifro** [comment]
Follow-up for #2502 as the logo color for the svg and the png logos currently don't align 

cc @nisarhassan12

**Comment by nisarhassan12** [comment]
@chrifro For the quotes section do we want to have the same colours? atm we are using the CSS grayscale filter when the logos are inactive and for active we're using different colours i.e sometimes they are the original logo colour 

![image](https://user-images.githubusercontent.com/46004116/184928648-6d85ecb4-875d-4dac-b238-2de88b500fa2.png)

**Comment by chrifro** [comment]
@nisarhassan12 Let's keep this change as simple as possible and keep the quote section as it is. We can keep that in mind for the next iteration
