### ISSUE TITLE
[Docs Enhacement - New Feature]: Add better examples for Git Integration Screens for Self Hosted

### ISSUE THREAD

**Issue by mrzarquon** [gitpod-io/website#2506]
### Describe your feature request

There is no clear "what do I do next" after you get the self hosted installation complete from the KOTS admin panel.

You are instead sent to our git integration guide but it isn't clear what exactly you should do next, since they talk about self hosted versions of the scm providers, but there's no mention of self hosted gitpod. The steps are pretty simple also:
- go to https://your-new-install
- add integration following on screen instructions

(as a side note, there should be included a "getting prepared for gitpod" that along with ssl certificates and DNS, mentions the need for the oauth tokens for git providers with concrete examples for those also)

And if you installed gitpod properly these are the screens you'd see, and if you didn't you didn't install it properly:

<img width="1563" alt="Screen Shot 2022-07-29 at 17 38 29" src="https://user-images.githubusercontent.com/57210/181824171-fcc3537c-5c71-49a6-a382-9156ccd5c0dc.png">

<img width="1563" alt="Screen Shot 2022-07-29 at 17 38 33" src="https://user-images.githubusercontent.com/57210/181824156-2aaefd2f-c5b8-48ac-ba98-b07c163e388f.png">

### User impact

In a situation where the installation isn't quite right, the users may think they have to add credentials via some other method, or generally feel lost. Since installing gitpod still isn't easy, it feels like the user has reached the summit only to realize there is more to go.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
