### ISSUE TITLE
Add question with drop down to self-hosted community and professional license 

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#2515]
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/83109781/182254938-7248f2a0-8668-4032-8bb6-2799ffef111b.png">
Add a question to the [community license](https://www.gitpod.io/community-license ) request form AND the[ professional license request](https://www.gitpod.io/enterprise-license) form. Same drop down for both license forms. 

**Title for the drop down:** 
How did you hear about the community license? Note: _not mandatory_

**Answer Options:**
Local preview installation
Gitpod website / docs
Someone else told me about it
Other

---
If anyone has great ideas which other options to add, please comment in the issue
/cc @lucasvaltl @MichaelAring

**Comment by lucasvaltl** [comment]
👋 Edited this issue to mention that we need this for both license forms :)

**Comment by nisarhassan12** [comment]
> **Title for the drop down:**
How did you hear about the community license? Note: not mandatory

@phimae Just to confirm `Note: not mandatory` is a note for me to mark this field as optional relating to the submission and not something that we want to show in the actual UI?

**Comment by nisarhassan12** [comment]
Also if you look at the Pr preview for https://github.com/gitpod-io/website/pull/2569 and resize the window to get to the tablet size it does not look good as the label spans two lines. Can we somehow shorten it? Any suggestions? Thanks 
![image](https://user-images.githubusercontent.com/46004116/184212197-0d177020-dc26-47d9-8dfd-7b821e51b69c.png)

**Comment by nisarhassan12** [comment]
@phimae Also if we want the selected item to be in the feedback sheet then can you please add a new column between `F` and `G`? Thanks

**Comment by lucasvaltl** [comment]
👋 What is the state of this? :)

**Comment by phimae** [comment]
Hey sorry for the delay in here, a few things came in the way. **Context**: The current leads processing flow is fragile so any change like this requires a lot of excel smithing to not break things. As a result Jakob and I have been preparing to transfer any lead processing fully to segment to make this more robust. See https://github.com/gitpod-io/website/pull/2609 

To unblock this issue, let's do the following @nisarhassan12 
- As for the sizing issue: Rename it to "What brought you here?"
- The selector preview should show "Select..."
- You can create a new column for the referrer after [column K](https://docs.google.com/spreadsheets/d/1DrgFXvDsLmu6kUoBHMfgYqBtqyT9kr4OHqcKX31FbXw/edit#gid=762308557) - Does your function depend on the specific location of the column or can it also be moved afterwards? 
- For now, please do not change anything that is included in the email that is triggered after a request ( do not include `Referrer: XYZ`) This relates to the current fragility of how the pipe leads into Salesforce. Again, this will be changed in a couple of days

**Comment by nisarhassan12** [comment]
@phimae My function depends on the specific location of the column i.e I can add the referrer anywhere from column `A` to column `G` that is from the Timestamp to the Message it could also be right after the message but it can't be after that. 

> ou can create a new column for the referrer after [column K](https://docs.google.com/spreadsheets/d/1DrgFXvDsLmu6kUoBHMfgYqBtqyT9kr4OHqcKX31FbXw/edit#gid=762308557)

Can I create one after G? Thanks

**Comment by phimae** [comment]
Yes you can create a new column to the right of F so that referrer becomes column G. Once you do that, please ping me right away as I need to adjust the Zaps for the new structure. Let's get this merged tomorrow

**Comment by nisarhassan12** [comment]
Thanks will do as you suggested. 

One thing: Would it make sense to have the referrer dropdown on the Sales form when the subject is "Self-hosting" or "Get a demo" is selected and the number of developers is `1-10` ?

**Comment by phimae** [comment]
> One thing: Would it make sense to have the referrer dropdown on the Sales form when the subject is "Self-hosting" or "Get a demo" is selected and the number of developers is 1-10 ?

In the local preview installations people are nudged towards the community license and we want to be able to measure the conversion of preview --> self-hosted install so I think it's fine it's only here
