### ISSUE TITLE
[Docs Feedback]: Improve Bitbucket Integrations Doc

### ISSUE THREAD

**Issue by Nancy-Chauhan** [gitpod-io/website#2519]
### Page URL

https://www.gitpod.io/docs/bitbucket-integration

### User feedback

Our hosted bitbucket documentation is pretty sparse. We do not have directions on how to add a BitBucket integration within a self-hosted instance of Gitpod.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
