### ISSUE TITLE
[Docs Enhacement - New Feature]: Product Compatibility Matrix in the docs

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2523]
### Describe your feature request

WE want to make our [Product Compatibility Matrix](https://www.notion.so/gitpod/Product-Compatibility-Matrix-a7f15b2155a545aa8a7b6c27cf7e00ae) public. This was discussed in this (internal) [RFC](https://www.notion.so/gitpod/Product-Compatibility-Matrix-in-the-docs-Process-and-Hierarchy-7499887c0d9c40a19c61c49868ef60d3).  

_tl:dr: we want to make this public in order to premptively answer questions around what works with Gitpod, in order to help (somewhat) standardise the environments that Self-Hosted is running on more and in order to force ourselves to keep it up to date in a better way._ 

Specifically, we envision a table in the references docs section that looks somewhat like this wireframe:
<img width="1475" alt="Screenshot 2022-08-02 at 14 12 14" src="https://user-images.githubusercontent.com/22516873/182371682-e13a84ef-d55e-4197-83cf-779fb2d582f2.png">
(taken from [here](https://www.figma.com/file/btvRBejD6RWf5skdoa1EEf/Product-Compatibility-Matrix?node-id=0%3A1))

WE cannot use a regular markdown table due to some specific features we are looking for: 
1. **Categories can span multiple rows:** In order to be visually appealing and avoid repition, we'd like categories to be able to group different components (represented by rows) 
2. **Filtering / different views on the table:** In order to avoid clutter and be more targeted to personas, we want to give the user the option to filter on relevance. Specifically filter on relevance towards different user personas (see user impact)
3. **Implicitly assign Gitpod Engineering teams to categories:** We want to assign teams to categories in a way that is transparent to the viewer of the actual page. This assignments are then used during a PR process to know which team needs to sign off on a change (e.g. a change to the supported version of Gitlab Enterprise).

### User impact

This enables the following types of users to self-service answering the question "does Gitpod Support X": 
- **Developers:** Developers can better understand the tools that they can use together with Gitpod (Browser, IDEs). Components that are used by the individual developer are relevant here.
- **Self-Hosted Admins:** Admins and installers can better understand if a component they usually use works with Gitpod (Registries, Databases etc.). Anything that is related to components required by a Gitpod Self-Hosted Installation are relevant here. 

### Related Context
- [Basic version](https://deploy-preview-2433--gitpod-kumquat.netlify.app/docs/self-hosted/latest/product-compatibility) of this that just uses a markdown table - taken from this [PR](https://github.com/gitpod-io/website/pull/2433).

**Comment by chrifro** [comment]
**Next steps:**
- create a PR that introduces the new component for the compatibility matrix (no visible changes to the website) -> @nisarhassan12 
- create a follow-up PR to publish the compatibility matrix -> @lucasvaltl 

**Mockup**
You can find the mockup[here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6410%3A10483), including a mobile mockup
<img width="779" alt="Bildschirmfoto 2022-08-04 um 08 58 42" src="https://user-images.githubusercontent.com/46345125/183652838-3f08d45a-c4e5-49fe-aa68-7bbdd2269ef3.png">
