### ISSUE TITLE
[blog] optimize images for dark theme

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2524]
Some images on https://www.gitpod.io/blog/i-said-goodbye-to-local-development-and-so-can-you are not readable on the dark theme and need to be replaced. 
 
The images optimized for dark theme can be found here
[dark theme images.zip](https://github.com/gitpod-io/website/files/9242469/dark.theme.images.zip)
 
Moving forward we need to use the export option for light and dark theme directly within excalidraw

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/pull/2558
