### ISSUE TITLE
Optimise scroll bar for dark theme

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2526]
See https://www.gitpod.io/docs/ides-and-editors for example

<img width="321" alt="Bildschirmfoto 2022-08-02 um 15 25 45" src="https://user-images.githubusercontent.com/46345125/182385884-703a0073-37a8-44ef-abb8-64464c59c256.png">

Let me know in case a mockup is needed

**Comment by chrifro** [comment]
Same for the standard scroll bar
<img width="278" alt="Bildschirmfoto 2022-08-03 um 13 28 30" src="https://user-images.githubusercontent.com/46345125/182597306-b91bc2b2-979e-4430-b238-b272a5d35d10.png">

**Comment by Cahllagerfeld** [comment]
Hey @chrifro, 
I've found this Codepen on how to fix it - I didn't test the implementation in our scenario yet.
Would we use the same colors from our current color palette, and make it look like Github for example 

![Image](https://user-images.githubusercontent.com/43843195/187146768-61348497-d653-42ce-abce-a730d7f03420.png)

or would we need an entirely new mockup?
