### ISSUE TITLE
Optimize icons for dark theme

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2530]
Some icons are not optimized for dark theme as they use a white background
<img width="661" alt="Bildschirmfoto 2022-08-03 um 10 30 49" src="https://user-images.githubusercontent.com/46345125/182571026-aa58fe83-23c1-4eab-b4fa-aac8f41b9636.png">
<img width="400" alt="Bildschirmfoto 2022-08-03 um 10 32 19" src="https://user-images.githubusercontent.com/46345125/182571034-1ee22642-8c67-43ed-b8be-488358a0eccc.png">

To do's:
- [x] check all icons 
- [x] replace icons with white background with transparent background (see [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A1119))

**Comment by NsdHSO** [comment]
Hi @chrifro, I would like to know more details about this issue, I don't have access to Figma.

**Comment by nisarhassan12** [comment]
Hi @NsdHSO Sorry at the moment the Figma component library is not publicly available so it would make sense for me to work on this issue.

Feel free to pick any issues from here https://github.com/gitpod-io/website/issues and let me know in case you'd like my help in contributing to them. Thanks
