### ISSUE TITLE
Align top navigation drop-down with banner

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2532]
Issue:

Currently, the navigation bar is not visible if the banner is active
<img width="1426" alt="Bildschirmfoto 2022-08-03 um 11 39 07" src="https://user-images.githubusercontent.com/46345125/182577075-b2ee16ef-625d-4f4c-966f-8b929a5f7c77.png">

**Comment by chrifro** [comment]
@Siddhant-K-code or @Cahllagerfeld could one of you look into this issue next? (tomorrow would be fine. Take a well-deserved rest for today :) )

**Comment by Cahllagerfeld** [comment]
Related to this are the sticky left and right menus in the docs layout that are off when displaying the banner
