### ISSUE TITLE
[docs] Add contact option to docs feedback widget

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2572]
**Context**
---
Currently, we have no option to start a dialog with users after they submitted their docs feedback. Some users take a lot of effort to report an issue and we should make sure they feel heard, that we value their feedback and that we keep them updated about changes. 

For that, we want to add a voluntary option to the docs widget to provide the email address and for legal concerns a checkbox that they agree to be contacted.

The decision for this improvement was made [here](https://www.notion.so/gitpod/Docs-Sync-0a2989dbbc874a2e910ce313b63c2a1c#626b674adeac4fdbbc7170685fcaefc6)

**Possible issues we could face**
---
Users submitting their email addresses are expecting to be contacted by us. We should watch out that we don't create false expectations. Based on historic data, around 10% of the feedback includes additional context (Q2: 237 total submissions, ca. 10% would include their email address -> 1-2 support requests per week). Agreed solution: let's try this out and reconsider if we can't handle the support requests.  @Siddhant-K-code volunteered to be the DRI to keep the overhead 🙏 ✨
Let's consider a special labeling for submissions that include an email address so they don't get overlooked in the Slack channel #feedback

**Implementation steps**
---

1. create mockup -> @chrifro 
2. technical implementation (update feedback widget, update Slack integration [I suggest a new channel just for docs-feedback]) -> 
3. DRI to handle support requests -> @Siddhant-K-code 

Would be curious to hear your thoughts on this as well once you are back from vacation @Cahllagerfeld 🙌

**Comment by chrifro** [comment]
|old design|new design|
|-|-|
|<img width="466" alt="Bildschirmfoto 2022-08-16 um 11 36 24" src="https://user-images.githubusercontent.com/46345125/184848090-847ed5bb-f2ae-4228-979d-d5b552fcb2e7.png">|<img width="471" alt="Bildschirmfoto 2022-08-16 um 11 40 54" src="https://user-images.githubusercontent.com/46345125/184848939-ee7547dd-c033-4099-97f4-c22e305d65e2.png">

Changes:
Next to the new email field, I adjusted the font size and some duplicate messaging.

@securitymirco would be great to get your feedback if the new footnote works fine or if it needs any adjustment. Thanks!

**Comment by securitymirco** [comment]
@chrifro thanks for flagging! Unfortunately we need to keep a reference to our Privacy Policy on contact forms. We could include a "For more information, see our Privacy Policy."

**Comment by chrifro** [comment]
Thanks, @securitymirco 🙏 I updated the new design above accordingly

**Comment by securitymirco** [comment]
Perfect, thanks @chrifro!

**Comment by Siddhant-K-code** [comment]
Design Looks Perfect 💯. Thanks @chrifro 

& thanks @securitymirco for checking all security concerns. I think we can move ahead with it.

@nisarhassan12 what do you think?

**Comment by nisarhassan12** [comment]
> @nisarhassan12 what do you think?

Thanks @Siddhant-K-code I have moved it to the scheduled column and will raise a Pr for it.

**Comment by chrifro** [comment]
This might also be something @Cahllagerfeld would like to get involved with as he is in charge of the structure of the docs [[1](https://www.notion.so/gitpod/Overhaul-Areas-of-Responsibilities-of-DCS-Team-Members-83679f3133c942c4b0f09c2fcefe90a9#e66e2e57f39843eaa1690045324cae32)]. FYI, Julian will be back from vacation on Monday. 👋

Mentioning this as I know that you have a lot of other things on your plate with a higher prioritization @nisarhassan12  e.g. #2401 #2540 🙏
