### ISSUE TITLE
Collecting Numbers when people send in Sales related Contact Forms

### ISSUE THREAD

**Issue by Thomas-Gitpod** [gitpod-io/website#2612]
On the sites where people are requesting sales reach out, it would be beneficial to collect phone numbers in order to get in touch more effectively.

These are the sites mentioned:

https://www.gitpod.io/enterprise-license
https://www.gitpod.io/contact/sales

**Comment by sky247-app** [comment]
yes, it is beneficial to add the contact number on your site, customer direct commnicate with you like  [sky247bet india](https://sky247bet.in/app/)

**Comment by Mrfaann** [comment]
yes it is beneficial to collect customer data[,](https://sky247bet.in/app/ ) you can send promotional messages on the number you have

**Comment by nisarhassan12** [comment]
@phimae I have addressed this in #2634 

A few questions:

- At the moment the field is marked as optional. Let me know if we want to make it required. 
- Do we want the number to go to the spreadsheet? Thanks

**Comment by Siddhant-K-code** [comment]
> * At the moment the field is marked as optional i.e the form can be submitted without it. Let me know if we want to make it required.

I think, it's good to have it optional.

**Comment by phimae** [comment]
Yes, we have to leave it optional. It should go to the spreadsheet as well. Can you ping me right when you create that column? I have to adjust the Zap otherwise it sends false data. Thanks @nisarhassan12 !

**Comment by nisarhassan12** [comment]
@phimae This column should go before the message column as well ?

**Comment by phimae** [comment]
Before or after, doesn't matter so much! Just ping me when you insert it pls
