### ISSUE TITLE
Change CTA Button on Gitpod vs Github Codespaces website

### ISSUE THREAD

**Issue by Thomas-Gitpod** [gitpod-io/website#2613]
Customers comparing Gitpod vs Codespaces are likely already very qualified and want to be in touch directly with our team.
Changing the Call to Action button on that website from "Try Now" to "Get a demo" button would improve conversion from that site.

https://www.gitpod.io/vs/github-codespaces

**Comment by phimae** [comment]
Let's put two buttons in there:

Try Now 
Get a Demo

**Comment by nisarhassan12** [comment]
@phimae I have addressed this in #2633 since the same section was rendered on other `/vs/*` pages like vs Coder, Local development and JetBrains page so I have updated it globally.
