### ISSUE TITLE
Use updated ready to code and open in Gitpod buttons

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#264]
Use the new buttons according to the [spec](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1%3A5253) 

<img width="193" alt="CleanShot 2021-04-07 at 14 26 25@2x" src="https://user-images.githubusercontent.com/22498066/113866137-3d638200-97ad-11eb-8a17-d705b38221a5.png">

<img width="177" alt="CleanShot 2021-04-07 at 14 26 01@2x" src="https://user-images.githubusercontent.com/22498066/113866106-32a8ed00-97ad-11eb-8c6c-e49ec1220ab8.png">

**Comment by nisarhassan12** [comment]
This issue now seems to be resolved. Please re-open if I missed something.
