### ISSUE TITLE
[Docs - Quickstart] - Requesting solidity

### ISSUE THREAD

**Issue by evronm** [gitpod-io/website#2686]
It's getting to be an increasingly used platform, and it would be great to be able to spin up e.g. ganache for testing, foundry, etc on gitpod.  Might well make me opt for a paid plan, and I'm sure I'm not alone.

**Comment by Siddhant-K-code** [comment]
Currently, there is no plan to create one for solidity. Will reopen the issue, once there is some update on this. 

Thanks for bringing this up 🧡
