### ISSUE TITLE
[Docs Feedback]: Add more limitations to the Self-Hosted Ref Archs

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2694]
### Page URL

https://www.gitpod.io/docs/self-hosted/latest/reference-architecture/single-cluster-ref-arch

### User feedback

There are certain limitations of the single cluster ref arch that are not well described, if at all. See internal [message](https://gitpod.slack.com/archives/C03UNNK1SKA/p1662480069085519).

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
