### ISSUE TITLE
Create new pages to integrate calendly's "get demo" integration

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2710]
**Context:**
We have a function to schedule a Demo ([https://www.gitpod.io/contact/sales?get-a-demo](https://www.gitpod.io/contact/sales?get-a-demo)), which, currently, deals with a lot of friction. It is not really easy to go from our website to talk to someone. This is why we decided to use a Calendly Routing Form to improve this process. The Routing form is created already: [https://calendly.com/d/d47-7n4-c63](https://calendly.com/d/d47-7n4-c63).

This can be embedded on the Gitpod website with the “Inline Embed” function in Calendly

**For this, we need to create two landing pages:**

1. `/get-demo` that has the demo booking form and potentially a little other useful information like link to screencasts
2. `/watch-demo` where people are routed to that should rather watch a demo, that shows the embedded video of the demo recording (it's basically a new screencast page with a little bit of extra information)

**Timeline:**
- create Mockup including review by @phimae until Tuesday EOD -> DRI: @chrifro 
- technical implementation including final review until Thursday -> DRI: @nisarhassan12 

View [Notion](https://www.notion.so/gitpod/Get-a-Demo-Function-Calendly-Routing-Form-6f87f17c564c418196372d90a49be5af) for more information

**Comment by chrifro** [comment]
**Update:**
I'd suggest the following URLs that are aligned with our naming convention: contact/get-demo and screencasts/demo

**Outstanding technical implementation:**
- create a new screencast page "screencasts/demo" (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6874%3A13304))
- add the new screencast preview to /screencasts
- add a new filter on /screencasts for "demo"
- create contact/get-demo (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6868%3A10871)) and embed this calendly snippet 
```
<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/d/d47-7n4-c63?primary_color=ffae33" style="min-width:320px;height:630px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->
```
- link all "get a demo" buttons to the new form 
- make sure the new pages are tracked for analytics

**Comment by nisarhassan12** [comment]
> make sure the new pages are tracked for analytics
@jakobhero I have made Pr #2732 for this. Can you have a look at that and help me make sure that we're covered with everything on the Analytics side?
