### ISSUE TITLE
[for/opensource]: post cards weird colors on dark mode

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2724]
![image](https://user-images.githubusercontent.com/46004116/189858441-0fea2110-960f-49d7-bf3d-53e15e2cef20.png)

**Comment by Siddhant-K-code** [comment]
Sometimes, it happened because CSS can't be applied to the whole. Try reloading the page once. It would work.

**Comment by nisarhassan12** [comment]
Thanks @Siddhant-K-code It is not because of some CSS does not load rather it's a conflict from what I have seen but I have not looked into it that deeply. 

For me, it does not seem to happen when I directly land on https://www.gitpod.io/for/opensource it only happens when I navigate here from another page.
