### ISSUE TITLE
[vs] GitPod vs Replit

### ISSUE THREAD

**Issue by hackermondev** [gitpod-io/website#2745]
I would like to request a [gitpod.io/vs/replit](https://www.gitpod.io/vs/github-codespaces) page.

> Replit, formerly Repl.it, is a San Francisco-based start-up and an online IDE. Replit being SaaS allows users to create online projects and write code in many supported languages. [Wikipedia](https://en.wikipedia.org/wiki/Replit)

It's very similar to Gitpod and some might consider it an alternative.
No hate on Replit, I just think a feature compare page would be nice, especially for people who can't decide their coding enviroment.

As for the actual coding of the page, I would happy to contribute.

**Comment by loujaybee** [comment]
Hey @hackermondev ! We really appreciate you opening this and caring about our website and content! 

I see where you're coming from, and can see how Replit looks similar to Gitpod on a feature level, as there are some similarities. However, we know from our customers and users that Gitpod serves a different purpose than Replit. Gitpod is used by professional teams and allows them to bring their own workflows, tools and preferred IDE's (VS Code, JetBrains, etc) and is a full platform to automate your developer environments bring productivity, security and collaboration not just to developers, but to entire teams and departments. I will close this issue for now, and we can re-open if the situation changes.

That said, we'd still encourage you to explore Gitpod and if you'd want to blog, or write about your experience using Gitpod or other products [we'd love to hear about it over in our Discord community](https://www.gitpod.io/chat)! We don't currently have a great way to host or share community content, but hopefully we will in future 🙏
