### ISSUE TITLE
Adding tooltip for social icons 

### ISSUE THREAD

**Issue by aashimawadhwa** [gitpod-io/website#2748]
### Describe your feature request

Adding tooltip to the social icons on the landing page.

### User impact

Tooltips provide: Context sensitive help and explanation right on the spot, Information readily when it is relevant

### Additional context

![Screenshot from 2022-09-16 23-24-04](https://user-images.githubusercontent.com/73706697/190704922-e0eab9df-b1ef-438c-b391-d8bfc007a4c8.png)

**Comment by aashimawadhwa** [comment]
@nisarhassan12  can you please review/approve/assign this issue.

**Comment by nisarhassan12** [comment]
Thanks for bringing this up. You meant adding a `title` attribute to the icons right? I think it'll be a good improvement, the titles could have values like `GitLab`, `GitHub` and `Bitbucket` feel free to make a PR if this is what you meant. 

If you didn't meant the above then feel free to discuss what your plan exactly is with @chrifro or if you have any other questions.

**Comment by aashimawadhwa** [comment]
> Thanks for bringing this up. You meant adding a `title` attribute to the icons right? I think it'll be a good improvement, the titles could have values like `GitLab`, `GitHub` and `Bitbucket` feel free to make a PR if this is what you meant.
> 
> If you didn't meant the above then feel free to discuss what your plan exactly is with @chrifro or if you have any other questions.

Yes I meant the same, adding tittle attributes to the icon , have no further doubts will start working on the issue. Thankyou so much.
