### ISSUE TITLE
Update config-ports page after new PortsView successful migration of most of users

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/website#2749]
Update [config-ports page](https://www.gitpod.io/docs/config-ports#specifying-port-names--descriptions) after new PortsView successful migration of most of users

See also https://github.com/gitpod-io/website/pull/2733#issuecomment-1248054412

**Comment by jeanp413** [comment]
We should remove old ports view and settings from code, keep configcat flag until next vscode realease this week
