### ISSUE TITLE
Utilize the Front API When Creating Tickets From the Contact Form(s)

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/website#2754]
This has been [discussed internally](https://gitpod.slack.com/archives/C01KGM9ETU6/p1660654817820749) and I have started a little work on this in [this branch](https://github.com/gitpod-io/website/tree/use-front-api-instead-of-sendgrid-on-contact-forms) however I am not familiar enough with the language used to build our website. So that we have a place to track and discuss this request I am creating this issue in GitHub.

Briefly, when a customer submits a ticket to the Contact, Sales and Support inboxes via the form(s) on our site, they should utilize the Front API and not SendGrid.

**Comment by jimmybrancaccio** [comment]
Sorry for the last minute request, may we enforce that the email entered into the email address field is value (basic validation is fine), and that there's something in the subject and description boxes? Quick mockup attached below.

![Untitled-2022-09-21-1234](https://user-images.githubusercontent.com/405585/191573501-7eed7f9f-fb0b-4da8-b43e-42ac67806082.png)

**Comment by Cahllagerfeld** [comment]
Todos:

- [ ] Add Subject Field for dynamic subject
- [ ] find a solution for line-breaks
- [ ] add switch for contact/support

**Comment by Mrfaann** [comment]
i can implement on the [brel](https://breldigital.com/)

**Comment by Cahllagerfeld** [comment]
Hey @Mrfaann, I already started working on this on a branch, but didn't open a PR just yet :( Feel free to pick another issue it you want to 🚀
