### ISSUE TITLE
[modal]: make sure it is at the top of everything else 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#2755]
![image](https://user-images.githubusercontent.com/46004116/191048770-396204ae-6758-4e08-97e2-521cafe14476.png)

**Comment by nisarhassan12** [comment]
Thanks feel free to make a Pr.

**Comment by aashimawadhwa** [comment]
> Thanks feel free to make a Pr.

Thankyou, I'll start working on it.

**Comment by Siddhant-K-code** [comment]
@aashimawadhwa are you still working on this?

**Comment by Asmit2952** [comment]
If there aren't any updates, I'll take this up and make a PR by tomorrow

**Comment by Asmit2952** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/81866614/195552825-acc7de7d-977d-47f7-ab63-521bb449166a.png)
I inspected the element and it seems like z-index is present and the modal is covering the entire screen. Can't figure out what's wrong though. @nisarhassan12

**Comment by Siddhant-K-code** [comment]
Hey, @Asmit2952 Nisar is not here in Gitpod anymore.

**Comment by chrifro** [comment]
Closing this issue as we removed the modal
