### ISSUE TITLE
/team page follow-up

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2784]
- [ ] we are distributed in 4 not 5 continents
- [ ] some images have a white border (looks fixed in [Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5550%3A8290))
<img width="469" alt="Bildschirmfoto 2022-09-23 um 20 02 23" src="https://user-images.githubusercontent.com/46345125/192029535-2c2a0991-c6d5-445a-9941-c1089729979e.png">
<img width="456" alt="Bildschirmfoto 2022-09-23 um 20 02 31" src="https://user-images.githubusercontent.com/46345125/192029539-f573f04e-6f98-48e6-95c1-360b135876a4.png">
 - [ ] the images load really slowly on slow internet. Are all images optimized? 
 
<img width="680" alt="Bildschirmfoto 2022-09-23 um 20 04 12" src="https://user-images.githubusercontent.com/46345125/192029819-4558a28d-268f-4f64-bfa2-11c4a94d83a5.png">

@Siddhant-K-code would this be something you could look into? 🙏

**Comment by Siddhant-K-code** [comment]
> the images load really slowly on slow internet. Are all images optimized?

yes, its flaky sometimes. can't do much on that. 


These images [[1](https://github.com/gitpod-io/website/blob/main/static/images/about/11.jpg)], [[2](https://github.com/gitpod-io/website/blob/main/static/images/about/3.jpg)] have white background for some reason (looks like a screenshot)

We need a image with transparent background

**Comment by chrifro** [comment]
>images [[1](https://github.com/gitpod-io/website/blob/main/static/images/about/11.jpg)], [[2](https://github.com/gitpod-io/website/blob/main/static/images/about/3.jpg)] have white background for some reason (looks like a screenshot)

Might have been a Figma framing issue. Looks resolved in Figma. Could you update the affected images? 🙏
