### ISSUE TITLE
Adjustments for Website Relaunch

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#280]
**General**

- [x] I'd like to try if the navigation works without the arrows(inspiration: https://circleci.com/) and have an adjusted drop-down-menu (see mockup)

- [x] please check the links, some are not correct, e.g. Choose your subscription should link to each table underneath

- [x] spelling mistakes (check for GitLab, GitHub, Trial, etc.)

- [x] let's change the button order in "Explore Gitpod": First "See Features" /"See Pricing" in blue and then "See Blog" in white

- [x] I think the border of the white button is too thin, can you try 2px? Can you make the buttons on the start screen a bit smaller?

**Home** 

- [x] Why Gitpod: If no hover is active, please display the initial graphic

- [x] Move Integration section up (also see updated text)

- [x] Align the first tweet with the headline, following tweets can scroll to the side like now

- [x] I updated the "Get Started" Section to make the form more recognizable. Does it work? What do you think?
<img width="964" alt="Bildschirmfoto 2019-12-05 um 12 09 45" src="https://user-images.githubusercontent.com/46345125/70230212-285d8580-1758-11ea-9fce-d8cd5750160e.png">

**Features**

- [x] could you add an arrow that scrolls with one and that can be clicked to get back to the overview?

@nisarhassan12 I also added a contact form and a 404 page to the mockup

**Comment by ChristinFrohne** [comment]
More Feedback: 
- [ ] Please add more tweets (e.g. https://twitter.com/LastZactionHero/status/1188910483698372608, https://twitter.com/CuriousNikhyl/status/1117141675745402881, https://twitter.com/YourETHGirl/status/1120015913024139265, https://twitter.com/hughdurkin/status/1102215129696010240, https://twitter.com/YourETHGirl/status/1120015913024139265, https://twitter.com/rocksetta/status/1134511186286768129)

- [ ] I like the new navigation, but can you make the drop-down without the animation? (see https://circleci.com/ for inspiration) and use the bubble-box?

- [ ] Graphic Ready-to-code: Can you make sure that the graphics are exactly aligned on each other? Currently, it's jumping around. 

- [ ] Vendor, Recruiting, Education: should have less spacing between the boxes, the quote and the image

- [ ] education: "are you a student" is too big. See mockup for the recent design

- [ ] add an icon for "community" to show that an external site will open up

- [ ] Buttons on the start screen and navigation are too big. Can you have less padding around? 

- [ ] documentation: please, give the edit-pen a gray filling and no shadow. Also, a little note on hover saying "edit" would help.

- [ ] documentation: the drop-down arrows don't make sense. I'm also not totally happy with the look. I'll see if I can come up with a better layout

**Comment by nisarhassan12** [comment]
![image](https://user-images.githubusercontent.com/46004116/70414101-e9427380-1a7a-11ea-9ab3-1f64172417fe.png)

@ChristinFrohne It is very hard to do so for all the different screen sizes as all the images have different heights and widths I can make the alignment right for one specific screen size. I think it would be possible to do so if you were to provide me with all the 3 of the same height & width & aspect-ratio. 

i.e for instance for the image "With Gitpod" have the other parts of default & ordinary invisible for ordinary have the gitpod logo invisible on the left just to make sure that they are all equal in size and aspect ratio. Does this make sense?

**Comment by svenefftinge** [comment]
I think we need to fix the images to be svgs. With that it should be easy to make them the same width and height.

**Comment by ChristinFrohne** [comment]
I made sure the width is always the same. Here are the .svg files
[icon-automated-setup.zip](https://github.com/gitpod-io/website/files/3939617/icon-automated-setup.zip)

**Comment by ChristinFrohne** [comment]
Nice! It's getting a lot better. Here some more Feedback: 

- [ ] Start Screen: spelling mistake "GitHub"

- [ ] breaking point should be after "providing prebuilt" so that "ready-to-code" stands in one line

- [ ] Updated image for Theia IDE 
[icon-IDE.svg.zip](https://github.com/gitpod-io/website/files/3939772/icon-IDE.svg.zip)

- [ ]  check the distances between headlines and content ("don't just take our word for it", "Free for open source", etc. have more spacing than other headlines) 

- [ ] Get started: the border is not needed for the URL bar. Maybe a gray font inside the white box makes it more visible that you can change the URL. What do you think? 

- [ ] Or select a Project: The boxes don't need a border

- [ ] Free for open source: white box should have exactly the same height as the screenshot. And minimal round corners (3px) as all boxes

- [ ] Explore Gitpod: Click on features: Can you link to the features immediately without the scrolling?

- [ ] Hover for features is missing

- [ ] Feature buttons: Add a break between "language support" 

- [ ] Use the same box style on "features" and "home screen". I prefer the border that you use on the feature page

- [ ] Features "share a running workspace": Have the image in the center

- [ ] Features: I updated the look for "Code Reviews" (see mockup)

- [ ] Blog Post: Add suggestions for further blog posts (see mockup)

- [ ] I guess "schedule a call" should link here:  to calendly (https://calendly.com/gitpod/onboarding?back=1&month=2019-12) Maybe we should create another event or update the messaging so it fits to enterprise, education, vendor and recruiting as well. @svenefftinge?

- [ ] "Contact Sales" should link to the contact form with a preset subject

- [ ] Contact form: Subject is missing and font color in the form should be the same

- [ ] Footer: "Career", "Community" and "report a bug" should have the icon that appears on hover that shows it'll be opened on an external site

- [ ] I updated the documentation layout a bit (see mockup)

**Comment by ChristinFrohne** [comment]
Additional Feedback from @jankeromnes (see #285):

- [ ] Delete "Explore Gitpod" section on feature, enterprise, vendor, recruiting and education page (currently too many buttons to choose from)

- [ ] Possibly delete "Are you a student?" -Education Page. Any thoughts? 

- [ ] Update layout of pricing tables: Delete "Features" and have only "White Labeling" and "Git Integration" in bold

- [ ] Have VS Code Extensions more visible in the table of Supported Programming Languages. And add refactoring to C++ and Rust. Does this help @jankeromnes?

<img width="668" alt="Bildschirmfoto 2019-12-09 um 15 52 27" src="https://user-images.githubusercontent.com/46345125/70445508-ead06380-1a9b-11ea-816b-7518967f381a.png">

- [ ] Add more information around each pricing table. (Mockup coming soon)
>Oh, there is a free trial. Cool! But what does the trial give me? And for how long? Where can I learn more about it? I have so many questions.

**Comment by nisarhassan12** [comment]
>     * [ ]  Updated image for Theia IDE
>       [icon-IDE.svg.zip](https://github.com/gitpod-io/website/files/3939772/icon-IDE.svg.zip)

@ChristinFrohne  The icon size is too big 10.3 MBs Can you make it smaller please?

**Comment by ChristinFrohne** [comment]
@nisarhassan12 That's because of the galaxy background. Shall I export it without the galaxy and you add the background manually afterwards?

**Comment by nisarhassan12** [comment]
@ChristinFrohne For now Thanks! for the PNG that you provided via Slack. I will work on adding the background to all the SVGs once I'm done with all the other things. I  will then need these images without background in SVG format.

**Comment by ChristinFrohne** [comment]
> Add more information around each pricing table. (Mockup coming soon)
>>Oh, there is a free trial. Cool! But what does the trial give me? And for how long? Where can I learn more about it? I have so many questions

Maybe it already helps to say "30 days free trial" and to link it to the documentation which explains more detailed how it's working. 
We can also add little question marks that open up on hover and explain each element

<img width="707" alt="Bildschirmfoto 2019-12-12 um 10 44 32" src="https://user-images.githubusercontent.com/46345125/70701299-6ca6d380-1ccc-11ea-8127-a23e6dd1c141.png">
