### ISSUE TITLE
Layout Pricing 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#281]
What do you think about this layout? The aim was to visualize that the Personal, Professional and Unlimited Plan is based on the open-source plan and to highlight more the free open-source plan. @svenefftinge @nisarhassan12 

![Pricing](https://user-images.githubusercontent.com/46345125/70317860-eb0ffb00-181e-11ea-91e3-28abb9860440.png)

**Comment by svenefftinge** [comment]
I like it! The open-source bit below the plans is not very visible though. But I think it is good enough, as we have the bigger box below. Maybe let's switch the open-source and student part <->.

Also I'd prefer the following text for the Open-Source box:

## Free for Open Source

Gitpod is free for up to 50 hours/month on any public repository. If you are a professional open-source developer and think you need more, let us know, by applying for unlimited hours. Your GitHub / GitLab track record should clearly show your regular open-source contributions.

**Comment by ChristinFrohne** [comment]
Great, I'll adjust the mockup accordingly
