### ISSUE TITLE
[Docs Feedback]: Code blocks not working in toggle tabs

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/website#2811]
### Page URL

https://www.gitpod.io/docs/sharing-and-collaboration

### User feedback

![image](https://user-images.githubusercontent.com/55068936/192930894-eb7b9eb4-2a59-4add-bd74-ee996f886b0d.png)

`gp snapshot` is not rendering as code

**Comment by axonasif** [comment]
Hi @Asmit2952, sure ✨

**Comment by Asmit2952** [comment]
Thank you so much!

**Comment by Asmit2952** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/81866614/195643122-f3c55c9a-997f-430c-bafc-0bd2ce509e68.png)
![Screenshot (56)](https://user-images.githubusercontent.com/81866614/195643136-cd290ebb-67a4-424a-9490-85ad72985e9c.png)
http://daringfireball.net/projects/markdown/syntax#html

So I read about markdown syntax a bit. It said that we can render markdown under html code blocks, but we have to separate the surrounding content by blank lines. This works! But adds an extra space under toggle tabs

**Comment by Asmit2952** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/81866614/195646242-a9854e48-0675-4bf5-8def-ad303e9d8c14.png)

But then, it will also cause problem here because we'll have to add extra spaces everywhere and use markdown syntax throughout for links

**Comment by Cahllagerfeld** [comment]
closed partially with #2887
