### ISSUE TITLE
Improve docs card style for mobile 

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2813]
|status quo| mockup|
|-|-|
|![Bildschirmfoto 2022-09-29 um 08 48 26](https://user-images.githubusercontent.com/46345125/192959754-f285a355-759a-4b91-a572-2e92bcec67e4.png)|![Bildschirmfoto 2022-09-29 um 08 54 38](https://user-images.githubusercontent.com/46345125/192960504-cda7ddb7-f856-4b17-8160-97815e66cfa2.png)

**Changes:**
- font line height

- spacing

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5151%3A5824)

**Comment by chrifro** [comment]
Much better, but it should follow the same style as other cards for mobile. Ideally, it's the same component. Currently, the padding is too big 

|this PR| usual card stlyle|
|-|-|
|<img width="404" alt="Bildschirmfoto 2022-10-05 um 10 02 34" src="https://user-images.githubusercontent.com/46345125/194011208-42bf07f6-69fb-417e-a2df-f28f6837886a.png">|<img width="399" alt="Bildschirmfoto 2022-10-05 um 10 03 12" src="https://user-images.githubusercontent.com/46345125/194011247-13b4fbb6-58da-4f50-a78e-e05ca0b89c7a.png">

cc @Cahllagerfeld

**Comment by Cahllagerfeld** [comment]
I made the adjustments 👍
