### ISSUE TITLE
Improve footer layout

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2816]
**Issue**
- the footer column for "Gitpod" is very long, has several line breaks and is unbalanced comparesd to the other columns
- 8 items start with "Gitpod" which makes it difficult to navigate to the correct place
- inconsistency in the capitalization

**Solution**
- [x]  "status" can be moved to the "developer" column
- [x]  links can be shortened e.g,. "for startups" instead of "Gitpod for startups"
- [x]  align capitalization (everything is in small letters except proper names and sentence starts)
- [x]  update the social icon for Discord 
- [x]  reduce the spacing between social icons 

**Note:** font sizes and line spacings can stay the same as they are already optimized for accessibility. 

See [component style](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=556%3A4656)

|status quo|new design|
|-|-|
|![Bildschirmfoto 2022-09-29 um 10 26 05](https://user-images.githubusercontent.com/46345125/192982842-e905a703-0942-4291-88ad-0bf94b2f43f0.png)|![Bildschirmfoto 2022-09-29 um 10 37 15](https://user-images.githubusercontent.com/46345125/192983117-b38650c9-9bb0-4a28-a06e-89c029bd2a81.png)

**Comment by Siddhant-K-code** [comment]
I think, Also following should be updated:

- `Report a bug` to **Legal**
- `Security` to **Legal**

**Comment by loujaybee** [comment]
Thanks for this 😍 - @chrifro I was thinking about this quite a lot, also. This is a really great 🛹 ! 

**Suggestion:** I believe `Self-Hosted` (capital on the `H`) is the preferred capitalisation (CC: @lucasvaltl)
**Suggestion:** **Customers** seems misplaced to me, and seems like it fits more with content under **Gitpod**?

---

**Thought (non-blocking):** 

We could break down the **developer** section based on product awareness, to make finding content a bit easier, taking inspiration from the [new docs sections](https://www.gitpod.io/docs/introduction):

* **Learn** => "Getting started", "Screencasts", "Blog", "Guides"
* **Help** => "Status", "Support", "Documentation", "Report a bug", "Community"

I also think the content under **Gitpod** is still quite long? And the goals of the content quite mixed, still? Would you be open to using more headers (e.g. not just at the top)? I had a quick/rough go editing in the console to show what I mean (**note:** would need "balancing" as columns are not weighted correctly, and the wording would need finalising). 

Something like...

|proposal|proposal v2|
|-|-|
|![Bildschirmfoto 2022-09-29 um 10 37 15](https://user-images.githubusercontent.com/46345125/192983117-b38650c9-9bb0-4a28-a06e-89c029bd2a81.png)|![image](https://user-images.githubusercontent.com/5528307/193540437-b4181645-2fd6-4d34-af6e-5a645b09be70.png)

**Comment by Siddhant-K-code** [comment]
@chrifro WDYT?

**Comment by chrifro** [comment]
Thanks for pitching in @loujaybee and great ideas! 🧡

I'd like to keep all columns on the same hierarchy for simplicity. Similar to how it's done on [jetbrains.com](https://www.jetbrains.com/). But we should be able to split it into 6 columns.

**What kind of columns do we want? and in which order?**
1. Gitpod: 
2. Compare: all /vs pages -> I like it a lot
3. Use cases: all /for -> makes sense
4. Resources: in alignment with the top navigation -> mostly replacing "Learn" WDYT @loujaybee 
5. Company:
6. Legal: -> this could also be moved below the list if necessary

**Note:**
- in order to have 6 columns we need to reduce the font size and increase the line height/spacing. We increased the footer text before to meet accessibility standards. I think with the extra line spacing, we should be fine. But this needs to be checked cc @Siddhant-K-code 

@Siddhant-K-code let's put the implementation on hold until we agreed on the structure

@loujaybee what do you think about this suggestion? (see [Figma](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2659%3A2849))
<img width="722" alt="Bildschirmfoto 2022-10-05 um 10 40 20" src="https://user-images.githubusercontent.com/46345125/194018537-69e87748-7240-4e63-a71b-de6a8ff823ce.png">

**Comment by chrifro** [comment]
As discussed during the last website sync, let's move forward with the last suggestion.  We can still continue iterating on the structure afterward but should overcomplicate things now.

First thing to figure out would be:
>in order to have 6 columns we need to reduce the font size and increase the line height/spacing. We increased the footer text before to meet accessibility standards. I think with the extra line spacing, we should be fine. But this needs to be checked

**Comment by chrifro** [comment]
You can find both mockups (desktop & mobile) [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=556%3A4656)

![Image](https://user-images.githubusercontent.com/46345125/196139080-70652c05-aa6d-447e-8107-e4cec6002a77.png)

cc @Siddhant-K-code

**Comment by Siddhant-K-code** [comment]
Ok, I will pick this up the next week 🙏🏼 

---

To Summarise, currently, we are going with [this layout & categories](https://github.com/gitpod-io/website/issues/2816#issuecomment-1268132434). @loujaybee Let us know if you have some thoughts about this.

**Comment by loujaybee** [comment]
> We can still continue iterating on the structure afterward but should overcomplicate things now.

💯 agree! 😍 - Looks great! It was already a great 🛹 — but now it's even a great 🛴 !

* **praise:** It does feel much easier to scan now to me. 
* **praise:** Columns and naming seems logical to me. 
* **praise:** I wouldn't have thought 6 columns could work, but seeing JetBrains page, it does seem to work. Dropping the columns responsively makes sense. Creative! ✨ 
* **Nit(non-blocking)**: I would move "_Getting Started_" **above** "_Documentation_" on the "Gitpod" section. **Justification:**  Whilst the _Documentation_ is likely to be overall more trafficked than _Getting Started_, I would prioritise the first-time user and really give the _Getting Started_ the priority spot. We will give some serious love to this page in future (it needs to be really, really great). Whilst the content is not there yet, we should build the foundation for when it is _really great_, so I'd move it to the top spot 😁 

> Resources: in alignment with the top navigation -> mostly replacing "Learn" WDYT @loujaybee

Looks good to me! As you say, we can make tweaks on top in follow-up work! 

P.S thanks a lot for being patient with the feedback! Really nice work! :)

**Comment by loujaybee** [comment]
CC: @atduarte, @jldec, @lucasvaltl, @mbrevoort - Sharing incase there is any product-side feedback. I don’t anticipate anything major from product, as it looks like a great skateboard to me (and we can always follow-up with more changes). 

That said, CC'ing you incase there is any last minute feedback from product. 

Otherwise, let’s :shipit: !
