### ISSUE TITLE
create overview page for webinars

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2822]

**Comment by chrifro** [comment]
We decided to create an overview page for all events happening at Gitpod including webinars and conferences.

The mockup is now ready for implementation and has already been under content review by Jacob. 

[See mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=7230%3A12039)



![Image](https://user-images.githubusercontent.com/46345125/196358686-4956b17b-4e57-476a-a800-3ea9b271410e.jpg)

**Comment by gtsiolis** [comment]
+1 for this!
