### ISSUE TITLE
[Docs Feedback]: Include `required upgrades` in SH Upgrade Guides and Release Notes

### ISSUE THREAD

**Issue by hellofromspark** [gitpod-io/website#2828]
### Page URL

https://www.gitpod.io/docs/configure/self-hosted/latest/upgrade-guides

### User feedback

https://www.gitpod.io/changelog/august-self-hosted-release

Required release versions should be highlighted in our upgrade guides and release notes to ensure users are aware of versions that cannot be skipped. 
Without visibility to those requirements, users upgrade plans (and success?) could be impacted.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
