### ISSUE TITLE
Document RubyMine and WebStorm

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/website#2832]
- Implement PR https://github.com/gitpod-io/gitpod/pull/13488

i.e. https://www.gitpod.io/docs/references/ides-and-editors/rubymine

**Comment by Siddhant-K-code** [comment]
TODO:

- [ ] Update [**Homepage**](https://www.gitpod.io/)

![image](https://user-images.githubusercontent.com/55068936/193514131-17a07400-b85a-4743-a48c-626e5abc83df.png)

- [ ] Update [**Rubymine Page**](https://www.gitpod.io/docs/references/ides-and-editors/rubymine)
- [ ] Update [**WebStorm Page**](https://www.gitpod.io/docs/references/ides-and-editors/webstorm)
- [ ] Update Lables `Soon` -> `Beta` on Menu Items:

**Comment by loujaybee** [comment]
Related to: 

- https://github.com/gitpod-io/website/pull/2847

**Comment by Mrfaann** [comment]
[brel](https://breldigital.com/), uses of rubymine.
