### ISSUE TITLE
New website looks slick! A few problems though...

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#285]
I just took a stroll through https://gitpod-staging.netlify.com/, looks great! Really good work everyone! 🎉

In general, the new website looks super slick and beautiful, and makes me want to learn more about Gitpod and maybe use it.

A also noticed a few problems:

---

<img width="1128" alt="Screenshot 2019-12-09 at 14 08 06" src="https://user-images.githubusercontent.com/599268/70439476-69270880-1a90-11ea-8379-aa27ac78930b.png">

Oops, the Enterprise version card looks broken. It should probably be bigger and have a different background, no?

---

<img width="973" alt="Screenshot 2019-12-09 at 14 11 37" src="https://user-images.githubusercontent.com/599268/70439394-354be300-1a90-11ea-8e5c-f3efa37d671e.png">

No refactorings in Rust or C++? That doesn't seem right. We should update this table.

Also, no mention of VS Code extensions here? Sad, because it's the only way to add support for new languages yourself.

---

<img width="1438" alt="Screenshot 2019-12-09 at 14 12 01" src="https://user-images.githubusercontent.com/599268/70439294-fddd3680-1a8f-11ea-9acb-63b7bd607207.png">

Wow, there is so much going on at the bottom of the page! Usually I expect a single, straightforward call-to-action that I can click without thinking.

Here there are multiple calls-to-action and too much text, so I just give up and navigate away.

---

<img width="663" alt="Screenshot 2019-12-09 at 14 14 38" src="https://user-images.githubusercontent.com/599268/70438895-1f89ee00-1a8f-11ea-82bf-08d8c0ae9e11.png">

Option 1: Sure! I want to schedule a call. 🙂 However, the `/schedule-call` page is a 404, so I give up.

Option 2: I'm a student! Wait, I can only tell my teacher, and that's it? No other action possible? That's boring, I give up.

---

<img width="1118" alt="Screenshot 2019-12-09 at 14 13 28" src="https://user-images.githubusercontent.com/599268/70438992-519b5000-1a8f-11ea-9919-17db8f8160e1.png">

So wait, aren't you just showing me the exact same pricing table in `/education`, `/recruiting` and `/vendor`? I feel cheated.

Oh, there is a free trial. Cool! But what does the trial give me? And for how long? Where can I learn more about it? I have so many questions.

Wait, "White Labeling" and "Features" have dedicated rows? And somehow none of the solutions have "White Labeling" in them? It's confusing to me that there are "holes" in the vertical lines of blue dots (like, there is no solution with all the available options active?)

I think we shouldn't try to make a hierarchy of options. Just list all the options without "parent categories" (also, don't put some options in bold and some not, that's confusing).

---

<img width="1109" alt="Screenshot 2019-12-09 at 14 15 25" src="https://user-images.githubusercontent.com/599268/70438849-0123f280-1a8f-11ea-8334-fa071dc01d51.png">

The docs menu looks cool! But what are the carets for? I tried clicking them to see if I could collapse or expand anything.

Maybe remove or replace the distracting carets?

---

<img width="1122" alt="Screenshot 2019-12-09 at 14 18 20" src="https://user-images.githubusercontent.com/599268/70438794-db96e900-1a8e-11ea-9d93-0db0b7da93ed.png">

With the discreet white buttons, I don't want to click on any of these. So I just scroll past this section.

Blue buttons would make me want to click.

**Comment by jankeromnes** [comment]
cc @ChristinFrohne @svenefftinge

**Comment by ChristinFrohne** [comment]
Cool! Thanks for the detailed feedback! 

>Oops, the Enterprise version card looks broken. It should probably be bigger and have a different background, no?

it's still work in progress on the pricing site

>Also, no mention of VS Code extensions here? Sad, because it's the only way to add support for new languages yourself

It's mentioned in bold in the text above. Do you think that's not enough? we could fill the rest of the table with gray dots and explain that blues means included by default and gray that it can be installed via VS Code extensions. What do you think? 

>Wow, there is so much going on at the bottom of the page! Usually I expect a single, straightforward call-to-action that I can click without thinking

Understandable. Maybe we can delete the "Explore Gitpod" Section here.

>Option 2: I'm a student! Wait, I can only tell my teacher, and that's it? No other action possible? That's boring, I give up.

Any idea which option would be helpful? Or maybe we can just delete the sentence?

>So wait, aren't you just showing me the exact same pricing table in /education, /recruiting and /vendor? I feel cheated

The table content has to be updated with the specific pricing

>Oh, there is a free trial. Cool! But what does the trial give me? And for how long? Where can I learn more about it? I have so many questions.

Good point, I'll see where we can put all these information

>Wait, "White Labeling" and "Features" have dedicated rows? And somehow none of the solutions have "White Labeling" in them? It's confusing to me that there are "holes" in the vertical lines of blue dots (like, there is no solution with all the available options active?)

It's supposed to be a headline. Maybe by deleting the columns for them it becomes more obvious

>I think we shouldn't try to make a hierarchy of options. Just list all the options without "parent categories" (also, don't put some options in bold and some not, that's confusing).

Nice catch only the headlines (White Labeling, Git Integration and Features) are supposed to be bold. Let's try if that helps :) 

>The docs menu looks cool! But what are the carets for? I tried clicking them to see if I could collapse or expand anything.

Thanks, work is still in progress there

>With the discreet white buttons, I don't want to click on any of these. So I just scroll past this section.

I tried it out, but blue buttons look way too noisy. Also, if they are blue they take all the attention from the first option, I feel.
