### ISSUE TITLE
Update YouTube embed for webinars/java-panel-discussion

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2853]
Issue:
Currently, the layout does not align with the standard layout for post-webinars (see [here](https://www.gitpod.io/webinars/java-remote-development))

|expected design| status quo|
|-|-|
|<img width="1423" alt="Bildschirmfoto 2022-10-05 um 08 29 39" src="https://user-images.githubusercontent.com/46345125/193995476-6d448450-c483-45b7-95bf-2b7bc94e9bb6.png">|<img width="1419" alt="Bildschirmfoto 2022-10-05 um 08 30 05" src="https://user-images.githubusercontent.com/46345125/193995494-b6b65965-dc83-4f62-a0ab-b66a44b8ca3e.png">|

**Required changes:**

- [ ] update preview image (see [Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=7201%3A11371))
- [ ] align card radius
- [ ] add card shadow
- [ ] alignment of the preview card (it's aligned with the label)
- [ ] add a headline to the preview card e.g. "watch the recording"
- [ ] change date to "past event" in the left description

Note: I like that the video plays directly and does not open in a pop-up. We can keep that. Same for the social share buttons :)

**Comment by chrifro** [comment]
@jacobparis is this something you could take care of as you created the initial version? 🙏

**Comment by jacobparis** [comment]
Yep I can take that, the other was a bit of a rush job just to get it live in time for the webinar

**Comment by jacobparis** [comment]
@chrifro How does this look for a popup free version of the expected design?

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/5633704/194094218-bd5aaa45-b5e6-45b8-a77e-8a56915df869.png">

**Comment by chrifro** [comment]
>@chrifro How does this look for a popup-free version of the expected design?

It's still very busy. Can we not use the preview image (similar to the JetBrains webinar) and change it to YouTube embed on click?
