### ISSUE TITLE
Revisit team plans section in pricing FAQ

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#2860]
### Page URL

https://www.gitpod.io/pricing

### User feedback

Re-pasting from https://github.com/gitpod-io/website/pull/2840#issuecomment-1268475165:

> @chrifro: Is this FAQ still correct? Should it be updated or removed?
> <img width="1185" alt="194078517-26ca8eed-6d40-41ba-a9a5-deda8bc520c5" src="https://user-images.githubusercontent.com/120486/194096176-6735b2ce-8511-497a-bd6c-eae93e3bde9f.png">

Cc @geropl @jldec because UBP (Usage-based Pricing)

**Comment by Mrfaann** [comment]
i['](https://wvw.mp3juice.blue/)ll check!.
