### ISSUE TITLE
[Docs Enhacement - New Feature]: Interactive Tutorials in the Docs

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/website#2863]
### Describe your feature request

We should look to create interactive tutorials that can allow users to learn the basics of Gitpod, but also some more advanced topics. A good example of this are [terraforms tutorials](https://developer.hashicorp.com/terraform/tutorials/gcp-get-started/infrastructure-as-code) that include a video for each section, and allow you then step through the tutorial. We could go as far as having check boxes to check of items that are done. 

### User impact

Improved UX when learning Gitpod: 
- It is more clear where one is at in the process, and how far they still have to go. 
- Clear focus - anything outside of the tutorial is hidden. This creates an increased sense of focus on the task at hand
- More consumable: this allows you to break a bigger task down into smaller steps, making them seem more achievable. This might even be useful for the [guides for our reference architectures.](https://www.gitpod.io/docs/configure/self-hosted/latest/reference-architecture/single-cluster-ref-arch)

### Additional context

- Assuming the UX is improved and "joyful", this could help with activating users in customer's installations or SaaS and thus increase the value a customer get's out of Gitpod.

**Comment by pawlean** [comment]
Closing this loop, I don’t think this should be included in this revamp skateboard [[1](https://www.notion.so/gitpod/Revamp-outdated-screencasts-and-tutorials-368f18b5b6314bd2b921810d46a93677)]. It feels like a bigger project that looks at perhaps big doc re-writes or even a dedicated “tutorial” section. I'll close this for now.
