### ISSUE TITLE
Website backdates security log and self-hosted release dates

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/website#2872]
We're in the process of releasing self-hosted 2022.09.0 and self-hosted upgrade guide; in the process we discovered that the website appears to backdating the document date by one day. (I'm in US/Pacific if this is timezone weirdness.)

[Affected pull request](https://github.com/gitpod-io/website/pull/2825)

![Backdated website link](https://user-images.githubusercontent.com/172194/194654398-b715dd6b-0fa7-44dc-b1ca-6577a5d3c21e.png)

![Associated source](https://user-images.githubusercontent.com/172194/194659993-03eda50c-663f-4207-a908-7f1648767920.png)

The really interesting thing is that when the page is refreshed, it'll briefly flash to the correct date (2022-10-07) but then be reverted to 2022.10.06.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
