### ISSUE TITLE
Dark theme scroll bar for code snippets

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#2881]
Enable the dark theme scroll bar for code snippets

<img width="813" alt="Bildschirmfoto 2022-10-11 um 12 13 01" src="https://user-images.githubusercontent.com/46345125/195063824-ec4587c5-9e51-4627-a4d4-440879752384.png">

cc @Siddhant-K-code because you took care of #2526 🙏

**Comment by Mrfaann** [comment]
i have no idea[.](https://getmusicplays.com/product/buy-audiomack-reups/)..but i do.

**Comment by Cahllagerfeld** [comment]
Just an assumption: 
maybe you can give the `pre`-element in the code-fence component a custom css class and use a similar selector like the one for the `ul` for example in `global.css`. Instead of `ul` you would target the custom css class that was applied to the `pre` tag 🤔

**Comment by Cahllagerfeld** [comment]
Another solution would be wildcarding the elements and use the dark-theme styles on all elements
