### ISSUE TITLE
[ref arch]: recommend a means to configure autoscaler `node_labels` for GKE by nodepool

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/website#2888]
### Page URL

https://www.gitpod.io/docs/configure/self-hosted/latest/reference-architecture/single-cluster-ref-arch#kubernetes-cluster

### User feedback

With the saas, we set the following metadata in the GCP instance template for the K3s cluster.

```
AUTOSCALER_ENV_VARS: os_distribution=ubuntu;os=linux;arch=amd64
NODE_LABELS: gitpod.io/registry-facade_ready_ns_default=true,gitpod.io/workload_workspace_regular=true,gitpod.io/workspace-class=standard,gitpod.io/ws-daemon_ready_ns_default=true
```

As nodes come online, they start out like:
- gitpod.io/registry-facade_ready_ns_default=false
- gitpod.io/workload_workspace_regular=true
- gitpod.io/workspace-class=standard
- gitpod.io/ws-daemon_ready_ns_default=false

And once `registry-facade` and `ws-daemon` are online, they mark the node's respective label from false to true using our [ready-probe-labeler](https://github.com/gitpod-io/gitpod/blob/fef62f3e9e778e404479f9062a0bfbc7ceee714b/dev/ready-probe-labeler/main.go#L43).

We're unsure how to set the related `NODE_LABELS` metadata for GKE clusters to influence the autoscaler. I've reached out to Google for support. 

Until we do this, some customers are adding `gitpod.io/registry-facade_ready_ns_default=false,gitpod.io/ws-daemon_ready_ns_default=false` when the node is created via their node pool configuration. This is problematic because it means the node will get marked as able to be scheduled to right away, resulting in regular and headless workspace failures until related services come online.

### Anything else

[Autoscaler docs](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler).

[The related autoscaler code for GCE that reads from metadata.](https://github.com/kubernetes/autoscaler/blob/ae9ed65639a927817336ada1505bac1d34cad831/cluster-autoscaler/cloudprovider/gce/templates.go#L394-L409)

`gcloud` CLI can specify metadata, but, `kube-env` is reserved for GKE...so...unclear how to set `node_labels` metadata within `kube-env`.

An excerpt from `gcloud container node-pools create --help`:
```
--metadata=KEY=VALUE,[KEY=VALUE,...]
        Compute Engine metadata to be made available to the guest operating
        system running on nodes within the node pool.

        Each metadata entry is a key/value pair separated by an equals sign.
        Metadata keys must be unique and less than 128 bytes in length. Values
        must be less than or equal to 32,768 bytes in length. The total size of
        all keys and values must be less than 512 KB. Multiple arguments can be
        passed to this flag. For example:

        --metadata key-1=value-1,key-2=value-2,key-3=value-3

        Additionally, the following keys are reserved for use by Kubernetes
        Engine:

        ◆ cluster-location
        ◆ cluster-name
        ◆ cluster-uid
        ◆ configure-sh
        ◆ enable-os-login
        ◆ gci-update-strategy
        ◆ gci-ensure-gke-docker
        ◆ instance-template
        ◆ kube-env
        ◆ startup-script
        ◆ user-data

        Google Kubernetes Engine sets the following keys by default:

        ◆ serial-port-logging-enable

        See also Compute Engine's documentation
        (https://cloud.google.com/compute/docs/storing-retrieving-metadata) on
        storing and retrieving instance metadata.
```

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rtxm)

**Comment by kylos101** [comment]
@aledbf is looking for some alternatives, too. 🤞

**Comment by aledbf** [comment]
Resource definition are not an option (same cluster-autoscaler issue) https://github.com/kubernetes/autoscaler/pull/5247

**Comment by kylos101** [comment]
:wave: @aledbf could we use [NoSchedule](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) taint? For example, change the [ready-probe-labeler](https://github.com/gitpod-io/gitpod/blob/main/dev/ready-probe-labeler/main.go) to `ready-probe-tainter`?! :rofl: 

For example, when `registry-facade` isn't ready:
`kubectl taint nodes workspace-node1 registry-facade=not-ready:NoSchedule`

And when ready:
`kubectl taint nodes workspace-node1 registry-facade:NoSchedule-`

**Comment by kylos101** [comment]
Socialized this issue with @aledbf , so long as customers running self-hosted do not scale to zero, this should not be an issue. I will spin up a preview environment built using GKE and do a load test to confirm.

**Comment by kylos101** [comment]
**Recommendation**: use the ref arch "as is". 

Do not scale node regular and headless node pools to zero, the autoscaler has a bug, and that'll cause you to intermittently be unable to scale-up.

Do not apply `gitpod.io/ws-daemon_ready_ns_gitpod` and `gitpod.io/registry-facade_ready_ns_gitpod` to your node pools. Instead, let our [ready-node-labeler](https://github.com/gitpod-io/gitpod/tree/main/dev/ready-probe-labeler) component apply them dynamically, after the node has joined your cluster and our required daemonsets have come online.

Using the ref arch "as is", we're able to prepare for a load test (do image builds), and then run a load test where 100 workspace start w/o issue, and nodes scale-up accordingly. 

Here's a [video of a load test showing node scale-up](https://www.loom.com/share/8cb5595073f94670b071ed142ceaee3a) (~6m).
