### ISSUE TITLE
[Docs Feedback]:  A proper guideline for opensource people to setup the repository.

### ISSUE THREAD

**Issue by ayushpaharia** [gitpod-io/website#2901]
### Page URL

https://github.com/gitpod-io/website/blob/main/README.md

### User feedback

A proper guideline for opensource people to setup the repository.
I tried to clone the website and the `yarn install` to `yarn dev` is failing.

I would appreciate if there was a guideline to set up the app and also a documentation of the `package.json` scripts

**Comment by Siddhant-K-code** [comment]
you can directly open it in Gitpod 😄 Also:

https://github.com/gitpod-io/website/blob/9b3038d192c8a4fb041b8c8a8a58b4becdac8059/.gitpod.yml#L20-L22
