### ISSUE TITLE
Epic: Sveltekit Upgrades

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#2907]
At the time of creating this issue, the current [version](https://www.npmjs.com/package/@sveltejs/kit) of the `@sveltejs/kit` package is at `516`.
This project is currently using `292`, which means that we are far behind the latest version.
When upgrading the version there are versions and things that require more work than others: 

## `1.0.0-next.306`

**Skipping this version because Symlinks aren't working here => 340**
[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next306)
- Introduction of named layouts
- Symlinks in the routes directory stop working because of a bug introduced in that version
- _comment_: Currently the docs are symlinked into the routes directory. Choices here would be removing the symlink and copying the docs inside the routes directly, or skipping to the version where this issue gets fixed

## `1.0.0-next.340`
- [x] #3075

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next340)
- Symlinks in the routes directory start working again

## `1.0.0-next.341`

- [x] #3152

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next341)
- We can't access the session object anymore in prerendered pages
- _comment_: We're having two choices here as well - Either remove the session object entirely (In a future version it will get removed entirely), or we just refactor it the way, it works with future versions until it gets removed entirely. I would vote for getting rid of it.

## `1.0.0-next.359`

- [x] #3208

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next359)
- Refactor `svelte.config.js` as the vite-config file gets intrduced

## `1.0.0-next.373`

- [x] #3281

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next373)
- Migration to Vite 3

## `1.0.0-next.395`

- [ ] #3282

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next395)
- Introduction of `$env`-modules

## `1.0.0-next.406`

- [ ] #3283

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next406)
- Refactoring of the entire routing and load-system
- _comment_: Potentially the biggest change. There's a helper script, which does parts of the heavy lifting, but we will probably end up with a ton of manual tasks still.

## `1.0.0-next.415`

- [ ] #3284

[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next415)
- session object gets removed entirely

## Additional notes

- Besides these changes, there will be other things affecting us, the mentioned ones should just point out the ones, that require the biggest adjustments to the app => **As we are having a lot of breaking changes we need to be extra careful when merging the corresponding PRs**
- After upgrading the versions, we also need to double-check and make sure that the `adapter-netlify` [[1](https://www.npmjs.com/package/@sveltejs/adapter-netlify)] stays compatible with the sveltekit version.

**Comment by ghostdevv** [comment]
I think the biggest pain point might be the outstanding PRs that would all get merge conflicts, not sure what the best thing to do there is. Hopefully a lot of it *should* be straightforward especially considering it seems to be a largely static website and there are some tests

**Comment by Siddhant-K-code** [comment]
> I think the biggest pain point might be the outstanding PRs

I think first we should create a draft PR (as planning for changes) then we can call for a deployment freeze before any PR with more extensive changes/ new features or landing pages. 

Like we did in #2587
