### ISSUE TITLE
Epic: V0.1 Documentation for Public API

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2911]
**In scope:** 
* Client library documentation
* Resource information documentation
* Authentication documentation

**Out of scope:**
* Introduction of additional documentation tooling

Relates to: 
- https://github.com/gitpod-io/website/issues/2911

**Comment by loujaybee** [comment]
Would be good to get a first iteration of this shipped by **Monday the 31st**. 

No expectations on scope, but at least a draft PR with the current API as it is currently so that we can get feedback. 🙏

**Comment by Mrfaann** [comment]
why you don't expect [mp3 juice](https://mp3juice.store/) scope

**Comment by loujaybee** [comment]
https://www.gitpod.io/docs/references/gitpod-public-api
