### ISSUE TITLE
Bug : card background-image disappears  

### ISSUE THREAD

**Issue by pavandeveloperr** [gitpod-io/website#2963]
### Page URL

https://www.gitpod.io/about

### Description

There is a minor bug in about section, where the card background-image disappears on maximizing the screen and appears upon minimizing. 

Above clip describes the bug 👇🏼 

[Screen Recording - Made with FlexClip (1).webm](https://user-images.githubusercontent.com/63870995/198536246-f47246c1-e1b0-4ddf-bd5b-0ad6b95c99dd.webm)

**Comment by Siddhant-K-code** [comment]
👋🏽 Unable to reproduce this bug except "Deleting" that particular image element. 


https://user-images.githubusercontent.com/55068936/214119891-3afa15bc-274f-4ace-b73e-b0e0f5811a68.mov



Feel free to re-open the issue, if you encountered this again.
