### ISSUE TITLE
Centralize pricing information

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#297]
There are a number of places where we display pricing as `{isEurope() ? "€35" : "$39"}`. When the time is right, let's centralize all pricing to make sure we stay consistent across the site.

**Comment by mikenikles** [comment]
@nisarhassan12 will this issue be closed as part of #1329?

**Comment by nisarhassan12** [comment]
Thanks, Mike for bringing this up. It looks like you have started your vacation and I had a few things to discuss about it. I have a few things to discuss about it i.e I think it would be ideal to have the pricing info derived out of the product may be through a GrahpQL endpoint from which we can fetch the data from at build time. Let's discuss this when you're back from your vacation.

**Comment by mikenikles** [comment]
I checked in with the team ([internal link](https://gitpod.slack.com/archives/C020VCB0U5A/p1657603381458379)) to find the most up-to-date information we can use to close this issue.

**Comment by mikenikles** [comment]
Closing based on internal communication.
