### ISSUE TITLE
Document workspace class option in project settings

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/website#2973]
### Description

Document that the workspace class can be specified in project settings [Context](https://github.com/gitpod-io/gitpod/issues/10963)

**Comment by kylos101** [comment]
:wave: @Furisto I recommend closing this issue as won't fix, and remove from our project, too.

**Comment by kylos101** [comment]
Reassigning to @svenefftinge and the WebApp project, refer to [this](https://github.com/gitpod-io/gitpod/issues/10963#issuecomment-1309427737) for context.

**Comment by kylos101** [comment]
:wave: @atduarte for awareness, this is on the WebApp project now
