### ISSUE TITLE
Date on Changelog flashes on page load

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2978]
### Page URL

https://gitpod.io/changelog

### Description

The date field in the changelog reformats on page load. 

https://user-images.githubusercontent.com/5528307/199049790-e31b25f6-f044-4d3e-9df4-84b8d33ab137.mov

**Comment by Siddhant-K-code** [comment]
> That’s not a bug I guess, it gets converted to your date format, but this happens onMount, as it can’t be done server-side. We should get rid of it though

[_Internal Conversation_](https://gitpod.slack.com/archives/C01KGM9ETU6/p1662089356908219)

**Comment by Cahllagerfeld** [comment]
This is caused by a function that converts the given Date to your local one. I had a discussion with Mike back then about removing this, and only displaying the date in one format. What do you think about this?

**Comment by Siddhant-K-code** [comment]
> only displaying the date in one format. What do you think about this?
I think, displaying the standard format will be a good thing, because currently, it feels weird when it changes again after rendering once.
