### ISSUE TITLE
Undefined Variable in Creating Kubernetes Cluster Example for GCP PoV Ref Arch

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/website#2980]
### Page URL

https://www.gitpod.io/docs/configure/self-hosted/latest/reference-architecture/proof-of-value#kubernetes-cluster

### Description

In our reference architecture within the Kubernetes Cluster section on the Google Cloud Platform (GCP) tab we have an example command that creates a cluster in GCP. In that command we reference a variable `${ZONE}` however I cannot seem to find out where this is being set. I wonder if it's just extraneous?

```shell
CLUSTER_NAME=gitpod
REGION=us-central1-b
GKE_VERSION=1.21.12

gcloud container clusters \
    create "${CLUSTER_NAME}" \
    --disk-type="pd-ssd" \
    --disk-size="100GB" \
    --image-type="UBUNTU_CONTAINERD" \
    --machine-type="n2d-standard-16" \
    --cluster-version="${GKE_VERSION}" \
    --zone="${ZONE}" \
    --service-account "${GKE_SA_EMAIL}" \
    --num-nodes=1 \
    --no-enable-basic-auth \
    --enable-autoscaling \
    --enable-autorepair \
    --no-enable-autoupgrade \
    --enable-ip-alias \
    --enable-network-policy \
    --create-subnetwork name="gitpod-${CLUSTER_NAME}" \
    --metadata=disable-legacy-endpoints=true \
    --scopes="gke-default,https://www.googleapis.com/auth/ndev.clouddns.readwrite" \
    --node-labels="gitpod.io/workload_meta=true,gitpod.io/workload_ide=true,gitpod.io/workload_workspace_services=true,gitpod.io/workload_workspace_regular=true,gitpod.io/workload_workspace_headless=true" \
    --min-nodes=1 \
    --max-nodes=50 \
    --addons=HorizontalPodAutoscaling,NodeLocalDNS,NetworkPolicy
```

Also right below the above command we reference `${ZONE}` again in another command:

```shell
gcloud container clusters get-credentials --zone="${ZONE}" "${CLUSTER_NAME}"
```

It's worth noting that the cluster creation command ran without issue and a cluster was created, it wasn't until that second command where I realized that `${ZONE}` hadn't been set. I double checked the document to make sure too. Unfortunately my command history is gone so I can't remember if I set the zone manually or just removed it from the command.

**Comment by lucasvaltl** [comment]
@adrienthebo This seems like an error, and `"${ZONE}"` should be replaced by `"${REGION}"? If that is the case I am happy to make the changes.

**Comment by Siddhant-K-code** [comment]
With Announcement of [Dedicated](https://www.gitpod.io/blog/introducing-gitpod-dedicated) 📢 
This issue is not relevant anymore.
