### ISSUE TITLE
Pay-as-you-go Pricing page

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#2988]
As we start to make [usage-based billing](https://www.gitpod.io/docs/configure/billing/usage-based-billing) available for early access users it would be helpful to point those users to the new pricing details.

The new usage-based pricing page should live at (or be reachable from) https://www.gitpod.io/pricing

**Comment by jldec** [comment]
[Draft](https://www.notion.so/gitpod/Draft-Pricing-page-for-website-8a4c2e8910ca4db09846bdd36fb36ea8) (internal)

**Comment by jldec** [comment]
Related to https://github.com/gitpod-io/gitpod/issues/14475 and https://github.com/gitpod-io/website/issues/3004

**Comment by jldec** [comment]
Updated [Draft](https://www.notion.so/gitpod/Draft-Pricing-page-for-website-8a4c2e8910ca4db09846bdd36fb36ea8) (internal)

**Comment by Siddhant-K-code** [comment]
@jldec I think, it is done 😄 

[`/pricing`](https://www.gitpod.io/pricing)

**Comment by jldec** [comment]
It is done indeed! Thanks @Siddhant-K-code 🙏

**Comment by Siddhant-K-code** [comment]
🥳
