### ISSUE TITLE
Remove custom breakpoints in favor of tailwind ones

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#2998]
### Page URL

layout, navigation

### Description

In some layout and navigation components we're still using custom breakpoints, e.g `max-width: 1189px` or `min-width: 1190px`. We should get rid of the custom ones and replace them with tailwind ones. 
Tailwind uses these 
```js
module.exports = {
  theme: {
    screens: {
      'sm': '640px',
      // => @media (min-width: 640px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1280px',
      // => @media (min-width: 1280px) { ... }

      '2xl': '1536px',
      // => @media (min-width: 1536px) { ... }
    }
  }
}
```
At the time writing I'd suggest using the `lg` breakpoint as its the closest to the current ones. We may want to recheck that, and test carefully as it adjusts the entire page-layout.

**Comment by asharonbaltazar** [comment]
Are any of the issues open to the public?
