### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#3]
This is the current layout for the features

![features new](https://user-images.githubusercontent.com/46345125/53945835-cf769900-40c2-11e9-81d8-cc59d826449a.jpg)

**Comment by jankeromnes** [comment]
Thanks a lot for this concept! I really like it, it looks great. 👍 

A few personal thoughts:

- `What Do You Get?` and `ARE YOU READY FOR FRICTIONLESS CODING?` feel like I'm being shouted at. I think we should make the call outs more "discreet".
  - For example, all lowercase, except the first letter? Or [Kapitälchen](https://de.wikipedia.org/wiki/Kapit%C3%A4lchen). 🙂 
- What is the purpose of the first line with just the feature names?
  - If it's some sort of tabs bar, how does it work?
  - If it's just there to list all features, I think users can already scroll vertically to look at feature titles, so maybe we don't need a "summary" type thing.
- I generally like feature pages that alternate when the visual is left or right, but that seems complicated to achieve with the awesome constellation graph, so I can live without alternation. 👍 
- Should all the visuals be static screenshots, or can they also be animations like on www.theia-ide.org? (Maybe less pixellated though. 😝)

I'm happy to start implementing that. 👍

**Comment by ChristinFrohne** [comment]
> * `What Do You Get?` and `ARE YOU READY FOR FRICTIONLESS CODING?` feel like I'm being shouted at. I think we should make the call outs more "discreet".
> 
>   * For example, all lowercase, except the first letter? Or [Kapitälchen](https://de.wikipedia.org/wiki/Kapit%C3%A4lchen). 🙂
- I like Kapitälchen, Just just don't have the style for this font on my laptop. Does it exist?


> * What is the purpose of the first line with just the feature names?
- to give the user an overview about everything Gitpod provides . Each of them shall link to the section where they are explained more detailed. And it makes the page visually more interesting :)


> * I generally like feature pages that alternate when the visual is left or right, but that seems complicated to achieve with the awesome constellation graph, so I can live without alternation. 👍
- I agree. I tried that but I couldn't come up with a nice solution. 


> * Should all the visuals be static screenshots, or can they also be animations like on [www.theia-ide.org](http://www.theia-ide.org)? (Maybe less pixellated though. 😝)
- totally. the current images are just screenshots from the existing website

**Comment by jankeromnes** [comment]
> I like Kapitälchen, Just just don't have the style for this font on my laptop. Does it exist?

Yes, it can be achieved with the CSS rule `font-variant: small-caps`, see [this page](https://css-tricks.com/almanac/properties/f/font-variant/) for examples.

**Comment by ChristinFrohne** [comment]
> Yes, it can be achieved with the CSS rule `font-variant: small-caps`, see [this page](https://css-tricks.com/almanac/properties/f/font-variant/) for examples.

awesome, let's try that :)

**Comment by ChristinFrohne** [comment]
Latest layout (supported languages were missing in the overview)
![features new](https://user-images.githubusercontent.com/46345125/53962644-e67db100-40eb-11e9-8b12-4ca09df4acb1.jpg)

**Comment by ChristinFrohne** [comment]
New layout with a git-path
![Features – git](https://user-images.githubusercontent.com/46345125/54436350-a85b3f80-4732-11e9-9397-249b0a1202f1.jpg)

**Comment by svenefftinge** [comment]
I'm updating the features according to latest layout changes.

**Comment by svenefftinge** [comment]
done
