### ISSUE TITLE
Pricing page is unclear about whether the hours in plans are addititve (they are not)

### ISSUE THREAD

**Issue by jldec** [gitpod-io/website#3005]
The way the [website pricing page](https://www.gitpod.io/pricing) page is laid out, may lead to the misunderstanding that the hours in the Personal plans are additive to the hours in the Free plan.

Specifically, the words “All in free” in the Personal tile, suggest that if you purchase the personal plan, you get 100 + 50 = 150 hours.

cc: @gtsiolis 

<img width="1215" alt="Screenshot 2022-11-07 at 18 09 05" src="https://user-images.githubusercontent.com/849592/200383484-a0a9653a-d087-4a01-abbf-0337132ba5e7.png">

**Comment by gtsiolis** [comment]
Looping in @chrifro in case there's an MVC we could ship here or the website until usage-based pricing ships.

| Dashboard | Website |
|-|-|
| <img width="919" alt="Screenshot 2022-11-08 at 7 22 15 PM" src="https://user-images.githubusercontent.com/120486/200633238-f624498b-3a2e-4478-a16f-fc03a7e9706d.png"> | <img width="1338" alt="Screenshot 2022-11-08 at 7 22 25 PM" src="https://user-images.githubusercontent.com/120486/200633259-2bf485b8-58fd-4825-bfd2-c43ebb25590c.png"> |

**Comment by chrifro** [comment]
Did we ever have a case of users being confused about having "just" 100h? Seems like an edge case. Not sure if it's worth investing time in it when we have new pricing coming up anyway. 

What we could do as a skateboard:
- replace "all in Free" by listing the 3 features separately 

Note: With the update for the usage-based pricing, I'd be in favor of aligning the pricing cards in the dashboard and on the website more, to make it obvious that they are identical. Currently, it's easy to get confused.
