### ISSUE TITLE
Document workaround to share/sync JetBrains settings

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/website#3029]
With the deployment of https://github.com/gitpod-io/gitpod/pull/14566 we will be able to provide options to the IDE before the backend-plugin starts, this enables certain use-cases where the IDE settings where lost at each workspace start.

Disclaimer: the solution is a workaround, asking the user to "export" the settings manually created, save those somewhere (docker image, git repo, etc) and when the workspace starts Gitpod will search in those locatiosn if the options files are provided, they will be copied in the right path.

Supported paths:

```
fmt.Sprintf("%s/.gitpod/jetbrains/options", userHomeDir),
fmt.Sprintf("%s/.gitpod/jetbrains/%s/options", userHomeDir, launchCtx.alias),
fmt.Sprintf("%s/.gitpod/jetbrains/options", launchCtx.projectDir),
fmt.Sprintf("%s/.gitpod/jetbrains/%s/options", launchCtx.projectDir, launchCtx.alias),
```

In the docs, we need to make sure to ask for feedback, and link to https://github.com/gitpod-io/gitpod/issues/6576 as a container for the feedback.

**Comment by akosyakov** [comment]
I've updated https://github.com/gitpod-io/gitpod/pull/14566 description and release notes with detailed description. I guess we can reuse it for docs.
