### ISSUE TITLE
[docs] code section overflows

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/website#303]
text which is inside <code><code/> element is overflowing it's container on docs/31_context_urls/ .

**Comment by svenefftinge** [comment]
Works nicely for me. 

![scroll-code](https://user-images.githubusercontent.com/372735/70788102-70039300-1d90-11ea-8e97-6606c12bd3b0.gif)

@nisarhassan12 am I missing something?

**Comment by nisarhassan12** [comment]
Two more lines are still overflowing at 430px.

![image](https://user-images.githubusercontent.com/46004116/70793550-5b89bf80-1dbd-11ea-9f86-a7aa33216e73.png)
![image](https://user-images.githubusercontent.com/46004116/70793580-6c3a3580-1dbd-11ea-84ac-132f0297fa45.png)

**Comment by nisarhassan12** [comment]
I'm going to do a new PR to fix this.
