### ISSUE TITLE
Update footer with additional links/resources

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3035]
**SOC 2 logo**
Consider if we want to include the SOC 2 logo in our footer. This might help to build trust. Other examples: [Orca](https://orca.security/)

**developerexperience.us**
Link to developerexperience.us to build a stronger connection between both pages 

**Link to community office hour recordings**
Not sure if that's needed. We will soon link to the YouTube playlist from /community

See[ internal discussion ](https://gitpod.slack.com/archives/C01LDA27WJC/p1667213329012379)

**Comment by chrifro** [comment]
Suggested solution:
|status quo|new|
|-|-|
|<img width="1154" alt="Bildschirmfoto 2022-11-25 um 12 05 33" src="https://user-images.githubusercontent.com/46345125/203972389-c271698f-2cb5-48ff-91c2-a256efdf1c8f.png">|<img width="1151" alt="Bildschirmfoto 2022-11-25 um 12 05 40" src="https://user-images.githubusercontent.com/46345125/203972435-bc4e7cbd-5ccc-435c-abe6-9bd99674705d.png">with SOC logo <img width="1152" alt="Bildschirmfoto 2022-11-25 um 12 05 52" src="https://user-images.githubusercontent.com/46345125/203972466-a0220a06-2111-4924-b315-8e2580a10eb6.png"> without SOC logo



**Changes:**
- (add SOC logo)
- add devX community logo
- remove Gitpod Logo
- add "Developed with Gitpod" (link to website repo opened in Gitpod)

**To be resolved:**
- I'm uncertain if we want to have the SOC logo this prominent in the footer (it was suggested by Mirco). WDYT @MichaelAring 
- What do you think about the "developed with Gitpod" link @MichaelAring ? I got inspired by [JetBrains' footer
](https://www.jetbrains.com/)

**Comment by MichaelAring** [comment]
Thanks @chrifro! 

I agree with all proposed changes except for adding "developed with Gitpod". I think it's a neat idea, but the footer is already very busy and this does not add a ton of immediate user value. I would prefer to keep it a bit cleaner and not add a text line below the orange logos. Or am I missing something?

The prominent SOC 2 badge is a great idea.

**Comment by chrifro** [comment]
**Agreed changes:**

- add SOC logo
- add devX community logo
- remove Gitpod Logo before Copyright

See[ component library ](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=556%3A4656&t=SSJR5XoyMG0pE3yN-1)
