### ISSUE TITLE
Gitpod vs Codespaces adjustments

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#305]
**graphic is missing round corners**
the first graphic has no rounded corners while the next graphic uses round corners. The first graphic should be aligned with that. 
<img width="632" alt="Bildschirmfoto 2021-04-08 um 08 05 48" src="https://user-images.githubusercontent.com/46345125/113976382-5ae22b80-9841-11eb-95f6-8dbcbe46cca9.png">

**spacing adjustments**
The second section has a different spacing (headline to text) than the first section. Let's move the text further up to align it with the "ready in a flash" section
<img width="1313" alt="Bildschirmfoto 2021-04-08 um 08 08 00" src="https://user-images.githubusercontent.com/46345125/113976699-c2987680-9841-11eb-8ff4-8c30494c3a32.png">

**Comment by nisarhassan12** [comment]
@ChristinFrohne In the past we created these graphics with code but now they are images. You have to edit the border in Figma and then I can change it on the site.

**Comment by ChristinFrohne** [comment]
@nisarhassan12 It's just about adding the same 8px border radius to the bar. I think you should have access to do that as well, don't you?
Anyway, I updated the graphic in Figma -Project Kumquat-Website 🙂
