### ISSUE TITLE
[SEO] Update meta description

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3062]
Current description (too long and outdated) (194 characters):

> Gitpod is an open-source developer platform for remote development. Accelerate your teams developer experience, remote collaboration and security - to ship new products faster and more securely.

New suggestion based on internal discussions [[1](https://www.notion.so/gitpod/Brand-Messaging-1d95c5c64061486f98521c85423c44a1)] (154 characters):

> Gitpod is an open-source development platform for teams to efficiently and securely develop software together. Ship new products faster and more securely.

**Requirements:**
recommend meta descriptions between 50 and 160 characters

cc @MichaelAring

**Comment by MichaelAring** [comment]
Updated suggestion that uses our keywords (158 chars):

> Gitpod is a cloud development environment for teams to efficiently and securely develop software. Improve your team's developer experience by coding in a CDE.
