### ISSUE TITLE
[SEO] homepage optimizations for mobile

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3064]
**mobile optimization**

- The file size of the HTML document is very large (1243.3 kB). Can we reduce it? := ❌ (#3108)
- [x] replace .png files with webp := Resolved in #3106
<img width="480" alt="Bildschirmfoto 2022-11-23 um 14 19 04" src="https://user-images.githubusercontent.com/46345125/203556717-c7b1b728-4d2d-4ac4-842f-026cc175da4a.png">

- [x] change image dimensions for mobile to reduce page load
 
<img width="911" alt="Bildschirmfoto 2022-11-23 um 14 20 28" src="https://user-images.githubusercontent.com/46345125/203556965-4c57eec3-1208-43f0-b83c-a2eaf376d0a4.png">

- [ ] consider using passive listeners to improve scrolling performance [[1](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr)] -> research required

- [x] add `width` and `height` settings to images
<img width="895" alt="Bildschirmfoto 2022-11-23 um 14 24 43" src="https://user-images.githubusercontent.com/46345125/203557860-843216b9-2344-4f5a-a401-e98f89909d3b.png">

Sources: https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.gitpod.io%2F&form_factor=mobile
<img width="489" alt="Bildschirmfoto 2022-11-23 um 14 25 54" src="https://user-images.githubusercontent.com/46345125/203558116-0fc81d0d-1fb4-4efd-80eb-f03d2699efb0.png">

**Comment by Siddhant-K-code** [comment]
> The file size of the HTML document is very large (1243.3 kB). Can we reduce it?

Tried in #3108 doesn't seems to be work

**Comment by Siddhant-K-code** [comment]
> - [ ] change image dimensions for mobile to reduce page load
>  
> <img width="911" alt="Bildschirmfoto 2022-11-23 um 14 20 28" src="https://user-images.githubusercontent.com/46345125/203556965-4c57eec3-1208-43f0-b83c-a2eaf376d0a4.png">


_I don't think, we should compress further, as **it would reduce the image quality**._
**💡  One potential solution for having low-res images for small screens.**

---

Current State (`~400kb` -> `~95kb`): 

![image](https://user-images.githubusercontent.com/55068936/211294440-119c1098-1da7-4ffe-a144-95e26c70c56a.png)

**Comment by Siddhant-K-code** [comment]
> - [ ] add `width` and `height` settings to images
> <img width="895" alt="Bildschirmfoto 2022-11-23 um 14 24 43" src="https://user-images.githubusercontent.com/46345125/203557860-843216b9-2344-4f5a-a401-e98f89909d3b.png">

🚀  We've a lot, recently & it would be resolved when we do the IDE changes on homepage: 
![image](https://user-images.githubusercontent.com/55068936/211295286-a28af748-04fb-4d90-a3f5-ec33ca814783.png)

**Comment by Siddhant-K-code** [comment]
> Sources: https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.gitpod.io%2F&form_factor=mobile
> <img width="489" alt="Bildschirmfoto 2022-11-23 um 14 25 54" src="https://user-images.githubusercontent.com/46345125/203558116-0fc81d0d-1fb4-4efd-80eb-f03d2699efb0.png">
> 
> 

Current State of Overall Mobile Performance:

![image](https://user-images.githubusercontent.com/55068936/211295741-efc6fddb-a660-47f8-96ae-a7c866bc269a.png)

**Comment by Siddhant-K-code** [comment]
> consider using passive listeners to improve scrolling performance [[1](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr)] -> research required

We could ignore this alert. `preventDefault()` is useful. See [official docs](https://svelte.dev/tutorial/event-modifiers). wdyt @Cahllagerfeld?

![image](https://user-images.githubusercontent.com/55068936/211299495-35adf8c0-fbbc-47c8-9874-4f8cee3f38f0.png)
