### ISSUE TITLE
[docs]  Prebuilt Workspaces buttons in the table don't look good 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#308]
Here in docs, https://gitpod-staging.netlify.com/docs/46_prebuilds/ 
the buttons in the table don't look good maybe we should update them ?

![image](https://user-images.githubusercontent.com/46004116/70798158-0b642a80-1dc8-11ea-95dd-120a759fe278.png)

**Comment by svenefftinge** [comment]
That is a Firefox-specific issue.

**Comment by ChristinFrohne** [comment]
I couldn't reproduce the issue, so I'm guessing it has been fixed.
