### ISSUE TITLE
update numbers in "used by" section

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3094]
Gitpod is used by +750k developers. We need to update all old counts (+500k) accordingly. 
e.g. 
<img width="1284" alt="Bildschirmfoto 2022-12-02 um 15 22 12" src="https://user-images.githubusercontent.com/46345125/205314095-7ff93651-9240-47bd-98b3-2739013ed3d7.png">
<img width="1457" alt="Bildschirmfoto 2022-12-02 um 15 22 19" src="https://user-images.githubusercontent.com/46345125/205314106-40baf179-9a43-4e99-a999-87bf84493f3c.png">

FYI @michael

**Comment by Siddhant-K-code** [comment]
We should also align the format we write numbers.
Like in the given screenshot ⬆️ - one place it is `500k+` & another one is `+500k`.

I think we should keep using ~`500k+`~ `750k+` format (`int+`). wdyt?
