### ISSUE TITLE
Remove Symlinks from Docs Directory

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#3107]
### Description

The Documentation is currently symlinked to the `src/routes`-directory.
This has a downside: search & replace isn't easy (as long as there is no scoped directory in the search).

The symlink was created in the context of #1393, for externalizing the docs to the main repo.
This currently not planned => we can get rid of the symlink again.

Steps:
- Remove Symlink
- Check existing logic if the `gitpod/docs`-directory is used somewhere

**Comment by Siddhant-K-code** [comment]
We need to rethink about this while #2907
