### ISSUE TITLE
Check and remove unused Svelte Files

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#3116]
### Description

We should check if we have any unused modules floating around the repo, and remove them if possible

**Comment by chrifro** [comment]
What's the consequence of having unused svelte files? Is it just messy or does it slow down the page? How likely is it that we do have any unused svelte files?

Having a bit more context to the issue would help to decide the priorities :) 
cc @Cahllagerfeld

**Comment by Cahllagerfeld** [comment]
There's nothing to add, to what Siddhant said 🙏
