### ISSUE TITLE
Fix internal linkings

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#3124]
### Description

For some pages, we added a Redirect within the load-function. We should get rid of these internal redirects by fixing the internal linking

**Comment by Siddhant-K-code** [comment]
> For some pages, we added a Redirect within the load-function. We should get rid of these internal redirects by fixing the internal linking

@Cahllagerfeld Can you please add some more context to this?

**Comment by Siddhant-K-code** [comment]
Related? #3107 -- #2907
