### ISSUE TITLE
Document TypeScript SDK in Public API documentation

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#3174]
The Go client is now added in: https://www.gitpod.io/docs/references/gitpod-public-api

We should add the TypeScript API.

**Comment by Siddhant-K-code** [comment]
We can now close this issue on behalf of our [internal conversation](https://gitpod.slack.com/archives/C0463A2KQUU/p1673450456027869?thread_ts=1673447389.466159&cid=C0463A2KQUU). We can re-open in future if required.
