### ISSUE TITLE
Add community heroes's profiles to /community/heroes

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3180]
Context: Requested improvement by @pawlean 

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2625%3A396&t=8FXnUoRG4zCZ1vds-1)

**Next steps:**
- @pawlean could you share the heroes' profile images, usernames & names?
- how do you want to sort them? alphabetically or by the date of joining the heroes program?
- would you like to add a subheadline underneath "meet the heroes" saying how awesome they are? If yes, please suggest the wording
- technical implementation

**Comment by pawlean** [comment]
> how do you want to sort them? alphabetically or by the date of joining the heroes program?

I'll share this issue with them on Discord ✨

> would you like to add a subheadline underneath "meet the heroes" saying how awesome they are? If yes, please suggest the wording

Alphabetically would make more sense in my opinion. 

I've also left some comments/thoughts on mockup.

**Comment by Siddhant-K-code** [comment]
> @pawlean could you share the heroes' profile images, usernames & names?

Regarding Details, Images, etc. We could ask them via Google Form. So that we got all our info. in a drive folder. Will be easier & faster to 🚀 this.

**Comment by pawlean** [comment]
Hey @Siddhant-K-code! Yes, agreed. I've created one and sent it on our private channel on Discord [[1](https://discord.com/channels/816244985187008514/914852149865877545)] I've given the deadline of 10th of February to collect all the Heroes who want to be included and will update this issue when we're ready.

**Comment by pawlean** [comment]
@Siddhant-K-code Sorry for the delay! The form answers are available []([here](https://docs.google.com/spreadsheets/d/1kpWW7PnC950fF5hl8uXzoI20oqM9bubB5siReyva620/edit?usp=sharing).) We still have some Heroes that hasn't completed the form, but a good portion have so let's get their profiles on the website 🚀

**Comment by Siddhant-K-code** [comment]
> form answers are available

@pawlean Where can I find the Form Answers (images, names) of them?

**Comment by pawlean** [comment]
@Siddhant-K-code Sorry, I forgot to link it in my comment above. 😮‍💨 See the form [here](https://docs.google.com/spreadsheets/d/1kpWW7PnC950fF5hl8uXzoI20oqM9bubB5siReyva620/edit?usp=sharing).

**Comment by Siddhant-K-code** [comment]
> See the form [here](https://docs.google.com/spreadsheets/d/1kpWW7PnC950fF5hl8uXzoI20oqM9bubB5siReyva620/edit?usp=sharing). - @pawlean 

Image assets are still not accessible. I have asked for access (can you please provide the read access response directory?)
