### ISSUE TITLE
Highlight Gitpod Dedicated on /enterprise

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3212]
<img width="733" alt="Bildschirmfoto 2023-01-03 um 11 24 34" src="https://user-images.githubusercontent.com/46345125/210339995-6d6098b3-cffb-4841-bfa0-b1bba571f4fa.png">

**Suggested changes:**
- change cloud icon with [security icon](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A1119&t=YKsgU5qOw5i6gwch-1) for Gitpod Dedicated
- update headline. "your cloud or our cloud" is very difficult to read. All letters look almost the same
- both CTA link to exactly the same place. We should add pre-selected subjects to the sales form.
Gitpod.io -> pre-select enterprise
Gitpod Dedicated -> change text to sign up for waitlist and link to https://www.gitpod.io/dedicated

WDYT @MichaelAring

**Comment by MichaelAring** [comment]
Let's make the changes Christin suggested, but keep the top headline unchanged for the time being.

For the Dedicated, CTA, please change the text to "Request early access"

Thank you!

**Comment by Siddhant-K-code** [comment]
> both CTA link to exactly the same place. We should add pre-selected subjects to the sales form.
> - Gitpod.io -> pre-select enterprise
> - Gitpod Dedicated -> change text to sign up for waitlist and link to https://www.gitpod.io/dedicated

@chrifro @MichaelAring What we exactly want is unclear?

Should We Link CTA of Dedicated to `/contact/sales` form or `/dedicated`

**Comment by chrifro** [comment]
Gitpod.io CTA should link to /contact/sales and preselect "Enterprise"

Gitpod Dedicated CTA should be renamed to "Request early access" and link to /dedicated

**Comment by Siddhant-K-code** [comment]
> and preselect "Enterprise"
For Now, we can skip this & merge this PR. We can resolve this in next iteration (in a new issue)
