### ISSUE TITLE
Update pricing calculator

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3237]
### **Issues:** 
- some messaging doesn't make sense. Calculations for one member shouldn't include any team messaging. Custom pricing shouldn't say get started now. It contradicts the CTA to contact sales

|||
|-|-|
|<img width="463" alt="Bildschirm­foto 2023-01-11 um 09 49 06" src="https://user-images.githubusercontent.com/46345125/211760451-5519e20d-42c1-455c-9bd5-58f32b5fcf53.png">|<img width="460" alt="Bildschirm­foto 2023-01-11 um 09 49 35" src="https://user-images.githubusercontent.com/46345125/211760455-2777ff12-8b5b-4003-925d-027640e793a3.png">
-  the calculated price can be confusing as it doesn't explain how the 500 free credits and 1000 credits are taken into account. 1 member & 20hours = €9, 2 members & 20hours = €62

### **Suggested solution**
update output messaging based on the calculation

|free|$9|team plan|custom|
|-|-|-|-|
|<img width="577" alt="Bildschirm­foto 2023-01-11 um 10 13 18" src="https://user-images.githubusercontent.com/46345125/211765879-91893030-1c8b-4e47-baf9-f3935f2fe4c1.png">|<img width="582" alt="Bildschirm­foto 2023-01-11 um 10 13 13" src="https://user-images.githubusercontent.com/46345125/211765919-e9cc504f-380c-4603-a44b-2898c7741de9.png">|<img width="585" alt="Bildschirm­foto 2023-01-11 um 10 13 32" src="https://user-images.githubusercontent.com/46345125/211766067-a130404c-8f78-4a4f-a7f7-f1bda74e8bce.png">|<img width="583" alt="Bildschirm­foto 2023-01-11 um 10 13 40" src="https://user-images.githubusercontent.com/46345125/211766090-9001228f-32da-4228-a8cd-567527839e91.png">

@MichaelAring WDYT?  could you finalize the messaging? 🙏

**Context**
[Slack discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1673277097669899)
[RFC
](https://www.notion.so/gitpod/UBP-Change-pricing-for-Teams-0dbb760ec23043649fbc0f864f4b7b4e)

**Comment by MichaelAring** [comment]
Great progress!

I've changed the messaging in the frames in [Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=8346%3A15369&t=BWomEoGfMeeRmNwQ-1). The messaging is final from my perspective @chrifro.
