### ISSUE TITLE
Update Navigation

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#3244]
See the [Figma mockup](https://www.figma.com/file/XL8jwSznvF6OFYTJkT9pYO/Barbara-x-Gitpod%3A-overhaul-website?node-id=251%3A907&t=EL3H82ZdYyNLHJGS-4)

**Comment by chrifro** [comment]
**Add drop-down menu to /docs**

Related changes (view [mockup](https://www.figma.com/file/XL8jwSznvF6OFYTJkT9pYO/Barbara-x-Gitpod%3A-overhaul-website?node-id=327%3A810&t=avbNV9uY1Fgjb9KD-1)):

- [ ] add new section for templates
- [ ] reuse existing style for `docs` `get started `and `help center`
- [ ] highlight the top menu by adding an underline
- [ ] update mobile design: arrows position and rotation
- [ ] update mobile design: drop-down look 
- [ ] update mobile design: remove all existing hovers for and under resources (color fill). Just the font should turn black

<img width="724" alt="Bildschirm­foto 2023-01-17 um 11 39 52" src="https://user-images.githubusercontent.com/46345125/212877819-baa1ad39-f24e-494f-be05-bdf40dc5f075.png">
<img width="212" alt="Bildschirm­foto 2023-01-17 um 11 40 00" src="https://user-images.githubusercontent.com/46345125/212877830-861650d1-f976-417e-878f-b375bb933be9.png">
