### ISSUE TITLE
Replace company name with company website and add validation to the website input field in contact forms

### ISSUE THREAD

**Issue by phimae** [gitpod-io/website#3249]
**Goal**
Add a validation rule that makes sure input in company website fields is an actual domain - doesn't need the www. but should make sure that there is a suffix like `.com` . This should be done for all contact forms where we have the company or website input field. If there is a `company name` or `company` input field (e.g. on https://www.gitpod.io/contact/support)  it should be changed to company website

**Context:**
Domain input is required for enriching leads - if the input is not a valid domain then our chances of success are significantly lower

<img width="878" alt="image" src="https://user-images.githubusercontent.com/83109781/212569119-f73468d1-2ebe-4be5-874c-e9ceeafb2ddf.png">

**Comment by Siddhant-K-code** [comment]
> doesn't need the [www](http://www/). but should make sure that there is a suffix like .com

Did we need to handle all cases or it should be limited to `.com`? Many of the domains could contain `.io`, `.in`, `.gov`, `.org`, `.net`, etc.?

**Comment by Siddhant-K-code** [comment]
Additionally, We could also add a Work Email check by not allowing the publicly available domains in the mail (e.g. `@gmail.com`) to actually allow the Work Emails on [sales page](https://www.gitpod.io/contact/sales). @phimae I wanted to know what is the conversion ratio of getting into a good lead came from `@gmail.com`, etc. _(if any or all were from work emails?)_


<img width="807" alt="image" src="https://user-images.githubusercontent.com/55068936/212592393-586d9100-f3b3-4864-84aa-1771f01b35eb.png">

**Comment by phimae** [comment]
> Did we need to handle all cases or it should be limited to .com? Many of the domains could contain .io, .in, .gov, .org, .net, etc.?

Yes, all cases. Maybe having a dot in there works already as validation rule? 

> Additionally, We could also add a Work Email check by not allowing the publicly available domains in the mail

Yeah, good thinking generally and we've discussed this before but felt that this is too intrusive - we can revisit later if identifying the lead becomes an actual problem.
