### ISSUE TITLE
Add newsletter sign-up to homepage

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3254]
Issue has been created based on [this internal task](https://www.notion.so/gitpod/Create-newsletter-sign-up-component-2f2d44e5f47e4654a2a37d00abf5b963?d=f9f5360ea2464df39744fa8632e724f1#c5712530e4b04c70a9c84ef11b176df8)

Task:
- Create component for newsletter sign-up to be placed at the bottom of the homepage (below the browser extension card)

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A6736&t=P2cHBWn1B4bFku9n-1)
<img width="599" alt="Bildschirm­foto 2023-01-17 um 09 33 15" src="https://user-images.githubusercontent.com/46345125/212848136-fd68ca5f-47a6-486b-999d-1ee0a44b2fa7.png">

**Next steps:**
- review messaging @MichaelAring 
- define the link for the button e.g. /notifications @MichaelAring 
    - or should the component include a form to enter the email address and forward them to a Google sheet? 
- technical implementation

**Comment by chrifro** [comment]
**Note:** I just got to know that the content should be forwarded to a Google sheet and not follow the sign-up logic on DevX blog posts. I will update the design accordingly later on.

**Comment by chrifro** [comment]
New component style 
<img width="725" alt="Bildschirm­foto 2023-01-17 um 10 18 16" src="https://user-images.githubusercontent.com/46345125/212858402-f4aec102-1dd1-455d-8628-3baa7f587349.png">

[Figma link](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A6736&t=P2cHBWn1B4bFku9n-1)

**Next steps:**
- technical implementation. @Cahllagerfeld could you take care of that? 🙏
- design review by Christin and messaging review by Michael

**Comment by phimae** [comment]
@jakobhero fyi - this signup form should be Segment tracked also
