### ISSUE TITLE
[Docs][Pricing page] Update flexible workspace timeouts

### ISSUE THREAD

**Issue by MichaelAring** [gitpod-io/website#3267]
### Description

See [PR15815](https://github.com/gitpod-io/gitpod/pull/15815). Previously, workspace timeout could be extended to 180 minutes, now, it can be extended to an arbitrary number.

Information needs to be updated in 2 places:

[Pricing page feature table](https://www.gitpod.io/pricing)
<img width="272" alt="Screenshot 2023-01-18 at 16 52 36" src="https://user-images.githubusercontent.com/99804441/213226537-1f6f2079-3bde-49f6-a1ad-ede80c8822d5.png">

Suggestion:
- Change hover-over information to: "Manually extend workspace timeout as long as you want"

[Docs](https://www.gitpod.io/docs/introduction/learn-gitpod/the-life-of-a-workspace#timeouts)
<img width="540" alt="Screenshot 2023-01-18 at 17 00 11" src="https://user-images.githubusercontent.com/99804441/213226335-a838bcf3-6149-4c42-8c07-fb9c61fabb54.png">

**Comment by Siddhant-K-code** [comment]
We need to update on gitpod cli docs page also.
