### ISSUE TITLE
Improve collaboration animation

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3300]
**Issue**:
The cursor animation is too fast and not smooth

https://user-images.githubusercontent.com/46345125/214583565-bf68a686-1b66-4a11-aca7-599c46189460.mov

**Solution**:
Cut the file in Adobe After Effects so that the animation starts and ends by showing the cursor. Thereby the animation will also be aligned with the "multi-track- development" animation

**Comment by Siddhant-K-code** [comment]
Fast thing is good, no? Just to showcasing that You Can Share workspace so fast by a single click 😄
