### ISSUE TITLE
Restructure contributionHighlights data

### ISSUE THREAD

**Issue by ghostdevv** [gitpod-io/website#3303]
### Description

Currently it's in two arrays: the months array `contributionMonths` and the `contributionHighlights` array. This data structure is a bit awkward. Here is the proposed solution:

 ```ts
 interface ContentCard {
  title: string;
  text: string;
  badge: ContentBadge;
  link?: { text: string; href: string };
  contributor: string;
};

export const contributionHighlights: Record<string, ContentCard[]> = {
	"December 2022": [
		// ...
	],
	
	// ...
}
```

**Comment by Siddhant-K-code** [comment]
Thanks, @ghostdevv. If you want, feel free to send out the PR. Happy to review it

**Comment by ghostdevv** [comment]
Will do after #3302 is merged!
