### ISSUE TITLE
Optimize Opengraph Description for each Docs sub-page

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/website#3313]
### Description

Currently, All Docs Pages contain the same OpenGraph Description. But, it should contain some page-specific details _(which are also crucial for SEO)_. i.e. If you Open [Projects page](https://www.gitpod.io/docs/configure/projects). It should have a description of something specific to the Project, but currently, it has just a generalized description. See [here](https://www.opengraph.xyz/url/https%3A%2F%2Fwww.gitpod.io%2Fdocs%2Fconfigure%2Fprojects)

![image](https://user-images.githubusercontent.com/55068936/214993425-c5b2778c-9d30-455c-975e-bb0df82f5389.png)

**Comment by ShashwatNautiyal** [comment]
@Siddhant-K-code I have started working on this. You can assign it to me.

**Comment by Siddhant-K-code** [comment]
Sorry, forgot to ask you.

@ShashwatNautiyal, what approach you are following right now?

I would suggest having a `description` tag like `title`:

https://github.com/gitpod-io/website/blob/3b58a9c64db9036fb84daca1d67211d906195d98/gitpod/docs/configure/projects/incremental-prebuilds.md?plain=1#L1-L4

And, if that doesn't exist we would return the default description (like we are doing for the title). And please feel free to raise a follow-up issue to add the `description` in each docs markdown file. This issue just focuses on the technical implementation of the solution, I mentioned above.

If you have any more questions, feel free to ping me.

**Comment by ShashwatNautiyal** [comment]
Yes, I have added a description tag like a title tag. Would you like me to raise a different issue for each doc sub-page?

**Comment by Siddhant-K-code** [comment]
> Would you like me to raise a different issue for each doc sub-page?

We can raise a follow-up issue after this issue got resolved.

**Comment by ShashwatNautiyal** [comment]
PR Raised Cc: @Siddhant-K-code
