### ISSUE TITLE
[features] add image for the 'Supported Programming Languages'

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#332]
Add image for supported programming languages

**Comment by svenefftinge** [comment]
I have removed the table already. Waiting for an image from @ChristinFrohne

**Comment by ChristinFrohne** [comment]
**Version 1** (easier) 
<img width="1068" alt="Bildschirmfoto 2019-12-18 um 13 29 54" src="https://user-images.githubusercontent.com/46345125/71086594-93687c80-219a-11ea-94a1-8a1d9f60b23a.png">

**Version 2** (interactive and more complex) 
On hover/click the bubble moves in the foreground, changes background color to white, logo gets the galaxy background and the name of the programming language will be displayed

<img width="717" alt="Bildschirmfoto 2019-12-18 um 13 22 32" src="https://user-images.githubusercontent.com/46345125/71086270-bcd4d880-2199-11ea-92a2-7ce870266487.png">
[supported-languages.zip](https://github.com/gitpod-io/website/files/3978411/supported-languages.zip)

**Comment by ChristinFrohne** [comment]
Or maybe giving all in light gray background and adding a shadow is cleaner. I think this works well for the hover effect
<img width="699" alt="Bildschirmfoto 2019-12-18 um 14 25 35" src="https://user-images.githubusercontent.com/46345125/71090011-4ab4c180-21a2-11ea-8c84-f0320a4aaa3c.png">
