### ISSUE TITLE
[Docs - New Feature]: Update Rust to 1.67

### ISSUE THREAD

**Issue by c3potheds** [gitpod-io/website#3322]
Need to update https://www.gitpod.io/docs/introduction/languages/rust to say "1.67" instead of "1.66"

**Comment by Siddhant-K-code** [comment]
Thanks, Will merge after deployment of https://github.com/gitpod-io/workspace-images/pull/1013

**Comment by Siddhant-K-code** [comment]
It is updated to `1.68` now. And, it's resolved for now. Thanks 🙏🏼
