### ISSUE TITLE
Add meet-up guidelines to /community

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#3352]
We want to bring more visibility to the meet-up guidelines [[1](https://www.notion.so/gitpod/Hosting-a-Gitpod-Community-meet-up-77bdde81c5b04d80b93e425ebdd568ef)] on `/community` page [[2](https://www.notion.so/gitpod/Gitpod-Paris-Retro-6f50d5b84f584b128c3c34d8acc9ac39#69b9001bef054cd3a4d763894714463b)]. 

My proposal is we create another card under this heading with the following copy:

<img width="997" alt="2023-02-01 at 16 09 07 - Google Chrome@2x" src="https://user-images.githubusercontent.com/17087373/216065663-faa3d148-b77a-4041-8f99-e7da06c6f70c.png">

## Host a Gitpod Community meet-up

Gitpod Community meet-ups are organized by passionate community members in their local area. They are an opportunity to connect with others in the community and learn and share the best Gitpod practices and knowledge. 

**Button 1:** Hosting guidelines (https://www.notion.so/gitpod/Hosting-a-Gitpod-Community-meet-up-77bdde81c5b04d80b93e425ebdd568ef)

**Button 2:** View playlist (https://www.youtube.com/playlist?list=PL3TSF5whlprWHSTPbBrpGyxetRMOgUTd5)

From a design POV, are you happy with this @chrifro?

**Comment by Shashwat-Groww** [comment]
Cc: @Siddhant-K-code You can assign this to me. I can work on this.

**Comment by ShashwatNautiyal** [comment]
Cc: @Siddhant-K-code Can you assign it to me? 

I can work on this issue.

**Comment by Siddhant-K-code** [comment]
Thank you. I assigned this to you. Let's wait until @chrifro finalizes the design

**Comment by chrifro** [comment]
Awesome, thanks for the specific proposal @pawlean ✨

Let's add this image to the post. 
![FnvYGmQXwAAH7kv](https://user-images.githubusercontent.com/46345125/216908706-6a62ccaa-58f4-4c1f-8232-4f870e1433cf.jpeg)


Note: I shortened the text a bit to fit well in the card
<img width="712" alt="Bildschirm­foto 2023-02-06 um 08 19 46" src="https://user-images.githubusercontent.com/46345125/216908520-ebfefd3b-8afa-413e-bb8c-2f0388f76774.png">


Thanks for picking up this issue @ShashwatNautiyal 🙌

**Comment by ShashwatNautiyal** [comment]
PR Raised.

Cc: @Siddhant-K-code @chrifro
