### ISSUE TITLE
(Docs) Update self-hosted deprecation info box

### ISSUE THREAD

**Issue by MichaelAring** [gitpod-io/website#3364]
### Description

**Context**
Links: 
- https://www.gitpod.io/docs/configure/self-hosted/latest
- https://www.gitpod.io/community-license

**Proposed Changes**
1. Shorten text to 3 lines
2. Add "Self-hosted alternative" in bold

**Current state**
<img width="543" alt="Screenshot 2023-02-02 at 10 22 57" src="https://user-images.githubusercontent.com/99804441/216284107-1afd7bf2-9083-4ebf-bdef-e0762529eef9.png">

<img width="664" alt="Screenshot 2023-02-02 at 10 25 41" src="https://user-images.githubusercontent.com/99804441/216284867-ef7f591f-ab8b-4a14-bf91-96db3a7658c4.png">

**Comment by Siddhant-K-code** [comment]
Yeah, sure @Utkarshn10. Let's wait for @MichaelAring for the text suggestion changes.

**Comment by taliamoyal** [comment]
@MichaelAring do we need anything different than the text changes you suggested above? 

Who does this email go to?

**Comment by taliamoyal** [comment]
⚠️ Gitpod Self-hosted is [no longer supported](https://www.gitpod.io/blog/introducing-gitpod-dedicated

The last update of Gitpod Self-hosted product was [November 2022](https://www.gitpod.io/changelog/november-self-hosted-release). Users can still request our [free community license](https://www.gitpod.io/community-license) however there will be no support or updates to the product. If you are interested in an isolated, private installation of Gitpod, take a look at [Gitpod Dedicated](https://www.gitpod.io/dedicated).

Copy changes ^

**Comment by Siddhant-K-code** [comment]
@Utkarshn10 are you still interested to work on this issue?
