### ISSUE TITLE
[breaking] All Mentions of Dashboard settings are not working on docs!

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/website#3389]
### Page URL

https://www.gitpod.io/docs/configure/user-settings/dotfiles

### Description

With 
- https://github.com/gitpod-io/gitpod/pull/16164

All Routes are now updated to `/user/{settings}`. This needs to be updated across the whole website!

**Comment by gtsiolis** [comment]
@Siddhant-K-code Is this still an issue? All links to the dashboard seem to work fine now, right?
