### ISSUE TITLE
Small glitches in the ToS

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/website#3391]
### Page URL

https://www.gitpod.io/terms

### Description

<img width="859" alt="image" src="https://user-images.githubusercontent.com/666176/217243429-af4750c4-4b80-45ce-88b7-40896de712f7.png">
<img width="498" alt="image" src="https://user-images.githubusercontent.com/666176/217243470-12dba60f-8847-40c9-89f1-21c3a0b2a012.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/666176/217243504-fd32d591-8ee6-4e3f-8aec-bda75a3b5b25.png">

**Comment by Siddhant-K-code** [comment]
regarding `-- begin model withdrawal form --`


I think it is intentional 🤔
