### ISSUE TITLE
(blog) preview of community meetup post image does not show

### ISSUE THREAD

**Issue by MichaelAring** [gitpod-io/website#3400]
### Page URL

https://www.gitpod.io/blog

### Description

**Description**
On the blog page, the preview of the image for the latest blog post does not show

<img width="898" alt="Screenshot 2023-02-08 at 09 46 31" src="https://user-images.githubusercontent.com/99804441/217479930-b752cda4-9ed8-4473-ac4c-ab0b1ebd6928.png">

**Comment by MichaelAring** [comment]
cc @pawlean

**Comment by pawlean** [comment]
This has confused me! According to this line: https://github.com/gitpod-io/website/pull/3398/files#diff-624f8fd16edbf7579784726e5d174f3770ad368cb763812cc11ac323aceb1a5eR8 it refers to the correct preview image. :eyes: Unless this preview image can't pick up .webp files for some reason? @Siddhant-K-code 🤷🏼
