### ISSUE TITLE
Minor Improvements on Homepage

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/website#3408]
### Description

> followup #3382, #3387

Tasks List:

- [x] the hover and active states of the IDE selector don't align with mockup yet - https://github.com/gitpod-io/website/pull/3426
    - active: bg-> white, stroke 3px and grey, no shadow
    - hover: bg -> white, linear stroke 1px, no shadow
    
    See mockup
<img width="593" alt="Bildschirm­foto 2023-02-10 um 09 24 48" src="https://user-images.githubusercontent.com/46345125/218040902-6e8799c5-dd95-4d47-b6f1-dc8d67f1a410.png">

- [x] the animated quotes should start a bit earlier now that we don't have the contact pop-up anymore - https://github.com/gitpod-io/website/pull/3409

- [x] align icon size. The JetBrains IDE icons are a lot bigger than the other icons. Let's align them to the smaller style. Because of that the spacing inside the cards is also not even - #3428

<img width="918" alt="Bildschirm­foto 2023-02-10 um 09 26 01" src="https://user-images.githubusercontent.com/46345125/218041067-0a0fb4b9-e1c9-4c40-88a9-6591f5828f02.png">

- [ ] responsive layout bug
<img width="1156" alt="Bildschirm­foto 2023-02-10 um 09 26 40" src="https://user-images.githubusercontent.com/46345125/218041176-aa7c0097-bb57-4d17-adb9-9fb0ec330406.png">

- [x] dark theme: change design to this - https://github.com/gitpod-io/website/pull/3436
<img width="637" alt="Bildschirm­foto 2023-02-08 um 15 00 16" src="https://user-images.githubusercontent.com/46345125/217550970-5a8f45b7-92f8-4986-a7e4-99bef2e309fa.png">

- [x] the Vim screenshot needs to be updated (see [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2056%3A3271&t=Tun0p4nGsulxrvSI-1)) - https://github.com/gitpod-io/website/pull/3424
- [x] the screenshots a slightly moving around when hovering over the different IDEs. We need to align their size and position - https://github.com/gitpod-io/website/pull/3424
- [x] remove white border from screenshots - https://github.com/gitpod-io/website/pull/3424
<img width="622" alt="Bildschirm­foto 2023-02-10 um 14 44 23" src="https://user-images.githubusercontent.com/46345125/218106958-2efbd5fd-8a2a-45e6-96b7-2e216a5aee7c.png">

- [x] reduce icon sizes and add spacing between icon and text (see mockup) - https://github.com/gitpod-io/website/pull/3425
<img width="213" alt="Bildschirm­foto 2023-02-10 um 14 41 14" src="https://user-images.githubusercontent.com/46345125/218107012-f176820d-fdbe-4aaf-9d0d-1af4002a37fa.png">

<s>- [ ] mobile layout still needs some improvements. @chrifro will create mockups for them </s> created a new issue for it #3413

**Comment by ShashwatNautiyal** [comment]
Please assign this to me. I will start working on these issues.

**Comment by Siddhant-K-code** [comment]
> Please assign this to me. I will start working on these issues

Yeah, Always feel free to send out the PR ✨
