### ISSUE TITLE
Rename "contact sales" CTA

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3427]
We'd like to test the impact of renaming all "contact sales" buttons to "talk to an expert".

How can we measure the success of this change?
1. we use the native [split testing ](https://docs.netlify.com/site-deploys/split-testing/)support by Netlify [thanks @gtsiolis for the suggestion] (preferred option)
2. compare button clicks before and after the change (wouldn't be very reliable as it can be influenced by other factors)

@Siddhant-K-code do you think we could implement option 1?

**Comment by Siddhant-K-code** [comment]
> we use the native [split testing ](https://docs.netlify.com/site-deploys/split-testing/)support by Netlify [thanks `@gtsiolis` for the suggestion] (preferred option)

### [Conext] Current State:
- We only deploy with our default (`main`) branch. 
    - 100% scalability no hiccups.
- We have server-side rendering (SSR) for some components/pages.

### Steps to achieve this:

- _[concern]_ Feature is in `Beta` & [doesn't work with SSR](https://docs.netlify.com/site-deploys/split-testing/#:~:text=This%20can%20be%20a%20concern%20for%20sites%20that%20use%20server%2Dside%20rendering%20(SSR))
- Multiple Branch Introduction, we need to create one or more branches (depending on requirement), which costs us:
    - Extra effort to maintain multiple branches & keeping them in sync (because we ship so many changes in a single day itself 😅)



> compare button clicks before and after the change (wouldn't be very reliable as it can be influenced by other factors)

Looks like a good starting solution as a workaround (at least till the [split-testing feature](https://docs.netlify.com/site-deploys/split-testing/) is not in GA)

**Comment by MichaelAring** [comment]
Agree @Siddhant-K-code - don't think we need split testing for this

**Comment by Siddhant-K-code** [comment]
@MichaelAring/@phimae did we get the final action item for the changed text, is it "talk to an expert" or something else?

**Comment by Siddhant-K-code** [comment]
You Can Track all the insights by following these steps => [Internal conversastion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1677155602636669)
