### ISSUE TITLE
[blog post] title has some unecessary spacing & decenders have white on top.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#343]
With some recent changes that we made The title on a Blog post now has some unnecessary space in the top left of first-line:

![image](https://user-images.githubusercontent.com/46004116/71158458-cdeb1b80-2265-11ea-80be-a73fac9c63e0.png)

Also, some part of the descenders in the first-line of the title is now under the white background of the 2nd line like the letter **g** in the screenshot below: 
![image](https://user-images.githubusercontent.com/46004116/71159487-89f91600-2267-11ea-9341-5d825f8383e8.png)

before that it was like this:

![image](https://user-images.githubusercontent.com/46004116/71159585-b57c0080-2267-11ea-8f58-76ffe058cb11.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Sorry! I'm not able to make it the way it is in the mockup while fixing the above issues. 

Maybe we can try this? 

![image](https://user-images.githubusercontent.com/46004116/71177447-d8b9a680-228d-11ea-91a3-1da0d65fa906.png)

or this one maybe ? 

![image](https://user-images.githubusercontent.com/46004116/71177069-f33f5000-228c-11ea-9c71-4fb2b6b8d624.png)

**Comment by ChristinFrohne** [comment]
Okay, thanks for trying. Then let's go with the second option :)

**Comment by svenefftinge** [comment]
Fixed
