### ISSUE TITLE
Change CTA in "get started" call-out

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3430]
swap “get demo” CTA with “talk to an expert” and “try now” to “start for free” 

Examples of affected pages: /enterprise, /events, etc.

Affected component
<img width="1269" alt="Bildschirm_foto 2023-02-09 um 21 52 43" src="https://user-images.githubusercontent.com/46345125/219607740-ff67d754-9eb7-404b-a1cc-2fff392ad110.png">

Could we track the change from " get a demo" to "contact sales" with A/B testing as explained in #3427?

**Comment by Siddhant-K-code** [comment]
You Can Track all the insights by following these steps => [Internal conversastion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1677155602636669)
