### ISSUE TITLE
Simplify form submission consent

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3432]
Tasks:
- [ ] remove checkbox and its text
- [ ] change note to "By submitting this form, I confirm that I acknowledge the collection and processing of personal data by Gitpod, as further described in the [Privacy Policy](https://www.gitpod.io/privacy)." 

Note: the changes have been approved by @securitymirco 

**Affected component**
<img width="601" alt="Bildschirm_foto 2023-02-09 um 21 23 14" src="https://user-images.githubusercontent.com/46345125/219613316-cc24b736-8154-4559-ab9c-1587dd0ffe0f.png">

**Affected pages:**
All forms e.g. /sales, /contact, /whitepaper/cde, /cde

**Comment by securitymirco** [comment]
lgtm @Siddhant-K-code
