### ISSUE TITLE
Update screencasts in /docs and /screencasts

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#3433]
We updated the following screencasts that need to be updated in the docs:

- Getting Started With Gitpod [[1](https://www.youtube.com/watch?v=ij1msCffQZA&list=PL3TSF5whlprXVp-7Br2oKwQgU4bji1S7H&index=2)]
- Fully Automate Your Dev Setup [[2](https://www.youtube.com/watch?v=E95oV_iqUtI&list=PL3TSF5whlprXVp-7Br2oKwQgU4bji1S7H&index=3)]
- Continuously prebuild your project [[3]](https://www.youtube.com/watch?v=DwkoOz1GSVg&list=PL3TSF5whlprXVp-7Br2oKwQgU4bji1S7H&index=5)
- Collaborating with your team [[4]](https://www.youtube.com/watch?v=HcKlXfKpolM&list=PL3TSF5whlprXVp-7Br2oKwQgU4bji1S7H&index=7)

A new screencast on dotfiles [[5]](https://www.youtube.com/watch?v=00dif9QWXNU&list=PL3TSF5whlprXVp-7Br2oKwQgU4bji1S7H&index=20) can be added to [our dotfiles page.](https://www.gitpod.io/docs/configure/user-settings/dotfiles#dotfiles)

Under [our contribute page](https://www.gitpod.io/docs/help/contribute), we could add a link to gitpod-samples screencast [[6]](https://www.youtube.com/watch?v=KcSeDGSMexs&list=PL3TSF5whlprXVp-7Br2oKwQgU4bji1S7H&index=19) with text that reads, "Contribute to gitpod-samples"

**Comment by chrifro** [comment]
When updating the links, we can also update the thumbnail and preview design on /screencasts (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=2945%3A1085&t=3p5d2IB2WlYyBaZe-1))
<img width="723" alt="Bildschirm­foto 2023-02-17 um 14 56 00" src="https://user-images.githubusercontent.com/46345125/219675372-f4564ba9-27e3-4465-9f58-7ee42f181e05.png">

You can find all new thumbnails [here](https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=2031%3A1647&t=UPT3chhznI9mFWYj-1). Please ping @pawlean or @chrifro in case any image is missing
