### ISSUE TITLE
Lighthouse performance: reducing image size for mobile

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#344]
Can we reduce image size for mobile? The performance for desktop is great (99/100)

<img width="966" alt="Bildschirmfoto 2021-04-09 um 14 51 58" src="https://user-images.githubusercontent.com/46345125/114182973-9107d400-9943-11eb-9035-5a3e03a7b35d.png">
<img width="773" alt="Bildschirmfoto 2021-04-09 um 14 53 01" src="https://user-images.githubusercontent.com/46345125/114182981-92390100-9943-11eb-85a7-e6bb70362170.png">

Not sure why the screenshot is partially in German and partially in English. Sorry about that.

**Comment by nisarhassan12** [comment]
This will get addressed by https://github.com/gitpod-io/website/pull/160 which is on hold at the moment.

**Comment by nisarhassan12** [comment]
This is a part of #135 so closing in favour of that as part of the issue clean up.
