### ISSUE TITLE
SEO improvements

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#346]
- [x] there should be only 1 `<h1>` heading per page [[1](https://www.seobility.net/en/wiki/H1-H6_headings)] currently there are 3  (`Always Ready to Code.`  `Remote-first. Secure by design.` `Get started now`)

- [x] here is no `<h4>`used instead it jumps to `<h5>`directly. We should avoid to skip heading levels

- [x] There are 28 headings on the page. The number of headings should be in a more proper relation to the amount of text. E.g. there are 16 `<h3>` tags, 6-8 tags are recommended
  - I removed 14 `<h3>` tags, one on each of the testimonials

- [ ]  There are too many external links (60). Not sure about the impact though. Still, we could remove the links from the tweets to improve this

- [x] There is no redirect from HTTP to HTTPS. Both protocols work and return the same content.

- [x] missing `<title>`tag for https://www.gitpod.io/docs, https://www.gitpod.io/pricing and https://www.gitpod.io/self-hosted

- [x] 9 missing alt-tags e.g.  `<img src="/images/illustration-zoom.jpg" alt="" role="presentation" width="1136" height="631" class="heroImage svelte-1mypwlo">` , `     <img src="/images/features/features-3.svg" alt="" role="presentation" height="223" width="382" class="svelte-133w2br">`

**Used Tools:** 
https://freetools.seobility.net/en/seocheck/check?url=https%3A%2F%2Fwww.gitpod.io%2F&crawltype=1
https://search.google.com/search-console?utm_source=about-page&resource_id=https://www.gitpod.io/
https://sitechecker.pro/app/main/project/1915360/audit/summary

**Comment by mikenikles** [comment]
The reasons they mention external links are valid, but don't apply in our case on the testimonials since we link to tweets which are immutable.

More about external links: https://www.seobility.net/en/wiki/External_Links

**Comment by nisarhassan12** [comment]
The document outlines still need to be adjusted i.e this is what it looks like for the features page. The H3s should be H2s while visually being H3s i.e the H3s are not subsections instead individual standalone sections. 

![image](https://user-images.githubusercontent.com/46004116/114423659-d55bd400-9bd0-11eb-95af-ac6ee38e784f.png)

There are multiple `h1`s on the Pricing Page:

![image](https://user-images.githubusercontent.com/46004116/114424379-7cd90680-9bd1-11eb-83e0-7ecd9b815b88.png)

**Comment by nisarhassan12** [comment]
> - [ ] There are too many external links (60). Not sure about the impact though. Still, we could remove the links from the tweets to improve this

@ChristinFrohne Should I make a Pr for this?

**Comment by ChristinFrohne** [comment]
I think instead of having several different links in each tweet, it would make the most sense to link the whole box to the original tweet. If someone is curious about the links included in the tweet, they can access them from there. 

If you agree, please open a PR for it @nisarhassan12 🙂

**Comment by nisarhassan12** [comment]
Thanks. I have opened https://github.com/gitpod-io/website/issues/492 for this will make a Pr soon.

**Comment by ChristinFrohne** [comment]
The remaining issue will be addressed in #492 . Therefore I will close this issue. Please reopen it if something else is missing
