### ISSUE TITLE
Mobile fixes

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#347]
- Logo freecodecamp moves weirdly around. On Start Screen and Enterprise ![A068BA68-A5E8-45D5-9E74-140D4BEFDB59](https://user-images.githubusercontent.com/46345125/71172314-29b2a600-2260-11ea-9358-4133e1d8d454.png)

-tweet arrangement doesn’t work 
![A98C6DB8-46ED-4043-84A7-4ED2B3D21CF1](https://user-images.githubusercontent.com/46345125/71172316-2a4b3c80-2260-11ea-87dd-05648368719f.png)

-do we need the overview on mobile view? Otherwise we can just delete the boxes
![DAA2C2DD-4C15-4CFB-8F8B-ECAD15315F5F](https://user-images.githubusercontent.com/46345125/71172319-2ae3d300-2260-11ea-98d7-afd26d4a84a3.png)

-could be less spacing above and below the images
![8B5557C6-3A88-44C3-8039-5DF9214963AC](https://user-images.githubusercontent.com/46345125/71172321-2ae3d300-2260-11ea-8aa3-7d20fe8ad545.png)

-the boxes should be shorter
![BC090291-4D69-4DA4-B4DF-4C0E930F535E](https://user-images.githubusercontent.com/46345125/71172322-2b7c6980-2260-11ea-9c54-ebecae692cdc.png)

-the text would be easier to read with wider boxes
![D71BC410-009A-4863-A3FE-8FA421E675BB](https://user-images.githubusercontent.com/46345125/71172324-2c150000-2260-11ea-8663-a14ef99b4d19.png)

-image is partly cut 
![681345AE-F04A-4BFC-98D1-E7983F30472B](https://user-images.githubusercontent.com/46345125/71172325-2c150000-2260-11ea-9af2-a1e6a8e57cff.png)

**Comment by nisarhassan12** [comment]
> -do we need the overview on mobile view? Otherwise we can just delete the boxes
@ChristinFrohne I'm in favour of removing it on mobile.

**Comment by nisarhassan12** [comment]
> -the boxes should be shorter
> ![BC090291-4D69-4DA4-B4DF-4C0E930F535E](https://user-images.githubusercontent.com/46345125/71172322-2b7c6980-2260-11ea-9c54-ebecae692cdc.png)

@ChristinFrohne The boxes are of this size intentionally because there is not enough space on the left the popover info appears in the bottom. If I will make the height smaller contents will overflow over each other & that won't look good. Do you have some other layout in mind for the popover on mobile so that we can make these boxes smaller?

![image](https://user-images.githubusercontent.com/46004116/71234430-938f8600-231a-11ea-8a37-47caf3ea4284.png)

**Comment by nisarhassan12** [comment]
> -tweet arrangement doesn’t work
> ![A98C6DB8-46ED-4043-84A7-4ED2B3D21CF1](https://user-images.githubusercontent.com/46345125/71172316-2a4b3c80-2260-11ea-87dd-05648368719f.png)

Weird! we're using `overflow-x` which is well supported across browsers. I'm not sure why it does not seem to work. For me it looks like this: 

![image](https://user-images.githubusercontent.com/46004116/71246383-5afea500-2338-11ea-9264-1ef45ad22884.png)

**Comment by svenefftinge** [comment]
I've fixed the issue with the tweets. It seem to be caused by the max-width: 100% and server side rendering, which Safari doesn't like somehow. I've changed it to min-width: 400px and it works. No idea...

**Comment by ChristinFrohne** [comment]
>@ChristinFrohne The boxes are of this size intentionally because there is not enough space on the left the popover info appears in the bottom. If I will make the height smaller contents will overflow over each other & that won't look good. Do you have some other layout in mind for the popover on mobile so that we can make these boxes smaller?

@nisarhassan12 What about either having a gray box on top of the existing text like here:
![image](https://user-images.githubusercontent.com/46345125/71512078-fb9f1880-2894-11ea-8463-f373058bd7ad.png)

Or having a little pop up box  like this
![image](https://user-images.githubusercontent.com/46345125/71512174-53d61a80-2895-11ea-93f7-83fed6ce2cc8.png)

What do you think? What is best to implement?
