### ISSUE TITLE
new media image

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#348]
![Media-image](https://user-images.githubusercontent.com/46345125/71175297-81a0db00-2267-11ea-9c2a-8cf89884b762.jpg)

square version:
![Media-image-square](https://user-images.githubusercontent.com/46345125/71175565-2c18fe00-2268-11ea-82b9-b04ead7eb70b.jpg)

**Comment by svenefftinge** [comment]
done
