### ISSUE TITLE
Design polish for /onboarding and /collaboration

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3480]
Align spacing with [mockup spacing](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=9362%3A21863&t=ie7f3pwqgX72RR5a-1)
- [ ] reduce top spacing from 160px to 72px
<img width="588" alt="Bildschirm­foto 2023-02-28 um 16 46 33" src="https://user-images.githubusercontent.com/46345125/221905940-6dc0ab15-5f81-41e1-9d09-28a0fcf85c5d.png">
- [ ] reduce spacing to 120px
<img width="659" alt="Bildschirm­foto 2023-02-28 um 16 47 00" src="https://user-images.githubusercontent.com/46345125/221905983-c931c47f-8a51-47b1-b1f3-59e43323a078.png">
- [ ] reduce spacing to 72px
<img width="682" alt="Bildschirm­foto 2023-02-28 um 16 47 50" src="https://user-images.githubusercontent.com/46345125/221906078-99b0a439-8ab4-4905-b633-02b97b70e1cf.png">
- [ ] increase spacing to 160px
<img width="403" alt="Bildschirm­foto 2023-02-28 um 16 50 24" src="https://user-images.githubusercontent.com/46345125/221906136-218e2527-9b1f-4826-9fce-e00c697e3cb9.png">

- [ ] align code snippet design with [mockup style ](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=9326%3A21637&t=ie7f3pwqgX72RR5a-1) -> decrease size, keep even line height
<img width="497" alt="Bildschirm­foto 2023-02-28 um 16 52 36" src="https://user-images.githubusercontent.com/46345125/221906816-bdfe4c9d-1961-444e-9c73-8841c6533275.png">

Mobile improvements:

- [ ] increase spacing between different sections (might be already fixed by the spacing improvements above)
<img width="815" alt="Bildschirm­foto 2023-02-28 um 16 55 15" src="https://user-images.githubusercontent.com/46345125/221907766-05ffa827-2cd1-4e63-b42d-d09ca83b49e6.png">

- [ ] increase spacing to avoid content overlay
- [ ] <img width="816" alt="Bildschirm­foto 2023-02-28 um 16 55 34" src="https://user-images.githubusercontent.com/46345125/221907794-8764e6d0-c0e9-4ceb-8f0a-6a2edcd2330b.png">

**Comment by Siddhant-K-code** [comment]
> - [ ] reduce spacing to 72px ~ @chrifro 
> <img width="682" alt="Bildschirm­foto 2023-02-28 um 16 47 50" src="https://user-images.githubusercontent.com/46345125/221906078-99b0a439-8ab4-4905-b633-02b97b70e1cf.png">

We are just reusing the similar one from existing components. Should we change for all?


![image](https://user-images.githubusercontent.com/55068936/222066104-2b962050-0de3-4251-9f4f-24ae876c5336.png)

**Comment by chrifro** [comment]
>We are just reusing the similar one from existing components. Should we change for all?

No as in the example you shared the context is different. On the homepage, the crossed-out text is its own section. On other pages like /onboarding or /collaboration it's a headline that belongs to the same section.

**Comment by Siddhant-K-code** [comment]
Done 😄 

<img width="981" alt="image" src="https://user-images.githubusercontent.com/55068936/222076420-16699db1-eeff-4601-b7d2-93fcdf483731.png">
