### ISSUE TITLE
[Bug] duplicated CTAs on /enterprise

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3482]
detected bug after merging #3427 <img width="743" alt="Bildschirm­foto 2023-03-01 um 10 05 03" src="https://user-images.githubusercontent.com/46345125/222093404-d28aef26-188e-4933-804a-2e6de7b976bc.png">

@Siddhant-K-code could you double-check if any other pages/CTAs were affected by this?

**Solution:**
- replace secondary CTA with "Get a demo" and link to https://www.gitpod.io/contact/get-demo

**Comment by Siddhant-K-code** [comment]
It occurred in https://github.com/gitpod-io/website/pull/3457. It doesn't affect any other components.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/55068936/222131223-0069eb80-8727-44b0-9e7d-c3c59b2f27bd.png">
