### ISSUE TITLE
Update recent blog posts in GitHub profile README using the blog RSS feed

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#3492]
### Problem to solve

The [`.github/profile/README.md`](https://github.com/gitpod-io/.github/blob/main/profile/README.md) that is also surfaced on our GitHub org contains the 3 most **[recent blog posts](https://github.com/gitpod-io#recent-blog-posts)**.

However, these are manually updated and easily outdated.

See [relevant discussion](https://gitpod.slack.com/archives/C01LDA27WJC/p1677675669345849) (internal). Cc @burningion 

### Proposal

Use the recently added **[blog RSS feed](https://www.gitpod.io/blog/rss.xml)** to automatically update the recent blog posts.

Cc @Siddhant-K-code because https://github.com/gitpod-io/website/pull/3306

**Comment by Siddhant-K-code** [comment]
Done ✅ 🎉 

It would be running weekly & will display recent 5 blog posts. Code ([`75028a0`](https://github.com/gitpod-io/.github/commit/75028a0bbfe66db22cf2d9cd1f804a1d6d95c42b))

**Comment by gtsiolis** [comment]
Awesome. Thanks, @Siddhant-K-code! 🌮 🌮
