### ISSUE TITLE
Update top navigation

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3499]
**Context**
---
we want to highlight the recently added solution pages in the top navigation and polish the general structure

**Mockup**
---
[View in Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=9373%3A22681&t=Iw0rF69aIFEtYBYm-1)
<img width="720" alt="Bildschirm­foto 2023-03-08 um 09 22 25" src="https://user-images.githubusercontent.com/46345125/223661103-e28fe43b-1c0a-46d1-bd16-9d000c0ad5ea.png">
<img width="720" alt="Bildschirm­foto 2023-03-08 um 09 24 57" src="https://user-images.githubusercontent.com/46345125/223661247-91fff68d-dd5d-4af7-b717-b0f96775b1c0.png">

Timeline: best to implement after /solutions/supply-chain-security is live

**Comment by nimraistikhar** [comment]
Hey @chrifro I want fix this issue. Please assign this issue to me and i send request for access to see the figma and  to make it appropriate and pixel perfect like figma file(mockup). Please give me access for figma.
My email adress is: nimraistikhar@gmail.com

**Comment by Siddhant-K-code** [comment]
Hey @nimraistikhar 👋 

Sorry, Figma file is only accessible to Gitpodders (Gitpod employees).

**Comment by nimraistikhar** [comment]
Ok @Siddhant-K-code .
But actually i want to do some open source contribution in Gitpod as Front-end Developer.
Can you please guide a little bit that how can i contribute in Gitpod if i will don't have access?
