### ISSUE TITLE
update contact confirmation screen

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3500]
context
---
We want to use the confirmation screen to add valuable resources to the confirmation screen

mockup
---
view [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=9425%3A23731&t=Iw0rF69aIFEtYBYm-1)
<img width="721" alt="Bildschirm­foto 2023-03-08 um 09 31 55" src="https://user-images.githubusercontent.com/46345125/223662714-bd583b5f-39c1-417d-82de-92abb920ca52.png">

**Comment by Siddhant-K-code** [comment]
@chrifro Can you please clarify the user flow & when this screen should popup is it something we already have, if yes then please add that screenshot OR do we need to introduce a new endpoint that would appear when a user submits "Sales" or "Support" form?

**Comment by chrifro** [comment]
Sure sorry for the missing context.

The screen already exists. You can see it when you submit a form e.g. the contact or sales form. Right now it only says "thanks for contacting us". With this issue, I'd like to add additional resources and a slight update to the design. 

This is a screenshot of the status quo
<img width="1451" alt="Bildschirm­foto 2023-03-10 um 11 25 55" src="https://user-images.githubusercontent.com/46345125/224292327-a22e25a1-8bbc-45b2-89d5-b2984ac31f99.png">
