### ISSUE TITLE
Bring links to /get-demo back

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3505]
**Context**
Based on an [internal discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1678367023285289), we decided to revert the change to swap all "get demo" CTAs to "talk to an expert".

**Required changes**

- [ ] swap CTA in the call-out section from "talk to an expert" to "get demo". The change was introduced in #3430 
- [ ] swap CTA in the navigation bar for new users from "talk to an expert" to "get a demo"

<img width="1376" alt="Bildschirm­foto 2023-03-09 um 14 31 48" src="https://user-images.githubusercontent.com/46345125/224038205-4be98eaf-9f6f-434c-ab3b-404d64c720be.png">

- [x] swap CTA on the homepage from "talk to an expert" to "get demo"
<img width="503" alt="Bildschirm­foto 2023-03-09 um 14 45 17" src="https://user-images.githubusercontent.com/46345125/224043815-cd05bd74-c6ad-411b-aa11-e32ad0c528c8.png">

**Comment by Siddhant-K-code** [comment]
Related https://github.com/gitpod-io/website/pull/3506
