### ISSUE TITLE
Add KubeCon EU 2023 under `/events`

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#3518]
- Create a new page `/events/kubecon-amsterdam`
- Update information based on content here [[1](https://www.notion.so/gitpod/Create-KubeCon-EU-2023-page-565cb15ef3954b2cba7eeebf2fcf93dd?pvs=4)]
- Update `/events` to add KubeCon EU 2023

See internal discussion [[2](https://gitpod.slack.com/archives/C04BGDL7NVD/p1678822135177039)]

**Comment by MichaelAring** [comment]
Suggest we keep it simple and only create a scheduling page (see [internal comment](https://www.notion.so/gitpod/Create-KubeCon-EU-2023-page-565cb15ef3954b2cba7eeebf2fcf93dd) and [new internal task](https://www.notion.so/gitpod/Add-scheduling-page-to-website-9c19acddc67a42dd84264b3217cf92e8))
