### ISSUE TITLE
Add scheduling page to website

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3521]
For more context see [Notion](https://www.notion.so/gitpod/Add-scheduling-page-to-website-9c19acddc67a42dd84264b3217cf92e8)

calendly embed link: https://calendly.com/d/yyt-j28-84m

**Comment by chrifro** [comment]
@Siddhant-K-code could you look into this? :)

**Comment by Siddhant-K-code** [comment]
what should be the endpoint (url) for the page? any preferences?

something like `/kubecon-demo` or `/gitpod-kubecon-demo` ?

**Comment by chrifro** [comment]
Let's use `/kubecon-demo-eu23`
