### ISSUE TITLE
[mobile] content is wider than the screen

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#354]
- [ ] on 6 pages the content is wider than the screen e.g. because of an embedded video or code snippets (https://www.gitpod.io/blog/opensource, https://www.gitpod.io/blog/docker-in-gitpod, https://www.gitpod.io/docs/self-hosted/latest/install/configure-ingress, https://www.gitpod.io/docs/self-hosted/latest/install/storage, https://www.gitpod.io/blog/open-vsx-in-gitpod, https://www.gitpod.io/docs/self-hosted/latest/install/database)

- [ ] on the same pages some text is too small to read and clickable items are too close to each other

For more information, see https://search.google.com/search-console/mobile-usability?resource_id=https%3A%2F%2Fwww.gitpod.io%2F&hl=de

**Comment by estelle** [comment]
Should be fixed in #367, but not closing with that since i need to confirm.

**Comment by nisarhassan12** [comment]
> For more information, see https://search.google.com/search-console/mobile-usability?resource_id=https%3A%2F%2Fwww.gitpod.io%2F&hl=de

Thanks, @ChristinFrohne for reporting this. I can't access the link you shared with my Gitpod email. 
![image](https://user-images.githubusercontent.com/46004116/122699586-18869300-d263-11eb-8d9a-02f0c7c6117e.png)

>  on the same pages some text is too small to read and clickable items are too close to each other

Can you please point out some specific areas here ? Thanks

Some of the things that I could be about are the following I guess we don't want to increase them and they are fine the way they are:

![image](https://user-images.githubusercontent.com/46004116/122699908-bf6b2f00-d263-11eb-8e61-9ea552afa830.png)

![image](https://user-images.githubusercontent.com/46004116/122699959-d6118600-d263-11eb-97a1-a5fce79f7694.png)

The above that is way smaller than 48px by 48px which is the least size for clickable items by google.

**Comment by ChristinFrohne** [comment]
The issue "text is too small to read it" seems to be related to content is wider than the screen. Let's fix that first and see.

**Comment by nisarhassan12** [comment]
>  Let's fix that first and see.

@ChristinFrohne I have fixed some of the issues regarding this i.e the ones on the docs and blog. Can you test again and share if the results are better now ? or else we look into these things specified here https://github.com/gitpod-io/website/issues/354#issuecomment-864682032  Thanks

**Comment by ChristinFrohne** [comment]
they are now 16 pages with either content wider than the screen, text too small, or clickable elements that are too close to each other. I guess these issues correlate to each other.

Example:
on https://www.gitpod.io/docs/self-hosted/latest/install/troubleshooting/
code snippets are cut on mobile
<img width="368" alt="Bildschirmfoto 2021-06-30 um 11 15 29" src="https://user-images.githubusercontent.com/46345125/123935820-dcef7580-d994-11eb-9325-3892ea904ea7.png">


Here is an overview of all 16 pages with these issues:
<img width="457" alt="Bildschirmfoto 2021-06-30 um 11 15 41" src="https://user-images.githubusercontent.com/46345125/123935892-f0024580-d994-11eb-80a4-396ad02e6429.png">

**Comment by estelle** [comment]
Do you need my help?

**Comment by nisarhassan12** [comment]
Thanks, @estelle Sorry I forgot to unassign you here I'm already working on it.

**Comment by ChristinFrohne** [comment]
@nisarhassan12 this issue is now fixed according to Google Search Console 🎉
