### ISSUE TITLE
(Docs) Preview on Google does not show for docs page

### ISSUE THREAD

**Issue by MichaelAring** [gitpod-io/website#3554]
### Page URL

https://www.gitpod.io/docs/configure/workspaces/multi-repo

### Description

See issue below

<img width="850" alt="Screenshot 2023-03-29 at 19 01 38" src="https://user-images.githubusercontent.com/99804441/228613844-ea7de381-11db-41d3-a1d4-6aa3db7e1108.png">

**Comment by Siddhant-K-code** [comment]
Related #3336. Will work on this early next week

**Comment by Siddhant-K-code** [comment]
I looked deeper into this & From the Search console, and all looks good. I've requested re-indexing also. It should be

![Image](https://user-images.githubusercontent.com/55068936/231091336-f98a5792-ae05-449c-8dd6-fccfd05673a8.png)
