### ISSUE TITLE
[docs] Missing oEmbed / OpenGraph tags: description, image

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#356]
When I share a link like https://www.gitpod.io/docs/life-of-workspace#garbage-collection in [our community](https://community.gitpod.io), it creates the following preview:

<img width="695" alt="Screenshot 2021-04-12 at 10 19 00" src="https://user-images.githubusercontent.com/599268/114363353-97cb5c80-9b78-11eb-8909-70f1fb66dd6d.png">

As you can see, the preview is broken, because of missing oEmbed / OpenGraph tags: `description` and `image`.

**Comment by nisarhassan12** [comment]
I'm not able to reproduce this looks like it is already fixed.
![Screen Shot 2021-05-25 at 4 41 23 PM](https://user-images.githubusercontent.com/46004116/119492067-17536a80-bd78-11eb-992b-deb71085b318.png)
