### ISSUE TITLE
Improve navigation bar drop down

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3571]
|how it looks| how it's supposed to look (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=9373%3A22681&t=fI35tgLnTFzKluda-1))|
|-|-|
|<img width="1436" alt="Bildschirm­foto 2023-04-17 um 09 21 41" src="https://user-images.githubusercontent.com/46345125/232413763-e02963cb-0868-4c1b-a4e8-27b82ad51b04.png">|<img width="865" alt="Bildschirm­foto 2023-04-17 um 09 22 57" src="https://user-images.githubusercontent.com/46345125/232413809-e84bab7d-1731-461d-bb32-2a2cfee0308f.png">|
|<img width="1432" alt="Bildschirm­foto 2023-04-17 um 09 21 54" src="https://user-images.githubusercontent.com/46345125/232413864-cc84db7e-ce53-45d6-a9c1-faf933102c53.png">|<img width="866" alt="Bildschirm­foto 2023-04-17 um 09 23 10" src="https://user-images.githubusercontent.com/46345125/232413919-bc852caf-97f5-4bb8-a663-1c4c71efd42c.png">

**Changes**

- [ ] align card heights (customer card doesn't align)
- [ ] align spacing e.g. before the templates
- [ ] align card width closer to the mockup (break community text into two lines)

**Comment by chrifro** [comment]
- can you use the same component style for the items under "resources" and "solutions". Currently they have a different width and different spacing between the links. The style under resources looks great, let's adjust the "solution" items to it
<img width="393" alt="Bildschirm­foto 2023-04-18 um 16 22 20" src="https://user-images.githubusercontent.com/46345125/232807948-434e3250-3372-4864-966f-723644e07887.png">
<img width="359" alt="Bildschirm­foto 2023-04-18 um 16 22 26" src="https://user-images.githubusercontent.com/46345125/232807952-9c2d8c73-d448-4572-803c-d97d4040b503.png">

- reduce the bottom spacing under "resources"
<img width="704" alt="Bildschirm­foto 2023-04-18 um 16 22 53" src="https://user-images.githubusercontent.com/46345125/232807856-c58066aa-bd24-406d-b11b-c1196f733d91.png">

**Comment by chrifro** [comment]
Both drop downs still have differnt starting positions. Could you align them to the left so that they both start below "CDE"?
![Bildschirm­foto 2023-04-20 um 07 27 28](https://user-images.githubusercontent.com/46345125/233266853-fba7fc8a-d8fa-411f-b2fc-0788512ce632.png)
![Bildschirm­foto 2023-04-20 um 07 27 19](https://user-images.githubusercontent.com/46345125/233266869-a18c975d-555b-454a-b50b-f81e439775e5.png)

**Comment by Siddhant-K-code** [comment]
> Could you align them to the left so that they both start below "CDE"?

It would be tricky and would be difficult to make it responsive

**Comment by Siddhant-K-code** [comment]
@chrifro Preview on 14" Screen: 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/55068936/233267779-18f1fa62-b5c4-43e0-ac82-1ba581c3bd2f.png">
