### ISSUE TITLE
Update GitLab brand images on sub websites 

### ISSUE THREAD

**Issue by dnsmichi** [gitpod-io/website#3573]
## Problem to solve 

Some sites use the old GitLab brand image and should be updated to using the current branding. https://about.gitlab.com/press/press-kit/ - https://design.gitlab.com/brand/overview 

- https://www.gitpod.io/media-kit  Media/Press kit at the bottom, old GitLab.com screenshot. => https://www.gitpod.io/images/blog/gitlab-integration/gitpod-button-on-gitlab.png 

![image](https://user-images.githubusercontent.com/382049/232516659-cc03eae5-0c54-4e75-9624-47989ba80d05.png)

- https://www.gitpod.io/vs/github-codespaces  - the logo in the "open source" circle. Seems to be SVG rendered. 

![image](https://user-images.githubusercontent.com/382049/232516171-bbc3df08-792a-450f-a2d5-231ad1ea1861.png)

Maybe there is more; I had these specifically opened while reading some Discord messages. 

The front website uses the current GitLab branding already. https://www.gitpod.io/ 

## Suggestion 

- [ ] Update the images / screenshots 
- [ ] Review existing website for more branding updates

**Comment by Siddhant-K-code** [comment]
cc: @chrifro

**Comment by chrifro** [comment]
Thanks for the lookout @dnsmichi 😊

@Siddhant-K-code let's update the logo in the "open source" section. For the screenshot, it's more involving swapping it. I'll keep it in mind when we are updating them.

**Comment by Siddhant-K-code** [comment]
I've updated some other occurrences in #3586. Regarding that "Open Source" section^. It's an  SVG. @chrifro We need to update in figma file then we can use that SVG here.

**Comment by chrifro** [comment]
Done, see [Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=3509%3A2672&t=cNSPHcdTfrPii4pU-1)
