### ISSUE TITLE
Integrate weekly visitor report

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3611]
For more details see the [internal discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1682456836445339)

**Comment by Utkarshn10** [comment]
Hey @chrifro , would love to take a look at the discussion, so that I can contribute further. But currently I can't access the internal discussion with my account. Could you help?

**Comment by Siddhant-K-code** [comment]
Hey @Utkarshn10, Thanks for showing your interest in this 🧡. We are still in the discussion of what we have right now & how we can integrate this. Will write the details here once we are done with our discussion.

**Comment by Siddhant-K-code** [comment]
We decided to not integrate this for now. (see internal [conversation thread](https://gitpod.slack.com/archives/C01KGM9ETU6/p1685113745002569?thread_ts=1682456836.445339&cid=C01KGM9ETU6))
