### ISSUE TITLE
Help with Gitpod config

### ISSUE THREAD

**Issue by JacobGoldenArt** [gitpod-io/website#3619]
Hi, I'm trying to set up a gitpod cofig file so that I can have a prebuild env with all of my dependencies installed when I create a new project. Here's what I make using. gp init command. when I ran gp validate it opened up a new gitpod and I could see that it had a shell for each name, it ran poetry env use 3.10 but I still had to run poetry install. Can someone have a look and let me know if I'm setting this up incorrectly? Thanks!

```
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Environment
    init: |
     pyenv install 3.10 
     pyenv local 3.10.9
  - name: Brew setup
    init: |
      brew install portaudio
      brew install ffmpeg
      sudo apt install python3-pyaudio
      pip install --no-use-pep517 playsound==1.3.0
  - name: Poetry setup
    init: |
      poetry env use 3.10
      poetry shell
      poetry install
```

**Comment by axonasif** [comment]
Hi @JacobGoldenArt 👋 

Please join our community server and ask this question there, I'll be happy to help:
- https://gitpod.io/chat
