### ISSUE TITLE
[example workspace mobile] reduce corner radii on buttons

### ISSUE THREAD

**Issue by nchristowitz** [gitpod-io/website#364]
Should match the git repo buttons in the module above

![IMG_4375](https://user-images.githubusercontent.com/48205934/114568370-5ae49000-9c74-11eb-9ef7-bc7ba992f74d.jpg)

**Comment by patriciaehrenreich** [comment]
Hello, can I work on this?

**Comment by gtsiolis** [comment]
Go for it @patriciaehrenreich! Feel free to ping `@mikenikles` or `@nisarhassan12` once you open a PR with a fix. 🏓

**Comment by patriciaehrenreich** [comment]
I will, thank you! :)

**Comment by patriciaehrenreich** [comment]
@gtsiolis @mikenikles @nisarhassan12 I opened the PR. If something else needs to be done, please let me know.
