### ISSUE TITLE
mobile issues

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/website#366]
- [x] Features, don't show the small feature boxes on mobile
 - [ ] Fix issues with graphics on start page (e.g. cropped top and no graphic on "With gitpod")
 - [x] remove superfluous height on graphics
<img width="346" alt="Screenshot 2019-12-25 at 12 07 47" src="https://user-images.githubusercontent.com/372735/71444060-2f503600-270f-11ea-8ec0-a7dbef197842.png">
 - [ ] Align padding of nav logo and burger menu (with rest of side)
<img width="364" alt="Screenshot 2019-12-25 at 12 08 42" src="https://user-images.githubusercontent.com/372735/71444103-6a526980-270f-11ea-98cd-718f7f9ea267.png">
- [ ] Center buttons and graphics
<img width="427" alt="Screenshot 2019-12-25 at 12 10 48" src="https://user-images.githubusercontent.com/372735/71444169-a685ca00-270f-11ea-8d0b-18900bc43f50.png">

**Comment by nisarhassan12** [comment]
> - [ ] Center buttons and graphics 

@svenefftinge Do you mean all the buttons on the site?

**Comment by ChristinFrohne** [comment]
![Button](https://user-images.githubusercontent.com/46345125/71514989-68201480-28a1-11ea-8269-0674e2b7dadb.JPG)

Maybe it would be best to delete the "with Gitpod" and "ordinary way" button on mobile view. If you already scrolled too far down you won't see the image changing. So I suggest just having the default image.

**Comment by ChristinFrohne** [comment]
Missing issues have been added to #413
