### ISSUE TITLE
Adjust feature overview

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#369]
- [x] have the second row with the four features aligned in the center

- [ ] the thought was to have all icons gray and to only use the galaxy background on hover. I feel the site has currently too many blue elements which makes it harder to find a focus

- [x] All explaining boxes should have a white background. Currently the bubbles of the image with the programming languages are not noticeable on the gray background 
![bubbles](https://user-images.githubusercontent.com/46345125/71511216-d066fa00-2891-11ea-8ffa-c29355e70259.JPG)

**Comment by nisarhassan12** [comment]
- [ ] the thought was to have all icons gray and to only use the galaxy background on hover. I feel the site has currently too many blue elements which makes it harder to find a focus

These were initially grey when we added the SVG backgrounds and they had a hover effect also which reveals the SVG background but it was quite glitchy so we removed it.
