### ISSUE TITLE
Small Fixes 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#370]
- [x] Pricing, Enterprise: Learn more button isn't blue on hover

- [x] scroll should only be visible if I need to scroll
![table-scroll](https://user-images.githubusercontent.com/46345125/71511873-2b99ec00-2894-11ea-83cd-0f650dd14d63.JPG)

**Comment by ChristinFrohne** [comment]
- [ ] Education and Enterprise have the same image and the image is cut at the top

- [ ] wrong image for recruiting page

- [ ] index page: contribute.dev button doesn't turn blue on hover

- [ ] features: Works on any device: Chromebook image is cut

**Comment by nisarhassan12** [comment]
So far not able to find the why the image is cut at the top though i have replaced the education image.
![image](https://user-images.githubusercontent.com/46004116/73063639-1333e600-3ec1-11ea-9017-25ce156586dd.png)

![image](https://user-images.githubusercontent.com/46004116/73063735-4d9d8300-3ec1-11ea-8b25-aca7e805342c.png)
