### ISSUE TITLE
Change 'certified' to 'compliant' in GDPR badges

### ISSUE THREAD

**Issue by taliamoyal** [gitpod-io/website#3705]
### Description

Please update the GDPR badge to say GDPR compliant instead of certified! Thank you :)

[
![image](https://github.com/gitpod-io/website/assets/42979276/78e9bc82-d435-4b28-a612-464b055fdaa7)
](url)

**Comment by Siddhant-K-code** [comment]
@chrifro we would require a new image for this (same for dark mode).
