### ISSUE TITLE
SEO Improvements

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#372]
- [x] Meta description is outdated, a bit too short and should include the most important keywords
It might be reasonable to continue using "online IDE" in the meta description as this was one of Gitpods main keywords and people should be still be able to find Gitpod this way. Suggestion: 

>Gitpod is an online IDE that launches ready-to-code development environments for your GitHub or GitLab project with a single click.<

- [x] URL resolve 
no 301 redirects are in place to redirect traffic to your preferred domain. Pages that load successfully both with and without www. are treated as duplicate content! We can use `rel="canonical" ` tag to tell the search engine which is the definitive version.

- [x] update `<title>` tag for start screen: "Gitpod - Your ready-to-code dev environment for GitHub or GitLab"

- [x] add a unique description to each site. For example: 
Education: "Gitpod simplifies the onboarding process, makes coding accessible from any device and provides a productive learning environment."
Blog: "Discover Articles and Tutorials about Gitpod"
Pricing: "Whether you would like to use Gitpod for open-source contribution or professionally for your self or in a team, here you can find your subscription."
Enterprise: "Adding Gitpod to your development tools means less waiting, no tedious setups, faster onboarding, higher code quality and a smoother workflow."

- [x] A site tracker said that there are more than on `<title>` tag on almost every site. We should check that

- [x] `<h1>` is missing on the blog site and pricing. Replace `<h2> ` with `<h1>  `

- [x] robots.txt file and a XML sitmap inside robots.txt is missing

- [x] Use hypens (-) instead of underscores (_) in URLs 
Google prefers hypens in URLs as it ignores underscores and then reads the URL as one words. This has a bad impact on SEO

- [ ] Mobile optimazation: website loads 7 javascript files. This might effect the loading time. 

- [x] Blog "Continuous dev environments"  has another canonical URL content than its URL-adress

- [ ] Add schema.org
![schema-org](https://user-images.githubusercontent.com/46345125/71516842-7d01a580-28ab-11ea-98cf-2c0ba50b014e.JPG)

- [ ] asset cacheability
![cache](https://user-images.githubusercontent.com/46345125/71516859-a15d8200-28ab-11ea-8c69-a6a5ce355999.JPG)

 
additional aspects from #202
- [x] using keywords in alt-tags for images

- [x] if using bold fonts, highlighting keywords with it

**Comment by jankeromnes** [comment]
> URL resolve
> no 301 redirects are in place to redirect traffic to your preferred domain. Pages that load successfully both with and without www. are treated as duplicate content! We can use rel="canonical" tag to tell the search engine which is the definitive version.

We already have both `30X` redirects and `rel="canonical"` tags. Could you please be specific about which redirections or canonicals are missing?

**Comment by jankeromnes** [comment]
> Use hypens (-) instead of underscores (_) in URLs
> Google prefers hypens in URLs as it ignores underscores and then reads the URL as one words. This has a bad impact on SEO

We already use hyphens pretty much everywhere. Please mention the specific URLs that have underscores.

**Comment by ChristinFrohne** [comment]
>We already use hyphens pretty much everywhere. Please mention the specific URLs that have underscores.

Underscores are used for almost all links in the documentation e.g. https://www.gitpod.io/docs/10_getting_started/, https://www.gitpod.io/docs/50_ide/

**Comment by ChristinFrohne** [comment]
>>URL resolve
no 301 redirects are in place to redirect traffic to your preferred domain. Pages that load successfully both with and without www. are treated as duplicate content! We can use rel="canonical" tag to tell the search engine which is the definitive version.

>We already have both 30X redirections and rel="canonical" tags. Could you please be specific about which redirections or canonicals are missing?
@jankeromnes 
Website checkers are noticing problems for http://gitpod.io/ and https://www.gitpod.io/, also a warning comes up that the canonical tag for the blog post Continuous Dev Environments isn't equal to the URL

**Comment by jankeromnes** [comment]
> Website checkers are noticing problems for http://gitpod.io/ and https://www.gitpod.io/

Thanks for catching these! Which checkers are you using?

Also, could you please copy/paste all the problems that they found?

**Comment by jankeromnes** [comment]
> also a warning comes up that the canonical tag for the blog post Continuous Dev Environments isn't equal to the URL

Thanks for mentioning that. Could you please also provide a screenshot of the warning? (Or copy/paste the error message.)

When I check https://www.gitpod.io/blog/continuous-dev-environment-in-devops/ it seems to be fine:

![Screenshot_20200106-075856](https://user-images.githubusercontent.com/599268/71801676-e461e700-305b-11ea-858e-d468e306873e.png)

**Comment by ChristinFrohne** [comment]
I mostly used https://www.woorank.com/en and https://sitechecker.pro/

The error message from sitechecker.pro is:
>Canonical ≠ URL
>URLs those have another canonical URL content than its URL-adresss

**Comment by jankeromnes** [comment]
Ah, I was hoping for very explicit URLs showing what exactly is different. I'll try to see if I can get these checkers to be more explicit. Thanks!

**Comment by jankeromnes** [comment]
I wasn't able to reproduce that specific error, but I got something canonical-related from sitechecker.pro:

<img width="1106" alt="Screenshot 2020-01-06 at 09 02 15" src="https://user-images.githubusercontent.com/599268/71804376-94871e00-3063-11ea-9c9b-494cf40e2931.png">

However, I don't get it, because the canonicals of these pages are correct (they 301-redirect to URLs with a final `/`, which all have correct canonical tags -- I just checked).

But I fixed the canonicals only recently. I wonder whether maybe sitechecker.pro analyzed the website before my fixes, and still lists old problems.

**Comment by ChristinFrohne** [comment]
@jankeromnes I checked the pages with another tool and that said that all canonical tags are there. So I think, we can just ignore this message. Thanks for looking into it :)

**Comment by jankeromnes** [comment]
Awesome, thanks for double-checking! (Canonical URL problems can really hurt our search engine ranking, so it's good to be extra careful there. 👍)

**Comment by jankeromnes** [comment]
> Meta description is outdated[...] Suggestion:
>
> > Gitpod is an online IDE that launches ready-to-code development environments for your GitHub or GitLab project with a single click.

I really like the essence of this suggestion, but I also think that it should be as short as possible (because the more text there is, the less likely I am to read it 😅)

Maybe it can be shortened like so?

> Gitpod is an online IDE for GitHub and GitLab. Launch ready-to-code dev environments in one click.

**Comment by ChristinFrohne** [comment]
>Online IDE for GitHub and GitLab. Launch ready-to-code dev environments in one click.

I like it! But it should contain Gitpod as well. I'll do a pull request with updated meta descriptions, would be great if you can review it :)

**Comment by ChristinFrohne** [comment]
Continues here #561
