### ISSUE TITLE
Cookies banner is overlapping content in some cases

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#373]
### Problem to solve

The cookies banner is overlapping some content in some cases.

| Footer | Screencasts |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/114699558-22eb5480-9d29-11eb-9532-9802b77cc9a3.png) | ![image](https://user-images.githubusercontent.com/120486/114699508-12d37500-9d29-11eb-8a6c-d00184767b06.png) |

**Comment by bastianjakobi** [comment]
I'd be happy to look into this if you need any help.

**Comment by gtsiolis** [comment]
Absolutely @bastianjakobi! This seems to be a low hanging fruit. Feel free to pick this up and open a PR with a fix. 🏓

**Comment by bastianjakobi** [comment]
@gtsiolis Sounds good! I'll try to come up with a fix and open a PR.

**Comment by asharonbaltazar** [comment]
@bastianjakobi Hey, are you still working on this? If not, I'd like to take over.

**Comment by bastianjakobi** [comment]
@asharonbaltazar Hi,I'm still working on it. I'll let you know know if I need any help though!

**Comment by bastianjakobi** [comment]
#408 @mikenikles @nisarhassan12 This PR should fix the issue. Please let me know if there are any concerns with this solution.

**Comment by nisarhassan12** [comment]
Closing this as I have not found any place where it exists anymore please re-open if I missed any place where the issue happens.
