### ISSUE TITLE
REQUEST: Dark theme for www.gitpod.io

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/website#374]
I've noticed that gitpod.io is now in light theme, requesting dark theme option for people suffering from photophobia and people like me with huge screen that blinds them everytime they open a light themed window.

**Comment by nisarhassan12** [comment]
@ChristinFrohne Can you provide me with the colours that we're gonna use for the dark version of the site?

**Comment by Kreyren** [comment]
![gitpod_colors](https://user-images.githubusercontent.com/11302521/77642973-d8047080-6f5e-11ea-8f22-149efbd6d3fc.png)


![image](https://user-images.githubusercontent.com/11302521/77642960-cf139f00-6f5e-11ea-9a08-d36cb0a804c7.png)
@nisarhassan12 

![image](https://user-images.githubusercontent.com/11302521/77642999-e5b9f600-6f5e-11ea-8b63-27f44fc3ccb2.png)

![image](https://user-images.githubusercontent.com/11302521/77643053-f8ccc600-6f5e-11ea-8249-23d6ce34affd.png)

Alternatively OLED optimization
![image](https://user-images.githubusercontent.com/11302521/77643108-0f731d00-6f5f-11ea-9477-8cb100099fc8.png)

**Comment by Kreyren** [comment]
@nisarhassan12 Also note https://darkreader.org/ which can be used to preview the colors in real time. 

Extension is using an algorithm to convert pages in preferred color palette in real time. (used for examples above)

**Comment by ChristinFrohne** [comment]
The page would need a lot more adjustments than just changing colors. Many graphics need to be adjusted and the galaxy background doesn't work well with a dark theme. Of course, it's doable but it takes quite some effort. As I'm currently loaded with other work and I don't think the dark theme is essential to have right now, I would rather address this issue at a later point. 
What do you think @jankeromnes @svenefftinge?

**Comment by Kreyren** [comment]
> Many graphics need to be adjusted @ChristinFrohne 

@ChristinFrohne i don't see any other graphics that would need change for this implementation.

> and the galaxy background doesn't work well with a dark theme.  @ChristinFrohne 

![image](https://user-images.githubusercontent.com/11302521/77651367-fa04ef80-6f6c-11ea-9b70-d0d0365cba35.png)

Agree

**Comment by ChristinFrohne** [comment]
If you @Kreyren and @nisarhassan12 have time to implement a dark theme, then that would be great, of course. I just don't have a lot of capacity to help out. 
looking now at the dark theme, I notice that some graphics have never been formatted the right way. E.g. the ice cream of `features` shouldn't have a white filling, some images have white borders, some don't. 

As a solution for the galaxy images, I would suggestion using a bright borders just like in the graphics on features, `create snapshot`.

Some other images need adjustments like to GitHub logo on index in `seamless GitHub GitLab integration`

For the colors, I'd recommend a greater difference. What about #424242 and #313131

**Comment by Kreyren** [comment]
> If you @Kreyren and @nisarhassan12 have time to implement a dark theme, then that would be great, of course. I just don't have a lot of capacity to help out.

I don't know how to implement the switch that would change the page from light to dark theme, but i would be willing to adapt the colors and graphics assuming that i get time frame on it (which i should since Czech republic is under quarantine).

**Comment by ChristinFrohne** [comment]
Awesome, thanks a lot! Maybe @nisarhassan12 could help out with implementing the switch? 
Stay safe 🍀

**Comment by nisarhassan12** [comment]
Ok. Thanks! @Kreyren @ChristinFrohne  I will implement this in the next week.

**Comment by nisarhassan12** [comment]
@Kreyren @ChristinFrohne Sorry! One week became more a month.I'm about to start working on it but I'm not sure whether it would be best to use a theme switcher or [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query which can be toggled from `System Preferences` > `General` > `Appearance` (Mac OS).

And if we want to use a theme switcher @ChristinFrohne Where should I put that in the Layout?

**Comment by Kreyren** [comment]
> use a theme switcher or prefers-color-scheme media query which can be toggled from @nisarhassan12 

Note:
![image](https://user-images.githubusercontent.com/11302521/81229233-c1d2e100-8fef-11ea-970d-23c7716514ce.png)

So that woudn't be usable for me assuming that it conflicts with privacy, but i like the idea.

FWIW i generally prefer light theme when i woke up and dark them when i am preparing to go sleep.

**Comment by nisarhassan12** [comment]
> And if we want to use a theme switcher @ChristinFrohne Where should I put that in the Layout?

@ChristinFrohne please look at https://github.com/gitpod-io/website/issues/374#issuecomment-624857047 whenever you'll have time. Thanks.

**Comment by ChristinFrohne** [comment]
What do you think about adding it to the footer?
<img width="1067" alt="Bildschirmfoto 2020-05-18 um 11 05 08" src="https://user-images.githubusercontent.com/46345125/82194690-7e357c80-98f7-11ea-822c-a24b4e577042.png">

**Comment by Kreyren** [comment]
> What do you think about adding it to the footer?

LGTM, but i think that requires scrolling through the whole site to set on dark theme which may be annoying in a dark room

**Comment by Kreyren** [comment]
What about something somewhat hidden alike small switch in the navbar? 
![image](https://user-images.githubusercontent.com/11302521/82195751-06685180-98f9-11ea-9057-11fd7d90dbe6.png)

**Comment by ChristinFrohne** [comment]
I'd like to keep the navbar as clean and simple as possible and focus on content. Too many things to click on can be distracting. 

Can we save the dark-light theme setting in cookies so that you don't have to scroll down every time?

**Comment by Kreyren** [comment]
> Can we save the dark-light theme setting in cookies so that you don't have to scroll down every time?

That would be sufficient ^-^

**Comment by ChristinFrohne** [comment]
Let's postpone this issue until a later point
