### ISSUE TITLE
[Edit|Improve] this page links on the documentation

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#380]
If there was a spelling error then the community or Gitpoder should be able to "edit (propose changes via PR) this file on GitHub" from the page they are viewing.

**Comment by gtsiolis** [comment]
FWIW, We used to have something similar (see https://github.com/gitpod-io/retired-gatsby-website/pull/918 and https://github.com/gitpod-io/retired-gatsby-website/issues/905) but this was removed after the redesign.
