### ISSUE TITLE
Community Contributions "pagination" looks overwhelming

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#3808]
### Description

Related to #3807.

The community contributions section of [/community](https://gitpod.io/community) is starting to look overwhelming the more we add to it. 

<img width="1338" alt="CleanShot 2023-07-03 at 16 06 45@2x" src="https://github.com/gitpod-io/website/assets/17087373/d5eacb93-3400-4823-85ff-fc1ed41adb7f">

**Suggestions:**

1. 🛹 Change the month text from full months to numbers:

<img width="1145" alt="CleanShot 2023-07-03 at 16 10 03@2x" src="https://github.com/gitpod-io/website/assets/17087373/81de0e00-9838-4ceb-900c-c8d143b667c7">

2. Implement a slider?
3. Implement a dropbox?

CC @chrifro you may have better design ideas
CC @ghostdevv for info (no action needed for now)

**Comment by ghostdevv** [comment]
This also ties into needing to start loading the data dynamically, since it's just going to exponentially grow

**Comment by pawlean** [comment]
Closing to move discussion to [Linear](https://linear.app/gitpod/issue/MKWEB-77/community-contributions-pagination-looks-overwhelming).
