### ISSUE TITLE
Screenshot radius is cropping the content on small viewports

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#386]
### Problem to solve

When viewing in small (mobile) viewports, the radius used for the editor screenshots is cropping the content.

![image](https://user-images.githubusercontent.com/120486/115288815-9098e580-a15a-11eb-8aeb-fb236eb271cd.png)

### Proposal

Using a smaller radius for the [`.screenshot`](https://github.com/gitpod-io/website/blob/605c47e16f1acbfc6dd87001b8b13bcd197c84ea/src/components/index/section-screenshot.svelte#L24) class could help.

```diff
diff --git a/src/components/index/section-screenshot.svelte b/src/components/index/section-screenshot.svelte
index aae364d..117d029 100644
--- a/src/components/index/section-screenshot.svelte
+++ b/src/components/index/section-screenshot.svelte
@@ -27,6 +27,7 @@
 
     @media (max-width: 768px) {
       margin-bottom: -20px;
+      border-radius: 0.25rem;
     }
   }
 
```

**Comment by asharonbaltazar** [comment]
Is this issue still up for grabs?

**Comment by mikenikles** [comment]
Yes, over to you :)

**Comment by asharonbaltazar** [comment]
@mikenikles, is there anything else I can work on? I have a whole day open. 

Thank you in advance.

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/website/pull/403. Thanks @asharonbaltazar @mikenikles! 🏀
