### ISSUE TITLE
screenshots in blog should consider recommendations for readibility

### ISSUE THREAD

**Issue by mi-hol** [gitpod-io/website#3863]
### Description

**Issue:**

https://www.gitpod.io/blog/boosting-developer-productivity-unleashing-the-power-of-sourcegraph-cody-in-gitpod has great information but unfortunately very hard to not readable at all screenshots. The 2 worst (meaning unreadable on a laptop screen) are: 

![image](https://github.com/gitpod-io/website/assets/22799428/e08a8a6e-d0f1-436a-96cb-554690c8c664)

**Solution:**

apply recommendations as outlined in [https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide](https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide
)

**Comment by Siddhant-K-code** [comment]
Sorry for the difficulties 🙏🏼. I've tried to make it a little better.

https://github.com/gitpod-io/website/assets/55068936/180e2302-e4f2-4efa-af75-d90305bd6974

**Comment by mi-hol** [comment]
A really great improvement!
