### ISSUE TITLE
Wrong title in documentation

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#387]
For example https://www.gitpod.io/docs/languages/php

Current title: `Gitpod Documentation` (not helpful e.g. when you're sharing this link to PHP developers)

Expected title: `PHP in Gitpod`

**Comment by asharonbaltazar** [comment]
Hello, can I try my hand at this? I don't see any instructions for setting up the `env`. If it's not a simple `npm i` `npm run dev`, then can you please share it here? Thank you.

**Comment by gtsiolis** [comment]
Absolutely @asharonbaltazar! Feel free to open a PR with a fix and ping `@mikenikles` or `@nisarhassan12` for a review. 🏓

**Comment by jankeromnes** [comment]
Hi @asharonbaltazar, yes please!

Also no need to worry about the setup -- it's all automated! 😇

You can simply open this repository in Gitpod, like so:

https://gitpod.io/#https://github.com/gitpod-io/website

This will give you a complete VSCode dev environment for this project, with the website already running in a preview. 🚀

**Comment by mikenikles** [comment]
Implemented in #389. Thank you @asharonbaltazar!
