### ISSUE TITLE
[Blog] Blog card problems

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#387]
In https://www.gitpod.io/blog/ there is a list of blog posts, with summary cards like this one:

<img width="346" alt="Screenshot 2020-01-08 at 10 17 39" src="https://user-images.githubusercontent.com/599268/71965549-2d52a080-3200-11ea-84ca-bfdc511d1a5c.png">

Problems to fix:
- [ ] The summary text omitted everything `formatted like code`, making it unintelligible. I think it should contain the `formatted text` as just simple text
- [x] Don't use the silly US date format ("wait, is this 1st of August or January 8th?"). Use something sensible like `2020-01-08` instead

**Comment by nisarhassan12** [comment]
@jankeromnes Does this format is ok ?
![image](https://user-images.githubusercontent.com/46004116/71977328-4f691480-323a-11ea-919f-0aa3f71a87ea.png)

**Comment by jankeromnes** [comment]
@nisarhassan12 Only the date format changed, right? Yes, this seems much better & less ambiguous. 🙂 Many thanks!

Personally, I prefer putting the date number before the month, and omitting the leading zero, like this: `8 Jan 2020`. But it's essentially the same fomat. Thanks for fixing it!

**Comment by nisarhassan12** [comment]
> The summary text omitted everything formatted like code, making it unintelligible. I think it should contain the formatted text as just simple text

Closing this as it no longer seems to be relevant.

![image](https://user-images.githubusercontent.com/46004116/92463952-e204ed80-f1e5-11ea-88da-0358b5bcdeb7.png)
