### ISSUE TITLE
New website is hard to log in to

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/website#393]
Login for returning users is **all the way at the bottom**?? - not sure how that is at all helpful

The try it button goes to an example - not login screen

**Comment by ChristinFrohne** [comment]
Hey @RDIL,
thanks for your feedback. You can also login via the `Go to App` button on the top right of every page.

**Comment by JesterOrNot** [comment]
But it couldn't hurt to move the login to the top

**Comment by jankeromnes** [comment]
There is a big login button at the top called `Go to app`. Sorry if that's confusing, maybe we should just call it `Login`?

**Comment by RDIL** [comment]
Yeah

**Comment by jankeromnes** [comment]
Done. 🙂
