### ISSUE TITLE
Outdated docs: Gitpod create one VPC, not four

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/website#3966]
### Page URL

https://www.gitpod.io/docs/gitpod-dedicated/guides/getting-started

### Description

I belive Gitpod only creates one VPC, not four:

https://github.com/gitpod-io/website/blob/6c34cba1418c09245ccf855cbc6e5c88c5a7edb7/src/content/docs/gitpod-dedicated/guides/getting-started.md?plain=1#L51

**Comment by Siddhant-K-code** [comment]
cc: @lucasvaltl

**Comment by meysholdt** [comment]
My mistake: The line describes quota requirements, not the actual VPCs Gitpod creates.
