### ISSUE TITLE
Embed Tweet component that generates the tweets at build time from IDs. 

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#400]
We need an embed tweet component that's something like...

`tweet: <$id>`

**Comment by nisarhassan12** [comment]
Thanks. for the issue we use to have the tweet embeds on our old website but removed that becuase of some performance reasons see for more info https://gitpod.slack.com/archives/C01KGM9ETU6/p1603818450009300?thread_ts=1603810899.008500&cid=C01KGM9ETU6

**Comment by nisarhassan12** [comment]
Thanks to @mikenikles for the following idea

> However, a much better approach is to develop something where we can provide a list of tweets and we fetch the tweet at build time. Then we don’t have to copy & paste the tweet content and create HTML manually.

**Comment by mikenikles** [comment]
There are two requirements:
1. What Geoff mentioned initially: A way to quickly embed a tweet in Markdown (i.e. the docs or a blog post)
2. A way to render tweets such as the testimonials

Both are closely related and we can track them in the same issue.

**Comment by mikenikles** [comment]
FYI, https://github.com/gitpod-io/website/issues/2323#issuecomment-1168831482

**Comment by Siddhant-K-code** [comment]
[Possible Solution](https://www.swyx.io/the-hard-problem-of-rendering-tweets/) suggested by Jacob.

But, It has a blocker to use `BEARER_TOKEN` (can [get it from here](https://developer.twitter.com/apitools/api?endpoint=/2/tweets&method=get)). but, it comes with a limitation to have a specific tweets/month rate. & Some parameters are in premium API keys. It will require some more effort.
