### ISSUE TITLE
Close button overlaps content on smaller screens

### ISSUE THREAD

**Issue by asharonbaltazar** [gitpod-io/website#404]
I'm unsure if there's a duplicate issue, despite my quick glance at the issues, so if it is, just delete this 😋.
While I worked on PR #403, I noticed the close button (X) in the top banner overlapped content on smaller screens. 

![image](https://user-images.githubusercontent.com/58940073/115979876-1a2b2780-a54e-11eb-90d4-e6278a813325.png)

If this issue isn't a duplicate, I'd like to be assigned it. Thank you.

**Comment by nisarhassan12** [comment]
Thanks @asharonbaltazar for reporting this please feel free to make a PR. 

For testing you can comment out line#7 and line#11 in https://github.com/gitpod-io/website/blob/main/src/routes/%24layout.svelte

**Comment by nisarhassan12** [comment]
Fixed in #443
