### ISSUE TITLE
Popovers do not have any focus state styles.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#407]
Popovers do not have any focus state styles i.e if you were to tab through the page when the focus is on one of the popover there is no visual feedback there and also I think the popover should reveal it contents on focus instead of having the user to press enter.
![image](https://user-images.githubusercontent.com/46004116/72719976-cab3ba00-3b9a-11ea-85bf-735c3aebef44.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Please help with how the focus styles  are gonna look visually?

**Comment by ChristinFrohne** [comment]
Let's display the tooltip automatically when the focus state is active on the icon. That's what you had in mind as well, isn't it?
