### ISSUE TITLE
Align graphics

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/website#412]
On the front page the graphics should be properly aligned with the buttons on the left.

Currently it looks like that.

<img width="1136" alt="Screenshot 2020-01-21 at 09 13 26" src="https://user-images.githubusercontent.com/372735/72786650-66423a80-3c2e-11ea-8421-9815312dbed2.png">

Also the horizontal alignment looks arbitrary.

**Comment by jbicker** [comment]
It was fixed once in this commit:
https://github.com/gitpod-io/website/commit/ffcd1f21afdd01df93c989367c122f7450786f16

**Comment by nisarhassan12** [comment]
Thanks! @jbicker I'm sorry! I think I broke it while I was working on this https://github.com/gitpod-io/website/issues/366 while fixing the following. 
![image](https://user-images.githubusercontent.com/46004116/72893174-3da76700-3d3a-11ea-8c58-4a997b65a4c6.png)

**Comment by jbicker** [comment]
I will fix that in https://github.com/gitpod-io/website/issues/430
