### ISSUE TITLE
[mobile issues] update

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#413]
- [x] Align padding of Gitpod logo and burger menu with rest of site #366

- [x] Add more spacing underneath the two buttons

![IMG_4347](https://user-images.githubusercontent.com/46345125/72791943-75c68100-3c38-11ea-98aa-d3a9ab8b6271.PNG)

- [x] Have less spacing around the open-source section
![IMG_4348](https://user-images.githubusercontent.com/46345125/72793234-7f50e880-3c3a-11ea-9144-2140a1032c94.PNG)

- [ ] Freecodecamp logo is sometimes displayed weirdly #347
![IMG_4349](https://user-images.githubusercontent.com/46345125/72793343-9db6e400-3c3a-11ea-90c5-0ad8b7ca9d84.PNG)

- [x] Use wider boxes for the pricing
![IMG_4350](https://user-images.githubusercontent.com/46345125/72793448-c0e19380-3c3a-11ea-832f-0ebb2b9027c7.PNG)

- [x] Have more spacing in the docs. Why not use the same layout for the spacing and boxes as for blog posts?
![IMG_4352](https://user-images.githubusercontent.com/46345125/72793522-de166200-3c3a-11ea-82da-4e9604ae0620.PNG)

- [x] Footer: have all navigation points centered

![IMG_4351](https://user-images.githubusercontent.com/46345125/72793474-c8a13800-3c3a-11ea-95d2-8c0b687f94e7.PNG)

**Comment by nisarhassan12** [comment]
> - [ ] Footer: have all navigation points centered

@ChristinFrohne All the navigation points are already centred the reason why external links seem to be left-aligned is that they have the transparent external link icon next to them which turns blue on hover. One solution would be to have the icon displayed even if there is no hover.

**Comment by ChristinFrohne** [comment]
Ah, I see. I like your solution of displaying the icon by default on mobile.

**Comment by nisarhassan12** [comment]
I don't have any clue why this happens 
![image](https://user-images.githubusercontent.com/46004116/73177949-1aadf600-4132-11ea-8952-13e56abdf856.png)
