### ISSUE TITLE
Properly redirect www.gitpod.io/#https://github.com/name/repo

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#43]
It seems that sometimes users try `www.gitpod.io/#` as URL prefix (instead of the correct `gitpod.io/#`).

Maybe we should detect and support that too with a simple JS redirect.

**Comment by svenefftinge** [comment]
Makes sense. Even better we could change the domain usage, such that the app is entirely below `app.gitpod.io` and the website can use `gitpod.io`. We would need to put the fragment detection into the index page of the website and forward to app accordingly.

**Comment by jankeromnes** [comment]
I think any `gitpod.io → app.gitpod.io / www.gitpod.io → gitpod.io` renaming is orthogonal to the website detecting app fragments and redirecting.

But on that note, personally as a Gitpod user I mostly care about the app, and I love that the URL is short. I don't like the idea of using a `app.` subdomain.

If we really want to make the website URL shorter, I think we should do it like CircleCI:
- `circleci.com` gives you the website with a `Go to app` link
- `circleci.com/dashboard` gives you the app

We could have something similar:
- `gitpod.io` website with `Go to app` link (or `Dashboard` or `Workspaces`)
- `gitpod.io/workspaces` gives you the app
- (`gitpod.io/#` prefix should never become longer)
