### ISSUE TITLE
[svg images] improve svg images

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#430]
@jbicker could you help out with adjusting the SVG images? 

- [x] Enterprise -Globe: cut image #370

- [x] Features - Notebook: cut image #370

- [ ] recovering your old PR with the optimized SVG images 

Currently, some images have a bad quality:

<img width="981" alt="Bildschirmfoto 2020-01-24 um 13 26 39" src="https://user-images.githubusercontent.com/46345125/73069111-305eb980-3ead-11ea-93ca-7c34ab11c64c.png">

**Comment by nisarhassan12** [comment]
Switching to https://www.gitpod.io/galaxy-big.jpg does not help with the zig-zack line this is how it looks It is a lot better than before though.
![image](https://user-images.githubusercontent.com/46004116/75420425-d3e23480-5959-11ea-828e-35629e5b4f10.png)

**Comment by nisarhassan12** [comment]
> - [ ] Enterprise -Globe: cut image #370

@ChristinFrohne  Can you provide me a new globe image without the Galaxy background?

**Comment by ChristinFrohne** [comment]
Let's delete the line then. Can you make the icons bigger instead. See mock-up
<img width="965" alt="Bildschirmfoto 2020-02-27 um 09 18 03" src="https://user-images.githubusercontent.com/46345125/75424998-16981280-5942-11ea-8523-618c19824be9.png">

It would also be nice if you can align the svg so that some of the purple background is visible.


[world-grey.svg.zip](https://github.com/gitpod-io/website/files/4260304/world-grey.svg.zip)

**Comment by ChristinFrohne** [comment]
Many images still have a bad quality. Please have another look at these icons:

- [ ] index: hourglass, target, graphic- automated dev environments

- [ ] features: ice, all characters, tablet, notebook, computer

- [ ] pricing: open-source logo

- [ ] Enterprise: world icon is cut

**Comment by nisarhassan12** [comment]
> - [ ] Enterprise: world icon is cut.

@ChristinFrohne Can you please provide me with a screenshot this is how it looks on my end. 
![image](https://user-images.githubusercontent.com/46004116/76312524-16f6bd00-62f5-11ea-8566-24e0999fe872.png)

**Comment by ChristinFrohne** [comment]
oh sorry, my mistake. It looks fine now :)

**Comment by nisarhassan12** [comment]
> oh sorry, my mistake. It looks fine now :)

Thanks :slightly_smiling_face:
