### ISSUE TITLE
embed service status of Gitpod into the website

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#431]
Here are the configuration options:

<img width="488" alt="2021-05-06_19-30-03" src="https://user-images.githubusercontent.com/127353/117275565-80df0800-aea1-11eb-83b2-e75bf6a9cd03.png">

Here is the JavaScript embed

```javascript
<script src="https://2wkvzfyrpv0h.statuspage.io/embed/script.js"></script>
```

**Comment by nisarhassan12** [comment]
Thanks. @ghuntley I can make a PR for this where should I put it probably in the footer, right ? 

@ChristinFrohne Can you help with the design here ? Thanks

**Comment by nisarhassan12** [comment]
Based on a response internally on [slack](https://gitpod.slack.com/archives/C01KGM9ETU6/p1624450233106500?thread_ts=1624395457.105100&cid=C01KGM9ETU6) I'm putting this on hold. For now, we decided to link to https://www.gitpodstatus.com/ from the footer.

**Comment by nisarhassan12** [comment]
Closing this as part of issue clean up. Please re-open if you find it is important to be implemented.
