### ISSUE TITLE
[docs] section "Self Hosted" Navigation arrows are broken

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#449]
On: 
www.gitpod.io/docs/self-hosted/latest/install/prepare-installation/
There is only one arrow which points to 
www.gitpod.io/docs/release-notes/2019-02-15/february-2019/ 
instead of 
www.gitpod.io/docs/self-hosted/latest/install/install-on-kubernetes/

Same is true for the other two pages in Self Hosted Section of the Docs.

**Comment by ChristinFrohne** [comment]
I assume this issue is fixed now, as I couldn't reproduce it. Please reopen it, if I missed something
