### ISSUE TITLE
Gitpod stuck on "Acquiring Node"

### ISSUE THREAD

**Issue by armedcor** [gitpod-io/website#456]
When opening a Gitpod workspace the loader is getting stuck on the "Acquiring Node..." screen.

Not a network issue as it is affecting a number of students in various locations on different networks.

First instance of the problem reported at 8.14 am GMT.

**Comment by AlanOSheadev** [comment]
I'm having the same issue

**Comment by armedcor** [comment]
Getting this error after 10 minutes of failed loading

last backup failed: pod has no hostIP. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.

**Comment by romangrubic** [comment]
Me too since 8:30 gmt

**Comment by OrlaBr** [comment]
Same issue

**Comment by armedcor** [comment]
On the European servers, after that last error, it now loads using the US servers it seems.

**Comment by meysholdt** [comment]
This should be resolved now for workspaces that are newly started. 
So please just try again and close the browser tab for the ones stuck in "acquiring node".

Apologies for the incident. We deployed many updates this morning and it looks like one bug went through undiscovered.
