### ISSUE TITLE
Documentation 2.0 - Table of contents

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#464]
Relates to #461.

This is work-in-progress. Please comment to provide feedback 🙏. The following ToC includes the feedback provided in comments.

### Table of contents
* Introduction (#468, @JohannesLandgraf)
  * Why Gitpod?
* Quickstart
* Getting Started (#466, @Rajakavitha1, @svenefftinge)
  * Start your first development environment
    * URL prefix
    * Browser extension
  * Configure your project
    * _A list of languages & frameworks_
* Configure
  * Configure your project (#509)
  * Customize your workspaces 
  * Prebuilds (#472)
    * Always ready-to-code
    * How to configure prebuilds
* Develop
  * _(essentially the current [_Workspaces_](https://www.gitpod.io/docs/workspaces) section)_
  * Workspaces (#471)
    * One workspace per task (i.e. ephemeral)
    * Timeouts
    * Unused workspaces
  * Contexts (#470)
  * Environment variables
  * Collaborate with others (#473)
    * Share a workspace
    * Share a snapshot
* Integrations (#469, @mikenikles, @JanKoehnlein)
  * GitLab
  * GitHub
  * Bitbucket
* Self-hosted Gitpod (@geropl & @solomonope)
* References
  * `.gitpod.yml` (#474)
    * Bring your own image
  * Architecture (see https://youtu.be/svV-uE0Cdjk)
  * Troubleshooting (#475)
  * Roadmap (`/roadmap`)
  * Changelog (`/changelog`)

**Comment by Rajakavitha1** [comment]
Hi @mikenikles.
This looks good. Here's my two cents. I have not gotten beyond the getting started yet....

- Overview
   Why Gitpod?
   Architecture (see https://youtu.be/svV-uE0Cdjk)

- Getting Started
  - Learning Environment 
      - Example Projects
      - URL Prefix
      - Browser Extension
   - Development Environment
      -  Working on Open Source Projects 
      -  Working on Personal Projects
          - Configure the project
         
 - Integrations
    - GitLab
    - GitHub
    - Bitbucket

- A list of languages & frameworks

**Comment by JohannesLandgraf** [comment]
The goal of rewriting our documentation is to 1) decrease the time until developers understand the value of Gitpod and 2) to have resources that make them feel everything is at their fingertips. Specifically, the getting started section is key for us as this provides the entry point / onboarding experience for lots of developers. Our current approach to that is essentially broken and leaves devs more confused. 

I'd vote for dividing the Getting Started section into two top-level entries:

- Quickstart with example project
- Getting Started with your project
-- Getting started with Svelte
-- Getting started with Node.js/Typescript
-- Getting started with Go
-- Getting started with Rust
-- Getting started with Java
-- Getting started with Ruby

### Quickstart with example project
This section essentially is what @Rajakavitha1 called above a "learning environment". I really like that concept! We should think about it as a step-by-step tutorial that demonstrates the added value of Gitpod and triggers relevant aha moments. The ultimate goal is to look at our documentation as a product and automate as much of the setup steps for the learning environment and make it really smooth. Vercel (as so often) is the North Star here doing an excellent job with the onboarding flow under their [Quickstarts](https://vercel.com/docs/introduction#quickstarts); just click on deploy on one of their examples and go through their flow. Until we have sth similar we need to manually describe the steps. A flow that could work and takes less than 10 minutes is: 

1. Install Browser Extension (quickly explaining why and referencing that it already is built-in in GitLab's UI; also explaining that if sb doesn't want to install the extension he can always prefix any git context with gitpod.io/#)
2. Clone/Copy the Spring Petclinic example (in the future we can have Quickstarts for different examples/templates) to your GitHub account (mention that it also works with other Git providers; would use GitHub for quickstarts though) 
3. Install Gitpod GitHub App
4. Create New Issue "Configure Gitpod"
5. Click on Gitpod Button on that issue or prefix with gitpod.io/# (now the prebuild is triggered; explain what is happening in the background) 
6. Once the workspace is up quickly show around + install a VS Code extension / theme etc
7. Change the gitpod.yml file by adding `github: prebuilds: addComment: true addBadge: true addLabel: true`
8. Commit changes with the UI in Gitpod and open a PR
9. Review the PR and merge 

### Getting started with your project
Describe how you can gitpodify one of your existing project and explain key concepts on the way. Resource to that can be https://www.gitpod.io/blog/gitpodify/

**Comment by JohannesLandgraf** [comment]
The goal of rewriting our documentation is to 1) decrease the time until developers understand the value of Gitpod and 2) to have resources that make them feel everything is at their fingertips. Specifically, the getting started section is key for us as this provides the entry point / onboarding experience for lots of developers. Our current approach to that is essentially broken and leaves devs more confused. 

I'd vote for dividing the Getting Started section into two top-level entries:

- Quickstart with example project
- Getting Started with your project
-- Getting started with Svelte
-- Getting started with Node.js/Typescript
-- Getting started with Go
-- Getting started with Rust
-- Getting started with Java
-- Getting started with Ruby

### Quickstart with example project
This section essentially is what @Rajakavitha1 called above a "learning environment". I really like that concept! We should think about it as a step-by-step tutorial that demonstrates the added value of Gitpod and triggers relevant aha moments. The ultimate goal is to look at our documentation as a product and automate as much of the setup steps for the learning environment and make it really smooth. Vercel (as so often) is the North Star here doing an excellent job with the onboarding flow under their [Quickstarts](https://vercel.com/docs/introduction#quickstarts); just click on deploy on one of their examples and go through their flow. Until we have sth similar we need to manually describe the steps. A flow that could work and takes less than 10 minutes is: 

1. Install Browser Extension (quickly explaining why and referencing that it already is built-in in GitLab's UI; also explaining that if sb doesn't want to install the extension he can always prefix any git context with gitpod.io/#)
2. Clone/Copy the Spring Petclinic example (in the future we can have Quickstarts for different examples/templates) to your GitHub account (mention that it also works with other Git providers; would use GitHub for quickstarts though) 
3. Install Gitpod GitHub App
4. Create New Issue "Configure Gitpod"
5. Click on Gitpod Button on that issue or prefix with gitpod.io/# (now the prebuild is triggered; explain what is happening in the background) 
6. Once the workspace is up quickly show around + install a VS Code extension / theme etc
7. Change the gitpod.yml file by adding `github: prebuilds: addComment: true addBadge: true addLabel: true`
8. Commit changes with the UI in Gitpod and open a PR
9. Review the PR and merge 

### Getting started with your project
Describe how you can gitpodify one of your existing project and explain key concepts on the way. Resource to that can be https://www.gitpod.io/blog/gitpodify/

**Comment by csweichel** [comment]
As discussed in sync, here's another Quickstart flow proposal.

**!Important!** spring-petclinic must not have a `.gitpod.yml` just yet. This way we can guide users through the full flow and show them how they can use this stuff for their own project.


1. Install Browser Extension (quickly explaining why and referencing that it already is built-in in GitLab's UI; also explaining that if sb doesn't want to install the extension he can always prefix any git context with gitpod.io/#)
2. Clone/Copy the Spring Petclinic example (in the future we can have Quickstarts for different examples/templates) to your GitHub account (mention that it also works with other Git providers; would use GitHub for quickstarts though) 
3. Install Gitpod GitHub App
4. Create New Issue "Configure Gitpod"
5. Click on Gitpod Button on that issue or prefix with gitpod.io/# (now there's NO prebuild is triggered; explain what is happening in the background) 
6. Once the workspace is open, use `gp init` to start the workspace configuration. Add Java extension and explain tasks and how we translate the commands in the readme to executable code. Make sure the config enables prebuilds.
7. Create PR
8. Open PR in Gitpod - explain prebuilds (now the user sees the prebuild box or the output in the terminal)
9. Review PR and merge

**Comment by JohannesLandgraf** [comment]
Let's go with the flow @csweichel suggested after our sync. We should write it in a way that it can be re-used for other languages where we add Quickstart guides/examples on the way. cc @Rajakavitha1

**Comment by JohannesLandgraf** [comment]
Okay we rethought the process and removed all steps that are unnecessary:

1. Create project from template link e.g. https://github.com/gitpod-io/spring-petclinic/generate (have quickstarts for different examples/templates) and add to your GitHub account (mention that it also works with other Git providers; would use GitHub for quickstarts though). Full Gitpod.yml/Gitpod setup should be in place. Have readme display the same steps as the docs and shown below.
2. Install Gitpod GitHub App
3. Run your first prebuild (create button/link that prefixes the repository url with #prebuild/gitpod.io/#[repoURL]. Give context on the time it takes for different examples and what happens in the background.
4. Enjoy being ready to code ⚡️
- Add theme
- Install the browser extension
- Open 3 parallel workspaces simultaneously

**Comment by svenefftinge** [comment]
> @svenefftinge will open a PR for that. Give context on the time it takes for different examples and what happens in the background.

This is not as low-hanging as I first thought. So we will go without the change in the app. But still, in the docs 3) should be the same.

**Comment by Rajakavitha1** [comment]
@JohannesLandgraf @svenefftinge @mikenikles and @csweichel  I will hold off working on the rewrite now. I can document the steps after the flow is finalised. Please let me know if it is okay?

**Comment by JohannesLandgraf** [comment]
@Rajakavitha1 For step 3 let's use the URL pasted in the [comment above](https://github.com/gitpod-io/website/issues/464#issuecomment-847649026). Unfortunately we cannot hide that behind a link so the user has to copy paste the URL for now to trigger prebuilds.

**Comment by JohannesLandgraf** [comment]
Thought again about our top-level entries and thinking about it I think we should try to be a bit clearer in the sections. Wdyt about the one below cc @mikenikles @svenefftinge @JanKoehnlein :

- Introduction 
- Quickstart
- Getting Started 
- Configure
- - Configure your project (what is now [_Configure your project_](https://www.gitpod.io/docs/configuration))
- - Customize your workspaces 
- Develop  (essentially the current [_Workspaces_](https://www.gitpod.io/docs/workspaces) section)
- Control (things like environment variables etc)
- Integrations
- Gitpod Self Hosted 
- References

**Comment by mikenikles** [comment]
That's clean 🧹 ! One request: Let's merge the chapters in "Control" into "Configure". If we all agree on that, I'll update the issue description to reflect this and start to put the structure in place in the docs.

👍 if you're ok with the above and my suggestion or please comment if you'd like to change the ToC.

**Comment by mikenikles** [comment]
✅ In #504, I added placeholders for the pages listed in the ToC so any contributor can open the relevant file and start writing ✍️.

**Comment by JohannesLandgraf** [comment]
Imo configure and control are a bit different. Configure is mainly about setting-up/configuring your project. For Control I also had a section about our dashboard in mind that helps people navigate. But I like the idea of aggregating the two in a first step and split the two later when we introduce teams / projects etc.

> so any contributor 
I think it is important to assign clear DRIs to the individual sections so we are all aligned in what court the 🏀 is

**Comment by gtsiolis** [comment]
> But I like the idea of aggregating the two in a first step and split the two later when we introduce teams / projects etc.

+1 🏀
