### ISSUE TITLE
Documentation: Write "References - `.gitpod.yml`"

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#474]
Relates to #461.

Use https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/data/gitpod-schema.json as the source of truth.

**Comment by theTisch21** [comment]
Is there a way to access the old documentation for the .gitpod.yml file while the new one is being written? I'm trying to create a .gitpod.yml for my repository and can't find documentation other than random snippets in other pages.
