### ISSUE TITLE
Documentation: have a visual differentiator b/w internal and external links. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#477]
We can use an icon like the one below for the external links 

![image](https://user-images.githubusercontent.com/46004116/119221106-2da6bf80-bb07-11eb-8db2-30a3f946f7c1.png)

### Context

[Slack Discussion](https://gitpod.slack.com/archives/C021JDXHXMF/p1621668935035800)(internal)

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/website/pull/484. Thanks @nisarhassan12 for adding this, @Rajakavitha1 for bringing this up in the relevant discussion (internal), and @JohannesLandgraf @ChristinFrohne for the feedback in the PR! 🏀
