### ISSUE TITLE
[pricing] rearranging pricing cards

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#481]
>Currently, it's very unclear to many users that:
>Gitpod can be used for free, right now
>Unlimited Open Source is not an Unlimited plan

>Suggestions:
>Make our free Open Source plan more obvious by re-adding its plan card
>Make the 1 month private repo trial more obvious
>Rename the Unlimited Open Source plan to avoid false expectations

mockup:
<img width="959" alt="Bildschirmfoto 2020-02-12 um 17 01 08" src="https://user-images.githubusercontent.com/46345125/74353313-04529c00-4dba-11ea-8b12-b7c581b5c506.png">

**Comment by ChristinFrohne** [comment]
Here is the new open-source icon
[open-source-icon.zip](https://github.com/gitpod-io/website/files/4198548/open-source-icon.zip)

**Comment by JesterOrNot** [comment]
I like it!
