### ISSUE TITLE
[subscriptions] UX improvements

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#485]
Issue:
- active subscriptions aren't clearly visible
- missing card for `open source`
- missing `professional open source` acknowledgment

Solution suggestion:
-optional: we could add a hover effect that fills each icon with the galaxy background
<img width="963" alt="Bildschirmfoto 2020-02-13 um 10 37 33" src="https://user-images.githubusercontent.com/46345125/74421174-e5e9b080-4e4c-11ea-9d56-73d197e34618.png">
<img width="963" alt="Bildschirmfoto 2020-02-13 um 10 37 43" src="https://user-images.githubusercontent.com/46345125/74421242-fef26180-4e4c-11ea-9999-530512445080.png">

@jankeromnes is this what you had in mind?

**Comment by jankeromnes** [comment]
Note: This issue is about https://gitpod.io/subscription/, not about https://www.gitpod.io/pricing/ (which also needs to be updated, but should keep the "Enterprise" card on the right).

**Comment by jankeromnes** [comment]
Also, small note, the Unlimited plan has:

> 60min Timeout
> 3h Timeout Boost

I personally find it nicer to have the same units there (it's also less "cognitively dissonant"):

> 1h Timeout
> 3h Timeout Boost

I've already updated the pricing page, and my upcoming https://gitpod.io/subscription/ will have it as well.

Just as a quick FYI @ChristinFrohne @nisarhassan12 since the mockups still have "60min" :) (no need to update the mock-ups)

**Comment by jankeromnes** [comment]
Not yet resolved, the subscription page is still very rough and needs to be adjusted as in the mock-up.

**Comment by jankeromnes** [comment]
This is now largely implemented. 🙂 There are a few small items left to do, but I won't have time to work on them in the short term.

**Comment by jankeromnes** [comment]
Issue is now largely addressed, and the remaining items are either outdated/unclear/not actionable.

So, calling this done! 😇 🎉
