### ISSUE TITLE
link the testimonials to original tweets and remove the @links from them. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#492]
See for more context https://github.com/gitpod-io/website/issues/346#issuecomment-848513823

**Comment by nisarhassan12** [comment]
@ChristinFrohne should I also remove the link from within the tweet text? Also, does the @company in the role after the Name needs some sort of different styling? What do you think about making it bold? Thanks

![image](https://user-images.githubusercontent.com/46004116/119781565-99f93880-bee4-11eb-8095-3aa4461fda0f.png)

**Comment by ChristinFrohne** [comment]
>should I also remove the link from within the tweet text?

Yes, I think we should keep it as simple as possible

>does the @Company in the role after the Name needs some sort of different styling? What do you think about making it bold?

having it bold is a great idea. Let's do that
