### ISSUE TITLE
Adjust `padding-right` for external links

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#493]
I noticed a large gap to the right of external links due to the `padding-right: 2rem;` CSS. @nisarhassan12 could you adjust that please 🙏 ?

![image](https://user-images.githubusercontent.com/788827/119742869-b8185780-be56-11eb-9195-9e81a551f806.png)

In the docs, we have various external links and the current gap breaks the flow when reading the content.

**Comment by nisarhassan12** [comment]
@mikenikles I have made a Pr for it https://github.com/gitpod-io/website/pull/497/files

**Comment by nisarhassan12** [comment]
Closing this as it is no longer relevant.
