### ISSUE TITLE
Create page for GitHub Teacher Toolbox

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#505]
Similar to the GitHub Student Developer Pack we will also offer a discount for teachers via GitHub. 

The announcement will be on 11th March:

Could you create this page please @nisarhassan12?
@jankeromnes feel free to make other messaging suggestions

<img width="480" alt="Bildschirmfoto 2020-02-27 um 10 44 09" src="https://user-images.githubusercontent.com/46345125/75441176-75b75080-595d-11ea-9020-92128710eb87.png">
![75394447-0c492a80-58e8-11ea-9ab1-2267cd416daf](https://user-images.githubusercontent.com/46345125/75441182-78b24100-595d-11ea-9e41-e6f71d570efd.png)
[owl-icon.svg.zip](https://github.com/gitpod-io/website/files/4261366/owl-icon.svg.zip)

**Comment by nisarhassan12** [comment]
I can create this for sure :) Should I wait for messaging updates from @jankeromnes :) ?

**Comment by ChristinFrohne** [comment]
Great thanks! You can just start implementing it. We can edit the text later on as well

**Comment by jankeromnes** [comment]
Looks good to me, thanks!

However we don't currently have any plan that's called **Teacher** (we have **Personal**, which we can probably make free for 6 months, just like we do for students).

Open Source logo is also still the old one (we should use the new heart icon).

**Comment by jankeromnes** [comment]
> However we don't currently have any plan that's called **Teacher**

Ah, I see that we also call the **Personal** plan **Student** in https://www.gitpod.io/github-student-developer-pack/

Then I'm ok with calling it **Teacher** here too.
