### ISSUE TITLE
The `<h3>` font size is smaller than the one for `<h4>`

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#505]
Examples:
* `<h3>`: https://www.gitpod.io/docs/prebuilds#github-integration
* `<h4>`: https://www.gitpod.io/docs/prebuilds#checks

The `<h4>` font size should be smaller than `<h3>`.

**Comment by asharonbaltazar** [comment]
Can I take this one? Do you want the font sizes switched? Seems to be an issue only on larger screens.

**Comment by opensas** [comment]
I sent this PR [fixes #503 - adjust font sizes in docs.scss](https://github.com/gitpod-io/website/pull/625)... and I think instead of #503 it should have been #505  :facepalm:
