### ISSUE TITLE
gitpod.io/security 404

### ISSUE THREAD

**Issue by Carlos-Schrodinger** [gitpod-io/website#512]
On the main repository (gitpod-io/gitpod) when filling a security vulnerability it takes you to gitpod.io/security, which doesnt exist.

![image](https://user-images.githubusercontent.com/48862659/120070890-ff882900-c08c-11eb-81f7-3f71f8e9d7c3.png)
![image](https://user-images.githubusercontent.com/48862659/120070905-12026280-c08d-11eb-9513-034ced2aacd7.png)

https://github.com/gitpod-io/gitpod/security/policy

**Comment by mikenikles** [comment]
Hey Carlos, thanks for letting us know! It turns out to be an issue with the URL that was missing `www`. I opened a PR at https://github.com/gitpod-io/gitpod/pull/4342 to get this sorted.

The correct URL is https://www.gitpod.io/security

**Comment by Carlos-Schrodinger** [comment]
Alright!

**Comment by nisarhassan12** [comment]
Waiting for https://github.com/gitpod-io/gitpod/pull/4342 to be merged I have asked internally on slack.
