### ISSUE TITLE
ToS doesn't reflect the service

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/website#533]
There is a whole clause about picking a strong username and password, but Gitpod uses OAuth...

**Comment by Kreyren** [comment]
@RDIL reference it

**Comment by Kreyren** [comment]
also why it is a bad thing to keep in ToS ? I consider that being future-proofing

**Comment by RDIL** [comment]
Because legally that information needs to be correct

**Comment by Kreyren** [comment]
> Because legally that information needs to be correct

So reference the problematic clause

**Comment by Kreyren** [comment]
![](https://media.giphy.com/media/3jN3GziOKUEmI/giphy.gif)

**Comment by RDIL** [comment]
I'm kind of tired of opening these since they never get fixed

**Comment by Kreyren** [comment]
Like i am willing to fix them, but i don't see what do you expect to be fixed here.. i guess i could something alike:

```
if applicable the <clause about picking a strong username and password>
```

you kinda make it hard to fix these issues without a sufficient explanation :p

**Comment by Kreyren** [comment]
> **Password and Security:** You shall chose a safe password (we recommend at least 8 signs, including a letter, cypher and special character) for your account and change such password on a regular basis. You shall only pass such password information to authorized persons.

**DISCLAIMER:** I am not your lawyer and this is not a legal advise that would create a lawyer to client relationship

To me that is more like a recommendation and covering up when user somehow force to make their password `1234` and to shift blame in case the end-user had such password and wanted to blame TypeFox for leaking of confidential info that was caused as a result of bad password.

**Comment by Kreyren** [comment]
Aldo assuming that currently gitpod is using GitHub for authentification the ToS should be probably written differently to account for ToS of GitHub which states on https://help.github.com/en/github/site-policy/github-terms-of-service:

> You are responsible for maintaining the security of your Account and password. GitHub cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.

Which to me is a better wording then what is typefox currently using.

**Comment by Kreyren** [comment]
cc @jankeromnes

**Comment by Kreyren** [comment]
@RDIL Btw. If you find something else in the ToS that doesn't seem right to you then make an issue about it and i will take a look with the same disclaimer as in https://github.com/gitpod-io/website/issues/533#issuecomment-633114725 ^-^

**Comment by Kreyren** [comment]
aldo probably cc @meysholdt the TypeFox ToS wording seems to me as quite weak in case there would be a legal conflict alike the account security mensioned and there seems to be more issues that i rather not discuss here. 

Would be nice if this was made an open-source to which people can contribute or express their concerns on a tracking.
