### ISSUE TITLE
[docs] search leads to old pages that are now 404

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#534]
**Problem**
When I'm searching for example for `theia`the serach recommends pages that don't exist anymore

<img width="887" alt="Bildschirmfoto 2021-06-02 um 11 59 11" src="https://user-images.githubusercontent.com/46345125/120461540-6150d780-c39a-11eb-83bc-8b29eccb9d04.png">

**Comment by mikenikles** [comment]
This has been fixed in https://github.com/algolia/docsearch-configs/pull/4164.
