### ISSUE TITLE
[docs] navigation doesn't work anymore once I used the search

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#535]
**Problem:**
When I search for `python`, I can select and open a recommended page. After I opened the page I can't use the left navigation anymore. 
See screenshot: URL=` /getting-started` but I'm still on the Python page.
I guess that's because `languages/python` is not part of the navigation structure anymore.

<img width="1122" alt="Bildschirmfoto 2021-06-02 um 11 59 57" src="https://user-images.githubusercontent.com/46345125/120462223-023f9280-c39b-11eb-95b7-01ca2f96061e.png">

**Comment by mikenikles** [comment]
This has been fixed in https://github.com/algolia/docsearch-configs/pull/4164.
