### ISSUE TITLE
[docs] left navigation bar is inconsistent 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#544]
**Problem:**
If `introduction` is selected there is no white bubble around the name. 
If `Getting started` is selected there is a white bubble around the name

**Solution**
If a topic has no sub-topics we can either
a) always use the white bubble or 
b) never use the white bubble

I vote for b) 🙂
<img width="440" alt="Bildschirmfoto 2021-06-02 um 14 27 23" src="https://user-images.githubusercontent.com/46345125/120480249-1f7e5c00-c3af-11eb-823e-5dc2fd3df68c.png">

**Comment by opensas** [comment]
I just submitted this [PR](https://github.com/gitpod-io/website/pull/624)

Personally I prefer the a) options, but implemented the second option and added a short note in case you choose to stick with the white card

**Comment by nisarhassan12** [comment]
Fixed in #624 #699
