### ISSUE TITLE
[docs] enabling linking to a specific section of a page

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#545]
**Problem**
It would be great to be able to link to a specific section of a page. Often, especially if the page is quite long, not every section is relevant for each use case. Being able to link to each section with a `#tag` would be really helpful

Inspiration:
https://customer.io/docs/getting-started-overview/#people

**Comment by mikenikles** [comment]
That functionality is actually already there, but not user-friendly. In #515, we are going to improve that.

For now, you'd have to inspect the heading element in the browser's developer tools, then copy the `id` attribute and add that to the URL as the hash. Complicated... Let me spend some time on #515 now and see if I can sort that out.
