### ISSUE TITLE
'refernce' should be spelled 'reference'

### ISSUE THREAD

**Issue by davidbasswwu** [gitpod-io/website#547]
on line 25.  Pull request coming soon...

**Comment by nisarhassan12** [comment]
Many Thanks, ❤️ @davidbasswwu for bringing this up and making a PR. It looks like you made a PR against your Fork and not this repo this does not look intentional.  Would be great if you can open it against this repo so that your change can go live 🚀. Let me know in case you need any help.

**Comment by davidbasswwu** [comment]
Looks like it's already been fixed, and I'm still learning how to do this, but thanks for the offer.  Will try again if I see anything else.  Keep up the great work with gitpod 👍
