### ISSUE TITLE
update blog post header images

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#553]
we should try to keep a consistent style for our header images. If you are an author of one of these blog posts and you agree with the changes, please comment with 👍

For https://www.gitpod.io/blog/from-gatsby-to-svelte I suggest
![Blog Post- header](https://user-images.githubusercontent.com/46345125/120643199-245a1300-c476-11eb-8085-b77a2536e1e9.png)
 @mikenikles 

For https://www.gitpod.io/blog/journey-to-site-reliability-engineering-at-gitpod i suggest 
![Blog Post- header (1)](https://user-images.githubusercontent.com/46345125/120643185-1efcc880-c476-11eb-8e16-7193b08bf486.png)
 @ArthurSens 

For https://github.com/gitpod-io/website/pull/548 I suggest
![Blog Post- header (2)](https://user-images.githubusercontent.com/46345125/120643161-186e5100-c476-11eb-9ea2-88f41702f4d0.png)
 @ghuntley

**Comment by ghuntley** [comment]
🤘✅👍

**Comment by ArthurSens** [comment]
🤘✅👍

**Comment by ChristinFrohne** [comment]
Does this quick fix work for you @ArthurSens ?
![Blog Post- header (4)](https://user-images.githubusercontent.com/46345125/120763009-1c9e7b00-c517-11eb-90fe-ca91d87d773f.png)

**Comment by JohannesLandgraf** [comment]
Let's take away the heart arrow from the picture and merge that before you are on holidays @ChristinFrohne 🙏

**Comment by ChristinFrohne** [comment]
Could you take care of this @nisarhassan12 ? 🙏
![Blog Post- header (5)](https://user-images.githubusercontent.com/46345125/120804296-c47e6d80-c544-11eb-8747-ac809084e1b9.png)

**Comment by ArthurSens** [comment]
Yep, that looks good! Thanks!
