### ISSUE TITLE
design: markdown bullet points are not aligned 

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#561]
bullet points are not aligned with the rest of the text

_Originally posted by @ChristinFrohne in https://github.com/gitpod-io/website/pull/548#discussion_r644571327_

See 

<img width="904" alt="2021-06-04_13-27-29" src="https://user-images.githubusercontent.com/127353/120741643-b9bddb80-c538-11eb-95a1-3bc37b72925d.png">

**Comment by nisarhassan12** [comment]
This is already fixed in #568 the change will be live once that is merged.
