### ISSUE TITLE
Self-Hosted improvements

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/website#564]
A couple of things I noticed
1. There is a admin.md file that does not have a route
2. A bit confusing for anyone not using GCP or running on vanilla Kubernetes (could be more generic or have specific guides for each one)

**Comment by nisarhassan12** [comment]
@JesterOrNot Is this still relevant?

**Comment by ChristinFrohne** [comment]
Please reopen the issue if it's still relevant
