### ISSUE TITLE
[blog] DevX Conf wrap styling issues

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#564]
- [x] "Event retrospective" is a `<h1>` but it should be a `<h2>`
- [ ] the Twitter screenshots have a bad quality
- [ ] could we adjust the size of all the Twitter screenshots so that they just take half the column space?
- [x] I still think there are too many images too close to each other taking too much space. It looks quite messy. Could we remove the screenshot above `At Gitpod, we firmly believe that working`? It's already used two times in another blog post.
- [ ] Could the Gmail screenshot and GitHub screen be displayed next to each other? 

<img width="286" alt="Bildschirmfoto 2021-06-04 um 08 50 45" src="https://user-images.githubusercontent.com/46345125/120758459-296ca000-c512-11eb-85b4-003724e82c9a.png">

cc @ghuntley @nisarhassan12

**Comment by nisarhassan12** [comment]
> - [ ] "Event retrospective" is a` <h1> `but it should be a `<h2>`

I have fixed it in https://github.com/gitpod-io/website/pull/568 the change will be live once the Pr is merged.

**Comment by nisarhassan12** [comment]
> - [ ] Could the Gmail screenshot and GitHub screen be displayed next to each other?
Yeah. but because the screenshot is radial at the top it looks bad. 
![image](https://user-images.githubusercontent.com/46004116/121681260-06268f80-cad4-11eb-8686-854d2dcd9e0f.png)

**Comment by ChristinFrohne** [comment]
Thanks! I think the issue can be closed. For the next time, we should watch out to use fewer images
