### ISSUE TITLE
Adjust pricing 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#575]
Problem:

- team subscription isn't clear
- missing option to buy a subscription immediately
- free trial is poorly communicated
- add feature of booking extra hours to personal plan (let's leave the tick out of the feature list until it's actually enabled) 

<img width="963" alt="Bildschirmfoto 2020-04-06 um 11 36 23" src="https://user-images.githubusercontent.com/46345125/78545072-71534280-77fb-11ea-986d-af1f76885be6.png">

Could you look into it when you find time @nisarhassan12 ?

**Comment by nisarhassan12** [comment]
Sure! I'm currently working on #560 there are just a few things remaining I will have a look at it afterwards please let me know it its urgent.

**Comment by ChristinFrohne** [comment]
It's not urgent and fine if you have a look at it after the current issue. Thanks!

**Comment by nisarhassan12** [comment]
I have added **Opt. Extra Hours" in the features list 

![image](https://user-images.githubusercontent.com/46004116/78626797-4293a580-78a9-11ea-9cf1-58b5268bd542.png)

What should I put in the description that appears once the question mark is hovered?

**Comment by nisarhassan12** [comment]
Also where this Create Team link is gonna point to 
![image](https://user-images.githubusercontent.com/46004116/78628071-994eae80-78ac-11ea-9358-8655ec1c3ab4.png)

**Comment by ChristinFrohne** [comment]
>I have added "Opt. Extra Hours" in the features list
>(let's leave the tick out of the feature list until it's actually enabled)

Extra hours have not been enabled yet. Let's add it at a later point to the list.

>Also where this Create Team link is gonna point to

https://gitpod.io/teams/
