### ISSUE TITLE
Implement: ImgBot?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/website#576]
I was recently testing github bots on my repositories and based on my short experience with this one i assume that it would fit here assuming that if it does what it presents itself to do then the loading of gitpod website should be significantly faster, see https://github.com/Kreyren/website-1/pull/1

![image](https://user-images.githubusercontent.com/11302521/78574562-7085d500-782a-11ea-8431-5d612c769d77.png)

Marketplace: https://github.com/marketplace/imgbot (free for open-source)

**Comment by Kreyren** [comment]
Also the images does not seem to lose quality after the optimization.

**Comment by nisarhassan12** [comment]
This seems quite interesting to me so far we have been optimizing images manually via https://tinypng.com and SVGOMG.

@jankeromnes I think we should add this. What do you say?

**Comment by nisarhassan12** [comment]
Thanks @Kreyren the bot is now installed. Thanks to @jankeromnes.
