### ISSUE TITLE
Provide a Python quickstart

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#582]
Based on feedback received through the docs feedback widget.

**Comment by JohannesLandgraf** [comment]
Self-assign to fix one typo and add the python example to the menu on the left

**Comment by mikenikles** [comment]
We now have the following:
- [Python Django Quickstart](https://www.gitpod.io/docs/quickstart/python)
- [Flask Quickstart](https://www.gitpod.io/docs/quickstart/flask)
