### ISSUE TITLE
Image update: Automated setup

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#588]
Is someone working on exchanging the current automated-setup-graphic @jbicker @nisarhassan12 ?

Would be great if someone can look into it. 
Here are the new files in .png format. Let me know if you prefer a .svg file and place the galaxy background manually. 
The new graphic should be a lot easier to align. 

Thanks for looking into it  :) 

![automatedsetup-graphic-default-15](https://user-images.githubusercontent.com/46345125/79547599-6ff40680-8094-11ea-8594-9b2cb2595b09.png)
![automatedsetup-graphic-gitpod-13](https://user-images.githubusercontent.com/46345125/79547607-73878d80-8094-11ea-8ecb-1b47682afc10.png)
![automatedsetup-graphic-without-gitpod-16](https://user-images.githubusercontent.com/46345125/79547608-74202400-8094-11ea-92fb-144445b24639.png)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Thanks for the images I have cropped them to be more squared now all 3 of them have a height 1100px and width of 1790px but I'm not being able to align them correctly. Are you sure that the 3 below arrow-like bars are equal in height and width?

You can view what the result by opening a workspace for https://github.com/gitpod-io/website/tree/update-automated-graphics

![automated-setup-gitpod](https://user-images.githubusercontent.com/46004116/79685926-cfe5db00-8255-11ea-883b-f5108c5e6709.png)
![automated-setup-default](https://user-images.githubusercontent.com/46004116/79685930-d96f4300-8255-11ea-83a1-984a9b048ba0.png)
![automated-setup-ordinary](https://user-images.githubusercontent.com/46004116/79685932-decc8d80-8255-11ea-91aa-2d94137275da.png)

**Comment by ChristinFrohne** [comment]
Thanks for checking. I adjusted them and tested them again. For me they work fine now
![automatedsetup-graphic-gitpod-13-13-16-15](https://user-images.githubusercontent.com/46345125/79719761-880b9600-82df-11ea-8f64-131b64689e70.png)
![automatedsetup-graphic-gitpod-13-13-16](https://user-images.githubusercontent.com/46345125/79719766-8b9f1d00-82df-11ea-8132-6dc9887f2ee9.png)
![automatedsetup-graphic-gitpod-13-13](https://user-images.githubusercontent.com/46345125/79719767-8c37b380-82df-11ea-9e77-9858982993c7.png)
