### ISSUE TITLE
[improvement] Align button style

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#591]
Currently, the button style isn't consistent. 
<img width="382" alt="Bildschirmfoto 2020-04-21 um 18 23 21" src="https://user-images.githubusercontent.com/46345125/79888680-54bf2900-83fd-11ea-9c82-ac9ac94d7754.png">
<img width="376" alt="Bildschirmfoto 2020-04-21 um 18 23 28" src="https://user-images.githubusercontent.com/46345125/79888691-57218300-83fd-11ea-9f19-df4d0becf117.png">
<img width="537" alt="Bildschirmfoto 2020-04-21 um 18 24 05" src="https://user-images.githubusercontent.com/46345125/79888694-5852b000-83fd-11ea-8a6e-3d727e293a51.png">

**Comment by nisarhassan12** [comment]
@ChristinFrohne should I make all the buttons of the same width and same font-size?

**Comment by ChristinFrohne** [comment]
Please give all buttons that have almost the same style the exact same style. Buttons that clearly differ like the "start for free" button on features, can keep their style. 

I would say the width can differ if the button text is unusual long. But the height and the font size should be the same.
