### ISSUE TITLE
Social proof looks weird

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#594]
This is what the list looks like by default:

<img width="1215" alt="Screenshot 2020-04-27 at 09 08 07" src="https://user-images.githubusercontent.com/599268/80343800-d3392200-8866-11ea-8f6c-54e2b943ac1e.png">

- 99% of visitors will only ever see these logos (i.e. all logos to the right are basically hidden because very few people will click on the right arrow)

- Maybe being able to horizontally scroll would be easier than clicking on this small `>` button

<img width="1169" alt="Screenshot 2020-04-27 at 09 08 36" src="https://user-images.githubusercontent.com/599268/80343803-d502e580-8866-11ea-9b4a-c8734ad0cd8f.png">

- The contrast of all these logos seems totally random/weird, especially for the Google logo. I wonder why we've changed the CSS style that I've spent a long time fine-tuning?

- There is no `<` button to go back left. This is surprising and makes the horizontal list feel even more awkward

<img width="1169" alt="Screenshot 2020-04-27 at 09 08 51" src="https://user-images.githubusercontent.com/599268/80343805-d59b7c00-8866-11ea-8207-6acd92cd8789.png">

- This is the maximum you can "scroll" to the right (by repeatedly clicking the `>` button). Why can you go so far to the right? It seems like a bug that there are 3 "empty" logo slots at the end

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes I will make a PR for this.
