### ISSUE TITLE
[bug] empty spaces between tweets

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#599]
Problem:
empty spaces between tweets

<img width="1629" alt="Bildschirmfoto 2020-04-29 um 12 44 09" src="https://user-images.githubusercontent.com/46345125/80587681-42ee0f00-8a17-11ea-8a07-f0a6d398190e.png">

**Comment by nisarhassan12** [comment]
It looks like twitter is hiding these.

![image](https://user-images.githubusercontent.com/46004116/80618522-ead9fb80-8a5c-11ea-89bc-c8b893c93879.png)

**Comment by nisarhassan12** [comment]
Those tweets that are being displayed have their visibility set to visible.

**Comment by ChristinFrohne** [comment]
Can we manually change that? Or do we need to delete/replace those tweets?

**Comment by nisarhassan12** [comment]
@ChristinFrohne Can you verify that those tweets that are not being displayed are still available on twitter?

**Comment by ChristinFrohne** [comment]
You're right. One tweet got deleted and for the other the privacy settings changed.
