### ISSUE TITLE
[docs] from-referrer

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#599]
Needed to look up how to implement open in Gitpod via `from-referer` ala https://github.com/gitpod-io/gitpod/issues/688 worked. 

a) I don't think this is documented currently
b) The first search result is currently the implementation of the `from-referer` in the gitpod product. Maybe this should be excluded in robots.txt.

<img width="960" alt="2021-06-10_19-10-18" src="https://user-images.githubusercontent.com/127353/121499297-9b684c00-ca20-11eb-99f5-34753ec4cbcc.png">

**Comment by mikenikles** [comment]
While this is a nice, generic way to create "Open in Gitpod" buttons in `README.md` files, it also means we rely on 3rd party products (GitHub, GitLab, Bitbucket and also browsers) to always send the referrer header.

This feels too fragile and unreliable.

I'm closing this for now and will keep an eye on https://github.com/gitpod-io/gitpod/issues/688 to see how this discussion progresses. If we find a reliable solution, we can reopen this ticket here and update the documentation.

**Comment by mikenikles** [comment]
Talked with Geoff in Slack. Reopening this for the time being as this (or a similar solution) is necessary for our quickstart examples where developers create their own repos based on our templates. We don't know the final repo URL ahead of time and asking developers to adjust the "Open in Gitpod" button isn't ideal.

**Comment by ghuntley** [comment]
@laushinka has resolved the problems we were experiencing with Safari at https://github.com/gitpod-io/gitpod/pull/5052
