### ISSUE TITLE
Why Gitpod?

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/website#6]
Here are my thoughts on the top benefits of Gitpod.

Maybe this can help articulate the top three benefits on the front page, or add to the features page.

---

### It's fast & convenient
Launch disposable cloud workspaces in one click, get code intelligence and a full Linux shell in a browser tab.

### It makes coding easy
Today's software is getting more complicated, that's why Gitpod automatically flags risky, inefficient code and suggests fixes and best practices as you type. Coding with Gitpod will make your code safer and faster.

### It makes environment management easy
Installing dependencies is tedious and boring, so Gitpod lets you describe your projects' development setup in code once and for all, so that your developers never have to worry about it again.

### It makes coding more zen
Gitpod fits right into your GitHub workflow, without fuss or interruptions, and it continuously builds your code and pull requests in the background to save your time and free your mind of cognitive overhead.

### It's open and free
Made in the open with love, Gitpod is free for the open-source community.

### For your team, your contributors, your students
With Gitpod, you can provide efficient workspaces to every developer, team mate or student, whether they use a desktop computer; a temporary laptop; a tablet or a chromebook.

**Comment by svenefftinge** [comment]
@jankeromnes Can we close this? Or there anything here that we should take action on?
