### ISSUE TITLE
enabling horizontal scrolling for logos

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#600]
@jankeromnes suggested to use horizontal scrolling instead of clicking through the "trusted by" logos. Could you implement that @nisarhassan12? 

Also, the spacing between the logos is inconsistent. Could you adjust that?

<img width="1119" alt="Bildschirmfoto 2020-04-29 um 14 16 57" src="https://user-images.githubusercontent.com/46345125/80594885-1e4c6400-8a24-11ea-8247-59ce95ea4267.png">

**Comment by nisarhassan12** [comment]
No longer relevant to the new website design.
