### ISSUE TITLE
[docs] how to configure Git aliases in gitpod.yml

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#601]
Discovered at https://github.com/bserem/gitpod-drupal-mysql-starterkit/blob/main/.gitpod.yml#L6 that it is possible to configure git aliases via YAML.

Expecting to find this information at https://www.gitpod.io/docs/config-gitpod-file/

Information was found at https://community.gitpod.io/t/what-is-the-best-way-to-configure-git-aliases/655

**Comment by mikenikles** [comment]
Closing in favour of #474
