### ISSUE TITLE
Outdated images

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/website#607]
There seem to be very old outdated images of Gitpod
i.e. on
https://www.gitpod.io/docs/
https://www.gitpod.io/docs/pull-requests/
https://www.gitpod.io/docs/code-reviews/

**Comment by ChristinFrohne** [comment]
That's totally right. We already have two issues for this #510 #74 
That's why I will close this issue, but it was a great reminder to finally fix them. I'll look into it soon. Thanks!
