### ISSUE TITLE
Add copyright year date at the footer

### ISSUE THREAD

**Issue by Panquesito7** [gitpod-io/website#632]
I think it'd be good if the copyright year is added to the footer.
Currently, I can only see `Copyright © Gitpod`, but I'd also like to know the year.

Thanks.

**Comment by nisarhassan12** [comment]
@Panquesito7 Thanks for bringing this up. Can you please tell me why you'd like to see a date ? Thanks

**Comment by Panquesito7** [comment]
> Can you please tell me why you'd like to see a date

I was going to look at the website and see when was Gitpod created, but I didn't see any date. I assume many other users may want to see when was Gitpod created. It also looks better IMO. 🙂

**Comment by nisarhassan12** [comment]
Thanks, @Panquesito7 We have decided to just add the current year to the footer. 
FYI the public beta of Gitpod was announced on Jul 31, 2018, https://www.gitpod.io/blog/gitpod-online-ide and it was launched on Apr 5, 2019, https://www.gitpod.io/blog/gitpod-launch.
