### ISSUE TITLE
Edit in Gitpod button does not focus the file

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#641]
On https://www.gitpod.io/docs/environment-variables/ the edit button has the link of https://gitpod.io/#https://github.com/gitpod-io/website/tree/main/src/routes/docs/environment-variables.md

Clicking on the button spins up Gitpod but the `src/routes/docs/environment-variables.md` file is not opened which means people have to go spelunking to work out the structure of our codebase vs getting in there and fixing it.

**Comment by mikenikles** [comment]
I can't reproduce that on Android using Brave as browser. What browser do you use? If it's broken, it may be a `gitpod-io/gitpod` issue when it parses the context.

**Comment by ghuntley** [comment]
```

Google Chrome | 91.0.4472.106&nbsp;(Official Build)&nbsp;(arm64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 11.4 (Build 20F71)
JavaScript | V8&nbsp;9.1.269.36
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

```

**Comment by ghuntley** [comment]
Closing this out as a potential user error on my end. Tried again on `https://amaranth-hyena-9s5g3pqo.ws-us08.gitpod.io/` and the file was focused.
