### ISSUE TITLE
tech debt: vite#1992 is now fixed

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#642]
Upstream https://github.com/vitejs/vite/pull/1992 is now resolved.

https://github.com/gitpod-io/website/blob/main/.gitpod.yml#L12 contains a techdebt note as follows 
<img width="1312" alt="2021-06-18_15-10-20" src="https://user-images.githubusercontent.com/127353/122509543-50b18a00-d047-11eb-9b96-418e40c16082.png">

**Comment by mikenikles** [comment]
This requires an upgrade of SvelteKit which we will do once the v1.0 is released.

**Comment by mikenikles** [comment]
Closing this as part of an issue cleanup. It will get addressed when we upgrade to SvelteKit 1.0 once it's available.
