### ISSUE TITLE
 this one is new: access control glitch

### ISSUE THREAD

**Issue by ret394** [gitpod-io/website#660]
write public repos is enabled. but can't access repo warning is displayed by tooltip on git push. the push succeeds.

cannot reproduce. And Github's acting up too, could be the cause. https://www.githubstatus.com/

-----

and you could add granular permissions for repo to the list, for both types of repos.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by ret394** [comment]
transfer issue!

**Comment by nisarhassan12** [comment]
Sorry! the issue does not make sense to me so gonna close this.
