### ISSUE TITLE
adjust ul style pointer position on mobile as per the specs. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#675]
This is how it is on prod at the moment:

![image](https://user-images.githubusercontent.com/46004116/123158535-595df200-d485-11eb-878d-fd5b84c5f98a.png)

In the specs:

![image](https://user-images.githubusercontent.com/46004116/123158781-a5a93200-d485-11eb-825b-08d136e4ab0a.png)

### Solution: 

The spacing between the text and the style pointer should be `8px`.

**Comment by mikenikles** [comment]
Resolved in #689
