### ISSUE TITLE
getContext hook deprecated and removed

### ISSUE THREAD

**Issue by nosovk** [gitpod-io/website#690]
In that PR https://github.com/sveltejs/kit/pull/1332/files
getContext hook was removed, and code from hook to populate list of blog posts is broken in current svelte kit version
https://github.com/gitpod-io/website/blob/main/src/hooks.ts#L1

**Comment by mikenikles** [comment]
Thank for reporting that Konstantin. At the moment, we are waiting for SvelteKit 1.0 to be released before we work on an upgrade. There are a number of changes that make this website project incompatible with SvelteKit's latest beta releases.

I tried to keep up, but changes are currently too frequent and lack a migration guide other than reading the changelog, PRs and issues. Too much work for a small team like ours 😞.

I'm going to close this issue, but rest assured it will get addressed as part of a bigger SvelteKit upgrade.
