### ISSUE TITLE
Provide option to sign up for the newsletter

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#696]
**Context:**
We want to provide an option for blog post readers to stay updated about the latest product news. Therefore we'll create a button to easily sign up for the newsletter underneath a blog post. 

The readers shall be able to sign in for the newsletter without logging into Gitpod and without being a registered user. 
[Related internal discussion](https://gitpod.slack.com/archives/C01LDA27WJC/p1624863892182900)

If the email address belongs to a registered Gitpod user, the user notification setting related to "Product tips & inspiration" is turned on and customer.io should be updated accordingly. If the email address does NOT belong to a registered Gitpod user, an entry for that email is upserted in customer.io.

Customer.io should not have, at any time, duplicate emails.

**Next steps:**
- [x] Create Mockup
- [x] Implement the mockup (@nisarhassan12)
- [ ] Technical integration (@jakobhero and @atduarte)
- [ ] Create newsletter segment in customer.io (@ChristinFrohne)

cc @JohannesLandgraf

**Comment by ChristinFrohne** [comment]
Mockup:
<img width="719" alt="Bildschirmfoto 2021-06-28 um 12 44 59" src="https://user-images.githubusercontent.com/46345125/123624286-ad166580-d80e-11eb-9b05-cee4ffe3aa55.png">

**Comment by nisarhassan12** [comment]
>  Implement the mockup @nisarhassan12

I have implemented the mockup in https://github.com/gitpod-io/website/pull/698

**Comment by ChristinFrohne** [comment]
Great, thanks! Could you look into the Segment integration now @jakobhero?

FYI, Pauline (our new college) will publish a blog post on her personal website and she would like to use the code snippet to sign up for the newsletter there as well.

**Comment by atduarte** [comment]
In order to implement this, I believe that the Gitpod app (not the website) should be responsible for the flow from form submission (or API call) to Segment updates. 

1. The website would call the Gitpod app with the email
2. The app would then check whether the email is registered to decide whether to update the associated setting
3. The app publishes a Segment event (to be listened to by customer.io) with the email, user id or anonymous id, and subscription status (i.e. `unsubscribed=false`)
4. Customer data is upserted in Customer.io, using the email as the identifier.

@jakobhero @csweichel thoughts?

**Comment by jakobhero** [comment]
@laushinka is tackling the unsubscription logic in #4761, which will solvee steps 1-3.
For step 4, customer.io can implicitly decide whether the userId or the email is the identifier if a user who is not signed up is tracked by assigning the email to the userId in Segment (see https://customer.io/docs/segment-destination/).

**Comment by atduarte** [comment]
> @laushinka is tackling the unsubscription logic in gitpod-io/gitpod#4761, which will solve steps 1-3.

@jakobhero It's quite similar but from what I have seen the endpoint is to be/was implemented only to unsubscribe users. In this case, we want to subscribe. 

Additionally, if that API endpoint triggers a Segment event for the existing users, we would have to different apps triggering similar events.

Regarding step 4, I don't think we need to change anything in Segment. Currently, customer.io is not configured to use the email as an identifier and it should (see [here](https://fly.customer.io/env/106338/settings/edit)).

**Comment by ChristinFrohne** [comment]
I forwarded this issue to the engineering team https://github.com/gitpod-io/gitpod/issues/5598
