### ISSUE TITLE
[careers] Export structured data for Google Jobs

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#696]
https://github.com/TypeFox/typefox-website/pull/60/files#diff-a1e8ff4a9d3a0693edaab7bf56b87ad2R110-R151
https://github.com/TypeFox/typefox-website/pull/60/files#diff-a1e8ff4a9d3a0693edaab7bf56b87ad2R168
https://search.google.com/structured-data/testing-tool/

**Comment by samuelpath** [comment]
The first 2 URL in your initial comment lead to 404 pages.

**Comment by nisarhassan12** [comment]
@samuelpath Thanks that's because they point to private repo to which you don't have read/write access to.
