### ISSUE TITLE
Design of the Start Screen

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#7]
As soon as we have a notebook on the start screen, it looks to me like we are a company selling screens (see Option1 & 2) 
For example: 
- apple: https://www.apple.com/de/macbook-pro/
- sony: https://www.sony.de/
- hp: https://www8.hp.com/de/de/home.html

If you prefer the screenshot on the front page, what do you think about option 3? The idea is that the image slides in the frame, when you hover over it. The website could be more dynamic by this.

![Screensdesign1](https://user-images.githubusercontent.com/46345125/54364422-2c4af400-466d-11e9-9f08-4cc536e6bbfa.JPG)
![Screensdesign2](https://user-images.githubusercontent.com/46345125/54365990-23a7ed00-4670-11e9-92cf-cc90e2c755ee.JPG)
![Screensdesign3](https://user-images.githubusercontent.com/46345125/54365994-260a4700-4670-11e9-8af3-6e07cb587ac2.JPG)

**Comment by jankeromnes** [comment]
Looks super nice! Thanks 👍

- I prefer 1 overall:
  1. Looks perfect, but I wonder if it still works on screens that are a little narrower
  2. I love the big partially visible video/laptop, but the centered texts look strange
  3. I'm not against screenshots on the side (like [JetBrains](https://www.jetbrains.com/pycharm/)), but the sliding feels like the website is stepping on its own toes
- I love the horizontal blue bar, but it needs to be much thinner (e.g. half the width?)
- The font sizes are just perfect 👌 (except the paragraph, which I wouldn't read unless it's a bit bigger)

**Comment by ChristinFrohne** [comment]
This is the new layout with the git-graph. What do you think about the icons?

![HomeScreen_git](https://user-images.githubusercontent.com/46345125/54441401-f8d79a80-473c-11e9-827c-f32e6113a9cc.jpg)
![Browser Extension – git](https://user-images.githubusercontent.com/46345125/54436620-27e90e80-4733-11e9-8e5d-63f45565d556.jpg)
![GitHubApp - git](https://user-images.githubusercontent.com/46345125/54436624-291a3b80-4733-11e9-8fc1-6032a688dd9c.jpg)

**Comment by ChristinFrohne** [comment]
**No Setup**
Based on your current context on GitHub, Gitpod beams you into the related dev environment. 
Get your entire workflow in one browser tab

****Less Waiting**
Gitpod builds your project before you start it. Install the GitHub App and Gitpod will prebuild workspaces whenever a change is pushed.
Now you can run your code immediately

**More Flow****
Thanks to the automated setup, your workspace is configurated in the background, so you can start coding right away.
Finally the click-and-code-experience comes true
