### ISSUE TITLE
Link to `https://<your-domain.com>` in self-hosted docs is broken

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/website#708]
The link in the self-hosted docs is broken.

```
Go to [https://\<your-domain.com\>](https://<your-domain.com>) and follow the steps to complete the installation.
```

![image](https://user-images.githubusercontent.com/24960040/123984630-14761600-d9c5-11eb-9f3e-ea3076fe7fcf.png)

e.g. here: https://www.gitpod.io/docs/self-hosted/latest/install/install-on-kubernetes#installation

**Comment by pawlean** [comment]
Hey @corneliusludmann 👋🏼 

Would it just make sense to not have this as a link at all? Instead, have it say `https://your-domain.com/` but not actually link anywhere? Right now the fact that it is a link is confusing. 

Would welcome your thoughts on this @mikenikles.

**Comment by corneliusludmann** [comment]
> Would it just make sense to not have this as a link at all?

Definitely yes. That would be the proper fix, IMO. Thanks for fixing this, Pauline! :+1:
