### ISSUE TITLE
Blog: Layout need to be adjusted for mini Desktops and small Laptops.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#709]
Post cards on /blog don't look that good with having a lot of space between them.

![image](https://user-images.githubusercontent.com/46004116/89400874-ee50e300-d72d-11ea-8716-772894cceefb.png)

**Comment by samuelpath** [comment]
## Before with `space-between`
![image](https://user-images.githubusercontent.com/6030745/89425056-cc109280-d738-11ea-9234-a12584221c3d.png)

## After with `space-around`
![image](https://user-images.githubusercontent.com/6030745/89425103-e21e5300-d738-11ea-8535-0837bb3e9638.png)
