### ISSUE TITLE
Replace screenshot with video

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#718]
The video shall replace the first screenshot. 
The thought is to use a freeze-frame until the user scrolled down and the video is completely visible.

A browser bar should be added manual to the video similar to https://github.com/features/codespaces

[video-website.mp4.zip](https://github.com/gitpod-io/website/files/5116276/video-website.mp4.zip)

**Comment by nisarhassan12** [comment]
Closing this one as we decided not to go with the Video.
