### ISSUE TITLE
[self-hosted] Add AWS in installing options

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#720]
Gitpod can now also be installed on AWS. 
Please update the website accordingly:

Mockup:
<img width="959" alt="Bildschirmfoto 2020-08-24 um 12 42 18" src="https://user-images.githubusercontent.com/46345125/91036269-52691780-e607-11ea-922d-9823419874c0.png">

Link: https://www.gitpod.io/docs/self-hosted/latest/install/install-on-aws-script/ (documentation will be implemented by tomorrow)

Also:
- [x] delete "see enterprise solution" button at the bottom

- [x] make sure the text is aligned on the same height

**Comment by nisarhassan12** [comment]
I have updated this https://github.com/gitpod-io/website/pull/716 Pr to add the AWS in the Install section. Please review that.
