### ISSUE TITLE
Add license key page

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#721]
Link connection:
self-hosted pricing: instead of "contact sales" -> "request license key"

Screenshot:
<img width="961" alt="Bildschirmfoto 2020-08-24 um 12 47 18" src="https://user-images.githubusercontent.com/46345125/91036619-f652c300-e607-11ea-915b-8f2288045e8a.png">

Mockup:
https://xd.adobe.com/view/c90ccd39-b05c-4ed8-b21b-a0993ddea220-9c5f/specs/

**Comment by nisarhassan12** [comment]
I'm working on this. Almost done with the interface wiring the functionality is remaining.

**Comment by ChristinFrohne** [comment]
FYI: the URL should be www.gitpod.io/enterprise-license

**Comment by ChristinFrohne** [comment]
@nisarhassan12  the "write us a mail" button is currently not linked correctly. Could you link it to the contact form?

**Comment by ChristinFrohne** [comment]
Could you also add another text field with "Domain Name" after "company"?
<img width="963" alt="Bildschirmfoto 2020-08-26 um 14 44 46" src="https://user-images.githubusercontent.com/46345125/91305113-d3acdf80-e7aa-11ea-90aa-84571f3be5da.png">

The user should be linked to this page via /pricing#self-hosted. Please exchange the "contact sales" button on the professional plan with "Request license" key

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made this pr https://github.com/gitpod-io/website/pull/738 for the requested additions and changes. Please review whenever you'll have time. Thanks
