### ISSUE TITLE
Missing line break between 2 headings in the prebuilds docs

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/website#733]
The subsection heading `On Gitpod` is on the same line as the prev. heading.

See https://www.gitpod.io/docs/prebuilds#on-github

![image](https://user-images.githubusercontent.com/24960040/124782309-6c23fc80-df44-11eb-8536-1742bc9f7db2.png)

**Comment by nisarhassan12** [comment]
Fixed in #734
