### ISSUE TITLE
Mobile improvements

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#737]
- [x] reduce spacing between each feature (currently, you need to scroll lots to go through the list, same for the start screen)

- [x] can we use a bit more horizontal space? Sometimes our text is quite narrow. For example:
![IMG_5167](https://user-images.githubusercontent.com/46345125/91298254-f8e82080-e79f-11ea-888e-9ca453a49880.PNG)
 
- [ ] can you place the image of the banner a bit differently? Currently, there is only one confetti to see which is aligned directly in the middle above the text. 

- [x] the pricing boxes have a lot of unused vertical space. Can we reduce their height?

- [x] features: add more spacing after "Code Intelligence" and before "start for free". Should be clear that this does not belong to the same section

- [x] have the pricing headline aligned in the center

- [ ] self-hosted: align the start screen in the center (same for education, recruiting & vendor)

**Comment by nisarhassan12** [comment]
> - [ ] can you place the image of the banner a bit differently? Currently, there is only one confetti to see which is aligned directly in the middle above the text.

![image](https://user-images.githubusercontent.com/46004116/91342190-1a72f780-e7f4-11ea-9523-593781e88277.png)

I can place it like the following but it does not look good.

**Comment by ChristinFrohne** [comment]
>I can place it like the following but it does not look good.
True, that doesn't look good. If you can't find a solution to improve the placing, please keep it as it is now.

**Comment by nisarhassan12** [comment]
> - []  self-hosted: align the start screen in the center (same for education, recruiting & vendor)

@ChristinFrohne Sorry I'm not able to understand what you meant here. Please elaborate.

Did you mean aligning both the img and text on the in the middle of the screen in the y-direction no matter what the height is? Thanks

![image](https://user-images.githubusercontent.com/46004116/91525716-93b93a00-e91b-11ea-8744-572c54ec5627.png)

**Comment by ChristinFrohne** [comment]
I'm only talking about the mobile view.
Currently, it looks like this:
<img width="362" alt="Bildschirmfoto 2020-08-28 um 11 17 15" src="https://user-images.githubusercontent.com/46345125/91544823-94a09a80-e920-11ea-9f74-f08e6ff0608f.png">

And I was thinking about changing it to the center, like this:
<img width="282" alt="Bildschirmfoto 2020-08-28 um 11 20 06" src="https://user-images.githubusercontent.com/46345125/91544867-a2eeb680-e920-11ea-8ede-12046eefce2b.png">

Is that clear now? What do you think?

**Comment by nisarhassan12** [comment]
@ChristinFrohne Thanks. Now it's clear. I have updated the Pr accordingly. Please have a look whenever you'll have time. Thanks.
