### ISSUE TITLE
Replace screenshot

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#742]
Could you replace the current screenshot with this one @nisarhassan12 ?
We decided to not use the reflection anymore
![Screenshot-gitpod](https://user-images.githubusercontent.com/46345125/92358860-78ec7f80-f0ea-11ea-8ab4-41a4a2d4b5ea.png)

**Comment by nisarhassan12** [comment]
sure. I'll shortly make a Pr.
