### ISSUE TITLE
[bug] tweets are not displayed

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#746]
The problem only occurs on chrome
 
<img width="1464" alt="Bildschirmfoto 2020-09-08 um 15 00 42" src="https://user-images.githubusercontent.com/46345125/92479831-59398200-f1e4-11ea-9857-0a200134a91f.png">

**Comment by nisarhassan12** [comment]
@ChristinFrohne I'm unable to re-produce this on Google Chrome 85.0.4183.83 

![image](https://user-images.githubusercontent.com/46004116/92850928-7352aa80-f406-11ea-9263-ab9d3b5d3c28.png)

**Comment by ChristinFrohne** [comment]
I just checked it again and now it's working. So we can close the issue and just keep an eye on the tweets, in case they disappear again.
