### ISSUE TITLE
Create the "GitHub Student Developer Pack" page

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#76]
Previous website source: https://github.com/gitpod-io/website/blob/master/src/pages/github-student-developer-pack.tsx
Previous website link: https://www.gitpod.io/github-student-developer-pack/

Note: There is no Figma design. Please follow the previous website guideline with the new branding applied.

**Comment by JanKoehnlein** [comment]
Can we please re-enable the GitHub StudentPack from our side? It causes a lot of effort on the first-responder side. 

If we decide to discontinue it later, we should rather announce that with a bit of a grace period, as classes/seminars are relying on it.
