### ISSUE TITLE
create landing page "gitpod vs codespaces"

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#766]
Why: We want to clarify the differences between Codespaces and Gitpod in a dedicated landing page. 

Look:
<img width="291" alt="Bildschirmfoto 2020-09-25 um 13 52 59" src="https://user-images.githubusercontent.com/46345125/94264130-708fa380-ff36-11ea-89c1-6c709a5014be.png">

Mockup: https://xd.adobe.com/view/c90ccd39-b05c-4ed8-b21b-a0993ddea220-9c5f/

**Comment by ChristinFrohne** [comment]
Could you implement this @nisarhassan12 ? :)

**Comment by nisarhassan12** [comment]
Thanks. @ChristinFrohne I have started working on it.
