### ISSUE TITLE
Student plan typo? 

### ISSUE THREAD

**Issue by ephetic** [gitpod-io/website#774]
https://github.com/gitpod-io/website/blob/b31ee8ceb5c4339332850603aa24a4758b901869/src/contents/pricing.ts#L82

Should this be "you can get our professional plan" or one of the other described plans?  Otherwise, there's no description of what the student plan entails on this plans page.

**Comment by ChristinFrohne** [comment]
Thanks for pointing this out @ephetic. I'll adjust it
