### ISSUE TITLE
Create the "Media Kit" page

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#78]
Previous website source: https://github.com/gitpod-io/website/blob/master/src/pages/media-kit.tsx
Previous website link: https://www.gitpod.io/media-kit/

Note: There is no Figma design. Please follow the previous website guideline with the new branding applied.

**Comment by ghuntley** [comment]
[Internal slack conversation](https://gitpod.slack.com/archives/C01KGM9ETU6/p1618898946133100?thread_ts=1618886067.131200&cid=C01KGM9ETU6).

**Comment by nisarhassan12** [comment]
I'll hopefully make a PR for this in the comming days of this week.
