### ISSUE TITLE
[bug] graphic has a different font style in safari

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#784]
Somehow the font changes in safari. It works fine in Chrome and Firefox
Could you adjust the font style in this graphic @nisarhassan12 ? 

<img width="675" alt="Bildschirmfoto 2020-10-02 um 10 57 07" src="https://user-images.githubusercontent.com/46345125/94906035-1b0b4780-049e-11eb-8094-a3f625a521e9.png">

**Comment by nisarhassan12** [comment]
@jbicker I don't have access to Safari. Would be great if you can look into this whenever you'll have time. Thanks
