### ISSUE TITLE
Many pages are tracked twice because of a `/` in the URL

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#787]
Many pages are tracked twice because of `/` at the end of the URL. e.g. /pricing and /pricing/.
The URLs are treated as different URLs and the website doesn’t redirect or define the canonical URL.

"On prod the redirect isn’t happening, but in dev it is. Probably need to talk with them (Nisar or Mike) to understand the difference between the two envs." - André

See [internal conversation](https://gitpod.slack.com/archives/C01KPEPKX0A/p1626955811029600?thread_ts=1626781673.023100&cid=C01KPEPKX0A)

<img width="406" alt="Bildschirmfoto 2021-07-22 um 11 51 25" src="https://user-images.githubusercontent.com/46345125/126962357-eed4a6a8-5406-4e97-ae62-5675c51f57b3.png">

cc @atduarte @nisarhassan12

**Comment by atduarte** [comment]
Probably related fix https://github.com/gitpod-io/website/pull/575 

cc @mikenikles

**Comment by nisarhassan12** [comment]
I have a PR up for adding the canonical URLs https://github.com/gitpod-io/website/pull/667 which is awaiting review from @mikenikles

**Comment by ChristinFrohne** [comment]
List of internal redirects from trailing slash mismatch https://docs.google.com/spreadsheets/d/19S1DzZIe5QO9aIFQpg6Gr5TkDa0Xf-y-hxk2hFL5Amw/edit#gid=0

**Comment by chrifro** [comment]
Is this still relevant? @Cahllagerfeld 🙏

**Comment by chrifro** [comment]
on hold until #2907

**Comment by chrifro** [comment]
The issue seems to be resolved already. I could see any URLs that are tracked twice in GA

**Comment by Siddhant-K-code** [comment]
it is fixed due to #3077
