### ISSUE TITLE
add hover effect to share icons

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#814]
<img width="285" alt="Bildschirmfoto 2021-08-03 um 13 17 46" src="https://user-images.githubusercontent.com/46345125/128006745-df56f97c-6131-40b6-baa1-2373300382c7.png">

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne for bringing this up. How do you envision the hover effect to look like ?

**Comment by ChristinFrohne** [comment]
Let's use the same effect as everywhere else. As far as I know it's a layer of white with 20% opacity.
