### ISSUE TITLE
update layout for the DevX Digest

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#827]
We want to use a hybrid of the Changelog and blog post design. By that we have the option to sign up for the newsletter and include the feedback widget. 

Could you implement this @nisarhassan12 ? 🙏

The feedback widget should link to a new tab in the feedback sheet

![Changelog](https://user-images.githubusercontent.com/46345125/128543079-13e6deeb-c255-4da1-8cc3-900d13957e97.jpg)

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/pull/819/commits/46b78aca036d7121c65caeb86f256c90956c54d7

**Comment by nisarhassan12** [comment]
Fixed by https://github.com/gitpod-io/website/pull/819
