### ISSUE TITLE
The current Syntax highlighting theme colors had bad color contrast.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#831]
The current theme used for Syntax highlighting on the site does not pass the accessibility audit Background and foreground colours do not have a sufficient contrast ratio

![image](https://user-images.githubusercontent.com/46004116/128742258-d34cb1c8-8434-435a-99b2-dfb76fde118d.png)

We should look into using a different theme or maybe come up with one of our own which passes the accessibility audit.

**Comment by mikenikles** [comment]
It looks like gitpod.io/new integrates the Monaco editor. Nisar, could you test if the default theme for https://prismjs.com/ passes the a11y audit?
