### ISSUE TITLE
[media-kit]: Gitpod brand SVG's do not render in Photoshop or Illustrator

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/website#844]
<img width="437" alt="2021-08-12_14-50-49" src="https://user-images.githubusercontent.com/127353/129139864-d5b70403-6f45-41f6-ae61-1fc5f4e27e5e.png">
<img width="650" alt="2021-08-12_14-51-29" src="https://user-images.githubusercontent.com/127353/129139885-93976331-5e35-4d54-a80c-00fb19644fb1.png">

**Comment by ChristinFrohne** [comment]
I can reproduce it, but I'm not sure what causes the issue. 

Could you replace the current svg files with these files @nisarhassan12 ? 🙏 
[Gitpod logo.zip](https://github.com/gitpod-io/website/files/7091244/Gitpod.logo.zip)
