### ISSUE TITLE
[tweets]: mixing scrolling and clicking the circle doubles the highlighted circles.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#848]
![image](https://user-images.githubusercontent.com/46004116/100594267-47ff9d80-331b-11eb-9e31-f2d3c12f7171.png)

![Peek 2020-11-30 14-36](https://user-images.githubusercontent.com/46004116/100594307-52ba3280-331b-11eb-864b-f0c747af6d9e.gif)

**Comment by ChristinFrohne** [comment]
I guess this can be closed, as the remaining issue is addressed in #915
