### ISSUE TITLE
[Docs Feedback]: Broken link in "Introduction" page

### ISSUE THREAD

**Issue by karfau** [gitpod-io/website#869]
### Page URL

https://www.gitpod.io/docs

### User feedback

The link in the following phrase (from the first paragrah) is broken:

> in the cloud accessible through your browser and [your local IDE](https://www.gitpod.io/blog/local-app).

I also searched the blog posts, but didn't find any obvious matching post.

**Comment by pawlean** [comment]
👋🏼 Hey @karfau - can you show us a screenshot? I had a look and this page links to our blog post on our local companion app. https://www.gitpod.io/blog/local-app

**Comment by karfau** [comment]
Strange, yesterday when i tried the link the page gave me a 500.
Now it seems to work.

**Comment by pawlean** [comment]
No problem @karfau - if it happens again, can you let us know? Unsure what happened there 🤔
