### ISSUE TITLE
Add a link to the GitHub repository on www.gitpod.io

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#882]
### Problem

We want to add a link to the GitHub repository for the `gitpod-io/gitpod` project on www.gitpod.io.

See relevant discussion in https://github.com/gitpod-io/website/pull/862#issuecomment-740449229.

### Proposal

**Plan A / Option A**: The first MVC (minimum viable change) could include only adding a static link as described in https://github.com/gitpod-io/website/pull/862#issuecomment-740449229:

> If there isn't an easy fix for the dynamically created GitHub star reference, let's start with a static link

**Plan A / Option B**: The second iteration could include a dynamic link which contains the number of stars of the `gitpod-io/gitpod` project on GH.

---

For future reference, I'm pasting below the plan from https://github.com/gitpod-io/website/pull/862#issuecomment-739907446.

> ### Plan A

> We could have an extra item for the GitHub repository but not sure if the current design (font family, spacing, etc) helps.

> The design proposal also changes the top right action to a primary action button which would allow adding the secondary button for GitHub with no hierarchy conflict, see https://github.com/gitpod-io/website/issues/876 for more context.

> | Option A | Option B |
> |-|-|
> | ![image](https://user-images.githubusercontent.com/120486/101353699-b05ef980-389c-11eb-868d-524f8a2f5729.png) | ![image](https://user-images.githubusercontent.com/120486/101353701-b1902680-389c-11eb-81e1-de05696304cb.png) |

> ### Plan B

> Alternatively, we could introduce a secondary button on the body to link to the repository as described in https://github.com/gitpod-io/website/issues/876, which I would strongly recommend regardless if we use this secondary button for linking to the repository.

> To demonstrate this in action, here's how this could look like.

> We could also skip the GitHub icon or rephrase  the button label to _View on GitHub_.

> | BEFORE | AFTER |
> |-|-|
> | ![image](https://user-images.githubusercontent.com/120486/101350356-82c38180-3897-11eb-8d3f-0aa9e8a6c344.png) | ![image](https://user-images.githubusercontent.com/120486/101350381-8951f900-3897-11eb-9b2a-8a63cf731aef.png) |

**Comment by ChristinFrohne** [comment]
I'm a bit afraid that having two buttons in the navigation bar might be confusing and visually a bit too much/ too heavy. If we have several highlighted options to click on the users might be confused and don't click anywhere.

Alternatively we could use a similar button as we're using on https://theia-ide.org/ or the GitHub Star button.
What do you think?

<img width="114" alt="Bildschirmfoto 2020-12-08 um 12 19 06" src="https://user-images.githubusercontent.com/46345125/101481249-29218c80-3955-11eb-93f4-ba91bdcf1d96.png">


<img width="801" alt="Bildschirmfoto 2020-12-08 um 12 49 02" src="https://user-images.githubusercontent.com/46345125/101481171-068f7380-3955-11eb-81d5-f017982929d3.png">

**Comment by JohannesLandgraf** [comment]
@ChristinFrohne I actually like your suggestion for now and we could deploy that even before universe today as we can copy the code from Theia. Would be great to immediately tell new website visitors that we are open source

@gtsiolis Wdyt?

**Comment by gtsiolis** [comment]
**Regarding multiple buttons, we should try to always have one primary button (blue button) as a CTA in any given context.** Having one primary button on the header and one on the hero section is fine as they are in a different context.

In this extend, having a primary and a secondary button on both header and hero section could be ok but probably not recommended because as you said in https://github.com/gitpod-io/website/pull/862#issuecomment-740570435 _it might be confusing and visually a bit too much_.

FWIW, since this could be related or helpful here, adding a secondary button button on the hero section is strongly suggested, see https://github.com/gitpod-io/website/issues/876.

---

As for the GitHub embedded button, adding this sounds good and a great next MVC (minimum viable change). /cc @ChristinFrohne  @JohannesLandgraf 

**Question**: Do we want to add this near the logo? Alternatively, it could also fit below the CTA button on the middle of the screen.

**Things to consider**:
1. It could be worth checking out if this will add any performance cost, although it seems quite light, as we recently tried to remove the Twitter embeds in https://github.com/gitpod-io/website/pull/828.
1. If we add this near the logo we'll have to figure out how this adapts on small viewports (mobile). If we add this on below the CTA button it should be fine as is.

**Comment by ChristinFrohne** [comment]
>If we add this near the logo we'll have to figure out how this adapts on small viewports (mobile)

For mobile devices it'd list the GitHub stars in the burger menu. Otherwise, the navigation bar gets quite cramped

<img width="490" alt="Bildschirmfoto 2020-12-08 um 15 21 11" src="https://user-images.githubusercontent.com/46345125/101495602-0600d800-3969-11eb-9d8f-f2cc5b028a05.png">

**Comment by JohannesLandgraf** [comment]
@ChristinFrohne I would rather put the Log In in the burger menu, no? I mean everybody who is (seriously) coding on her phone will accept the extra click on the burger. 

More likely that sb stumbles upon our side on his phone, sees we are open source and as a result bookmarks us for the next day.

**Comment by ChristinFrohne** [comment]
Okay makes sense :) 
On the tablet there should be enough space to display the `login button`and the `Github stars`

**Comment by JohannesLandgraf** [comment]
@gtsiolis Any updates on that one? I think this is a nice MVC we could land 🤽‍♂️

**Comment by gtsiolis** [comment]
Hey @JohannesLandgraf! Let's merge the MVC in https://github.com/gitpod-io/website/pull/884 as discussed in the [relevant discussion](https://typefox.slack.com/archives/CGRK8L804/p1608206621148100) (internal).
