### ISSUE TITLE
Add Gitpod vs GitHub Codespaces Landing Page to the website

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#883]
We should add our Gitpod vs GitHub Codespaces Landing Page to the footer navigation menu at www.gitpod.io. I'd suggest to put it under the gitpod section in the footer:
<img width="165" alt="Screenshot 2020-12-08 at 13 07 41" src="https://user-images.githubusercontent.com/22498066/101482037-5b7fb980-3956-11eb-8b6a-096da285b5b4.png">

Between Self-Hosted and Log In (https://www.gitpod.io/gitpod-vs-github-codespaces/)

**Comment by nisarhassan12** [comment]
I'm working on this now.
