### ISSUE TITLE
add Open in Gitpod + Gitpod Badges to the Media Kit page

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#885]
As suggested here we should add the Open in Gitpod button + the Gitpod badges to the media kit page alongside “how-tos, code snippets and ideas” for using the buttons as suggested here https://discord.com/channels/816244985187008514/878021456259321886/880393225418977281

**Comment by mikenikles** [comment]
Do we need an image for these buttons? Where would someone use it?

From my experience, the only way I've seen these buttons used is in Markdown files like so:

```
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/gitpod-io/website)
```

which renders this:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/gitpod-io/website)

**Comment by ChristinFrohne** [comment]
Thanks for the input @mikenikles. I don't think it makes sense to have on the media-kit page then. Let's just create the documentation explaining the badges #886 and from-referrer #599
