### ISSUE TITLE
Update navigation bar

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#892]
**Goal:** 
Let's make it easier for new users to try Gitpod

- [x] Add primary "Sign Up" CTA to the navigation bar
- [x] make the navigation fixed when scrolling. When scrolling hide most navigation items and set the background opacity to 80%

For reference so [vercel.com](https://vercel.com/)

<img width="721" alt="Bildschirmfoto 2021-08-26 um 09 34 46" src="https://user-images.githubusercontent.com/46345125/131097220-a373e521-b026-49fa-86f1-f625b2292991.png">
<img width="724" alt="Bildschirmfoto 2021-08-26 um 09 25 56" src="https://user-images.githubusercontent.com/46345125/131097234-cb8aa72c-82fa-4f21-b4de-ebd60eb86d9d.png">

**Comment by nisarhassan12** [comment]
> set the background opacity to 80%

@ChristinFrohne  80% felt too light to me so I'm now 85%.
