### ISSUE TITLE
Make the editing docs button more visible and prominent

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/website#905]
### Problem to solve

Currently, the _Edit this page in Gitpod_ button on the docs is not making it clear that this will _**not**_ edit the markdown file in GitHub as commonly seen elsewhere.

There's a lot of magic going on behind a click on that pencil button.

### Proposal

Let's make this button more visible and prominent.

This could use the _Open in Gitpod_ button as seen in various repositories or create a new one with the label _Edit in Gitpod_ if needed.

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/102217428-3a364480-3ee5-11eb-9eca-602c1ed3c729.png) | ![image](https://user-images.githubusercontent.com/120486/102217435-3c000800-3ee5-11eb-8b5f-c0491a0f3358.png) |

**Comment by ChristinFrohne** [comment]
I like your idea of having an `edit in Gitpod` button. Just using the `open in Gitpod` button wouldn't convey the message that everyone can contribute and complement the documentation.  
Alternatively we could name it `contribute in Gitpod`

**Comment by gtsiolis** [comment]
The verb _Edit_ is also common across a lot of documentation tools. _Contribute_ could be also nice.

| VuePress | Docusaurus | Read the Docs | docsify | ... |
|-|-|-|-|-|
| ![image](https://user-images.githubusercontent.com/120486/102342617-2e5c8800-3fa2-11eb-808a-9e499e0c822f.png) | ![image](https://user-images.githubusercontent.com/120486/102342731-551abe80-3fa2-11eb-8e1e-cba834aa84bc.png) | ![image](https://user-images.githubusercontent.com/120486/102342741-56e48200-3fa2-11eb-84b8-68f3307382c2.png) | ![image](https://user-images.githubusercontent.com/120486/102342750-58ae4580-3fa2-11eb-9f8e-25ddff54d912.png) | ... |

We could also use a simple link button on every page.

**Comment by ChristinFrohne** [comment]
Works both for me. The Gitpod button would be more visible and stick out more though. And it might also help to educate the user: every time they see the blue button, they know that it will start a complete dev environment

**Comment by JohannesLandgraf** [comment]
+1 for @gtsiolis suggestion of the blue Gitpod button with the label "Edit in Gitpod", which is more descriptive for docs than "Contribute" - aaand another 0.5% improvement 🚀

**Comment by nisarhassan12** [comment]
@ChristinFrohne Please provide me with the SVG for the `Edit in Gitpod` button so that I can make a PR for this.

**Comment by ChristinFrohne** [comment]
Sure, here is the svg

[edit-in-gitpod.svg.zip](https://github.com/gitpod-io/website/files/5747612/edit-in-gitpod.svg.zip)
