### ISSUE TITLE
Update call-out section "explore Gitpod"

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#907]
**Problem:**
on several pages (screencasts, features, pricing, etc.) we have call-out sections. Either linking to features or to the screencasts. Instead, we should have a "get started" call-out similar to Vercel to get more users trying out Gitpod

**mockup:**
<img width="347" alt="Bildschirmfoto 2021-08-26 um 11 59 54" src="https://user-images.githubusercontent.com/46345125/131481059-5cb44b93-6547-4a06-8026-ac9a9dc98736.png">
[Figma file](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1%3A4781)

**Question:**
What's the best place to link the "try now" button to @gtsiolis ?
1) https://www.gitpod.io/#get-started
2) https://gitpod.io/login/ (do we also have a /signup page?

Note: Vercel links to https://vercel.com/signup and then continues with the onboarding https://vercel.com/new?onboarding=true.

**Comment by ChristinFrohne** [comment]
@gtsiolis would be great to hear your thoughts on this 🙂

**Comment by gtsiolis** [comment]
Hey @ChristinFrohne! We currently don't have a visually distinct page for sign up although the `/login` automatically removes the left section if a user has logged in the dashboard before.

| First time visiting user | Previously logged in user |
|-|-|
| <img width="1440" alt="Screenshot 2021-09-01 at 4 43 56 PM (2)" src="https://user-images.githubusercontent.com/120486/131682487-50601b83-1b5e-4d21-845f-3182570a87a6.png"> | <img width="1440" alt="Screenshot 2021-09-01 at 4 44 14 PM (2)" src="https://user-images.githubusercontent.com/120486/131682496-a67ae8c7-4819-428a-8516-32379edfda37.png"> |

Also, we do have a `/new` page in the dashboard which we could link to in the future but this would require to have the feature enabled for each user as it's currently hidden behind a feature flag. We recently merged https://github.com/gitpod-io/website/issues/907 which enables the feature for anyone who joins a team or visits `/new` but this has not landed yet on production.

I think using the same link (`https://www.gitpod.io/#get-started`) as in the home page header (_Try Now_) could be best here for now as a) the `/new` flow has not landed in production yet and b) users landing into the pricing page don't have a similar call to action.

**Comment by ChristinFrohne** [comment]
Great thanks for the explanation @gtsiolis ✨
Happy to reconsider this once the new changes are live. Until then, we will use https://www.gitpod.io/#get-started
cc @nisarhassan12
