### ISSUE TITLE
Moving GitHub link to navigation bar

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#912]
Follow-up issue for #882

### Problem
- the link to GitHub is only visible on the start screen 
- there are quite a lot of clickable items relatively close to each other with no clear relation to each other

### Proposal
| before | after |
|-|-|
|<img width="1192" alt="Bildschirmfoto 2020-12-17 um 14 49 07" src="https://user-images.githubusercontent.com/46345125/102495941-09861480-4077-11eb-9627-023378b1cdd3.png">|<img width="1124" alt="Bildschirmfoto 2020-12-17 um 14 52 21" src="https://user-images.githubusercontent.com/46345125/102496275-7d282180-4077-11eb-88d4-c8204d89ba4f.png">|

**Comment by gtsiolis** [comment]
Adding some relevant feedback from the previous iteration in https://github.com/gitpod-io/website/issues/882#issuecomment-740610624:

> Do we want to add this near the logo? 

> If we add this near the logo we'll have to figure out how this adapts on small viewports (mobile).

**Comment by ChristinFrohne** [comment]
>If we add this near the logo we'll have to figure out how this adapts on small viewports (mobile).

As Johannes suggested, I'd move the `log in` button to the drop down menu (see [here](https://github.com/gitpod-io/website/issues/882#issuecomment-740658147) ) and keep the GitHub link. On tablet there should be enough space for both items

<img width="379" alt="Bildschirmfoto 2020-12-17 um 15 11 00" src="https://user-images.githubusercontent.com/46345125/102498352-26701700-407a-11eb-989e-8428b3194709.png">

**Comment by ChristinFrohne** [comment]
What do you think @JohannesLandgraf @svenefftinge? Shall we keep the layout the way it is or implement this suggestion?

**Comment by JohannesLandgraf** [comment]
Let’s keep it for now, I don’t think it makes sense to add such (small) improvements to the website before the redesign
