### ISSUE TITLE
Add Screenshot for both browser and desktop VS Code to Mediakit and Brand Assets

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#916]
One of our larger customers mentioned that on https://www.gitpod.io/media-kit there are only screenshots that look like desktop VS Code. Similar to https://github.com/features/codespaces we should have two screenshots displaying the editor: 
- One for Desktop VS Code
- One for VS Code running in the browser

**Comment by ChristinFrohne** [comment]
Sure. Here are the screenshots:
![Group 998](https://user-images.githubusercontent.com/46345125/131974198-80eeb6d4-1a42-4a0b-b3d5-f4b75b8da6ac.png)
![Group 999](https://user-images.githubusercontent.com/46345125/131974222-c4a8485a-ede3-4144-bc45-bc067cf4469f.png)

- [ ] add to media kit

- [ ] add to brand assets

**Comment by ChristinFrohne** [comment]
@nisarhassan12 could you add the screenshots to the media page? In the PR you could address #885 as well. Until we have more detailed docs about the badge you can just use this link (https://www.gitpod.io/docs/references/gitpod-yml#prebuilds.addcomment)

<img width="451" alt="Bildschirmfoto 2021-09-03 um 10 33 12" src="https://user-images.githubusercontent.com/46345125/131976404-c796298e-8c79-4ceb-b95b-883b52984275.png">
