### ISSUE TITLE
Community rename

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/website#917]
💭 on Community

- [x] rename communtiy.gitpod.io to discuss.gitpod.io (Or forum.gitpod.io, @ghuntley?)
- [ ] change mentions of community to "community forum"
- [x] make community discord more obvious (add to footer?) 
- [x] create community page

**Comment by ghuntley** [comment]
💭 create www.gitpod.io/community similar to https://devxconf.org/community

<img width="1431" alt="2021-09-02_13-53-01" src="https://user-images.githubusercontent.com/127353/131779177-38509ff7-303e-4885-9c9a-11f673a68e63.png">

**Comment by ghuntley** [comment]
💡 as follows:

- rename community.gitpod.io to forums.gitpod.io (open to better suggestions but I like vanilla descriptors like "chat" and "forums" vs "discussions" as discussions also happen in "chat")
- create www.gitpod.io/community (see above) and have all references to "community" go there.
- make discord more obvious
- make the forums less "the community"
- update references on gitpod.io/contact (see below)

<img width="1300" alt="2021-09-02_13-52-23" src="https://user-images.githubusercontent.com/127353/131779381-347fcb6f-226c-466c-a933-396fc9a627aa.png">

**Comment by ChristinFrohne** [comment]
Great suggestions! :) 

>rename community.gitpod.io to forums.gitpod.io
💯 

>create www.gitpod.io/community (see above) and have all references to "community" go there.
I can look into that next week 🙋‍♀️

**Comment by ChristinFrohne** [comment]
>rename community.gitpod.io to forums.gitpod.io

Can you take care of this one @ghuntley ?

**Comment by gtsiolis** [comment]
Adding a minor vote for going with `forum.gitpod.io` instead of `forums.gitpod.io` unless there's a strong reasoning for the second one. 🍊

**Comment by ChristinFrohne** [comment]
Ah great detail catch. Totally agree!

**Comment by ghuntley** [comment]
DRI = Geoff.

**Comment by pawlean** [comment]
Leaving a comment to remind me to bring this up in next sync.

**Comment by mikenikles** [comment]
Please re-open if there is work left to do.
