### ISSUE TITLE
Edit in Gitpod - Invalid path for `*/index.svelte` files

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#948]
Docs pages such as `src/routes/docs/configure/index.svelte` or any other `*/index.svelte` page break the logic in the `src/components/docs/edit-in-gitpod.svelte` component.

A solution, if it gets implemented, is https://github.com/sveltejs/kit/issues/269.

Otherwise, we have to think of a different approach and may be able to leverage meta information provided by Vite :thinking:.

**Comment by gtsiolis** [comment]
Thanks for opening this @mikenikles! Cross-posting from the [relevant discussion](https://gitpod.slack.com/archives/C021JDXHXMF/p1631191736007600) (internal) for more context:

> Is it known that all top-level docs pages that include sub-pages are using a wrong path when clicking the _Edit in Gitpod_ button and do not load any page when opening in Gitpod? For example, see [Getting Started](https://www.gitpod.io/docs/getting-started) v. [Configure](https://www.gitpod.io/docs/configure).
