### ISSUE TITLE
Fix feature page

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#952]
Some of the recent changes led to the feature page looking very strange

<img width="1435" alt="CleanShot 2021-09-10 at 19 30 18@2x" src="https://user-images.githubusercontent.com/22498066/132894048-c8612b0f-bb64-4ec8-abb0-9a36899fa925.png">

**Comment by ChristinFrohne** [comment]
There is no need to fix this issue, as we will remove merge the landing page and the feature page soon. By that, the layout will be adjusted as well
