### ISSUE TITLE
Swap position of values with the call to action to join us on careers page

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#955]
Swap the position of the four values with the picture/diversity. @ChristinFrohne would be great if you could suggest a very rough layout (not sure if the picture etc works similarly well with the white background for example) and either implement it on your own or hand over to @nisarhassan12 🙌

**Comment by ChristinFrohne** [comment]
Would be great if you could swap these two sections @nisarhassan12. The icons work fine on the structured back as well. Thanks!
